Repository replicatedhq/kURL, pull requests merged in 2021-11, with the labels that each got.

#2311 feat(rook): info message to add troubleshoot block volumes
  addons/rook/1.4.3/install.sh
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/template/base/install.sh
Labels: type::enhancement

#2327 Fix flakey docker pull with retry
  bin/save-manifest-assets.sh
Labels: type::chore

#2328 bugsnag-source-maps upload-node overwrite for duplcate uploads for st…
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#2334 Produce invalid bundle archive on error
  cmd/server/main.go
Labels: type::bug, bug::normal

#2362 kotsadm automatic pr branch name improvements
  .github/workflows/update-kotsadm.yaml
  addons/kotsadm/template/generate.sh
Labels: kind/chore

#2361 report rook-ceph to longhorn migrations, not just rook-ceph removal
  scripts/common/object_store.sh
  scripts/common/rook.sh
  testgrid/specs/full.yaml
Labels: kind/chore

#2342 Testgrid post install and upgrade scripts
  testgrid/migrations/tables/testinstance.yaml
  testgrid/tgapi/pkg/handlers/dequeue_instance.go
  testgrid/tgapi/pkg/handlers/ref_start.go
  testgrid/tgapi/pkg/testinstance/testinstance.go
  testgrid/tgapi/pkg/testinstance/types/types.go
  testgrid/tgrun/pkg/runner/embed/runcmd.sh
  testgrid/tgrun/pkg/runner/loop.go
  testgrid/tgrun/pkg/runner/runner.go
  testgrid/tgrun/pkg/runner/types/types.go
  testgrid/tgrun/pkg/scheduler/scheduler.go
  testgrid/tgrun/pkg/scheduler/types/types.go
  testgrid/web/src/components/views/InstanceTable.jsx
Labels: type::chore

#2363 Fix testgrid update grub failure
  testgrid/deploy/tg-script.sh
Labels: type::chore

#2374 Debug output for testgrid airgap failures
  testgrid/tgrun/pkg/runner/embed/runcmd.sh
Labels: type::chore

#2383 Yum module reset kurl.local to prevent yum update error
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal

#2391 Only run test-addon-pr workflow on path 'addons/**'
  .github/workflows/test-addon-pr.yaml
Labels: type::chore

#2392 Unify project into one go module
  .github/workflows/deploy-testgrid.yaml
  go.mod
  go.sum
  testgrid/tgapi/deploy/Dockerfile
  testgrid/tgapi/go.mod
  testgrid/tgapi/go.sum
  testgrid/tgrun/go.mod
  testgrid/tgrun/go.sum
Labels: type::chore

#2393 Fix tgrun build
  testgrid/tgapi/deploy/Dockerfile
  testgrid/tgrun/Dockerfile
Labels: type::chore

#2394 remove gomod testgrid from dependabot.yml
  .github/dependabot.yml
Labels: type::chore

#2398 Fix dependabot pr labels
  .github/dependabot.yml
Labels: type::chore
