Repository replicatedhq/kURL, pull requests merged in 2021-12, with the labels that each got.

#2390 fix(registry): pvc migration with no minio
  addons/registry/2.7.1/install.sh
  addons/registry/2.7.1/tmpl-configmap-migrate-s3.yaml
  scripts/common/object_store.sh
Labels: type::bug, bug::normal

#2402 Build test success job
  .github/workflows/build-test.yaml
Labels: type::chore

#2403 Auto-merge Dependabot pull requests
  .github/auto-merge.yaml
  .github/workflows/dependabot-automerge.yaml
Labels: type::chore

#2407 Fix testgrid build, webpack ignore plugin options
  testgrid/web/webpack.config.js
Labels: type::chore

#2408 build-test should build web
  .github/workflows/build-test.yaml
Labels: type::chore

#2405 Only auto-approve once
  .github/workflows/dependabot-automerge.yaml
Labels: type::chore

#2414 update troubleshoot (and go 1.17) to fix dep errors
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cron-rebuild-packages-prod.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/daily-testgrid.yaml
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  .github/workflows/test-addon-pr.yaml
  .github/workflows/update-longhorn.yaml
  go.mod
  go.sum
  kurl_util/deploy/Dockerfile
  kurlkinds/Dockerfile
  kurlkinds/Makefile
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/zz_generated.deepcopy.go
  testgrid/tgapi/Dockerfile.skaffold
  testgrid/tgapi/deploy/Dockerfile
  testgrid/tgrun/Dockerfile
  testgrid/tgrun/pkg/runner/cleanup.go
  testgrid/tgrun/pkg/runner/runner.go
Labels: type::chore

#2422 Create story on auto-merge failure
  .github/workflows/dependabot-automerge.yaml
  .github/workflows/dependabot-buildfailure.yaml
Labels: type::chore

#2426 Fix get story id after create on dependabot auto-merge failure
  .github/workflows/dependabot-automerge.yaml
  .github/workflows/dependabot-buildfailure.yaml
Labels: type::chore

#2305 Automated Velero version update 1.7.1
  addons/velero/1.7.1/Manifest
  addons/velero/1.7.1/install.sh
  addons/velero/1.7.1/internal-snaps-deployment-patch.yaml
  addons/velero/1.7.1/internal-snaps-ds-patch.yaml
  addons/velero/1.7.1/restic-daemonset-privileged.yaml
  addons/velero/1.7.1/s3-migration-configmap.yaml
  addons/velero/1.7.1/tmpl-change-storageclass.yaml
  addons/velero/1.7.1/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.7.1/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.7.1/tmpl-kustomization.yaml
  addons/velero/1.7.1/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.7.1/tmpl-s3-migration-bsl.yaml
  addons/velero/1.7.1/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.7.1/tmpl-s3-migration-secret.yaml
  addons/velero/1.7.1/tmpl-velero-deployment-proxy.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero

#2443 add go tools to go mod
  go.mod
  go.sum
  tools/tools.go
Labels: type::chore

#2444 update pvmigrate from v0.3.2 to v0.4.1
  go.mod
  go.sum
Labels: type::chore

#2439 Adding Ekco 0.13.0
  addons/README.md
  addons/ekco/0.13.0/Manifest
  addons/ekco/0.13.0/README.md
  addons/ekco/0.13.0/deployment.yaml
  addons/ekco/0.13.0/ekco-purge-node.sh
  addons/ekco/0.13.0/install.sh
  addons/ekco/0.13.0/kustomization.yaml
  addons/ekco/0.13.0/namespace.yaml
  addons/ekco/0.13.0/rbac-rook.yaml
  addons/ekco/0.13.0/rbac.yaml
  addons/ekco/0.13.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.13.0/reboot/ekco-reboot.service
  addons/ekco/0.13.0/reboot/shutdown.sh
  addons/ekco/0.13.0/reboot/startup.sh
  addons/ekco/0.13.0/regen-cert-pod.yaml
  addons/ekco/0.13.0/rolebinding-rook.yaml
  addons/ekco/0.13.0/rolebinding.yaml
  addons/ekco/0.13.0/rotate-certs-rbac.yaml
  addons/ekco/0.13.0/tmpl-configmap.yaml
  addons/ekco/0.13.0/upgrade/ekco-upgrade.service
  addons/ekco/0.13.0/upgrade/ekco-upgrade.timer
  addons/ekco/0.13.0/upgrade/upgrade.sh
  web/src/installers/versions.js
Labels: type::feature

#2490 1.19.15 1.20.11 kubernetes step versions
  scripts/Manifest
Labels: type::bug, bug::regression

#2491 Hack weird escape sequence to allow go template
  web/src/util/services/templates.ts
Labels: type::bug, bug::normal

#2500 Add ipv6 flag to kurl web server
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature

#2497 Triggered Kotsadm version update 2021.12.16-nightly
  addons/kotsadm/alpha/Manifest
  addons/kotsadm/alpha/deployment/kotsadm-deployment.yaml
  addons/kotsadm/alpha/install.sh
  addons/kotsadm/alpha/kotsadm-postgres-rename-pvc.yaml
  addons/kotsadm/alpha/kurl-proxy/tmpl-deployment.yaml
  addons/kotsadm/alpha/statefulset/kotsadm-statefulset.yaml
  addons/kotsadm/alpha/statefulset/patches/s3-migration.yaml
Labels: automated-pr, kotsadm

#2504 Create contour namespace with --save-config
  addons/contour/1.18.0/install.sh
  addons/contour/1.19.1/install.sh
  addons/contour/template/base/install.sh
Labels: type::bug, bug::normal

#2510 Port changes for ipv6 support to ekco 0.13.0
  addons/ekco/0.13.0/install.sh
Labels: type::bug, bug::normal

#2507 Hash complex types to prevent id collisions
  web/package-lock.json
  web/package.json
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::bug, bug::normal
