Repository replicatedhq/kURL, pull requests merged in 2021-10, with the labels that each got.

#2308 Use unique version for bugsnag appVersion
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  cmd/server/main.go
  web/src/commands/serve.ts
Labels: type::bug, bug::normal

#2304 github actions cron-contour-update workflow_dispatch
  .github/workflows/update-contour.yaml
Labels: type::chore

#2309 feat(kotsadm): allow kotsadm to deploy without object store
  addons/kotsadm/alpha/install.sh
  addons/kotsadm/template/base/install.sh
Labels: type::enhancement
