Repository replicatedhq/kURL, pull requests merged in 2022-04, with the labels that each got.

#2806 fix ekco podImageOverrides test
  addons/ekco/template/testgrid/k8s-docker.yaml
  scripts/common/object_store.sh
  testgrid/specs/full.yaml
Labels: type::chore

#2678 Fixup registry velero config
  addons/registry/2.7.1/tmpl-configmap-velero.yaml
Labels: type::bug, bug::regression

#2816 Fixes an issue where migrating from Docker to Containerd was failing when upgrading two minor kubernetes versions at the same time.
  scripts/upgrade.sh
Labels: type::bug, bug::normal, team::orange

#2818 Upgrade pvmigrate to v0.4.3
  go.mod
  go.sum
Labels: type::bug, bug::normal, team::orange

#2817 lower requests for contour
  addons/contour/1.20.1/patches/resource-limits.yaml
  addons/contour/template/base/patches/resource-limits.yaml
Labels: type::bug, bug::normal, team::orange

#2821 Upgrade pvmigrate to v0.4.4
  go.mod
  go.sum
Labels: type::bug, bug::normal, team::blue

#2823 failure to read logs from sync-object-store should not be fatal
  scripts/common/object_store.sh
Labels: type::bug, bug::normal, team::blue

#2824 run 'kubectl describe nodes' after 'kubectl get pods -A' at the end of testgrid
  testgrid/tgrun/pkg/runner/embed/runcmd.sh
Labels: type::chore, team::blue

#2703 Automated Kubernetes version update 1.23.5 1.22.8 1.21.11 1.20.15
  packages/kubernetes/1.21.11/Manifest
  packages/kubernetes/1.21.11/conformance/Manifest
  packages/kubernetes/1.22.8/Manifest
  packages/kubernetes/1.22.8/conformance/Manifest
  packages/kubernetes/1.23.5/Manifest
  packages/kubernetes/1.23.5/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes

#2728 Automated Containerd version update 1.4.6
  addons/containerd/1.4.13/Manifest
  addons/containerd/1.4.13/crictl.yaml
  addons/containerd/1.4.13/host-preflight.yaml
  addons/containerd/1.4.13/install.sh
  addons/containerd/1.4.13/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.5.10/Manifest
  addons/containerd/1.5.10/crictl.yaml
  addons/containerd/1.5.10/host-preflight.yaml
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.10/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.5.11/Manifest
  addons/containerd/1.5.11/crictl.yaml
  addons/containerd/1.5.11/host-preflight.yaml
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.5.11/kubeadm-init-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd

#2826 fix ekco podImageOverrides test
  addons/ekco/template/testgrid/k8s-docker.yaml
  testgrid/specs/full.yaml
Labels: type::chore, team::blue

#2827 test more containerd versions in daily tests and merges
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore, team::blue

#2825 Increase timeout when waiting for kotsadm to start
  addons/kotsadm/1.68.0/install.sh
  addons/kotsadm/template/base/install.sh
Labels: type::bug, bug::normal, team::orange

#2829 containerd 1.5.x does not appear to work in airgap yet, so rollback for this release
  addons/containerd/1.5.10/Manifest
  addons/containerd/1.5.10/crictl.yaml
  addons/containerd/1.5.10/host-preflight.yaml
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.10/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.5.11/Manifest
  addons/containerd/1.5.11/crictl.yaml
  addons/containerd/1.5.11/host-preflight.yaml
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.5.11/kubeadm-init-config-v1beta2.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/versions.js
Labels: type::bug, bug::normal, team::blue

#2814 Use kurl version from spec if provided
  web/package-lock.json
  web/package.json
  web/src/controllers/Scripts.ts
  web/src/installers/index.ts
  web/src/test/controllers/scripts.ts
  web/src/test/services/templates.ts
  web/src/util/services/templates.ts
Labels: type::bug, bug::normal, team::blue

#2840 fix the PR title for the automated containerd PR
  addons/containerd/template/script.sh
Labels: type::chore, team::blue

#2841 use s3override URLs in airgap bundles
  web/src/controllers/Bundles.ts
  web/src/installers/index.ts
Labels: type::feature, team::blue

#2842 fix goldpinger automated PR to actually update image
  addons/goldpinger/template/values.yaml
Labels: type::chore, team::support

#2587 Automated Goldpinger version update 3.3.0-5.1.0
  addons/goldpinger/3.3.0-5.1.0/Manifest
  addons/goldpinger/3.3.0-5.1.0/goldpinger.yaml
  addons/goldpinger/3.3.0-5.1.0/install.sh
  addons/goldpinger/3.3.0-5.1.0/kustomization.yaml
  addons/goldpinger/3.3.0-5.1.0/servicemonitor.yaml
  web/src/installers/versions.js
Labels: automated-pr, goldpinger

#2848 update local-volume-provider to v0.3.3
  addons/velero/1.7.1/Manifest
  addons/velero/1.7.1/install.sh
  addons/velero/template/base/Manifest.tmpl
  addons/velero/template/base/install.sh.tmpl
Labels: type::security

#2850 Fix testgrid, unknown containerd version
  testgrid/specs/full.yaml
Labels: type::chore

#2852 install nfs client package with velero addon
  addons/velero/1.5.1/Manifest
  addons/velero/1.5.1/install.sh
  addons/velero/1.5.3/Manifest
  addons/velero/1.5.3/install.sh
  addons/velero/1.5.4/Manifest
  addons/velero/1.5.4/install.sh
  addons/velero/1.6.0/Manifest
  addons/velero/1.6.0/install.sh
  addons/velero/1.6.1/Manifest
  addons/velero/1.6.1/install.sh
  addons/velero/1.6.2/Manifest
  addons/velero/1.6.2/install.sh
  addons/velero/1.7.1/Manifest
  addons/velero/1.7.1/install.sh
  addons/velero/template/base/Manifest.tmpl
  addons/velero/template/base/install.sh.tmpl
  bin/save-manifest-assets.sh
Labels: type::feature, team::orange

#2856 Adds recommendation to change kots password on fresh install
  addons/kotsadm/1.69.1/install.sh
  addons/kotsadm/alpha/install.sh
  addons/kotsadm/nightly/install.sh
  addons/kotsadm/template/base/install.sh
Labels: type::chore, team::blue

#2855 Fix containerd migrate from docker on airgapped server
  addons/containerd/1.3.7/install.sh
  addons/containerd/1.3.7/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.3.9/install.sh
  addons/containerd/1.3.9/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.10/install.sh
  addons/containerd/1.4.10/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.11/install.sh
  addons/containerd/1.4.11/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.12/install.sh
  addons/containerd/1.4.12/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.13/install.sh
  addons/containerd/1.4.13/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.3/install.sh
  addons/containerd/1.4.3/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.4/install.sh
  addons/containerd/1.4.4/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.6/install.sh
  addons/containerd/1.4.6/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.8/install.sh
  addons/containerd/1.4.8/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.9/install.sh
  addons/containerd/1.4.9/kubeadm-join-config-v1beta2.yaml
  addons/containerd/template/base/install.sh
  addons/containerd/template/base/kubeadm-join-config-v1beta2.yaml
  addons/containerd/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  scripts/common/common.sh
  scripts/common/docker.sh
  scripts/common/upgrade.sh
  scripts/distro/kubeadm/distro.sh
  scripts/join.sh
  scripts/upgrade.sh
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal

#2863 Fix upgrade remote master two versions
  scripts/common/upgrade.sh
Labels: type::bug, bug::normal

#2857 Remove support for Ubuntu 16.04
  addons/containerd/template/script.sh
  scripts/common/preflights.sh
  testgrid/specs/full.yaml
  testgrid/specs/os.yaml
  testgrid/tgrun/hack/os-spec.yaml
Labels: type::chore

#2865 Fix containerd s3override
  scripts/common/preflights.sh
  scripts/distro/kubeadm/distro.sh
Labels: type::bug, bug::normal

#2864 Kube-apiserver fails to start after docker to containerd migration, overridden pause image missing
  addons/containerd/1.3.7/install.sh
  addons/containerd/1.3.9/install.sh
  addons/containerd/1.4.10/install.sh
  addons/containerd/1.4.11/install.sh
  addons/containerd/1.4.12/install.sh
  addons/containerd/1.4.13/install.sh
  addons/containerd/1.4.3/install.sh
  addons/containerd/1.4.4/install.sh
  addons/containerd/1.4.6/install.sh
  addons/containerd/1.4.8/install.sh
  addons/containerd/1.4.9/install.sh
  addons/containerd/template/base/install.sh
Labels: type::bug, bug::normal

#2866 Add 'Steps to reproduce' section to the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type::chore
