Repository replicatedhq/kURL, pull requests merged in 2022-07, with the labels that each got.

#2893 set cpu/memory resource requests and limits
  kustomize/base/deployment.yaml
  kustomize/overlays/production/deployment.yaml
  kustomize/overlays/staging/deployment.yaml
  testgrid/tgapi/kustomize/overlays/production/deployment.yaml
  testgrid/tgapi/kustomize/overlays/staging/deployment.yaml
Labels: type::chore

#2934 Upgrade kurlsh/s3cmd image to alpine 3.16
  .github/workflows/build-image.yaml
  addons/registry/build-images/s3cmd/Dockerfile
  addons/registry/build-images/s3cmd/Makefile
  addons/rook/1.0.4-14.2.21/build-images/ceph/Makefile
  addons/rook/1.0.4-14.2.21/build-images/rook-ceph/Makefile
  addons/rook/1.0.4/build-images/ceph/Makefile
  addons/rook/1.0.4/build-images/rook-ceph/Makefile
Labels: type::chore, type::security

#2995 Automated Containerd version update 1.6.6
  addons/containerd/1.6.6/Manifest
  addons/containerd/1.6.6/crictl.yaml
  addons/containerd/1.6.6/host-preflight.yaml
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.6/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.6/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd

#3083 Automated Sonobuoy version update 0.56.8
  addons/sonobuoy/0.56.8/Manifest
  addons/sonobuoy/0.56.8/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy

#3095 up limits and requests for both containers
  kustomize/overlays/production/deployment.yaml
  kustomize/overlays/staging/deployment.yaml
Labels: bug::normal

#3093 Don't pin trivy version
  .github/workflows/build-image.yaml
  addons/weave/2.6.5/build-images/weave-kube/Makefile
  addons/weave/2.6.5/build-images/weave-npc/Makefile
  addons/weave/2.6.5/build-images/weaveexec/Makefile
  addons/weave/2.8.1/build-images/weave-kube/Makefile
  addons/weave/2.8.1/build-images/weave-npc/Makefile
  addons/weave/2.8.1/build-images/weaveexec/Makefile
Labels: type::chore

#3106 Use docker/login-action@v2
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  .github/workflows/deploy-testgrid.yaml
Labels: type::chore

#3108 Set AWS_DEFAULT_REGION in actions
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-package-staging.yaml
  .github/workflows/cron-rebuild-packages-prod.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  .github/workflows/deploy-testgrid.yaml
Labels: type::chore

#3109 upload-dist-[action] requires env var AWS_REGION
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3110 Actions build-package support for event workflow_dispatch
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-package-staging.yaml
Labels: type::chore

#3111 Fix kurlsh/s3cmd build action
  addons/registry/build-images/s3cmd/Makefile
Labels: type::chore

#3112 kurlsh/s3cmd sortable tag
  addons/registry/build-images/s3cmd/Makefile
Labels: type::bug, bug::normal

#3116 provide common test helper functions for post-install scripts
  testgrid/tgrun/pkg/runner/vmi/embed.go
  testgrid/tgrun/pkg/runner/vmi/embed/testhelpers.sh
  testgrid/tgrun/pkg/runner/vmi/vmi.go
Labels: type::chore

#3118 add airgap tests for kotsadm, and use localPathStorge for the no-s3 test
  addons/kotsadm/template/testgrid/k8s-docker.yaml
Labels: type::tests

#3119 tgrun should retry upon network errors
  testgrid/deploy/.terraform.lock.hcl
  testgrid/tgrun/pkg/runner/loop.go
Labels: type::chore

#3121 automatically set euo pipefail in test helper code, and better check diffs
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
  testgrid/tgrun/pkg/runner/vmi/embed/testhelpers.sh
Labels: testgrid, type::chore

#3123 Automated kubernetes updates are failing
  .gitignore
  packages/kubernetes/template/script.sh
  web/src/installers/versions.js
Labels: type::chore

#3125 Update to node 14
  deploy/Dockerfile-slim
  web/Dockerfile
  web/Dockerfile.okteto
Labels: type::security

#3129 Add back node-fetch
  web/package-lock.json
  web/package.json
  web/src/controllers/Bundles.ts
  web/src/installers/index.ts
  web/src/installers/installer-versions.ts
  web/src/metrics.ts
  web/src/test/controllers/installer-k3s.ts
  web/src/util/services/templates.ts
Labels: type::security

#3130 Remove extra .nvmrc files
  testgrid/web/.nvmrc
  web/.nvmrc
Labels: type::chore

#3132 Fix testgrid web
  testgrid/web/package-lock.json
  testgrid/web/package.json
  testgrid/web/src/components/containers/Run.jsx
  testgrid/web/src/components/views/InstanceTable.jsx
Labels: type::bug, bug::regression

#3133 Testgrid fix navigate to line in editor
  testgrid/web/src/components/views/InstanceTable.jsx
Labels: type::bug, bug::regression

#3136 --no-headers comes after the rest of the kubectl command
  scripts/common/kubernetes.sh
Labels: type::bug, bug::normal

#3135 update health checks for goldpinger
  addons/goldpinger/3.5.1-5.2.0/install.sh
  addons/goldpinger/template/base/install.sh
Labels: type::chore

#3053 Automated Kubernetes version update 1.24.3 1.23.9 1.22.12 1.21.14
  packages/kubernetes/1.21.14/Manifest
  packages/kubernetes/1.21.14/conformance/Manifest
  packages/kubernetes/1.22.12/Manifest
  packages/kubernetes/1.22.12/conformance/Manifest
  packages/kubernetes/1.23.9/Manifest
  packages/kubernetes/1.23.9/conformance/Manifest
  packages/kubernetes/1.24.3/Manifest
  packages/kubernetes/1.24.3/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes

#3140 Fix testgrid infinite loop
  .github/workflows/deploy-staging.yaml
  .github/workflows/deploy-testgrid.yaml
  testgrid/web/src/components/views/InstanceTable.jsx
Labels: type::bug, bug::regression

#3141 Patch CephCluster storage.useAllDevices=false prior to migrating from rook to longhorn
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#3143 Testgrid fix background images
  testgrid/web/package-lock.json
  testgrid/web/src/assets/scss/images/banner-arrow.png
  testgrid/web/src/assets/scss/images/github.png
  testgrid/web/src/assets/scss/images/kurl-footer@2x.png
  testgrid/web/src/assets/scss/images/kurl-header@2x.png
  testgrid/web/src/assets/scss/images/kurl_logo@2x.png
  testgrid/web/src/assets/scss/images/kurl_logo_small@2x.png
  testgrid/web/src/assets/scss/shared/Footer.scss
  testgrid/web/src/assets/scss/shared/Layout.scss
  testgrid/web/src/assets/scss/shared/NavBar.scss
  testgrid/web/webpack.config.js
Labels: type::bug, bug::normal

#3162 Testgrid improvements
  testgrid/tgapi/pkg/handlers/instance_sonobouy.go
  testgrid/tgrun/pkg/runner/vmi/embed/common.sh
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
Labels: type::chore

#3163 Automate velero add-on replicated/local-volume-provider image tag
  addons/velero/template/base/Manifest.tmpl
  addons/velero/template/base/install.tmpl.sh
  addons/velero/template/generate.sh
Labels: type::chore

#3170 report_status_update failed after report_failure cluster_not_ready
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
Labels: type::bug, bug::normal

#3171 Increase testgrid timeout
  testgrid/tgrun/pkg/runner/cleanup.go
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
Labels: type::bug, bug::normal

#3172 Fix dependabot buildfailure workflow creating duplicate shortcut stories
  .github/workflows/dependabot-buildfailure.yaml
Labels: type::chore

#3176 Update kurlsh/s3cmd image
  addons/registry/2.8.1/Manifest
  addons/registry/2.8.1/patch-deployment-migrate-s3.yaml
  addons/registry/2.8.1/patch-deployment-velero.yaml
  addons/registry/template/generate.sh
  addons/velero/1.9.0/Manifest
  addons/velero/1.9.0/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/template/generate.sh
Labels: type::security

#3173 Dependabot automerge failures create shortcut stories in untriaged
  .github/workflows/dependabot-buildfailure.yaml
Labels: type::chore

#3180 No longer ignore false positive in weave images
  addons/weave/2.6.5/build-images/weave-kube/.trivyignore.rego
  addons/weave/2.6.5/build-images/weave-npc/.trivyignore.rego
  addons/weave/2.6.5/build-images/weaveexec/.trivyignore.rego
  addons/weave/2.8.1/build-images/weave-kube/.trivyignore.rego
  addons/weave/2.8.1/build-images/weave-npc/.trivyignore.rego
  addons/weave/2.8.1/build-images/weaveexec/.trivyignore.rego
Labels: type::chore

#3179 Add flag kubernetes-enable-internal-load-balancer
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/bashmerge/main_test.go
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/prompts.sh
  scripts/common/utilbinaries.sh
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature

#3189 Update conformance nginx image to 1.14-2 for k8s 1.23+
  packages/kubernetes/1.23.2/conformance/Manifest
  packages/kubernetes/1.23.3/conformance/Manifest
  packages/kubernetes/1.23.5/conformance/Manifest
  packages/kubernetes/1.23.6/conformance/Manifest
  packages/kubernetes/1.23.9/conformance/Manifest
  packages/kubernetes/1.24.0/conformance/Manifest
  packages/kubernetes/1.24.3/conformance/Manifest
  packages/kubernetes/template/script.sh
  scripts/common/k3s.sh
  scripts/common/kubernetes.sh
  scripts/common/rke2.sh
  scripts/common/upgrade.sh
Labels: type::bug, bug::normal

#3175 Sonobuoy conformance image is now hosted at registry.k8s.io
  addons/sonobuoy/0.56.8/install.sh
  addons/sonobuoy/template/base/install.sh
  addons/sonobuoy/template/generate.sh
  addons/sonobuoy/template/testgrid/k8s-docker.yaml
Labels: type::bug, bug::normal

#3190 Only switch mirror to vault.centos.org if centos 8
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
Labels: type::bug, bug::regression

#3177 EKCO add-on version 0.19.3
  .github/workflows/update-ekco.yaml
  addons/ekco/0.19.3/Manifest
  addons/ekco/0.19.3/README.md
  addons/ekco/0.19.3/deployment.yaml
  addons/ekco/0.19.3/ekco-purge-node.sh
  addons/ekco/0.19.3/install.sh
  addons/ekco/0.19.3/kustomization.yaml
  addons/ekco/0.19.3/namespace.yaml
  addons/ekco/0.19.3/rbac-rook.yaml
  addons/ekco/0.19.3/rbac.yaml
  addons/ekco/0.19.3/reboot/ekco-reboot-containerd.service
  addons/ekco/0.19.3/reboot/ekco-reboot.service
  addons/ekco/0.19.3/reboot/shutdown.sh
  addons/ekco/0.19.3/reboot/startup.sh
  addons/ekco/0.19.3/regen-cert-pod.yaml
  addons/ekco/0.19.3/rolebinding-rook.yaml
  addons/ekco/0.19.3/rolebinding.yaml
  addons/ekco/0.19.3/rotate-certs-rbac.yaml
  addons/ekco/0.19.3/tmpl-configmap.yaml
  addons/ekco/0.19.3/upgrade/ekco-upgrade.service
  addons/ekco/0.19.3/upgrade/ekco-upgrade.timer
  addons/ekco/0.19.3/upgrade/upgrade.sh
  addons/ekco/template/base/Manifest
  addons/ekco/template/base/README.md
  addons/ekco/template/base/deployment.yaml
  addons/ekco/template/base/ekco-purge-node.sh
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/kustomization.yaml
  addons/ekco/template/base/namespace.yaml
  addons/ekco/template/base/rbac-rook.yaml
  addons/ekco/template/base/rbac.yaml
  addons/ekco/template/base/reboot/ekco-reboot-containerd.service
  addons/ekco/template/base/reboot/ekco-reboot.service
  addons/ekco/template/base/reboot/shutdown.sh
  addons/ekco/template/base/reboot/startup.sh
  addons/ekco/template/base/regen-cert-pod.yaml
  addons/ekco/template/base/rolebinding-rook.yaml
  addons/ekco/template/base/rolebinding.yaml
  addons/ekco/template/base/rotate-certs-rbac.yaml
  addons/ekco/template/base/tmpl-configmap.yaml
  addons/ekco/template/base/upgrade/ekco-upgrade.service
  addons/ekco/template/base/upgrade/ekco-upgrade.timer
  addons/ekco/template/base/upgrade/upgrade.sh
  addons/ekco/template/generate.sh
  addons/ekco/template/testgrid/k8s-docker.yaml
  testgrid/web/env/development.js
  web/src/installers/versions.js
Labels: type::feature

#3193 Remove building add on images from contributing doc
  CONTRIBUTING.md
Labels: type::chore

#3195 Testgrid fixes
  testgrid/tgapi/pkg/testinstance/testinstance.go
  testgrid/tgrun/pkg/runner/vmi/embed/common.sh
  testgrid/tgrun/pkg/runner/vmi/embed/primarynodecmd.sh
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
  testgrid/tgrun/pkg/runner/vmi/embed/secondarynodecmd.sh
Labels: type::bug, bug::normal

#3196 'tgrun run' and 'tgapi' print version info on run
  .github/workflows/deploy-testgrid.yaml
  testgrid/tgapi/deploy/Dockerfile
  testgrid/tgapi/pkg/cli/api/run.go
  testgrid/tgapi/pkg/version/build.go
  testgrid/tgrun/Dockerfile
  testgrid/tgrun/pkg/cli/run/run.go
  testgrid/tgrun/pkg/version/build.go
Labels: type::chore

#3168 Upgrade Postgres from 10.21 to 14.4
  addons/kotsadm/template/base/Manifest
  addons/kotsadm/template/base/install.sh
  addons/kotsadm/template/base/postgres.yaml
  addons/kotsadm/template/generate.sh
Labels: type::feature, team::orange

#3197 fix tgapi version
  .github/workflows/deploy-testgrid.yaml
Labels: type::chore

#3198 include buildtime and sha on tgapi staging too
  .github/workflows/deploy-testgrid.yaml
Labels: type::chore

#3199 testgrid scheduling vmi wait for initial primary
  testgrid/tgrun/pkg/runner/loop.go
  testgrid/tgrun/pkg/runner/runner.go
Labels: type::bug, bug::normal

#3203 Dequeue instance with ref
  testgrid/tgapi/pkg/cli/api/run.go
  testgrid/tgapi/pkg/handlers/dequeue_instance.go
  testgrid/tgapi/pkg/testinstance/testinstance.go
Labels: type::chore

#3205 Always use latest kube-bench version
  scripts/common/common.sh
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal

#3204 Testgrid additional nodes must wait until test is done
  testgrid/tgrun/pkg/runner/vmi/embed/common.sh
  testgrid/tgrun/pkg/runner/vmi/embed/primarynodecmd.sh
  testgrid/tgrun/pkg/runner/vmi/embed/secondarynodecmd.sh
Labels: type::tests

#3206 Testgrid save sysctl settings with higher precidence when reloaded
  testgrid/specs/os-latest.yaml
  testgrid/specs/os.yaml
  testgrid/tgrun/hack/os-spec.yaml
  testgrid/tgrun/pkg/runner/vmi/embed/common.sh
Labels: type::tests

#3208 quote integer env var values
  addons/kotsadm/alpha/postgres.yaml
  addons/kotsadm/nightly/postgres.yaml
Labels: type::tests
