Repository replicatedhq/kURL, pull requests merged in 2022-03, with the labels that each got.

#2712 Automated Contour version update 1.20.1
  addons/contour/1.20.1/Manifest
  addons/contour/1.20.1/contour.yaml
  addons/contour/1.20.1/install.sh
  addons/contour/1.20.1/patches/job-image.yaml
  addons/contour/1.20.1/tmpl-configmap.yaml
  addons/contour/1.20.1/tmpl-kustomization.yaml
  addons/contour/1.20.1/tmpl-namespace.yaml
  addons/contour/1.20.1/tmpl-service-patch.yaml
  addons/contour/template/testgrid/k8s-docker.yaml
  web/src/installers/versions.js
Labels: type::feature, automated-pr, contour, team::blue

#2713 prometheus_pods_gone should return 1 if either label matches, not only if both match
  scripts/common/rook.sh
Labels: type::bug, bug::normal, team::blue

#2535 Triggered Kotsadm version update 2022.3.3-8-nightly
  addons/kotsadm/alpha/Manifest
  addons/kotsadm/alpha/deployment/kotsadm-deployment.yaml
  addons/kotsadm/alpha/install.sh
  addons/kotsadm/alpha/kotsadm-postgres-rename-pvc.yaml
  addons/kotsadm/alpha/kurl-proxy/tmpl-deployment.yaml
  addons/kotsadm/alpha/statefulset/kotsadm-statefulset.yaml
  addons/kotsadm/alpha/statefulset/patches/s3-migration.yaml
Labels: automated-pr, kotsadm

#2727 Add EKCO version 0.18.0 to fix overriding pods images
  addons/ekco/0.18.0/Manifest
  addons/ekco/0.18.0/README.md
  addons/ekco/0.18.0/deployment.yaml
  addons/ekco/0.18.0/ekco-purge-node.sh
  addons/ekco/0.18.0/install.sh
  addons/ekco/0.18.0/kustomization.yaml
  addons/ekco/0.18.0/namespace.yaml
  addons/ekco/0.18.0/rbac-rook.yaml
  addons/ekco/0.18.0/rbac.yaml
  addons/ekco/0.18.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.18.0/reboot/ekco-reboot.service
  addons/ekco/0.18.0/reboot/shutdown.sh
  addons/ekco/0.18.0/reboot/startup.sh
  addons/ekco/0.18.0/regen-cert-pod.yaml
  addons/ekco/0.18.0/rolebinding-rook.yaml
  addons/ekco/0.18.0/rolebinding.yaml
  addons/ekco/0.18.0/rotate-certs-rbac.yaml
  addons/ekco/0.18.0/tmpl-configmap.yaml
  addons/ekco/0.18.0/upgrade/ekco-upgrade.service
  addons/ekco/0.18.0/upgrade/ekco-upgrade.timer
  addons/ekco/0.18.0/upgrade/upgrade.sh
  web/src/installers/versions.js
Labels: type::bug, bug::regression, team::orange

#2734 Preserve kurl addon installerVersion field when saving/promoting an installer
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::bug, bug::regression, team::orange

#2736 Adds tests for adding flags to kURL installs
  testgrid/README.md
  testgrid/migrations/tables/testinstance.yaml
  testgrid/specs/full.yaml
  testgrid/tgapi/pkg/handlers/dequeue_instance.go
  testgrid/tgapi/pkg/handlers/ref_start.go
  testgrid/tgapi/pkg/testinstance/testinstance.go
  testgrid/tgapi/pkg/testinstance/types/types.go
  testgrid/tgrun/pkg/runner/embed/runcmd.sh
  testgrid/tgrun/pkg/runner/loop.go
  testgrid/tgrun/pkg/runner/runner.go
  testgrid/tgrun/pkg/runner/types/types.go
  testgrid/tgrun/pkg/scheduler/scheduler.go
  testgrid/tgrun/pkg/scheduler/types/types.go
  testgrid/web/src/components/views/InstanceTable.jsx
Labels: type::tests, team::blue

#2738 fix(api): add missing host preflight and longhorn fields for validation
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::bug, bug::normal, team::orange

#2746 sc-31335 disable profiling for scheduler, apiserver and controller-manager to …
  scripts/kustomize/kubeadm/init-orig/kubeadm-cluster-config-v1beta2.yml
Labels: type::feature, team::blue

#2745 set protectKernelDefaults to true
  scripts/install.sh
Labels: type::feature, team::blue

#2748 Ensure that the --kubelet-certificate-authority argument is set as ap…
  scripts/kustomize/kubeadm/init-orig/kubeadm-cluster-config-v1beta2.yml
Labels: type::feature, team::blue

#2750 add a flag for CIS compliance
  kurl_util/cmd/yamltobash/main.go
  kurl_util/cmd/yamltobash/main_test.go
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature, team::blue

#2751 Revert "Ensure that the --kubelet-certificate-authority argument is s…
  scripts/kustomize/kubeadm/init-orig/kubeadm-cluster-config-v1beta2.yml
Labels: type::feature

#2752 update readme link
  README.md
Labels: type::chore, team::blue

#2755 set protectKernelDefaults: true if CIS compliance is requested
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/kubelet-config-v1beta1.yaml
  scripts/kustomize/kubeadm/init-orig/kustomization.yaml
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-21.yaml
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-cis-compliance.yaml
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-log-max-files.tpl
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-log-max-size.tpl
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-pre21.yaml
Labels: type::feature, team::blue

#2753 Add ekco podImageOverrides test to testgrid
  addons/ekco/template/testgrid/k8s-docker.yaml
  testgrid/specs/full.yaml
Labels: type::tests

#2756 Change ownership of admin.conf to root:root if CIS_COMPLIANCE flag is set
  scripts/common/common.sh
Labels: type::feature, team::blue

#2754 Ability to specify a kotsadm application version label to be installed
  addons/kotsadm/template/base/install.sh
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/yamltobash/main.go
  kurl_util/cmd/yamlutil/main.go
  kurl_util/cmd/yamlutil/main_test.go
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/k3s.sh
  scripts/common/rke2.sh
  scripts/common/utilbinaries.sh
  scripts/install.sh
  scripts/join.sh
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature, team::orange

#2759 Testgrid is paging and truncating instances
  testgrid/tgapi/pkg/handlers/get_run.go
  testgrid/web/src/components/containers/Run.jsx
Labels: type::chore

#2760 Testgrid fix providers for darwin arm
  testgrid/deploy/.terraform.lock.hcl
  testgrid/deploy/README.md
  testgrid/deploy/versions.tf
Labels: type::chore

#2758 add pod-security-policy for CIS compliance
  scripts/common/kubernetes.sh
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/patch-cluster-config-cis-compliance.yaml
  scripts/kustomize/kubeadm/init-orig/pod-security-policy-privileged.yaml
Labels: type::feature, type::security, team::blue

#2757 CIS audit logging
  scripts/install.sh
  scripts/join.sh
  scripts/kustomize/kubeadm/init-orig/audit.yaml
  scripts/kustomize/kubeadm/init-orig/kubeadm-cluster-config-v1beta2.yml
  scripts/kustomize/kubeadm/join-orig/audit.yaml
Labels: type::feature, team::blue

#2763 fix audit log max age and max backup to match CIS minimums
  scripts/kustomize/kubeadm/init-orig/kubeadm-cluster-config-v1beta2.yml
Labels: type::feature, team::blue

#2764 create an etcd user and group, and ensure it owns /var/lib/etcd for CIS compliance
  scripts/install.sh
  scripts/join.sh
Labels: type::feature, team::blue

#2761 Add EKCO version 0.19.0 to enable privileges to approve CSRs
  addons/ekco/0.19.0/Manifest
  addons/ekco/0.19.0/README.md
  addons/ekco/0.19.0/deployment.yaml
  addons/ekco/0.19.0/ekco-purge-node.sh
  addons/ekco/0.19.0/install.sh
  addons/ekco/0.19.0/kustomization.yaml
  addons/ekco/0.19.0/namespace.yaml
  addons/ekco/0.19.0/rbac-rook.yaml
  addons/ekco/0.19.0/rbac.yaml
  addons/ekco/0.19.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.19.0/reboot/ekco-reboot.service
  addons/ekco/0.19.0/reboot/shutdown.sh
  addons/ekco/0.19.0/reboot/startup.sh
  addons/ekco/0.19.0/regen-cert-pod.yaml
  addons/ekco/0.19.0/rolebinding-rook.yaml
  addons/ekco/0.19.0/rolebinding.yaml
  addons/ekco/0.19.0/rotate-certs-rbac.yaml
  addons/ekco/0.19.0/tmpl-configmap.yaml
  addons/ekco/0.19.0/upgrade/ekco-upgrade.service
  addons/ekco/0.19.0/upgrade/ekco-upgrade.timer
  addons/ekco/0.19.0/upgrade/upgrade.sh
  scripts/install.sh
Labels: type::feature

#2765 Enable kubelet to use pki based cacert instead of self-signed
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/patch-cluster-config-cis-compliance.yaml
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-cis-compliance.yaml
Labels: type::feature, team::blue

#2766 bump up ekco version to 0.19.0
  web/src/installers/versions.js
Labels: type::feature, team::blue

#2762 add k8s 1.23 cis benchmarks test-grid test
  testgrid/specs/full.yaml
Labels: type::feature, testgrid, team::blue

#2772 add ecko for cis testgrid tests
  testgrid/specs/full.yaml
Labels: type::bug, testgrid, bug::normal, team::blue

#2773 Fixes testgrid labels to use the labels= prefix
  testgrid/specs/full.yaml
  testgrid/tgrun/pkg/runner/embed/runcmd.sh
Labels: type::tests, team::blue

#2778 Add kernel settings to testgrid
  testgrid/tgrun/pkg/runner/embed/runcmd.sh
Labels: type::tests, team::blue

#2779 fix kernel flags for testgrid
  testgrid/tgrun/pkg/runner/embed/runcmd.sh
Labels: type::chore, team::blue

#2780 fix kubelet-container-log filenames, and test the option
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-container-log-max-files.tpl
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-container-log-max-size.tpl
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::bug, bug::regression, team::support

#2781 fix leftover code in container-log-max-size handler
  scripts/install.sh
Labels: type::bug, bug::regression, team::support

#2785 Adds Kots addon version to 1.67.0
  web/src/installers/versions.js
Labels: type::chore, team::blue

#2788 do not attempt to change existing velero-internal-snapshots PVCs
  addons/velero/1.7.1/install.sh
  addons/velero/template/base/install.sh.tmpl
Labels: type::bug, bug::normal, team::support

#2784 support kubeReserved kubelet option
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/Makefile
  kurlkinds/README.md
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/kubernetes.sh
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-reserve-compute-resources.tpl
Labels: type::feature, team::blue

#2793 adds support for eviction-threshold and adds tests in testgrid
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/kubernetes.sh
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-eviction-threshold.tpl
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/index.ts
Labels: type::feature, team::blue

#2794 Allow the user to specify system-reserved resources
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-system-reserved.tpl
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/index.ts
Labels: type::feature, team::blue

#2795 rename kubernetesReserved to kubeReserved and evictionThreshold to evictionThresholdResources
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/install.sh
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/index.ts
Labels: type::chore, team::blue

#2796 fix docs for evictionThresholdResources and systemReservedResources
  web/src/installers/index.ts
Labels: type::docs, team::blue

#2797 Fix ekco podImageOverrides test
  addons/ekco/template/testgrid/k8s-docker.yaml
  testgrid/specs/full.yaml
Labels: type::tests, team::blue

#2800 queue staging runs before prod runs in testgrid
  .github/workflows/daily-testgrid.yaml
Labels: type::chore, team::blue

#2802 add kurl spec to test cust1 install/upgrade path
  testgrid/specs/full.yaml
Labels: type::chore, team::orange

#2803 kurlkinds crds should be generated by CI
  Makefile
  kurlkinds/.gitignore
  kurlkinds/Makefile
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
Labels: type::chore
