Repository replicatedhq/kURL, pull requests merged in 2022-01, with the labels that each got.

#2566 feat(k8s): 1.22 support
  packages/kubernetes/1.22.5/Manifest
  packages/kubernetes/1.22.5/conformance/Manifest
  packages/kubernetes/template/script.sh
  testgrid/specs/full.yaml
  web/src/installers/versions.js
Labels: type::feature

#2581 feat(ekco): ekco 0.14.0
  addons/ekco/0.14.0/Manifest
  addons/ekco/0.14.0/README.md
  addons/ekco/0.14.0/deployment.yaml
  addons/ekco/0.14.0/ekco-purge-node.sh
  addons/ekco/0.14.0/install.sh
  addons/ekco/0.14.0/kustomization.yaml
  addons/ekco/0.14.0/namespace.yaml
  addons/ekco/0.14.0/rbac-rook.yaml
  addons/ekco/0.14.0/rbac.yaml
  addons/ekco/0.14.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.14.0/reboot/ekco-reboot.service
  addons/ekco/0.14.0/reboot/shutdown.sh
  addons/ekco/0.14.0/reboot/startup.sh
  addons/ekco/0.14.0/regen-cert-pod.yaml
  addons/ekco/0.14.0/rolebinding-rook.yaml
  addons/ekco/0.14.0/rolebinding.yaml
  addons/ekco/0.14.0/rotate-certs-rbac.yaml
  addons/ekco/0.14.0/tmpl-configmap.yaml
  addons/ekco/0.14.0/upgrade/ekco-upgrade.service
  addons/ekco/0.14.0/upgrade/ekco-upgrade.timer
  addons/ekco/0.14.0/upgrade/upgrade.sh
  addons/ekco/template/testgrid/k8s-docker.yaml
Labels: type::feature

#2585 update pvmigrate to v0.4.2
  go.mod
  go.sum
Labels: type::chore

#2603 fix(velero): internal storage when object store is available
  addons/velero/1.6.0/install.sh
  addons/velero/1.6.1/install.sh
  addons/velero/1.6.2/install.sh
  addons/velero/1.7.1/install.sh
  addons/velero/template/base/install.sh.tmpl
Labels: type::bug, bug::regression

#2607 fix(prom): fix nodeports for alertmanager and grafana
  addons/prometheus/0.53.1-30.1.0/nodeport-services.yaml
  addons/prometheus/template/base/nodeport-services.yaml
Labels: type::bug, bug::regression

#2613 chore: update aws mod version
  go.mod
  go.sum
Labels: go, type::chore

#2615 update express rate limit node mod version
  web/package-lock.json
  web/package.json
  web/src/server/server.ts
Labels: dependencies, javascript, type::chore

#2617 Revert "update express rate limit node mod version (#2615)"
  web/package-lock.json
  web/package.json
  web/src/server/server.ts
Labels: bug::regression

#2621 Shipping Kubernetes 1.21 as Latest
  web/src/installers/index.ts
Labels: type::bug

#2628 Revert "Bump react-router-dom from 5.3.0 to 6.2.1 in /testgrid/web"
  testgrid/web/package-lock.json
  testgrid/web/package.json
Labels: type::bug, bug::regression

#2614 feat(host preflights): blocking host preflights and wording changes
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  pkg/cli/errors.go
  pkg/cli/host_preflight.go
  pkg/cli/host_preflight_test.go
  scripts/common/addon.sh
  scripts/common/common.sh
  scripts/common/preflights.sh
  scripts/common/utilbinaries.sh
Labels: type::feature

#2630 fix(preflights): typo in legacy ignore command
  scripts/common/utilbinaries.sh
Labels: bug::normal

#2631 chore(testgrid): fix 1.22 daily tests
  testgrid/specs/full.yaml
Labels: type::chore

#2635 fix(antrea): warn missing wireguard on red hat OSes
  addons/antrea/1.4.0/install.sh
  addons/antrea/template/base/install.sh
  testgrid/specs/full.yaml
Labels: bug::normal

#2548 fix styling in ipv6 docs
  docs/ipv6.md
Labels: type::docs

#2639 123 testgrid tests
  testgrid/specs/full.yaml
Labels: type::chore, team::orange

#2640 log when a registry backup/restore/migration script starts/finishes
  addons/registry/2.7.1/tmpl-configmap-migrate-s3.yaml
  addons/registry/2.7.1/tmpl-configmap-velero.yaml
Labels: type::feature

#2641 fix(kotsadm): airgap images in 1.60.0
  addons/kotsadm/1.60.0/postgres.yaml
  addons/kotsadm/alpha/postgres.yaml
  addons/kotsadm/nightly/postgres.yaml
  addons/kotsadm/template/base/postgres.yaml
  addons/kotsadm/template/generate.sh
Labels: type::bug, bug::regression
