Repository replicatedhq/kURL, pull requests merged in 2022-12, with the labels that each got.

#3788 individually release/label each staging commit
  .github/workflows/build-package-staging.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/deploy-staging.yaml
  ARCHITECTURE.md
  testgrid/specs/deploy.yaml
Labels: type::chore

#3785 Automated Velero version update 1.9.4
  addons/velero/1.9.4/Manifest
  addons/velero/1.9.4/install.sh
  addons/velero/1.9.4/restic-daemonset-privileged.yaml
  addons/velero/1.9.4/s3-migration-configmap.yaml
  addons/velero/1.9.4/tmpl-change-storageclass.yaml
  addons/velero/1.9.4/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.9.4/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.9.4/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.9.4/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.9.4/tmpl-kustomization.yaml
  addons/velero/1.9.4/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.9.4/tmpl-s3-migration-bsl.yaml
  addons/velero/1.9.4/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.9.4/tmpl-s3-migration-secret.yaml
  addons/velero/1.9.4/tmpl-velero-deployment-proxy.yaml
  addons/velero/1.9.4/velero-args-json-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3790 Update k8s and containerd versions in CONTRIBUTING.md to latest
  CONTRIBUTING.md
Labels: type::chore

#3791 Remove failing shell tests and add others to make command
  Makefile
  scripts/common/test/cli-script-test.sh
  scripts/common/test/docker-test.sh
  scripts/common/test/docker-version-test.sh
  scripts/common/test/proxy-test.sh
  scripts/common/test/test.sh
Labels: type::chore

#3793 Automate updating k8s STEP_VERSIONS
  hack/testdata/manifest/clean
  packages/kubernetes/template/script.sh
  scripts/Manifest
Labels: type::chore

#3792 Add add-on prereq to prefix add-on functions with name to documentation
  addons/README.md
Labels: type::chore

#3795 Separate testgrid pr comments per add-on version
  .github/workflows/test-addon.yaml
Labels: type::chore

#3784 feat: add kurl command line for disk space check
  pkg/cli/cluster_free_disk_space.go
  pkg/cli/cluster_free_disk_space_test.go
  pkg/cli/commands.go
Labels: type::feature

#3794 Ignore POOL_PG_NUM_NOT_POWER_OF_TWO in health, add option to specify …
  pkg/cli/rook_health.go
  pkg/cli/rook_wait_for_health.go
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/migrate.go
  pkg/rook/testfiles/hypotheticalCheckHealthWarnCephStatus.json
  pkg/rook/testfiles/poolPgNumNotPowerOfTwoCephStatus.json
  pkg/rook/testfiles/static.go
  pkg/rook/toolbox.go
Labels: type::bug, bug::normal

#3803 test getting+filtering old items in the kurl bucket without deleting them
  .github/workflows/deploy-staging.yaml
  bin/cleanup-staging-s3.sh
Labels: type::chore

#3804 run the actual script, and run in parallel with testgrid
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3806 reinclude 'require' function for cleanup-staging-s3
  bin/cleanup-staging-s3.sh
Labels: type::chore

#3796 Automated Flannel version update 0.20.2
  addons/flannel/0.20.2/Manifest
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.20.2/kubeadm.yaml
  addons/flannel/0.20.2/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.20.2/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.20.2/yaml/kube-flannel.yml
  addons/flannel/0.20.2/yaml/kustomization.yaml
  addons/flannel/0.20.2/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#3773 feat: migrate minio away from fs back store
  addons/minio/template/base/install.sh
  addons/minio/template/base/migrate-fs/hostpath/deployment.yaml
  addons/minio/template/base/migrate-fs/hostpath/kustomization.yaml
  addons/minio/template/base/migrate-fs/hostpath/service.yaml
  addons/minio/template/base/migrate-fs/minio-backup-pvc.yaml
  addons/minio/template/base/migrate-fs/minio-pvc.yaml
  addons/minio/template/base/migrate-fs/pvc/deployment.yaml
  addons/minio/template/base/migrate-fs/pvc/kustomization.yaml
  addons/minio/template/base/migrate-fs/pvc/pvc.yaml
  addons/minio/template/base/migrate-fs/pvc/service.yaml
  addons/minio/template/generate.sh
  scripts/common/object_store.sh
Labels: type::feature

#3809 Add missing code to rook 1.10.6 add-on
  addons/rook/1.10.6/install.sh
  addons/rook/template/base/install.sh
Labels: type::chore

#3810 bug: read minio store format file inside a loop
  addons/minio/template/base/install.sh
Labels: type::bug, bug::normal

#3812 enable cleaning up testgrid files from old PRs
  bin/cleanup-staging-s3.sh
Labels: type::chore

#3816 Rook upgrade disable ekco operator
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#3817 Test rook upgrades with ekco
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal

#3815 fix: issue faced to upgrade docker to containerd (follow up 3798)
  scripts/common/docker.sh
  scripts/common/host-packages.sh
  scripts/upgrade.sh
Labels: type::chore

#3824 chore: begin more generous with regards to timeouts
  addons/minio/template/base/install.sh
  scripts/common/object_store.sh
Labels: type::chore

#3825 chore: adding more test cases for minio migration
  addons/minio/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3835 fix: preflight to only recommend Docker Enterprise Edition to RHEL installs when containerd is not selected
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#3831 Automated Kubernetes version update 1.25.5 1.24.9 1.23.15 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.22.17/Manifest
  packages/kubernetes/1.22.17/conformance/Manifest
  packages/kubernetes/1.23.15/Manifest
  packages/kubernetes/1.23.15/conformance/Manifest
  packages/kubernetes/1.24.9/Manifest
  packages/kubernetes/1.24.9/conformance/Manifest
  packages/kubernetes/1.25.5/Manifest
  packages/kubernetes/1.25.5/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#3819 Automated Contour version update 1.23.1
  addons/contour/1.23.1/Manifest
  addons/contour/1.23.1/contour.yaml
  addons/contour/1.23.1/install.sh
  addons/contour/1.23.1/patches/job-image.yaml
  addons/contour/1.23.1/patches/resource-limits.yaml
  addons/contour/1.23.1/tmpl-configmap.yaml
  addons/contour/1.23.1/tmpl-kustomization.yaml
  addons/contour/1.23.1/tmpl-namespace.yaml
  addons/contour/1.23.1/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#3820 Automated Containerd version update 1.6.12
  addons/containerd/1.6.11/Manifest
  addons/containerd/1.6.11/crictl.yaml
  addons/containerd/1.6.11/host-preflight.yaml
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.11/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.11/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.6.12/Manifest
  addons/containerd/1.6.12/crictl.yaml
  addons/containerd/1.6.12/host-preflight.yaml
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.12/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.12/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#3833 fix: install docker 20.10.17 when docker or containerd is not specified in the installer
  scripts/common/docker.sh
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#3836 chore: temporarily removing longhorn logs
  addons/minio/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3838 do not fail cleanup task if no files are to be cleaned up
  bin/cleanup-staging-s3.sh
Labels: type::chore

#3850 Fix rook upgrade tasks
  scripts/common/rook-upgrade.sh
  scripts/tasks.sh
Labels: type::bug, bug::normal

#3839 fix: error to install containerd.io that conflicts with containerd because an containerd pkg installed within docker (only for new installs)
  scripts/common/docker.sh
  scripts/install.sh
Labels: type::bug, bug::normal

#3851 Bug fix operator reduces mon count when upgrading to Rook 1.1
  addons/rookupgrade/10to14/install.sh
Labels: type::bug, bug::normal

#3832 Explicitly Set HAProxy Config file Permission
  addons/ekco/0.26.1/install.sh
  addons/ekco/template/base/install.sh
  addons/ekco/template/testgrid/k8s-docker.yaml
Labels: type::bug, bug::normal

#3856 bug: use mon actual count rather than preferred count
  addons/rookupgrade/10to14/install.sh
Labels: type::bug, bug::normal

#3849 Automated EKCO version update 0.26.2
  addons/ekco/0.26.2/Manifest
  addons/ekco/0.26.2/README.md
  addons/ekco/0.26.2/deployment.yaml
  addons/ekco/0.26.2/ekco-purge-node.sh
  addons/ekco/0.26.2/install.sh
  addons/ekco/0.26.2/kustomization.yaml
  addons/ekco/0.26.2/namespace.yaml
  addons/ekco/0.26.2/rbac-kotsadm.yaml
  addons/ekco/0.26.2/rbac-minio.yaml
  addons/ekco/0.26.2/rbac-rook.yaml
  addons/ekco/0.26.2/rbac.yaml
  addons/ekco/0.26.2/reboot/ekco-reboot-containerd.service
  addons/ekco/0.26.2/reboot/ekco-reboot.service
  addons/ekco/0.26.2/reboot/shutdown.sh
  addons/ekco/0.26.2/reboot/startup.sh
  addons/ekco/0.26.2/regen-cert-pod.yaml
  addons/ekco/0.26.2/rolebinding-kotsadm.yaml
  addons/ekco/0.26.2/rolebinding-minio.yaml
  addons/ekco/0.26.2/rolebinding-rook.yaml
  addons/ekco/0.26.2/rolebinding.yaml
  addons/ekco/0.26.2/rotate-certs-rbac.yaml
  addons/ekco/0.26.2/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#3853 Remove lint and vet from kurl_util
  .github/workflows/build-test.yaml
  kurl_util/Makefile
Labels: type::chore

#3854 Use kustomize bases rather than resources for k8s <= 1.20
  addons/longhorn/template/testgrid/k8s-ctrd.yaml
  addons/minio/template/testgrid/k8s-docker.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/rook/1.10.6/install.sh
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  addons/rook/template/testgrid/k8s-docker.yaml
  scripts/common/yaml-test.sh
  scripts/common/yaml.sh
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal

#3857 wait for an OSD to be marked as safe-to-destroy 3x over 2s before destroying it
  pkg/rook/health.go
Labels: type::bug, bug::normal

#3852 feat: upgrade k8s and kurl-kind dependencies from 1.25 to 1.26
  go.mod
  go.sum
  pkg/k8sutil/exec.go
Labels: type::security

#3848 Automated Contour version update 1.23.2
  addons/contour/1.23.2/Manifest
  addons/contour/1.23.2/contour.yaml
  addons/contour/1.23.2/install.sh
  addons/contour/1.23.2/patches/job-image.yaml
  addons/contour/1.23.2/patches/resource-limits.yaml
  addons/contour/1.23.2/tmpl-configmap.yaml
  addons/contour/1.23.2/tmpl-kustomization.yaml
  addons/contour/1.23.2/tmpl-namespace.yaml
  addons/contour/1.23.2/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#3612 Automated MinIO version update RELEASE.2022-12-12T19-27-27Z
  addons/minio/2022-12-12T19-27-27Z/Manifest
  addons/minio/2022-12-12T19-27-27Z/deployment.yaml
  addons/minio/2022-12-12T19-27-27Z/install.sh
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/hostpath/service.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/minio-pvc.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2022-12-12T19-27-27Z/migrate-fs/pvc/service.yaml
  addons/minio/2022-12-12T19-27-27Z/service.yaml
  addons/minio/2022-12-12T19-27-27Z/tmpl-creds-secret.yaml
  addons/minio/2022-12-12T19-27-27Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-12-12T19-27-27Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-12-12T19-27-27Z/tmpl-ha-statefulset.yaml
  addons/minio/2022-12-12T19-27-27Z/tmpl-kustomization.yaml
  addons/minio/2022-12-12T19-27-27Z/tmpl-namespace.yaml
  addons/minio/2022-12-12T19-27-27Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3859 Scale device_health_metrics pool for multi node cluster during rook upgrade
  addons/rookupgrade/10to14/install.sh
Labels: type::bug, bug::normal

#3860 Set correct cephfs pool replication on upgrades from 1.0.4
  addons/rook/1.10.6/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.10.6/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.10.6/install.sh
  addons/rook/1.7.11/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.7.11/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.8.10/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.9.12/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/template/base/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/template/base/install.sh
Labels: type::bug, bug::normal

#3847 Automated Sonobuoy version update 0.56.13
  addons/sonobuoy/0.56.13/Manifest
  addons/sonobuoy/0.56.13/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#3834 feat: warning when docker be installed that it is deprecated for k8s versions >= 1.20
  scripts/common/docker.sh
Labels: type::chore

#3767 Run Node Disk and Volume Validation Checks when Upgrading from Rook to OpenEBS
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  go.mod
  go.sum
  kurl_util/cmd/pvmigrate/main.go
  scripts/common/rook.sh
Labels: type::feature

#3858 fix(centos|rhel|ol): allow allowerasing previous packages installed when conflicts are faced with yum install
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal

#3861 Wait longer for device_health_metrics pool to scale
  addons/rookupgrade/10to14/install.sh
Labels: type::chore

#3864 Set correct cephfs pool replication on upgrades - 1.6.11
  addons/rook/1.6.11/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.6.11/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.6.11/install.sh
Labels: type::bug, bug::normal

#3865 Revert "fix(centos|rhel|ol): allow allowerasing previous packages installed when conflicts are faced with yum install"
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal

#3866 fix: add --allowerasing flag to allow remove conflicts
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal

#3872 Revert "fix: add --allowerasing flag to allow remove conflicts"
  scripts/common/host-packages.sh
Labels: type::chore

#3873 Pin Rook upgrades to 1.7.x as greatest
  scripts/common/rook-upgrade.sh
Labels: type::feature

#3844 feat: (for ubuntu) check status and try to fix broken dependency automatically
  scripts/common/host-packages.sh
Labels: type::chore

#3876 feat: adding kubernetes 1.26 support
  packages/kubernetes/template/script.sh
  web/src/installers/versions.js
Labels: type::feature

#3878 Automated Kubernetes version update 1.26.0 1.25.5 1.24.9 1.23.15 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.26.0/Manifest
  packages/kubernetes/1.26.0/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#3875 Fix nodes-missing-images loop closure may report incorrect nodes
  pkg/cluster/nodes.go
Labels: type::bug, bug::normal

#3868 Automated Sonobuoy version update 0.56.14
  addons/sonobuoy/0.56.14/Manifest
  addons/sonobuoy/0.56.14/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#3879 Mkdir assets package path if not exists
  scripts/common/addon.sh
Labels: type::bug, bug::normal

#3882 Rook upgrade airgap fixes
  scripts/common/rook-upgrade.sh
  scripts/tasks.sh
Labels: type::bug, bug::normal

#3883 Wait for pgs to scale down before proceeding with upgrade
  addons/rookupgrade/10to14/install.sh
Labels: type::bug, bug::normal

#3884 Rook add-on ceph image version mismatch - should be v16.2.7
  addons/rook/1.7.11/Manifest
  addons/rook/1.7.11/cluster/cluster.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
Labels: type::bug, bug::normal

#3880 chore: adding tests for kube 1.26
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3887 fix: preflight check which verifies if docker is or not supported
  scripts/common/docker.sh
Labels: type::bug, bug::regression

#3871 chore: using rebuilt s3cmd image
  addons/registry/2.8.1/Manifest
  addons/registry/2.8.1/patch-deployment-migrate-s3.yaml
  addons/registry/2.8.1/patch-deployment-velero.yaml
  addons/velero/1.9.2/Manifest
  addons/velero/1.9.2/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.9.3/Manifest
  addons/velero/1.9.3/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.9.4/Manifest
  addons/velero/1.9.4/tmpl-s3-migration-deployment-patch.yaml
Labels: type::security

#3885 Fix rook to longhorn migration regression
  scripts/common/rook.sh
Labels: type::bug, bug::regression

#3874 update label for troubleshoot/918
  addons/flannel/0.20.1/yaml/troubleshoot.yaml
  addons/flannel/0.20.2/yaml/troubleshoot.yaml
  addons/flannel/template/base/yaml/troubleshoot.yaml
Labels: type::chore

#3863 Automated Containerd version update 1.6.14
  addons/containerd/1.6.13/Manifest
  addons/containerd/1.6.13/crictl.yaml
  addons/containerd/1.6.13/host-preflight.yaml
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.13/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.13/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.6.14/Manifest
  addons/containerd/1.6.14/crictl.yaml
  addons/containerd/1.6.14/host-preflight.yaml
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.14/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.14/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#2983 fix golang lint errors shown on github PRs
  pkg/cli/cli.go
  pkg/cli/commands.go
  pkg/cli/errors.go
  pkg/cli/format_address.go
  pkg/cli/host.go
  pkg/cli/host_preflight.go
  pkg/cli/host_preflight_test.go
  pkg/cli/host_protectedid.go
  pkg/cli/root.go
  pkg/cli/sync_object_store.go
  pkg/cli/version.go
  pkg/host/protectedid.go
  pkg/installer/installer.go
  pkg/installer/template.go
  pkg/preflight/builtin.go
  pkg/preflight/preflight.go
Labels: type::chore, team::blue

#3888 EKCO disable rook-priority.kurl.sh mutating webhook on Rook upgrade
  addons/ekco/0.26.2/install.sh
  addons/ekco/template/base/install.sh
  addons/ekco/template/generate.sh
  scripts/common/rook-upgrade.sh
Labels: type::bug, bug::normal

#3870 feat: ask permission to allow remove docker in new installs to avoid …
  scripts/common/docker.sh
  scripts/common/preflights.sh
  scripts/install.sh
Labels: type::chore

#3890 chore: added missing quote to echo command
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#3894 fix testgrid k8s119_ctrd_longhorn-airgap targeting 20.04
  testgrid/specs/full.yaml
Labels: type::chore

#3893 fix airgap testgrid k8s121-airgap by upgrading valero version
  testgrid/specs/full.yaml
Labels: type::chore

#3897 chore: fix go mod unknown revision
  go.mod
  go.sum
Labels: type::chore

#3898 chore(deps): bump with fix github.com/vmware-tanzu/velero from 1.9.3 to 1.10.0
  go.mod
  go.sum
  kurl_util/cmd/veleroplugin/main.go
Labels: type::chore

#3895 chore: fix longhorn generate script by skipping version 1.2.6
  addons/longhorn/template/generate.sh
Labels: type::chore
