Repository replicatedhq/kURL, pull requests merged in 2022-08, with the labels that each got.

#3219 Add Rook 1.6.11 to testgrid
  addons/ekco/template/testgrid/k8s-docker.yaml
  addons/kotsadm/template/testgrid/k8s-docker.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3202 Automated Contour version update 1.22.0
  addons/contour/1.22.0/Manifest
  addons/contour/1.22.0/contour.yaml
  addons/contour/1.22.0/install.sh
  addons/contour/1.22.0/patches/job-image.yaml
  addons/contour/1.22.0/patches/resource-limits.yaml
  addons/contour/1.22.0/tmpl-configmap.yaml
  addons/contour/1.22.0/tmpl-kustomization.yaml
  addons/contour/1.22.0/tmpl-namespace.yaml
  addons/contour/1.22.0/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour

#3084 Automated Prometheus version update 0.58.0-39.4.0
  addons/prometheus/0.58.0-39.4.0/Manifest
  addons/prometheus/0.58.0-39.4.0/crds/crds.yaml
  addons/prometheus/0.58.0-39.4.0/crds/kustomization.yaml
  addons/prometheus/0.58.0-39.4.0/crds/preserveUnknown.yaml
  addons/prometheus/0.58.0-39.4.0/host-preflight.yaml
  addons/prometheus/0.58.0-39.4.0/install.sh
  addons/prometheus/0.58.0-39.4.0/nodeport-services.yaml
  addons/prometheus/0.58.0-39.4.0/operator/adapter.yaml
  addons/prometheus/0.58.0-39.4.0/operator/default.yaml
  addons/prometheus/0.58.0-39.4.0/operator/kustomization.yaml
  addons/prometheus/0.58.0-39.4.0/operator/longhorn.yaml
  addons/prometheus/0.58.0-39.4.0/operator/matchlabel-release.yaml
  addons/prometheus/0.58.0-39.4.0/operator/ns.yaml
  addons/prometheus/0.58.0-39.4.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.58.0-39.4.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus

#3174 Automated MinIO version update RELEASE.2022-08-02T23-59-16Z
  addons/minio/2022-08-02T23-59-16Z/Manifest
  addons/minio/2022-08-02T23-59-16Z/deployment.yaml
  addons/minio/2022-08-02T23-59-16Z/install.sh
  addons/minio/2022-08-02T23-59-16Z/service.yaml
  addons/minio/2022-08-02T23-59-16Z/tmpl-creds-secret.yaml
  addons/minio/2022-08-02T23-59-16Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-08-02T23-59-16Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-08-02T23-59-16Z/tmpl-kustomization.yaml
  addons/minio/2022-08-02T23-59-16Z/tmpl-namespace.yaml
  addons/minio/2022-08-02T23-59-16Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, minio

#3191 Automated Kubernetes version update 1.24.3 1.23.9 1.22.12 1.21.14
  packages/kubernetes/1.21.14/conformance/Manifest
  packages/kubernetes/1.22.12/conformance/Manifest
Labels: automated-pr, kubernetes

#3192 Update EKCO action doesn't need go
  .github/workflows/update-ekco.yaml
  .github/workflows/update-longhorn.yaml
  .github/workflows/update-openebs.yaml
Labels: type::chore

#3227 Updated outdated npm packages in web
  kustomize/overlays/okteto/deployment.tmpl.yaml
  testgrid/README.md
  testgrid/tgrun/pkg/scheduler/scheduler.go
  testgrid/web/env/okteto.js
  web/package-lock.json
  web/package.json
Labels: type::security

#3229 Update kubevirt.io/client-go to v0.55.0
  .github/workflows/deploy-testgrid.yaml
  go.mod
  go.sum
Labels: type::security

#3231 Update github.com/vmware-tanzu/velero to v1.9.0
  go.mod
  go.sum
Labels: type::security

#3232 Update outdated npm deps in testgrid/web
  testgrid/web/package-lock.json
  testgrid/web/package.json
  web/package-lock.json
  web/package.json
Labels: type::security

#3233 Testgrid skip run ref support
  testgrid/migrations/tables/testinstance.yaml
  testgrid/tgapi/pkg/cli/api/run.go
  testgrid/tgapi/pkg/handlers/skip_instances.go
  testgrid/tgapi/pkg/testinstance/testinstance.go
  testgrid/tgapi/pkg/testinstance/types/types.go
  testgrid/tgapi/pkg/testrun/testrun.go
  testgrid/web/src/assets/scss/components/InstanceTable.scss
  testgrid/web/src/components/views/InstanceTable.jsx
Labels: type::tests

#3234 Fix ref skip route
  testgrid/tgapi/pkg/cli/api/run.go
  testgrid/tgapi/pkg/handlers/skip_instances.go
Labels: type::tests

#3236 Remove dep github.com/replicatedhq/yaml/v3
  go.mod
  go.sum
  kurl_util/cmd/yamlutil/main.go
  kurl_util/cmd/yamlutil/main_test.go
Labels: type::security

#3221 Retry package download on failure
  scripts/common/common-test.sh
  scripts/common/common.sh
Labels: type::feature

#3239 Testgrid separate pending from running
  testgrid/tgapi/pkg/testrun/testrun.go
  testgrid/tgapi/pkg/testrun/types/types.go
  testgrid/web/src/components/views/RunTable.jsx
Labels: type::tests

#3238 Testgrid IsSkipped is not a failure
  testgrid/tgapi/pkg/handlers/get_run.go
Labels: type::tests

#3237 Do not auth_allow_insecure_global_id_reclaim on initial installation
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/template/base/install.sh
  addons/rook/template/test/install.sh
Labels: type::bug, bug::regression

#3243 Always set TESTGRID_ID in testgrid, even for airgap
  scripts/common/reporting.sh
Labels: type::bug, bug::normal, type::chore

#3244 Package download dont resume with --continue-at
  scripts/common/common.sh
Labels: type::bug, bug::regression

#3228 Add Ubuntu-22_04 Support to kURL
  Makefile
  addons/containerd/1.3.7/host-preflight.yaml
  addons/containerd/1.3.9/host-preflight.yaml
  addons/containerd/1.4.10/host-preflight.yaml
  addons/containerd/1.4.11/host-preflight.yaml
  addons/containerd/1.4.12/host-preflight.yaml
  addons/containerd/1.4.13/host-preflight.yaml
  addons/containerd/1.4.3/host-preflight.yaml
  addons/containerd/1.4.4/host-preflight.yaml
  addons/containerd/1.4.6/host-preflight.yaml
  addons/containerd/1.4.8/host-preflight.yaml
  addons/containerd/1.4.9/host-preflight.yaml
  addons/containerd/1.5.10/Manifest
  addons/containerd/1.5.10/host-preflight.yaml
  addons/containerd/1.5.11/Manifest
  addons/containerd/1.5.11/host-preflight.yaml
  addons/containerd/1.6.4/Manifest
  addons/containerd/1.6.4/host-preflight.yaml
  addons/containerd/1.6.6/Manifest
  addons/containerd/1.6.6/host-preflight.yaml
  addons/containerd/template/Dockerfile.ubuntu22
  addons/containerd/template/script.sh
  bin/save-manifest-assets.sh
  bundles/docker-ubuntu2204/Dockerfile
  bundles/docker-ubuntu2204/build.sh
  bundles/k8s-ubuntu2204/Dockerfile
  bundles/k8s-ubuntu2204/kubernetes.list
  scripts/common/preflights.sh
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::feature

#3217 Create scheduled functionality in kUrl to scan configured repositorie…
  .github/actions/addon-manifest-downloader/action.yml
  .github/actions/import-external-addon/.gitignore
  .github/actions/import-external-addon/action.yml
  .github/actions/import-external-addon/dist/index.js
  .github/actions/import-external-addon/index.js
  .github/actions/import-external-addon/package-lock.json
  .github/actions/import-external-addon/package.json
  .github/workflows/import-external-addons.yaml
  ARCHITECTURE.md
Labels: type::feature

#3245 Deploy workflows dont fail fast
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3246 Omit v2022.09.04 when generating changelog
  .github/workflows/deploy-prod.yaml
Labels: type::chore

#3247 Fix a directory naming issue
  .github/actions/import-external-addons/.gitignore
  .github/actions/import-external-addons/action.yml
  .github/actions/import-external-addons/dist/index.js
  .github/actions/import-external-addons/index.js
  .github/actions/import-external-addons/package-lock.json
  .github/actions/import-external-addons/package.json
Labels: type::bug, bug::normal

#3261 Remove Makefile Target for Building Docker on Ubuntu-22.04
  Makefile
Labels: type::feature

#3262 Omit future version v2022.09.04 when deploying
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-package-staging.yaml
  .github/workflows/cron-rebuild-packages-prod.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3270 Require PR labels
  .github/workflows/require-pr-labels.yaml
Labels: type::chore, team::orange

#3268 Seanrester/sc 55220/add external addon support to kurl api
  .github/PULL_REQUEST_TEMPLATE.md
  web/package-lock.json
  web/package.json
  web/src/commands/serve.ts
  web/src/controllers/InstallerAPI.ts
  web/src/installers/index.ts
  web/src/installers/installer-versions.ts
Labels: type::feature

#3276 Fix a bug with semver evaluation for external addons.
  web/src/installers/installer-versions.ts
Labels: type::feature

#3277 patch the hostname in addition to the cluster ip
  scripts/common/object_store.sh
Labels: type::bug

#3271 rook hostpath to blockdevice
  go.mod
  go.sum
  pkg/cli/commands.go
  pkg/cli/rook.go
  pkg/cli/rook_health.go
  pkg/cli/rook_hostpath_to_block.go
  pkg/k8sutil/exec.go
  pkg/rook/cephtypes/status.go
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/migrate.go
  pkg/rook/migrate_test.go
  pkg/rook/output.go
  pkg/rook/static/static.go
  pkg/rook/static/toolbox.yaml
  pkg/rook/testfiles/6 blockdevice pods.json
  pkg/rook/testfiles/healthyCephStatus1.json
  pkg/rook/testfiles/hostpathpods.json
  pkg/rook/testfiles/rebalanceCephStatus1.json
  pkg/rook/testfiles/rebalanceCephStatus2.json
  pkg/rook/testfiles/rebalanceCephStatusFull.json
  pkg/rook/testfiles/rebalanceCephStatusMultinode.json
  pkg/rook/testfiles/rook-6osd-deployments.json
  pkg/rook/testfiles/rook-hostpath-deployments.json
  pkg/rook/testfiles/rookBlockSpec.yaml
  pkg/rook/testfiles/rookHostpathSpec.yaml
  pkg/rook/testfiles/static.go
  pkg/rook/toolbox.go
  pkg/rook/toolbox_test.go
Labels: type::feature

#3266 Automated Containerd version update 1.6.7
  addons/containerd/1.6.7/Manifest
  addons/containerd/1.6.7/crictl.yaml
  addons/containerd/1.6.7/host-preflight.yaml
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.7/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.7/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd

#3279 Use release git tag plus commit sha for image tags in KURL
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::bug, bug::normal

#3294 Add fall back logic for kurl to try internal addons first then faill …
  cmd/server/main.go
Labels: type::feature

#3293 Added missing env for version tag
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::bug, bug::normal

#3296 Added the modified tag to kurl image on staging
  .github/workflows/deploy-staging.yaml
Labels: type::bug, bug::normal

#3297 beginnings of rook_10_to_14 function
  pkg/cli/commands.go
  pkg/cli/rook_wait_for_health.go
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/migrate.go
  pkg/rook/testfiles/static.go
  pkg/rook/testfiles/tooManyPgsPerOsd.json
  scripts/common/common.sh
  scripts/common/rook.sh
  scripts/install.sh
Labels: type::feature

#3305 improve the reliability and output of rook 1.0 to 1.4 migration
  Makefile
  addons/rookupgrade/10to14/Manifest
  addons/rookupgrade/10to14/install.sh
  addons/rookupgrade/10to14/rook-ceph-osd-rbac.yaml
  addons/rookupgrade/10to14/rook-ceph-tools-14.yaml
  addons/rookupgrade/10to14/rook-config-override.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.0-apply.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.0-crds.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.0-create.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.1-apply.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.1-crds.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.2-apply.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.2-crds.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.3-apply.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.3-crds.yaml
  addons/rookupgrade/10to14/upgrade-from-v1.3-delete.yaml
  addons/rookupgrade/README.md
  pkg/cli/commands.go
  pkg/cli/rook_wait_for_version.go
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/migrate.go
  pkg/rook/output.go
  pkg/rook/toolbox.go
  pkg/rook/toolbox_test.go
  pkg/rook/upgrade.go
  scripts/common/rook.sh
Labels: type::feature

#3304 Doc: kurl directory is needed for cURL commands to work
  CONTRIBUTING.md
Labels: type::docs

#3295 Remove EKCO auto-upgrade experimental feature
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/upgrade/ekco-upgrade.service
  addons/ekco/template/base/upgrade/ekco-upgrade.timer
  addons/ekco/template/base/upgrade/upgrade.sh
  addons/ekco/template/generate.sh
  addons/ekco/template/testgrid/k8s-docker.yaml
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/yamltobash/main.go
  kurl_util/cmd/yamltobash/testdata/expected/weave_no_masq_local_default
  kurl_util/cmd/yamltobash/testdata/expected/weave_no_masq_local_unset
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/utilbinaries.sh
Labels: type::chore

#3306 build correct directory in rookupgrade
  Makefile
  addons/rookupgrade/10to14/Manifest
Labels: type::bug, bug::normal

#3308 Add verb patch for EKCO Rook rbac
  addons/ekco/template/base/rbac-rook.yaml
Labels: type::chore

#3309 Automated EKCO version update 0.20.0
  addons/ekco/0.20.0/Manifest
  addons/ekco/0.20.0/README.md
  addons/ekco/0.20.0/deployment.yaml
  addons/ekco/0.20.0/ekco-purge-node.sh
  addons/ekco/0.20.0/install.sh
  addons/ekco/0.20.0/kustomization.yaml
  addons/ekco/0.20.0/namespace.yaml
  addons/ekco/0.20.0/rbac-rook.yaml
  addons/ekco/0.20.0/rbac.yaml
  addons/ekco/0.20.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.20.0/reboot/ekco-reboot.service
  addons/ekco/0.20.0/reboot/shutdown.sh
  addons/ekco/0.20.0/reboot/startup.sh
  addons/ekco/0.20.0/regen-cert-pod.yaml
  addons/ekco/0.20.0/rolebinding-rook.yaml
  addons/ekco/0.20.0/rolebinding.yaml
  addons/ekco/0.20.0/rotate-certs-rbac.yaml
  addons/ekco/0.20.0/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco

#3307 Go mod github.com/rook/rook v1.7.11
  go.mod
  go.sum
Labels: type::chore

#3291 Fix mismatched containerd versions between docker and installer spec
  addons/containerd/1.5.11/install.sh
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal

#3302 Automated Velero version update 1.9.1
  addons/velero/1.9.1/Manifest
  addons/velero/1.9.1/install.sh
  addons/velero/1.9.1/restic-daemonset-privileged.yaml
  addons/velero/1.9.1/s3-migration-configmap.yaml
  addons/velero/1.9.1/tmpl-change-storageclass.yaml
  addons/velero/1.9.1/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.9.1/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.9.1/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.9.1/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.9.1/tmpl-kustomization.yaml
  addons/velero/1.9.1/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.9.1/tmpl-s3-migration-bsl.yaml
  addons/velero/1.9.1/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.9.1/tmpl-s3-migration-secret.yaml
  addons/velero/1.9.1/tmpl-velero-deployment-proxy.yaml
  addons/velero/1.9.1/velero-args-json-patch.yaml
  web/src/installers/versions.js
Labels: type::feature, automated-pr, velero

#3313 improve health checks, watch for the right ceph when upgrading, set autoscale after updating to 1.4 and add a tasks.sh call for rook 1.0 to 1.4
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/testfiles/autoscalerCephStatus.json
  pkg/rook/testfiles/noreplicasCephStatus.json
  pkg/rook/testfiles/static.go
  scripts/common/rook.sh
  scripts/install.sh
  scripts/tasks.sh
Labels: type::feature

#3314 EKCO add-on toggle reconcile_rook_mds_placement
  addons/ekco/0.20.0/install.sh
  addons/ekco/0.20.0/tmpl-configmap.yaml
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/tmpl-configmap.yaml
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/Makefile
  kurlkinds/config/test/cluster.kurl.sh_example.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  kurlkinds/schemas/installer-cluster-v1beta1.json
  kurlkinds/schemas/installer-kurl-v1beta1.json
  testgrid/specs/full.yaml
  web/src/client/index_test.ts
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::chore

#3315 block rook 10-to-14 upgrade on airgap
  scripts/common/rook.sh
  scripts/tasks.sh
Labels: type::bug, bug::normal

#3317 Testgrid test Rook 1.7.x
  addons/ekco/template/testgrid/k8s-docker.yaml
  addons/kotsadm/template/testgrid/k8s-docker.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3318 show progressevents while waiting for rook health
  pkg/rook/health.go
Labels: type::bug, bug::normal

#3320 Remove newline from containerd template file to prevent changes
  addons/containerd/template/base/install.sh
Labels: type::chore

#3251 Automated Sonobuoy version update 0.56.10
  addons/sonobuoy/0.56.10/Manifest
  addons/sonobuoy/0.56.10/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore

#3321 Fix cron-openebs-update github actions workflow
  .github/workflows/update-openebs.yaml
Labels: type::chore

#3335 Update GHA workflows to ubuntu-20.04 [sc-56448]
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-package-staging.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cron-rebuild-packages-prod.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  .github/workflows/deploy-testgrid.yaml
  .github/workflows/update-containerd.yaml
  .github/workflows/update-contour.yaml
  .github/workflows/update-ekco.yaml
  .github/workflows/update-goldpinger.yaml
  .github/workflows/update-kubernetes.yaml
  .github/workflows/update-local-path-provisioner.yaml
  .github/workflows/update-longhorn.yaml
  .github/workflows/update-openebs.yaml
  .github/workflows/update-prometheus.yaml
  .github/workflows/update-registry.yaml
  .github/workflows/update-sonobuoy.yaml
  .github/workflows/update-velero.yaml
  Makefile
Labels: type::chore

#3336 Testgrid OpenEBS move some specs from Docker to Containerd
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::chore

#3339 Correctly resolve weave .x versions as patch with prerelease
  web/package-lock.json
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::bug, bug::normal

#3347 Fix velero automation
  addons/velero/template/generate.sh
  addons/velero/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3337 Allow for running testgrid add-on tests manually from CI
  .github/workflows/test-addon-pr.yaml
  .github/workflows/test-addon.yaml
  bin/test-addon-pr.sh
Labels: type::chore

#3338 Daily scan only scan greatest version and some fixes
  .github/workflows/daily-scan-images.yaml
  bin/scan-images/addons-test.js
  bin/scan-images/addons.js
  bin/scan-images/matrix.js
  bin/scan-images/package-lock.json
  bin/scan-images/package.json
Labels: type::chore

#3348 Workflow test-addon.yaml on workflow_call input types
  .github/workflows/test-addon.yaml
Labels: type::chore

#3341 Create new OpenEBS version 3.3.0
  addons/openebs/3.3.0/Manifest
  addons/openebs/3.3.0/install.sh
  addons/openebs/3.3.0/spec/crds/crds.yaml
  addons/openebs/3.3.0/spec/crds/kustomization.yaml
  addons/openebs/3.3.0/spec/openebs.tmpl.yaml
  addons/openebs/3.3.0/spec/storage/kustomization.yaml
  addons/openebs/3.3.0/spec/storage/tmpl-localpv-storage-class.yaml
  addons/openebs/3.3.0/spec/storage/tmpl-patch-localpv-default.yaml
  addons/openebs/3.3.0/spec/tmpl-kustomization.yaml
  addons/openebs/3.3.0/spec/tmpl-namespace.yaml
  addons/openebs/template/generate.sh
  web/src/installers/versions.js
Labels: type::chore

#3346 chore: update local-volume-provider image to v0.3.7
  addons/velero/1.9.1/Manifest
  addons/velero/1.9.1/install.sh
Labels: type::security

#3349 test-addon-pr.yaml workflow broken calling reusable workflow
  .github/workflows/test-addon-pr.yaml
  .github/workflows/test-addon.yaml
  bin/test-addon-pr.sh
Labels: type::chore

#3340 Remove Local Path Provisioner
  .github/workflows/update-local-path-provisioner.yaml
  Makefile
  addons/local-path-provisioner/0.0.22/Manifest
  addons/local-path-provisioner/0.0.22/install.sh
  addons/local-path-provisioner/0.0.22/local-path-provisioner.yaml
  addons/local-path-provisioner/0.0.22/storageclass-default-annotation.yaml
  addons/local-path-provisioner/categories.json
  addons/local-path-provisioner/template/base/Manifest
  addons/local-path-provisioner/template/base/install.sh
  addons/local-path-provisioner/template/base/storageclass-default-annotation.yaml
  addons/local-path-provisioner/template/script.sh
  addons/local-path-provisioner/template/testgrid/k8s-docker.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  kurlkinds/schemas/installer-cluster-v1beta1.json
  kurlkinds/schemas/installer-kurl-v1beta1.json
  scripts/common/kubernetes.sh
  scripts/distro/k3s/distro.sh
  scripts/distro/kubeadm/distro.sh
  testgrid/specs/deploy.yaml
  web/src/installers/index.ts
  web/src/installers/versions.js
  web/src/test/controllers/installers.ts
Labels: type::feature

#3351 timeout post-install and post-upgrade scripts after 30m
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
Labels: type::chore

#3249 Automated MinIO version update RELEASE.2022-08-22T23-53-06Z
  addons/minio/2022-08-22T23-53-06Z/Manifest
  addons/minio/2022-08-22T23-53-06Z/deployment.yaml
  addons/minio/2022-08-22T23-53-06Z/install.sh
  addons/minio/2022-08-22T23-53-06Z/service.yaml
  addons/minio/2022-08-22T23-53-06Z/tmpl-creds-secret.yaml
  addons/minio/2022-08-22T23-53-06Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-08-22T23-53-06Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-08-22T23-53-06Z/tmpl-kustomization.yaml
  addons/minio/2022-08-22T23-53-06Z/tmpl-namespace.yaml
  addons/minio/2022-08-22T23-53-06Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: type::feature, automated-pr, minio

#3250 Automated Prometheus version update 0.58.0-39.9.0
  addons/prometheus/0.58.0-39.9.0/Manifest
  addons/prometheus/0.58.0-39.9.0/crds/crds.yaml
  addons/prometheus/0.58.0-39.9.0/crds/kustomization.yaml
  addons/prometheus/0.58.0-39.9.0/crds/preserveUnknown.yaml
  addons/prometheus/0.58.0-39.9.0/host-preflight.yaml
  addons/prometheus/0.58.0-39.9.0/install.sh
  addons/prometheus/0.58.0-39.9.0/nodeport-services.yaml
  addons/prometheus/0.58.0-39.9.0/operator/adapter.yaml
  addons/prometheus/0.58.0-39.9.0/operator/default.yaml
  addons/prometheus/0.58.0-39.9.0/operator/kustomization.yaml
  addons/prometheus/0.58.0-39.9.0/operator/longhorn.yaml
  addons/prometheus/0.58.0-39.9.0/operator/matchlabel-release.yaml
  addons/prometheus/0.58.0-39.9.0/operator/ns.yaml
  addons/prometheus/0.58.0-39.9.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.58.0-39.9.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore

#3303 Automated Kubernetes version update 1.24.4 1.23.10 1.22.13 1.21.14
  packages/kubernetes/1.22.13/Manifest
  packages/kubernetes/1.22.13/conformance/Manifest
  packages/kubernetes/1.23.10/Manifest
  packages/kubernetes/1.23.10/conformance/Manifest
  packages/kubernetes/1.24.4/Manifest
  packages/kubernetes/1.24.4/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore

#3353 improve testgrid log reporting
  testgrid/tgapi/pkg/testinstance/testinstance.go
  testgrid/tgrun/pkg/runner/cleanup.go
  testgrid/tgrun/pkg/runner/helpers/config.go
  testgrid/tgrun/pkg/runner/loop.go
  testgrid/tgrun/pkg/runner/metrics.go
  testgrid/tgrun/pkg/runner/vmi/embed.go
  testgrid/tgrun/pkg/runner/vmi/embed/finalizelogs.sh
  testgrid/tgrun/pkg/runner/vmi/vmi.go
Labels: type::chore

#3357 send logs for every cleaned up VM, and include a message at the end of the logs
  testgrid/tgrun/pkg/runner/cleanup.go
  testgrid/tgrun/pkg/runner/vmi/embed/finalizelogs.sh
Labels: type::chore

#3358 Use longhorn instead of localPathProvisioner
  addons/kotsadm/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3359 fix localpath provisioner references
  addons/local-path-provisioner/0.0.22/kustomization.yaml
  addons/local-path-provisioner/template/base/kustomization.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  kurl_util/cmd/yamltobash/main.go
Labels: type::bug, bug::normal

#3350 Output table rather than sarif for daily-scan-images workflow
  .github/workflows/daily-scan-images.yaml
Labels: type::chore

#3361 fix enabling pg autoscale
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/migrate.go
  pkg/rook/output.go
  pkg/rook/upgrade.go
  scripts/common/rook.sh
  scripts/tasks.sh
Labels: type::bug, bug::normal

#3355 Patch kurlsh/s3cmd for CVE-2022-37434
  addons/registry/2.8.1/Manifest
  addons/registry/2.8.1/patch-deployment-migrate-s3.yaml
  addons/registry/2.8.1/patch-deployment-velero.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/velero/1.9.1/Manifest
  addons/velero/1.9.1/tmpl-s3-migration-deployment-patch.yaml
Labels: type::chore, type::security

#3356 Patch weave add-on images for CVE-2022-37434
  addons/weave/2.6.5-20220825/Manifest
  addons/weave/2.6.5-20220825/host-preflight.yaml
  addons/weave/2.6.5-20220825/install.sh
  addons/weave/2.6.5-20220825/kustomization.yaml
  addons/weave/2.6.5-20220825/patch-daemonset.yaml
  addons/weave/2.6.5-20220825/patch-encrypt.yaml
  addons/weave/2.6.5-20220825/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.6.5-20220825/tmpl-patch-no-masq-local.yaml
  addons/weave/2.6.5-20220825/tmpl-secret.yaml
  addons/weave/2.6.5-20220825/weave-daemonset-k8s-1.11.yaml
  addons/weave/2.8.1-20220825/Manifest
  addons/weave/2.8.1-20220825/host-preflight.yaml
  addons/weave/2.8.1-20220825/install.sh
  addons/weave/2.8.1-20220825/kustomization.yaml
  addons/weave/2.8.1-20220825/patch-daemonset.yaml
  addons/weave/2.8.1-20220825/patch-encrypt.yaml
  addons/weave/2.8.1-20220825/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.8.1-20220825/tmpl-patch-no-masq-local.yaml
  addons/weave/2.8.1-20220825/tmpl-secret.yaml
  addons/weave/2.8.1-20220825/weave-daemonset-k8s-1.11.yaml
  addons/weave/template/generate.sh
  addons/weave/template/testgrid/k8s-docker.yaml
  scripts/distro/kubeadm/distro.sh
  web/src/installers/versions.js
Labels: type::chore, type::security

#3360 Wrapper Script to Run kube-bench on Kubernetes Host
  bin/run-kube-bench.sh
Labels: type::chore

#3363 Update testgrid web deps
  testgrid/web/package-lock.json
  testgrid/web/package.json
Labels: type::chore

#3362 Update web deps
  web/package-lock.json
  web/package.json
  web/src/server/server.ts
Labels: type::chore

#3365 Add make command tag-and-release
  Makefile
  README.md
  bin/tag-and-release.sh
Labels: type::chore

#3367 fix race condition between deleting VMI PVCs and sending logs from the PVC
  testgrid/tgrun/pkg/runner/cleanup.go
Labels: type::bug, bug::normal

#3364 Go module updates
  Makefile
  go.mod
  go.sum
Labels: type::chore

#3369 Use sass over node-sass for testgrid/web
  testgrid/web/env/development.js
  testgrid/web/package-lock.json
  testgrid/web/package.json
Labels: type::chore

#3370 generate release notes on tag
  .github/workflows/deploy-prod.yaml
  .github/workflows/require-pr-labels.yaml
Labels: type::chore

#3301 add a type::chore label to automated addon PRs
  .github/workflows/update-antrea.yaml
  .github/workflows/update-containerd.yaml
  .github/workflows/update-contour.yaml
  .github/workflows/update-ekco.yaml
  .github/workflows/update-goldpinger.yaml
  .github/workflows/update-kotsadm.yaml
  .github/workflows/update-kubernetes.yaml
  .github/workflows/update-longhorn.yaml
  .github/workflows/update-minio.yaml
  .github/workflows/update-openebs.yaml
  .github/workflows/update-prometheus.yaml
  .github/workflows/update-registry.yaml
  .github/workflows/update-rook.yaml
  .github/workflows/update-sonobuoy.yaml
  .github/workflows/update-velero.yaml
  .github/workflows/update-weave.yaml
Labels: type::chore

#3384 add a period at the end of release notes sentences
  .github/workflows/update-antrea.yaml
  .github/workflows/update-containerd.yaml
  .github/workflows/update-contour.yaml
  .github/workflows/update-ekco.yaml
  .github/workflows/update-goldpinger.yaml
  .github/workflows/update-kotsadm.yaml
  .github/workflows/update-kubernetes.yaml
  .github/workflows/update-longhorn.yaml
  .github/workflows/update-minio.yaml
  .github/workflows/update-openebs.yaml
  .github/workflows/update-prometheus.yaml
  .github/workflows/update-registry.yaml
  .github/workflows/update-rook.yaml
  .github/workflows/update-sonobuoy.yaml
  .github/workflows/update-velero.yaml
  .github/workflows/update-weave.yaml
Labels: type::chore

#3383 include rook upgrade in main script
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/testfiles/recentCrashCephStatus.json
  pkg/rook/testfiles/static.go
  scripts/common/rook.sh
  scripts/install.sh
Labels: type::feature

#3387 fix function name for rook in main script
  scripts/install.sh
Labels: type::bug, bug::regression

#3386 always validate rook scale when rerunning the installer
  addons/rook/1.7.11/install.sh
  addons/rook/template/base/install.sh
Labels: type::bug, bug::normal

#3354 Add latest version of docker to kURL
  Makefile
  bin/list-all-packages.sh
  bundles/docker-ubuntu2204/Dockerfile
  bundles/docker-ubuntu2204/build.sh
  pkg/preflight/assets/host-preflights.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/versions.js
Labels: type::feature

#3390 Remove unsupported osids for latest docker version
  testgrid/specs/full.yaml
Labels: type::feature

#3389 Make kurlkinds separate go module, go 1.19, no more controller-gen
  .github/dependabot.yml
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cron-rebuild-packages-prod.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/daily-testgrid.yaml
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  .github/workflows/test-addon.yaml
  .github/workflows/update-longhorn.yaml
  .github/workflows/update-openebs.yaml
  go.mod
  go.sum
  kurl_util/deploy/Dockerfile
  kurlkinds/Dockerfile
  kurlkinds/Makefile
  kurlkinds/PROJECT
  kurlkinds/README.md
  kurlkinds/client/kurlclientset/clientset.go
  kurlkinds/client/kurlclientset/fake/clientset_generated.go
  kurlkinds/client/kurlclientset/fake/register.go
  kurlkinds/client/kurlclientset/scheme/register.go
  kurlkinds/client/kurlclientset/typed/cluster/v1beta1/cluster_client.go
  kurlkinds/client/kurlclientset/typed/cluster/v1beta1/fake/fake_installer.go
  kurlkinds/cmd/manager/main.go
  kurlkinds/config/default/kustomization.yaml
  kurlkinds/config/default/manager_auth_proxy_patch.yaml
  kurlkinds/config/default/manager_image_patch.yaml
  kurlkinds/config/default/manager_prometheus_metrics_patch.yaml
  kurlkinds/config/manager/manager.yaml
  kurlkinds/config/rbac/auth_proxy_role.yaml
  kurlkinds/config/rbac/auth_proxy_role_binding.yaml
  kurlkinds/config/rbac/auth_proxy_service.yaml
  kurlkinds/config/rbac/rbac_role.yaml
  kurlkinds/config/rbac/rbac_role_binding.yaml
  kurlkinds/config/samples/cluster_v1beta1_installer_object.yaml
  kurlkinds/config/test/cluster.kurl.sh_example.yaml
  kurlkinds/config/webhook/manifests.yaml
  kurlkinds/go.mod
  kurlkinds/go.sum
  kurlkinds/pkg/controller/add_installer.go
  kurlkinds/pkg/controller/controller.go
  kurlkinds/pkg/controller/installer/installer_controller.go
  kurlkinds/pkg/controller/installer/installer_controller_suite_test.go
  kurlkinds/pkg/controller/installer/installer_controller_test.go
  kurlkinds/pkg/webhook/webhook.go
  testgrid/tgapi/Dockerfile.okteto
  testgrid/tgapi/Dockerfile.skaffold
  testgrid/tgapi/deploy/Dockerfile
  testgrid/tgrun/Dockerfile
  web/Dockerfile.okteto
Labels: type::chore

#3396 Remove unsupported osid ubuntu-22.04 from addon testgrid specs
  addons/ekco/template/testgrid/k8s-docker.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3368 Output daily-scan-images trivy results as artifacts
  .github/workflows/daily-scan-images.yaml
Labels: type::chore

#3402 test combined rook and kubernetes upgrades
  scripts/install.sh
  testgrid/specs/full.yaml
Labels: type::chore

#3401 Output workflow testgrid run message as notice
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  bin/test-addon-pr.sh
Labels: type::chore

#3403 uninstall docker-scan-plugin package during docker uninstall
  scripts/common/docker.sh
Labels: type::bug, bug::normal

#3400 Fix longhorn check for default storage class false positive
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  addons/longhorn/1.3.1/install.sh
  addons/longhorn/template/base/install.sh
  addons/longhorn/template/testgrid/k8s-ctrd.yaml
  bin/test-addon-pr.sh
  scripts/common/rook.sh
Labels: type::bug, bug::regression
