Repository replicatedhq/kURL, pull requests merged in 2022-06, with the labels that each got.

#2974 no longer attempt to rerun testgrid instances if they are incomplete for 12h
  testgrid/tgapi/pkg/handlers/cluster_node.go
  testgrid/tgapi/pkg/handlers/dequeue_instance.go
  testgrid/tgapi/pkg/testinstance/testinstance.go
Labels: type::bug, bug::normal, team::blue

#2975 update latest installer to k8s 1.24.x
  web/src/installers/index.ts
Labels: type::bug, team::blue

#2971 cleanly shut down the kurl server during rollouts
  cmd/server/main.go
  kustomize/base/deployment.yaml
Labels: type::chore, team::blue

#2976 Update CVE dependencies
  web/Dockerfile.okteto
  web/package-lock.json
  web/package.json
Labels: type::chore, team::orange

#2973 allow tgapi health checks to take up to 5s, but log if it takes more than 1s
  testgrid/tgapi/pkg/cli/api/run.go
  testgrid/tgapi/pkg/handlers/healthz.go
  testgrid/tgapi/pkg/metrics/reporting.go
  testgrid/tgapi/pkg/testinstance/testinstance.go
Labels: type::chore, team::blue

#2982 handle sigterm in nodejs container
  cmd/server/main.go
  kustomize/overlays/okteto/deployment.tmpl.yaml
  web/src/commands/serve.ts
Labels: type::bug, bug::normal, team::blue

#2984 specify nodejs command in k8s deployment so that it receives sigterm
  kustomize/base/deployment.yaml
Labels: type::bug, bug::normal, team::blue

#2985 prevent 'main' from exiting while the sigterm handler is still running
  cmd/server/main.go
Labels: type::bug, bug::normal, team::blue

#2986 Ability to generate json schemas
  kurlkinds/Makefile
  kurlkinds/schemagen/cli/root.go
  kurlkinds/schemagen/main.go
  kurlkinds/schemas/installer-kurl-v1beta1.json
Labels: type::chore, team::orange

#2992 local-path-storage provisioner
  .github/workflows/update-local-path-storage.yaml
  Makefile
  addons/local-path-storage/0.0.22/Manifest
  addons/local-path-storage/0.0.22/install.sh
  addons/local-path-storage/0.0.22/local-path-storage.yaml
  addons/local-path-storage/0.0.22/storageclass-default-annotation.yaml
  addons/local-path-storage/0.0.22/tmpl-kustomization.yaml
  addons/local-path-storage/categories.json
  addons/local-path-storage/template/base/Manifest
  addons/local-path-storage/template/base/install.sh
  addons/local-path-storage/template/base/storageclass-default-annotation.yaml
  addons/local-path-storage/template/base/tmpl-kustomization.yaml
  addons/local-path-storage/template/script.sh
  addons/local-path-storage/template/testgrid/k8s-docker.yaml
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/kubernetes.sh
  scripts/distro/k3s/distro.sh
  scripts/distro/kubeadm/distro.sh
  web/src/installers/index.ts
  web/src/installers/versions.js
  web/src/test/controllers/installers.ts
Labels: type::feature, team::blue

#2993 containerd set http and https proxy vars
  addons/containerd/1.3.7/install.sh
  addons/containerd/1.3.9/install.sh
  addons/containerd/1.4.10/install.sh
  addons/containerd/1.4.11/install.sh
  addons/containerd/1.4.12/install.sh
  addons/containerd/1.4.13/install.sh
  addons/containerd/1.4.3/install.sh
  addons/containerd/1.4.4/install.sh
  addons/containerd/1.4.6/install.sh
  addons/containerd/1.4.8/install.sh
  addons/containerd/1.4.9/install.sh
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/template/base/install.sh
Labels: type::bug, bug::regression, team::orange

#2994 local-path-storage generation fix
  addons/local-path-storage/0.0.22/Manifest
  addons/local-path-storage/0.0.22/install.sh
  addons/local-path-storage/0.0.22/kustomization.yaml
  addons/local-path-storage/0.0.22/local-path-storage.yaml
  addons/local-path-storage/template/base/Manifest
  addons/local-path-storage/template/base/install.sh
  addons/local-path-storage/template/base/kustomization.yaml
  addons/local-path-storage/template/script.sh
  addons/local-path-storage/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
Labels: type::feature, team::blue

#2997 rename the local-path-storage addon to local-path-provisioner
  .github/workflows/update-local-path-provisioner.yaml
  Makefile
  addons/local-path-provisioner/0.0.22/Manifest
  addons/local-path-provisioner/0.0.22/install.sh
  addons/local-path-provisioner/0.0.22/kustomization.yaml
  addons/local-path-provisioner/0.0.22/local-path-provisioner.yaml
  addons/local-path-provisioner/0.0.22/storageclass-default-annotation.yaml
  addons/local-path-provisioner/categories.json
  addons/local-path-provisioner/template/base/Manifest
  addons/local-path-provisioner/template/base/install.sh
  addons/local-path-provisioner/template/base/kustomization.yaml
  addons/local-path-provisioner/template/base/storageclass-default-annotation.yaml
  addons/local-path-provisioner/template/script.sh
  addons/local-path-provisioner/template/testgrid/k8s-docker.yaml
  addons/local-path-storage/0.0.22/kustomization.yaml
  addons/local-path-storage/template/base/kustomization.yaml
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/kubernetes.sh
  scripts/distro/k3s/distro.sh
  scripts/distro/kubeadm/distro.sh
  testgrid/specs/deploy.yaml
  web/src/installers/index.ts
  web/src/installers/versions.js
  web/src/test/controllers/installers.ts
Labels: type::chore, team::blue

#2999 some things needed to remain 'local-path-storage'
  addons/local-path-provisioner/0.0.22/kustomization.yaml
  addons/local-path-provisioner/template/base/kustomization.yaml
Labels: type::bug, bug::normal, team::blue

#3006 log at the beginning of the load-images task
  scripts/tasks.sh
Labels: type::feature, team::support

#3008 Update minio image to latest upstream tag to resolve CVEs
  addons/minio/2020-01-25T02-50-51Z/Manifest
  addons/minio/2020-01-25T02-50-51Z/deployment.yaml
Labels: type::security, team::orange

#3010 Revert "Update minio image to latest upstream tag to resolve CVEs"
  addons/minio/2020-01-25T02-50-51Z/Manifest
  addons/minio/2020-01-25T02-50-51Z/deployment.yaml
Labels: type::bug, bug::normal, team::orange

#3012 Create new minio version with latest upstream image tag to resolve CVEs
  addons/minio/2022-06-11T19-55-32Z/Manifest
  addons/minio/2022-06-11T19-55-32Z/deployment.yaml
  addons/minio/2022-06-11T19-55-32Z/install.sh
  addons/minio/2022-06-11T19-55-32Z/service.yaml
  addons/minio/2022-06-11T19-55-32Z/tmpl-creds-secret.yaml
  addons/minio/2022-06-11T19-55-32Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-06-11T19-55-32Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-06-11T19-55-32Z/tmpl-kustomization.yaml
  addons/minio/2022-06-11T19-55-32Z/tmpl-namespace.yaml
  addons/minio/2022-06-11T19-55-32Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: type::security, team::orange

#3015 AWS add-on to support latest
  web/src/installers/versions.js
Labels: type::bug, team::blue

#3009 needs to be string
  testgrid/migrations/tables/testinstance.yaml
Labels: type::chore

#3016 Add new testgrid reservation ids
  testgrid/deploy/.terraform.lock.hcl
  testgrid/deploy/vars.tf
Labels: type::chore

#3007 add dockerfile patch and makefile for weave CVEs
  addons/weave/2.6.5/build-images/README.md
  addons/weave/2.6.5/build-images/weave-kube/.trivyignore.rego
  addons/weave/2.6.5/build-images/weave-kube/Dockerfile
  addons/weave/2.6.5/build-images/weave-kube/Makefile
  addons/weave/2.6.5/build-images/weave-npc/.trivyignore.rego
  addons/weave/2.6.5/build-images/weave-npc/Dockerfile
  addons/weave/2.6.5/build-images/weave-npc/Makefile
  addons/weave/2.6.5/build-images/weaveexec/.trivyignore.rego
  addons/weave/2.6.5/build-images/weaveexec/Dockerfile
  addons/weave/2.6.5/build-images/weaveexec/Makefile
  addons/weave/2.8.1/build-images/README.md
  addons/weave/2.8.1/build-images/weave-kube/.trivyignore.rego
  addons/weave/2.8.1/build-images/weave-kube/Dockerfile
  addons/weave/2.8.1/build-images/weave-kube/Makefile
  addons/weave/2.8.1/build-images/weave-npc/.trivyignore.rego
  addons/weave/2.8.1/build-images/weave-npc/Dockerfile
  addons/weave/2.8.1/build-images/weave-npc/Makefile
  addons/weave/2.8.1/build-images/weaveexec/.trivyignore.rego
  addons/weave/2.8.1/build-images/weaveexec/Dockerfile
  addons/weave/2.8.1/build-images/weaveexec/Makefile
  addons/weave/2.8.1/weave-daemonset-k8s-1.11.yaml
  addons/weave/template/testgrid/k8s-docker.yaml
  testgrid/specs/full.yaml
Labels: type::chore, team::blue

#3018 Adding testgrid installer spec for k8s121x_openebs_containerd
  testgrid/specs/full.yaml
Labels: type::tests

#3021 Add test for upgrading minio from 2020-01-25T02-50-51Z to testgrid
  addons/minio/template/testgrid/k8s-docker.yaml
Labels: type::tests, team::orange

#3022 update weave add-on to use patched images
  addons/weave/2.6.5/Manifest
  addons/weave/2.6.5/daemonset.yaml
  addons/weave/2.8.1/Manifest
  addons/weave/2.8.1/weave-daemonset-k8s-1.11.yaml
  addons/weave/template/testgrid/k8s-docker.yaml
  scripts/distro/kubeadm/distro.sh
  scripts/tasks.sh
Labels: type::chore

#3001 Automated Contour version update 1.21.1
  addons/contour/1.21.1/Manifest
  addons/contour/1.21.1/contour.yaml
  addons/contour/1.21.1/install.sh
  addons/contour/1.21.1/patches/job-image.yaml
  addons/contour/1.21.1/patches/resource-limits.yaml
  addons/contour/1.21.1/tmpl-configmap.yaml
  addons/contour/1.21.1/tmpl-kustomization.yaml
  addons/contour/1.21.1/tmpl-namespace.yaml
  addons/contour/1.21.1/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour

#2633 Automated Sonobuoy version update 0.56.7
  addons/sonobuoy/0.56.7/Manifest
  addons/sonobuoy/0.56.7/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy

#3034 Update local-volume-provider image to v0.3.5 in the Velero add-on
  addons/velero/1.8.1/Manifest
  addons/velero/1.8.1/install.sh
  addons/velero/template/base/Manifest.tmpl
  addons/velero/template/base/install.sh.tmpl
  bin/save-manifest-assets.sh
Labels: type::security, team::orange

#3035 report whether openebs is being installed using cstor vs localpv
  addons/openebs/1.12.0/install.sh
  addons/openebs/1.6.0/install.sh
  addons/openebs/2.6.0/install.sh
Labels: type::chore

#2931 Automated Kubernetes version update 1.24.2 1.23.8 1.22.11 1.21.14 1.20.15
  web/src/installers/versions.js
Labels: automated-pr, kubernetes

#2918 Automated Prometheus version update 0.57.0-36.0.3
  addons/prometheus/0.57.0-36.0.3/Manifest
  addons/prometheus/0.57.0-36.0.3/crds/crds.yaml
  addons/prometheus/0.57.0-36.0.3/crds/kustomization.yaml
  addons/prometheus/0.57.0-36.0.3/crds/preserveUnknown.yaml
  addons/prometheus/0.57.0-36.0.3/host-preflight.yaml
  addons/prometheus/0.57.0-36.0.3/install.sh
  addons/prometheus/0.57.0-36.0.3/nodeport-services.yaml
  addons/prometheus/0.57.0-36.0.3/operator/adapter.yaml
  addons/prometheus/0.57.0-36.0.3/operator/default.yaml
  addons/prometheus/0.57.0-36.0.3/operator/kustomization.yaml
  addons/prometheus/0.57.0-36.0.3/operator/longhorn.yaml
  addons/prometheus/0.57.0-36.0.3/operator/matchlabel-release.yaml
  addons/prometheus/0.57.0-36.0.3/operator/ns.yaml
  addons/prometheus/0.57.0-36.0.3/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.57.0-36.0.3/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus

#3038 log the start time of testgrid runs, and report logs earlier
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
Labels: type::chore

#3039 improve save-manifest-assets logic
  bin/save-manifest-assets.sh
Labels: type::chore

#3041 retry s3 uploads
  bin/upload-dist-staging.sh
  bin/upload-dist-versioned.sh
Labels: type::bug, bug::normal

#3044 Testgrid add unique test id for test instance
  testgrid/migrations/tables/testinstance.yaml
  testgrid/tgapi/pkg/cli/api/run.go
  testgrid/tgapi/pkg/handlers/ref_start.go
  testgrid/tgapi/pkg/persistence/pg.go
  testgrid/tgapi/pkg/testinstance/testinstance.go
  testgrid/tgapi/pkg/testinstance/types/types.go
  testgrid/tgrun/pkg/scheduler/scheduler.go
  testgrid/web/.nvmrc
  testgrid/web/Dockerfile.skaffold
  testgrid/web/package.json
  testgrid/web/src/components/containers/Run.jsx
  testgrid/web/src/components/views/InstanceTable.jsx
  testgrid/web/webpack.dev.config.js
Labels: type::chore

#3056 Optimize testgrid runcmd
  testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh
Labels: type::chore

#3052 More cpus for testgrid specs where needed
  addons/containerd/1.3.7/install.sh
  addons/containerd/1.3.9/install.sh
  addons/containerd/1.4.10/install.sh
  addons/containerd/1.4.11/install.sh
  addons/containerd/1.4.12/install.sh
  addons/containerd/1.4.13/install.sh
  addons/containerd/1.4.3/install.sh
  addons/containerd/1.4.4/install.sh
  addons/containerd/1.4.6/install.sh
  addons/containerd/1.4.8/install.sh
  addons/containerd/1.4.9/install.sh
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/template/base/install.sh
  addons/longhorn/template/testgrid/k8s-ctrd.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  scripts/common/docker.sh
  testgrid/specs/full.yaml
Labels: type::chore

#3066 Add debug info to release workflow
  bin/upload-dist-staging.sh
  bin/upload-dist-versioned.sh
Labels: type::chore

#3069 Add more debug info to release process
  bin/upload-dist-staging.sh
Labels: type::chore

#3068 allow openebs 3.x on k8s 1.22+
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature

#3054 Automated Velero version update 1.9.0
  addons/velero/1.9.0/Manifest
  addons/velero/1.9.0/install.sh
  addons/velero/1.9.0/restic-daemonset-privileged.yaml
  addons/velero/1.9.0/s3-migration-configmap.yaml
  addons/velero/1.9.0/tmpl-change-storageclass.yaml
  addons/velero/1.9.0/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.9.0/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.9.0/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.9.0/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.9.0/tmpl-kustomization.yaml
  addons/velero/1.9.0/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.9.0/tmpl-s3-migration-bsl.yaml
  addons/velero/1.9.0/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.9.0/tmpl-s3-migration-secret.yaml
  addons/velero/1.9.0/tmpl-velero-deployment-proxy.yaml
  addons/velero/1.9.0/velero-args-json-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero

#3071 Set AWS_REGION when deploying
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  bin/upload-dist-staging.sh
  bin/upload-dist-versioned.sh
Labels: type::chore

#3072 automated velero PRs should update plugin versions for the latest velero version
  addons/velero/template/generate.sh
Labels: type::chore

#3070 upgrade to openebs 3.2 from 1.12
  addons/openebs/2.12.9/install.sh
  addons/openebs/3.2.0/install.sh
  addons/openebs/template/base/install.sh
  addons/openebs/template/testgrid/k8s-docker-cstor.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::feature

#3076 allow rhel 8.6 and ol 8.6 to pass preflights
  scripts/common/preflights.sh
Labels: type::chore

#3078 latest openebs add-on in rke2 spec
  web/src/installers/index.ts
  web/src/test/installers/index.ts
Labels: type::bug, bug::normal
