Repository replicatedhq/kURL, pull requests merged in 2022-05, with the labels that each got.

#2875 No longer support ubuntu-16, pin containerd to latest
  web/src/installers/versions.js
Labels: type::chore

#2874 Create ARCHITECTURE.md
  ARCHITECTURE.md
Labels: type::chore, type::docs

#2876 Add missing NoExecute toleration to weave
  addons/weave/2.5.2/daemonset.yaml
  addons/weave/2.6.4/daemonset.yaml
  addons/weave/2.6.5/daemonset.yaml
Labels: type::bug, bug::normal

#2879 Update troubleshoot dep
  go.mod
  go.sum
  kurl_util/cmd/vendorflights/testdata/basic/expected_preflights.yaml
Labels: type::feature

#2881 Testgrid allow passing any flag to install command
  testgrid/specs/full.yaml
  testgrid/tgrun/pkg/runner/embed/runcmd.sh
  testgrid/tgrun/pkg/runner/runner.go
Labels: type::feature

#2877 added parameter to set --restic-timeout for velero
  addons/velero/1.2.0/install.sh
  addons/velero/1.2.0/velero-args-json-patch.yaml
  addons/velero/1.5.1/install.sh
  addons/velero/1.5.1/velero-args-json-patch.yaml
  addons/velero/1.5.3/install.sh
  addons/velero/1.5.3/velero-args-json-patch.yaml
  addons/velero/1.5.4/install.sh
  addons/velero/1.5.4/velero-args-json-patch.yaml
  addons/velero/1.6.0/install.sh
  addons/velero/1.6.0/velero-args-json-patch.yaml
  addons/velero/1.6.1/install.sh
  addons/velero/1.6.1/velero-args-json-patch.yaml
  addons/velero/1.6.2/install.sh
  addons/velero/1.6.2/velero-args-json-patch.yaml
  addons/velero/1.7.1/install.sh
  addons/velero/1.7.1/velero-args-json-patch.yaml
  addons/velero/template/base/install.sh.tmpl
  addons/velero/template/base/velero-args-json-patch.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/utilbinaries.sh
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature, team::orange

#2878 Fix check if enough space for docker to containerd migration
  addons/containerd/1.3.7/install.sh
  addons/containerd/1.3.9/install.sh
  addons/containerd/1.4.10/install.sh
  addons/containerd/1.4.11/install.sh
  addons/containerd/1.4.12/install.sh
  addons/containerd/1.4.13/install.sh
  addons/containerd/1.4.3/install.sh
  addons/containerd/1.4.4/install.sh
  addons/containerd/1.4.6/install.sh
  addons/containerd/1.4.8/install.sh
  addons/containerd/1.4.9/install.sh
  addons/containerd/template/base/install.sh
Labels: type::bug, bug::normal

#2882 test add ekco on upgrade
  addons/ekco/0.19.0/install.sh
  addons/ekco/template/testgrid/k8s-docker.yaml
Labels: type::bug, bug::normal, type::tests

#2884 Ensure openebs runs with critical priority
  addons/openebs/1.12.0/cstor-provisioner.yaml
  addons/openebs/1.12.0/localpv-provisioner.yaml
  addons/openebs/1.12.0/ndm.yaml
  addons/openebs/1.12.0/operator.yaml
  addons/openebs/1.12.0/snapshot-operator.yaml
  addons/openebs/1.6.0/cstor-provisioner.yaml
  addons/openebs/1.6.0/localpv-provisioner.yaml
  addons/openebs/1.6.0/ndm.yaml
  addons/openebs/1.6.0/operator.yaml
  addons/openebs/2.6.0/cstor-provisioner.yaml
  addons/openebs/2.6.0/operator.yaml
Labels: type::feature, team::orange

#2894 Display message if incompatible openebs config is chosen
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::chore, team::blue

#2886 Addon to setup k8s AWS cloud provider for kURL
  addons/aws/0.1.0/Manifest
  addons/aws/0.1.0/install.sh
  addons/aws/0.1.0/kubeadm-cluster-config-v1beta2.yml
  addons/aws/0.1.0/kubeadm-init-config-v1beta2.yml
  addons/aws/0.1.0/kubeadm-join-config-v1beta2.yaml
  addons/aws/0.1.0/kustomization.yaml
  addons/aws/0.1.0/storageclass.yaml
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/bashmerge/main_test.go
  kurl_util/cmd/yamltobash/main.go
  kurl_util/cmd/yamltobash/main_test.go
  kurlkinds/config/samples/cluster_v1beta1_installer_object.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  scripts/common/utilbinaries.sh
  scripts/distro/kubeadm/distro.sh
  scripts/kustomize/kubeadm/init-orig/kubeadm-cluster-config-v1beta2.yml
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature, team::blue

#2897 CVE scanning for severity HIGH,CRITICAL only
  .github/workflows/daily-scan-images.yaml
  addons/registry/build-images/s3cmd/Makefile
  addons/rook/1.0.4-14.2.21/build-images/ceph/Makefile
  addons/rook/1.0.4-14.2.21/build-images/rook-ceph/Makefile
  addons/rook/1.0.4/build-images/ceph/Makefile
  addons/rook/1.0.4/build-images/rook-ceph/Makefile
Labels: type::security

#2898 Fix code scanning sarif uri error
  bin/scan-images/matrix.js
Labels: type::security

#2896 Fix testgrid run k8s123-all-the-flags
  testgrid/specs/full.yaml
Labels: type::chore, type::tests

#2899 change the aws storageclass name from 'default' to 'aws-ebs'
  addons/aws/0.0.1/storageclass.yaml
  addons/aws/0.1.0/storageclass.yaml
Labels: type::feature, team::blue

#2895 Automated Contour version update 1.21.0
  addons/contour/1.21.0/Manifest
  addons/contour/1.21.0/contour.yaml
  addons/contour/1.21.0/install.sh
  addons/contour/1.21.0/patches/job-image.yaml
  addons/contour/1.21.0/patches/resource-limits.yaml
  addons/contour/1.21.0/tmpl-configmap.yaml
  addons/contour/1.21.0/tmpl-kustomization.yaml
  addons/contour/1.21.0/tmpl-namespace.yaml
  addons/contour/1.21.0/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour

#2697 Automated Velero version update 1.8.1
  addons/velero/1.8.1/Manifest
  addons/velero/1.8.1/install.sh
  addons/velero/1.8.1/restic-daemonset-privileged.yaml
  addons/velero/1.8.1/s3-migration-configmap.yaml
  addons/velero/1.8.1/tmpl-change-storageclass.yaml
  addons/velero/1.8.1/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.8.1/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.8.1/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.8.1/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.8.1/tmpl-kustomization.yaml
  addons/velero/1.8.1/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.8.1/tmpl-s3-migration-bsl.yaml
  addons/velero/1.8.1/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.8.1/tmpl-s3-migration-secret.yaml
  addons/velero/1.8.1/tmpl-velero-deployment-proxy.yaml
  addons/velero/1.8.1/velero-args-json-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero

#2901 Report started testgrid
  testgrid/tgrun/pkg/runner/runner.go
Labels: type::bug, bug::regression

#2883 remove debug comment
  .github/workflows/test-addon-pr.yaml
  addons/ekco/0.19.0/install.sh
Labels: type::chore

#2904 fix less command on amazon linux 2
  Makefile
  bundles/k8s-rhel7-force/Dockerfile
  go.sum
  scripts/common/kubernetes.sh
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal, team::blue

#2912 update addon/aws/categories.json
  .gitignore
  addons/aws/categories.json
Labels: type::chore, team::blue

#2915 Revert "fix less command on amazon linux 2"
  Makefile
  bundles/k8s-rhel7-force/Dockerfile
  go.sum
  scripts/common/kubernetes.sh
  testgrid/specs/full.yaml
Labels: type::chore

#2854 Automated Kubernetes version update 1.23.6 1.22.9 1.21.12 1.20.15
  packages/kubernetes/1.21.12/Manifest
  packages/kubernetes/1.21.12/conformance/Manifest
  packages/kubernetes/1.22.9/Manifest
  packages/kubernetes/1.22.9/conformance/Manifest
  packages/kubernetes/1.23.6/Manifest
  packages/kubernetes/1.23.6/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes

#2923 add automation for kubernetes 1.24.x versions
  packages/kubernetes/template/script.sh
  web/src/installers/versions.js
Labels: type::chore, team::blue

#2924 import reporting functions in tasks.sh
  scripts/tasks.sh
Labels: type::bug, bug::regression, team::support

#2925 Automated Kubernetes version update 1.24.0 1.23.6 1.22.9 1.21.12 1.20.15
  packages/kubernetes/1.24.0/Manifest
  packages/kubernetes/1.24.0/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes

#2928 May24 dependabot merge
  .github/workflows/build-image.yaml
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-package-staging.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cron-rebuild-packages-prod.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/daily-scan-images.yaml
  .github/workflows/daily-testgrid.yaml
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  .github/workflows/deploy-testgrid.yaml
  .github/workflows/test-addon-pr.yaml
  .github/workflows/update-antrea.yaml
  .github/workflows/update-containerd.yaml
  .github/workflows/update-contour.yaml
  .github/workflows/update-goldpinger.yaml
  .github/workflows/update-kotsadm.yaml
  .github/workflows/update-kubernetes.yaml
  .github/workflows/update-longhorn.yaml
  .github/workflows/update-prometheus.yaml
  .github/workflows/update-rook.yaml
  .github/workflows/update-sonobuoy.yaml
  .github/workflows/update-velero.yaml
  .github/workflows/update-weave.yaml
  go.mod
  go.sum
  testgrid/web/package-lock.json
  testgrid/web/package.json
  web/package-lock.json
  web/package.json
Labels: type::chore, team::orange

#2937 Start tgrun on reboot
  testgrid/deploy/tg-script.sh
Labels: type::chore

#2933 Ekco 0.19.1
  addons/ekco/0.19.1/Manifest
  addons/ekco/0.19.1/README.md
  addons/ekco/0.19.1/deployment.yaml
  addons/ekco/0.19.1/ekco-purge-node.sh
  addons/ekco/0.19.1/install.sh
  addons/ekco/0.19.1/kustomization.yaml
  addons/ekco/0.19.1/namespace.yaml
  addons/ekco/0.19.1/rbac-rook.yaml
  addons/ekco/0.19.1/rbac.yaml
  addons/ekco/0.19.1/reboot/ekco-reboot-containerd.service
  addons/ekco/0.19.1/reboot/ekco-reboot.service
  addons/ekco/0.19.1/reboot/shutdown.sh
  addons/ekco/0.19.1/reboot/startup.sh
  addons/ekco/0.19.1/regen-cert-pod.yaml
  addons/ekco/0.19.1/rolebinding-rook.yaml
  addons/ekco/0.19.1/rolebinding.yaml
  addons/ekco/0.19.1/rotate-certs-rbac.yaml
  addons/ekco/0.19.1/tmpl-configmap.yaml
  addons/ekco/0.19.1/upgrade/ekco-upgrade.service
  addons/ekco/0.19.1/upgrade/ekco-upgrade.timer
  addons/ekco/0.19.1/upgrade/upgrade.sh
  web/src/installers/versions.js
Labels: type::security

#2939 ekco-enable-internal-load-balancer flag
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/bashmerge/main_test.go
Labels: type::feature

#2936 use amazonlinux and install ncurses-compat-libs to fix less command
  Makefile
  bundles/k8s-rhel7-force/Dockerfile
  scripts/common/kubernetes.sh
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal, team::blue

#2715 only load kubectl completion if `bash-completion` is installed
  scripts/common/common.sh
Labels: type::chore

#2943 Add cni plugin to less_command test
  testgrid/specs/full.yaml
Labels: type::tests, team::blue

#2940 security update for Docker images
  deploy/Dockerfile-slim
  kurl_util/deploy/Dockerfile
  testgrid/web/package-lock.json
  web/Dockerfile
  web/package-lock.json
Labels: type::chore, team::orange

#2941 Allow including arbitrary characters in the url
  web/src/controllers/InstallerAPI.ts
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature, team::orange

#2938 Added support for Kubernetes 1.24.0
  scripts/install.sh
  scripts/join.sh
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature, team::blue

#2947 Velero replicated/local-volume-provider:v0.3.4
  addons/velero/1.8.1/Manifest
  addons/velero/1.8.1/install.sh
  addons/velero/template/base/Manifest.tmpl
  addons/velero/template/base/install.sh.tmpl
Labels: type::security

#2951 Ensure /usr/local/bin is in the path
  addons/kotsadm/alpha/install.sh
  scripts/common/reporting.sh
  scripts/install.sh
  scripts/join.sh
  scripts/tasks.sh
  scripts/upgrade.sh
Labels: type::bug, bug::regression

#2960 Fix ekco-enable-internal-load-balancer flag
  scripts/common/utilbinaries.sh
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::feature

#2950 bump newrelic and @tsed/platform-express to eliminate CVE
  web/package-lock.json
  web/package.json
Labels: type::chore, team::orange

#2962 endpoints must report healthy during kurl server rollout completes
  cmd/server/main.go
  kustomize/base/deployment.yaml
Labels: type::chore, team::blue

#2965 Ekco addon 0.19.2
  addons/ekco/0.19.2/Manifest
  addons/ekco/0.19.2/README.md
  addons/ekco/0.19.2/deployment.yaml
  addons/ekco/0.19.2/ekco-purge-node.sh
  addons/ekco/0.19.2/install.sh
  addons/ekco/0.19.2/kustomization.yaml
  addons/ekco/0.19.2/namespace.yaml
  addons/ekco/0.19.2/rbac-rook.yaml
  addons/ekco/0.19.2/rbac.yaml
  addons/ekco/0.19.2/reboot/ekco-reboot-containerd.service
  addons/ekco/0.19.2/reboot/ekco-reboot.service
  addons/ekco/0.19.2/reboot/shutdown.sh
  addons/ekco/0.19.2/reboot/startup.sh
  addons/ekco/0.19.2/regen-cert-pod.yaml
  addons/ekco/0.19.2/rolebinding-rook.yaml
  addons/ekco/0.19.2/rolebinding.yaml
  addons/ekco/0.19.2/rotate-certs-rbac.yaml
  addons/ekco/0.19.2/tmpl-configmap.yaml
  addons/ekco/0.19.2/upgrade/ekco-upgrade.service
  addons/ekco/0.19.2/upgrade/ekco-upgrade.timer
  addons/ekco/0.19.2/upgrade/upgrade.sh
  web/src/installers/versions.js
Labels: type::feature, team::blue
