Repository replicatedhq/kURL, pull requests merged in 2022-11, with the labels that each got.

#3656 Update to kurlsh/s3cmd:20221029-37473ee image
  addons/registry/2.8.1/Manifest
  addons/registry/2.8.1/patch-deployment-migrate-s3.yaml
  addons/registry/2.8.1/patch-deployment-velero.yaml
  addons/registry/2.8.1/service.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
Labels: type::security, kurl::type::feature

#3557 Automated Goldpinger version update 3.7.0-5.5.0
  addons/goldpinger/3.7.0-5.5.0/Manifest
  addons/goldpinger/3.7.0-5.5.0/goldpinger.yaml
  addons/goldpinger/3.7.0-5.5.0/install.sh
  addons/goldpinger/3.7.0-5.5.0/kustomization.yaml
  addons/goldpinger/3.7.0-5.5.0/servicemonitor.yaml
  web/src/installers/versions.js
Labels: automated-pr, goldpinger, type::chore, kurl::type::feature, auto-merge

#3659 Rook 1.8+ not supported on 3.10.0-693.el7.x86_64 kernel
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3658 Fix latest weave 2.6.5 version
  addons/weave/template/generate.sh
  web/src/installers/versions.js
Labels: type::bug, bug::normal

#3661 Testgrid on pr test for migration from rook to openebs
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::chore

#3663 Wait longer for openebs validatingwebhookconfigurations
  addons/openebs/1.12.0/install.sh
  addons/openebs/2.12.9/install.sh
  addons/openebs/2.6.0/install.sh
  addons/openebs/3.2.0/install.sh
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
Labels: type::bug, bug::normal

#3662 Automated Sonobuoy version update 0.56.11
  addons/sonobuoy/0.56.11/Manifest
  addons/sonobuoy/0.56.11/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#3665 Testgrid checker merge pull request and use github app for auth
  .github/actions/testgrid-checker/action.yml
  .github/actions/testgrid-checker/dist/index.js
  .github/actions/testgrid-checker/github.js
  .github/actions/testgrid-checker/index.js
  .github/actions/testgrid-checker/package-lock.json
  .github/actions/testgrid-checker/package.json
  .github/actions/testgrid-checker/pullrequests.js
  .github/actions/testgrid-checker/test.js
  .github/workflows/test-testgrid-results.yaml
Labels: type::chore

#3666 export VERSION_TAG when building prod packages
  .github/workflows/build-package-prod.yaml
  kurl_util/Makefile
Labels: type::bug, bug::normal

#3669 Fix testgrid auto-merge functionality
  .github/actions/testgrid-checker/pullrequests.js
Labels: type::chore

#3670 Fix testgrid auto-merge functionality
  .github/actions/testgrid-checker/dist/index.js
  .github/actions/testgrid-checker/dist/package.json
  .github/actions/testgrid-checker/github.js
  .github/actions/testgrid-checker/pullrequests.js
Labels: type::chore

#3667 Automated EKCO version update 0.24.1
  addons/ekco/0.24.1/Manifest
  addons/ekco/0.24.1/README.md
  addons/ekco/0.24.1/deployment.yaml
  addons/ekco/0.24.1/ekco-purge-node.sh
  addons/ekco/0.24.1/install.sh
  addons/ekco/0.24.1/kustomization.yaml
  addons/ekco/0.24.1/namespace.yaml
  addons/ekco/0.24.1/rbac-minio.yaml
  addons/ekco/0.24.1/rbac-rook.yaml
  addons/ekco/0.24.1/rbac.yaml
  addons/ekco/0.24.1/reboot/ekco-reboot-containerd.service
  addons/ekco/0.24.1/reboot/ekco-reboot.service
  addons/ekco/0.24.1/reboot/shutdown.sh
  addons/ekco/0.24.1/reboot/startup.sh
  addons/ekco/0.24.1/regen-cert-pod.yaml
  addons/ekco/0.24.1/rolebinding-minio.yaml
  addons/ekco/0.24.1/rolebinding-rook.yaml
  addons/ekco/0.24.1/rolebinding.yaml
  addons/ekco/0.24.1/rotate-certs-rbac.yaml
  addons/ekco/0.24.1/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature, auto-merge

#3664 ADR 5: Host Packages - proposed changes
  docs/arch/adr-005-host-packages.md
Labels: type::chore

#3671 Fix testgrid-checker undefined variables
  .github/actions/testgrid-checker/dist/index.js
  .github/actions/testgrid-checker/pullrequests.js
Labels: type::chore

#3668 Correct sonobuoy spelling
  .github/workflows/update-sonobuoy.yaml
Labels: type::chore

#3675 Remove support for k3s and rke2 add-ons
  ARCHITECTURE.md
  Makefile
  addons/rook/template/base/install.sh
  addons/rook/template/base/operator/patches/deployment-rke2.yaml
  addons/velero/template/base/install.tmpl.sh
  bin/generate-addons.js
  bin/list-all-packages.sh
  bundles/k3s-rhel7-force/Dockerfile
  bundles/k3s-rhel7-force/rancher-k3s-common.repo.tmpl
  bundles/k3s-rhel7/Dockerfile
  bundles/k3s-rhel7/rancher-k3s-common.repo.tmpl
  bundles/k3s-rhel8/Dockerfile
  bundles/k3s-rhel8/rancher-k3s-common.repo.tmpl
  bundles/rke2-rhel7-force/Dockerfile
  bundles/rke2-rhel7-force/rancher-rke2.repo.tmpl
  bundles/rke2-rhel7/Dockerfile
  bundles/rke2-rhel7/rancher-rke2.repo.tmpl
  bundles/rke2-rhel8/Dockerfile
  bundles/rke2-rhel8/rancher-rke2.repo.tmpl
  go.mod
  go.sum
  kurl_util/cmd/yamltobash/main.go
  kurl_util/cmd/yamltobash/main_test.go
  kurl_util/cmd/yamltobash/testdata/expected/weave_no_masq_local_default
  kurl_util/cmd/yamltobash/testdata/expected/weave_no_masq_local_unset
  packages/k-3-s/v1.19.7-k3s1/Manifest
  packages/k-3-s/v1.23.3-k3s1/Manifest
  packages/kubernetes/1.18.13/conformance/Manifest
  packages/rke-2/v1.18.13-rke2r1/Manifest
  packages/rke-2/v1.19.7-rke2r1/Manifest
  packages/rke-2/v1.22.6-rke2r1/Manifest
  scripts/common/common.sh
  scripts/common/k3s.sh
  scripts/common/kubernetes.sh
  scripts/common/rke2.sh
  scripts/distro/k3s/distro-test.sh
  scripts/distro/k3s/distro.sh
  scripts/distro/kubeadm/distro.sh
  scripts/distro/rke2/distro-test.sh
  scripts/distro/rke2/distro.sh
  scripts/install.sh
  scripts/join.sh
  scripts/tasks.sh
  scripts/upgrade.sh
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/versions.js
Labels: type::feature

#3673 Automated Flannel version update 0.20.1
  addons/flannel/0.20.1/Manifest
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.1/kubeadm.yaml
  addons/flannel/0.20.1/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.20.1/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.20.1/yaml/kube-flannel.yml
  addons/flannel/0.20.1/yaml/kustomization.yaml
  addons/flannel/0.20.1/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, auto-merge, flannel

#3678 wipe prometheus CRD last-applied-configuration before update
  addons/prometheus/template/base/install.sh
Labels: type::bug, bug::normal

#3677 :bug: fix docker install steps to build bundle/package/images
  bundles/docker-ubuntu1604/Dockerfile
  bundles/docker-ubuntu1804/Dockerfile
  bundles/docker-ubuntu2004/Dockerfile
  bundles/docker-ubuntu2204/Dockerfile
Labels: bug::normal, type::chore

#3682 Run add-on update workflows on weekdays
  .github/workflows/update-antrea.yaml
  .github/workflows/update-containerd.yaml
  .github/workflows/update-contour.yaml
  .github/workflows/update-ekco.yaml
  .github/workflows/update-flannel.yaml
  .github/workflows/update-goldpinger.yaml
  .github/workflows/update-kubernetes.yaml
  .github/workflows/update-longhorn.yaml
  .github/workflows/update-minio.yaml
  .github/workflows/update-openebs.yaml
  .github/workflows/update-prometheus.yaml
  .github/workflows/update-registry.yaml
  .github/workflows/update-rook.yaml
  .github/workflows/update-sonobuoy.yaml
  .github/workflows/update-velero.yaml
  .github/workflows/update-weave.yaml
Labels: type::chore

#3689 Transition FOSSA to centrally-managed action
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#3681 Fix build-test-success is skipped on failure
  .github/workflows/build-test.yaml
Labels: type::chore

#3694 check out merge ref
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#3697 Fix install mode when installing shunit2
  Makefile
Labels: type::chore

#3696 OpenEBS should be the default storage class if no other
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::bug, bug::normal

#3693 scale down ekco before running rgw to minio migration
  scripts/common/object_store.sh
Labels: type::bug, bug::normal

#3692 add help to allow we doc the makefile targets and a few clean ups
  .github/workflows/build-test.yaml
  Makefile
Labels: type::chore

#3699 add kotsadm-rqlite to no_proxy list
  scripts/common/proxy.sh
Labels: type::bug, bug::regression

#3701 add an 'airgap upgrade k8s and docker->containerd' on-merge test
  testgrid/specs/deploy.yaml
Labels: type::chore

#3703 doc/contributing guide: just change the layout for less back and forwards
  CONTRIBUTING.md
Labels: type::chore

#3704 (addon/containerd): replace apt-key which is deprecated.
  addons/containerd/template/Dockerfile.ubuntu16
  addons/containerd/template/Dockerfile.ubuntu18
  addons/containerd/template/Dockerfile.ubuntu20
  addons/containerd/template/Dockerfile.ubuntu22
Labels: containerd, type::chore

#3700 Automated Kubernetes version update 1.25.4 1.24.8 1.23.14 1.22.16
  packages/kubernetes/1.22.16/Manifest
  packages/kubernetes/1.22.16/conformance/Manifest
  packages/kubernetes/1.23.14/Manifest
  packages/kubernetes/1.23.14/conformance/Manifest
  packages/kubernetes/1.24.8/Manifest
  packages/kubernetes/1.24.8/conformance/Manifest
  packages/kubernetes/1.25.4/Manifest
  packages/kubernetes/1.25.4/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#3706 doc/contributing: Clarifies that virtual box works only for intel arch
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3716 Do not deploy to staging when changing more docs files
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3722 list every make command required to build the example spec
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3711 doc/contributing: add export default platform envvar for local env
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3714 docs/contributing: add info for replicated's about gcp/codeserver env
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3679 Automated Velero version update 1.9.3
  addons/velero/1.9.3/Manifest
  addons/velero/1.9.3/install.sh
  addons/velero/1.9.3/restic-daemonset-privileged.yaml
  addons/velero/1.9.3/s3-migration-configmap.yaml
  addons/velero/1.9.3/tmpl-change-storageclass.yaml
  addons/velero/1.9.3/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.9.3/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.9.3/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.9.3/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.9.3/tmpl-kustomization.yaml
  addons/velero/1.9.3/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.9.3/tmpl-s3-migration-bsl.yaml
  addons/velero/1.9.3/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.9.3/tmpl-s3-migration-secret.yaml
  addons/velero/1.9.3/tmpl-velero-deployment-proxy.yaml
  addons/velero/1.9.3/velero-args-json-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3723 Fix cron rook update missing version
  addons/rook/template/generate.sh
Labels: type::chore

#3709 doc/contributing: adding teardown step/info
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3707 doc/contributing: add info about supportability and pre-requirements
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3724 openebs should test upgrading from the latest released version
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::chore

#3674 feat: checking for disk space before migrating
  go.mod
  go.sum
  kurl_util/cmd/pvmigrate/main.go
  pkg/cluster/space/openebs.go
  pkg/cluster/space/openebs_test.go
  pkg/cluster/space/rook.go
  pkg/cluster/space/rook_test.go
  pkg/k8sutil/job.go
  pkg/k8sutil/pod.go
  pkg/k8sutil/pod_test.go
  pkg/k8sutil/storage.go
  pkg/k8sutil/storage_test.go
Labels: type::feature

#3733 do not bail when installing RHEL and OL 8.7
  scripts/common/preflights.sh
Labels: type::chore, kurl::type::feature

#3702 weave-to-flannel ADR
  docs/arch/adr-008-weave-to-flannel-migration.md
Labels: type::chore

#3735 Accept weave-to-flannel migration ADR
  docs/arch/adr-008-weave-to-flannel-migration.md
Labels: type::chore

#3729 doc/contributing: add info to track how the things work
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3732 docs/contributing: just add the link for the task
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3731 doc/contributing: track info about how to do the tests with previous versions
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3710 doc/contributing: update/supplement example to test install
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3730 docs/contributing: clarifies what is or not possible to do from macos dev env
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3727 doc/contributing: add info about how to run preflight checks via FAQ
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3708 docs/contributing: add faq section
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3737 bundles/k8s: replace apt-key which is deprecated to use gpg
  bundles/k8s-ubuntu1604/Dockerfile
  bundles/k8s-ubuntu1804/Dockerfile
  bundles/k8s-ubuntu2004/Dockerfile
  bundles/k8s-ubuntu2204/Dockerfile
  packages/kubernetes/template/Dockerfile
Labels: type::chore

#3736 Automated Velero version update 1.9.3
  addons/velero/1.9.3/Manifest
  addons/velero/1.9.3/install.sh
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3738 doc/contributing: remove duplication
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3741 Revert "chore: add a helper to test the project and make eaiser the p…
  CONTRIBUTING.md
  Makefile
  hack/testdata/sample/Manifest
  scripts/Manifest
Labels: type::bug, bug::regression

#3742 gitignore scripts/Manifest, as changes to it are far rarer than accidental commits
  .gitignore
Labels: type::chore

#3740 Fix cron rook update
  addons/rook/template/generate.sh
Labels: type::chore

#3739 docs/contributing: faq: track info about path used to run the scripts
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3747 bug: verify if port 9090 is available (rook)
  addons/rook/1.9.12/host-preflight.yaml
  addons/rook/template/base/host-preflight.yaml
Labels: type::feature

#3748 yumol lvm2 missing from Rook version 1.0.4-14.2.21
  addons/rook/1.0.4-14.2.21/Manifest
Labels: type::bug, bug::normal

#3728 doc/contributing: info about where the docs are located
  CONTRIBUTING.md
Labels: type::chore, type::docs

#3753 Improved add-on documentation including requirements
  ARCHITECTURE.md
  addons/README.md
Labels: type::chore

#3751 Use OpenEBS app version as add-on version
  addons/openebs/template/generate.sh
Labels: type::chore

#3758 Only create updates for openebs version 3
  .github/workflows/update-openebs.yaml
Labels: type::chore

#3752 Enable OpenEBS add-on auto-merge
  .github/workflows/update-openebs.yaml
Labels: type::chore

#3759 Remove the rest of openebs 2 add-on version generation
  .github/workflows/update-openebs.yaml
Labels: type::chore

#3763 Merged Patch weave images for vulnerabilities
  addons/weave/2.8.1-20221122/Manifest
  addons/weave/2.8.1-20221122/host-preflight.yaml
  addons/weave/2.8.1-20221122/install.sh
  addons/weave/2.8.1-20221122/kustomization.yaml
  addons/weave/2.8.1-20221122/patch-daemonset.yaml
  addons/weave/2.8.1-20221122/patch-encrypt.yaml
  addons/weave/2.8.1-20221122/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.8.1-20221122/tmpl-patch-no-masq-local.yaml
  addons/weave/2.8.1-20221122/tmpl-secret.yaml
  addons/weave/2.8.1-20221122/weave-daemonset-k8s-1.11.yaml
  web/src/installers/versions.js
Labels: type::security

#3761 Automated Sonobuoy version update 0.56.12
  addons/sonobuoy/0.56.12/Manifest
  addons/sonobuoy/0.56.12/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#3750 Automated Containerd version update 1.6.10
  addons/containerd/1.6.10/Manifest
  addons/containerd/1.6.10/crictl.yaml
  addons/containerd/1.6.10/host-preflight.yaml
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.10/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.10/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#3765 ensure build with the latest built image version for weave and waveexec patches
  addons/weave/2.8.1-20221122/Manifest
  addons/weave/2.8.1-20221122/patch-daemonset.yaml
  addons/weave/2.8.1-20221122/weave-daemonset-k8s-1.11.yaml
Labels: type::security

#3764 fix/issue: HashiCorp Vault vulnerabilities
  go.mod
  go.sum
Labels: type::chore

#3749 Document object storage architecture and deployment and releases
  ARCHITECTURE.md
  addons/README.md
Labels: type::chore

#3768 addons/weave: patch release 2.6.5-20221122 to address cve
  addons/weave/2.6.5-20221122/Manifest
  addons/weave/2.6.5-20221122/host-preflight.yaml
  addons/weave/2.6.5-20221122/install.sh
  addons/weave/2.6.5-20221122/kustomization.yaml
  addons/weave/2.6.5-20221122/patch-daemonset.yaml
  addons/weave/2.6.5-20221122/patch-encrypt.yaml
  addons/weave/2.6.5-20221122/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.6.5-20221122/tmpl-patch-no-masq-local.yaml
  addons/weave/2.6.5-20221122/tmpl-secret.yaml
  addons/weave/2.6.5-20221122/weave-daemonset-k8s-1.11.yaml
  web/src/installers/versions.js
Labels: type::security

#3770 fix ubuntu dockerfiles to not requires dialog interaction
  addons/containerd/template/Dockerfile.ubuntu16
  addons/containerd/template/Dockerfile.ubuntu18
  addons/containerd/template/Dockerfile.ubuntu20
  addons/containerd/template/Dockerfile.ubuntu22
  bundles/docker-ubuntu1604/Dockerfile
  bundles/docker-ubuntu1804/Dockerfile
  bundles/docker-ubuntu2004/Dockerfile
  bundles/docker-ubuntu2204/Dockerfile
  bundles/helm/Dockerfile
  bundles/k8s-ubuntu1604/Dockerfile
  bundles/k8s-ubuntu1804/Dockerfile
  bundles/k8s-ubuntu2004/Dockerfile
  bundles/k8s-ubuntu2204/Dockerfile
  bundles/krew/Dockerfile
Labels: type::chore

#3744 add ci test to not allow merge changes in the script/Manifest by mistake
  .gitignore
  CONTRIBUTING.md
  Makefile
  hack/testdata/manifest/clean
Labels: type::chore

#3771 Update go.mod dependencies to address vulnerabilities
  go.mod
  go.sum
Labels: type::chore

#3772 feat: accept environment vars as well as flags
  pkg/cli/sync_object_store.go
Labels: type::feature

#3766 fix: ensure that runc version added is the same used/supported by
  addons/containerd/1.5.10/Manifest
  addons/containerd/1.5.11/Manifest
  addons/containerd/1.6.10/Manifest
  addons/containerd/1.6.4/Manifest
  addons/containerd/1.6.6/Manifest
  addons/containerd/1.6.7/Manifest
  addons/containerd/1.6.8/Manifest
  addons/containerd/1.6.9/Manifest
  addons/containerd/template/Dockerfile.ubuntu22
  addons/containerd/template/script.sh
Labels: type::bug, bug::normal

#3778 Normalize rook version for comparison
  pkg/rook/upgrade.go
  pkg/rook/upgrade_test.go
Labels: type::bug, bug::normal

#3779 Change polling interval for new rook and ceph versions from 1 second to 10 seconds
  pkg/rook/upgrade.go
Labels: type::bug, bug::normal

#3780 Rook add-on scales down ekco operator without scaling it back up
  addons/ekco/0.25.0/deployment.yaml
  addons/ekco/template/base/deployment.yaml
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  scripts/common/kubernetes.sh
Labels: type::bug, bug::regression

#3782 fix: ensure that binaries installed in usr/local/bin are owned by root
  scripts/common/plugins.sh
Labels: type::security

#3776 doc: add addon content from the website into the CONTRIBUTING guide
  CONTRIBUTING.md
  README.md
  addons/README.md
Labels: type::chore, type::docs

#3777 Automated EKCO version update 0.26.0
  addons/ekco/0.26.0/Manifest
  addons/ekco/0.26.0/README.md
  addons/ekco/0.26.0/deployment.yaml
  addons/ekco/0.26.0/ekco-purge-node.sh
  addons/ekco/0.26.0/install.sh
  addons/ekco/0.26.0/kustomization.yaml
  addons/ekco/0.26.0/namespace.yaml
  addons/ekco/0.26.0/rbac-kotsadm.yaml
  addons/ekco/0.26.0/rbac-minio.yaml
  addons/ekco/0.26.0/rbac-rook.yaml
  addons/ekco/0.26.0/rbac.yaml
  addons/ekco/0.26.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.26.0/reboot/ekco-reboot.service
  addons/ekco/0.26.0/reboot/shutdown.sh
  addons/ekco/0.26.0/reboot/startup.sh
  addons/ekco/0.26.0/regen-cert-pod.yaml
  addons/ekco/0.26.0/rolebinding-kotsadm.yaml
  addons/ekco/0.26.0/rolebinding-minio.yaml
  addons/ekco/0.26.0/rolebinding-rook.yaml
  addons/ekco/0.26.0/rolebinding.yaml
  addons/ekco/0.26.0/rotate-certs-rbac.yaml
  addons/ekco/0.26.0/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#3786 Automated EKCO version update 0.26.1
  addons/ekco/0.26.1/Manifest
  addons/ekco/0.26.1/README.md
  addons/ekco/0.26.1/deployment.yaml
  addons/ekco/0.26.1/ekco-purge-node.sh
  addons/ekco/0.26.1/install.sh
  addons/ekco/0.26.1/kustomization.yaml
  addons/ekco/0.26.1/namespace.yaml
  addons/ekco/0.26.1/rbac-kotsadm.yaml
  addons/ekco/0.26.1/rbac-minio.yaml
  addons/ekco/0.26.1/rbac-rook.yaml
  addons/ekco/0.26.1/rbac.yaml
  addons/ekco/0.26.1/reboot/ekco-reboot-containerd.service
  addons/ekco/0.26.1/reboot/ekco-reboot.service
  addons/ekco/0.26.1/reboot/shutdown.sh
  addons/ekco/0.26.1/reboot/startup.sh
  addons/ekco/0.26.1/regen-cert-pod.yaml
  addons/ekco/0.26.1/rolebinding-kotsadm.yaml
  addons/ekco/0.26.1/rolebinding-minio.yaml
  addons/ekco/0.26.1/rolebinding-rook.yaml
  addons/ekco/0.26.1/rolebinding.yaml
  addons/ekco/0.26.1/rotate-certs-rbac.yaml
  addons/ekco/0.26.1/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature
