Repository replicatedhq/kURL, pull requests merged in 2022-09, with the labels that each got.

#3399 [CONTRIBUTING.md] Add note to install host packages prior to installing add-on
  CONTRIBUTING.md
Labels: type::chore

#3407 improve the dependency resolution behavior of golang make commands
  Makefile
Labels: type::chore

#3410 include hostpath in expected results for migrate unit tests
  pkg/rook/migrate_test.go
Labels: type::chore

#3411 use type::feature label for new kots versions
  .github/workflows/update-kotsadm.yaml
Labels: type::chore

#3366 Automated MinIO version update RELEASE.2022-09-01T23-53-36Z
  addons/minio/2022-09-01T23-53-36Z/Manifest
  addons/minio/2022-09-01T23-53-36Z/deployment.yaml
  addons/minio/2022-09-01T23-53-36Z/install.sh
  addons/minio/2022-09-01T23-53-36Z/service.yaml
  addons/minio/2022-09-01T23-53-36Z/tmpl-creds-secret.yaml
  addons/minio/2022-09-01T23-53-36Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-09-01T23-53-36Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-09-01T23-53-36Z/tmpl-kustomization.yaml
  addons/minio/2022-09-01T23-53-36Z/tmpl-namespace.yaml
  addons/minio/2022-09-01T23-53-36Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio

#3404 Testgrid longhorn should use k8s 1.23.x
  addons/longhorn/template/testgrid/k8s-ctrd.yaml
  testgrid/specs/full.yaml
  testgrid/specs/latest.yaml
Labels: type::chore

#3414 Use fixed-strings grep in kubeadm_registry_containerd_configure
  scripts/distro/kubeadm/distro.sh
Labels: type::chore

#3412 Preflight check for supported docker versions on ubuntu 22.04
  pkg/preflight/assets/host-preflights.yaml
  pkg/preflight/builtin_test.go
Labels: type::feature

#3421 Enable containerd 1.6.x to be latest
  addons/containerd/template/script.sh
  addons/containerd/template/testgrid/k8s-docker.yaml
  pkg/preflight/assets/host-preflights.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3371 Automated Containerd version update 1.6.8
  addons/containerd/1.6.8/Manifest
  addons/containerd/1.6.8/crictl.yaml
  addons/containerd/1.6.8/host-preflight.yaml
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.8/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.8/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore

#3422 Validate version tag in CI and bail if necessary
  .github/workflows/deploy-prod.yaml
  bin/verify-tag.sh
Labels: type::chore

#3424 Add cert-manager 1.9.1
  addons/cert-manager/1.9.1/Manifest
  addons/cert-manager/1.9.1/cert-manager.yaml
  addons/cert-manager/1.9.1/install.sh
  addons/cert-manager/1.9.1/kustomization.yaml
  addons/cert-manager/template/testgrid/k8s-docker.yaml
  web/src/installers/versions.js
Labels: type::feature

#3423 Add cert-manager 1.9.1
  addons/cert-manager/1.9.1/Manifest
  addons/cert-manager/1.9.1/cert-manager.yaml
  addons/cert-manager/1.9.1/install.sh
  addons/cert-manager/1.9.1/kustomization.yaml
  web/src/installers/versions.js
Labels: type::feature

#3425 Automated MinIO version update RELEASE.2022-09-07T22-25-02Z
  addons/minio/2022-09-07T22-25-02Z/Manifest
  addons/minio/2022-09-07T22-25-02Z/deployment.yaml
  addons/minio/2022-09-07T22-25-02Z/install.sh
  addons/minio/2022-09-07T22-25-02Z/service.yaml
  addons/minio/2022-09-07T22-25-02Z/tmpl-creds-secret.yaml
  addons/minio/2022-09-07T22-25-02Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-09-07T22-25-02Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-09-07T22-25-02Z/tmpl-kustomization.yaml
  addons/minio/2022-09-07T22-25-02Z/tmpl-namespace.yaml
  addons/minio/2022-09-07T22-25-02Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio

#3426 Automated Contour version update 1.22.1
  addons/contour/1.22.1/Manifest
  addons/contour/1.22.1/contour.yaml
  addons/contour/1.22.1/install.sh
  addons/contour/1.22.1/patches/job-image.yaml
  addons/contour/1.22.1/patches/resource-limits.yaml
  addons/contour/1.22.1/tmpl-configmap.yaml
  addons/contour/1.22.1/tmpl-kustomization.yaml
  addons/contour/1.22.1/tmpl-namespace.yaml
  addons/contour/1.22.1/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore

#3429 Allow upgrading certmanager 1.0 to 1.9
  addons/cert-manager/1.0.3/install.sh
  addons/cert-manager/1.9.1/install.sh
  addons/cert-manager/template/testgrid/k8s-docker.yaml
Labels: type::feature

#3430 Deploy workflow to set current version in s3
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3413 Prompt to load images before running Rook 1.0 to 1.4 migration
  pkg/cli/cluster.go
  pkg/cli/cluster_images.go
  pkg/cli/commands.go
  pkg/cli/rook_wait_for_version.go
  pkg/cluster/nodes.go
  pkg/cluster/nodes_test.go
  pkg/rook/migrate_test.go
  pkg/rook/testfiles/static.go
  pkg/rook/testfiles/upgradedNode.json
  scripts/common/rook.sh
Labels: type::feature

#3428 chore: migrating testgrid to k8s 1.24.x
  addons/containerd/template/testgrid/k8s-docker.yaml
  addons/ekco/template/testgrid/k8s-docker.yaml
  addons/longhorn/template/testgrid/k8s-ctrd.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/sonobuoy/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/latest.yaml
  web/src/installers/index.ts
Labels: type::chore

#3432 chore: fix testgrid for k8s 1.24 docker incompatibility
  addons/cert-manager/template/testgrid/k8s-docker.yaml
  addons/collectd/template/testgrid/k8s-docker.yaml
  addons/containerd/template/testgrid/k8s-docker.yaml
  addons/contour/template/testgrid/k8s-docker.yaml
  addons/ekco/template/testgrid/k8s-docker.yaml
  addons/fluentd/template/testgrid/k8s-docker.yaml
  addons/metrics-server/template/testgrid/k8s-docker.yaml
  addons/minio/template/testgrid/k8s-docker.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/latest.yaml
Labels: type::chore

#3439 figure out how to run rook 1.0 to 1.4 on airgap installs
  addons/rookupgrade/10to14/Manifest
  scripts/common/addon.sh
  scripts/common/rook.sh
Labels: type::feature

#3446 chore: fix testgrid (incompatible velero 1.6.x k8s 1.23.x)
  testgrid/specs/full.yaml
Labels: type::chore

#3441 Fix openebs automation. Revert hardcoding images.
  addons/openebs/template/generate.sh
Labels: type::chore

#3438 Add Upgrade from Containerd 1.5.x Test
  addons/containerd/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3449 Remove deploy-prod testgrid-run needs deploy-production-eks
  .github/workflows/deploy-prod.yaml
Labels: type::chore

#3442 Automated Prometheus version update 0.58.0-39.12.1
  addons/prometheus/0.58.0-39.12.1/Manifest
  addons/prometheus/0.58.0-39.12.1/crds/crds.yaml
  addons/prometheus/0.58.0-39.12.1/crds/kustomization.yaml
  addons/prometheus/0.58.0-39.12.1/crds/preserveUnknown.yaml
  addons/prometheus/0.58.0-39.12.1/host-preflight.yaml
  addons/prometheus/0.58.0-39.12.1/install.sh
  addons/prometheus/0.58.0-39.12.1/nodeport-services.yaml
  addons/prometheus/0.58.0-39.12.1/operator/adapter.yaml
  addons/prometheus/0.58.0-39.12.1/operator/default.yaml
  addons/prometheus/0.58.0-39.12.1/operator/kustomization.yaml
  addons/prometheus/0.58.0-39.12.1/operator/longhorn.yaml
  addons/prometheus/0.58.0-39.12.1/operator/matchlabel-release.yaml
  addons/prometheus/0.58.0-39.12.1/operator/ns.yaml
  addons/prometheus/0.58.0-39.12.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.58.0-39.12.1/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore

#3453 include why ceph is unhealthy in health status output
  go.sum
  pkg/cli/rook_wait_for_health.go
  pkg/rook/health.go
  pkg/rook/health_test.go
Labels: type::feature

#3448 Separate openebs 2.x and 3.x automation into separate pull requests
  .github/workflows/update-openebs.yaml
  addons/openebs/template/generate.sh
Labels: type::chore

#3452 Fix docker to containerd migration when upgrading to k8s 1.24
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.5.11/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.5.11/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.8/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.8/kubeadm-join-config-v1beta2.yaml
  addons/containerd/template/base/install.sh
  addons/containerd/template/base/kubeadm-init-config-v1beta2.yaml
  addons/containerd/template/base/kubeadm-join-config-v1beta2.yaml
  scripts/Manifest
  scripts/common/docker.sh
  scripts/common/kubernetes-test.sh
  scripts/common/kubernetes.sh
  scripts/common/upgrade.sh
  scripts/install.sh
  scripts/upgrade.sh
Labels: type::bug, bug::normal

#3450 test upgrading from rook 1.0 to 1.5 in an airgapped environment
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/testfiles/nonPowerOfTwoCephStatus.json
  pkg/rook/testfiles/static.go
  scripts/common/addon.sh
  testgrid/specs/full.yaml
Labels: type::feature

#3077 fix oracle linux label to show that it will use the latest version
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#3456 Revert "test upgrading from rook 1.0 to 1.5 in an airgapped environment"
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/testfiles/nonPowerOfTwoCephStatus.json
  pkg/rook/testfiles/static.go
  scripts/common/addon.sh
  testgrid/specs/full.yaml
Labels: type::bug, bug::regression

#3455 Automated Velero version update 1.9.1
  addons/velero/1.9.1/Manifest
  addons/velero/1.9.1/install.sh
Labels: automated-pr, velero, type::security

#3457 testgrid improvements for docker to containerd migration scenarios
  testgrid/specs/full.yaml
Labels: type::chore

#3460 add k8s 1.25, drop 1.21
  packages/kubernetes/template/script.sh
  web/src/installers/versions.js
Labels: type::feature

#3458 Automated Kubernetes version update 1.25.0 1.24.5 1.23.10 1.22.13
  packages/kubernetes/1.24.5/Manifest
  packages/kubernetes/1.24.5/conformance/Manifest
  packages/kubernetes/1.25.0/Manifest
  packages/kubernetes/1.25.0/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore

#3461 the latest versions of OpenEBS are 3.x, not 1.x
  web/src/installers/versions.js
Labels: type::chore

#3462 fix openebs testgrid specs
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::chore

#3463 fix openebs testgrid specs, again
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::chore

#3459 Automated Containerd version update 1.6.8
  addons/containerd/1.3.7/install.sh
  addons/containerd/1.3.7/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.3.7/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.3.9/install.sh
  addons/containerd/1.3.9/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.3.9/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.10/install.sh
  addons/containerd/1.4.10/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.10/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.11/install.sh
  addons/containerd/1.4.11/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.11/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.12/install.sh
  addons/containerd/1.4.12/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.12/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.13/install.sh
  addons/containerd/1.4.13/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.13/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.3/install.sh
  addons/containerd/1.4.3/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.3/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.4/install.sh
  addons/containerd/1.4.4/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.4/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.6/install.sh
  addons/containerd/1.4.6/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.6/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.8/install.sh
  addons/containerd/1.4.8/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.8/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.4.9/install.sh
  addons/containerd/1.4.9/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.4.9/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.10/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.5.10/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.4/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.4/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.6/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.6/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.7/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.7/kubeadm-join-config-v1beta2.yaml
Labels: automated-pr, containerd, type::chore

#3464 Automated Kubernetes version update 1.25.1 1.24.5 1.23.11 1.22.14
  packages/kubernetes/1.22.14/Manifest
  packages/kubernetes/1.22.14/conformance/Manifest
  packages/kubernetes/1.23.11/Manifest
  packages/kubernetes/1.23.11/conformance/Manifest
  packages/kubernetes/1.25.1/Manifest
  packages/kubernetes/1.25.1/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore

#3451 fix: ignore PDB on single node upgrades
  scripts/common/kubernetes.sh
Labels: type::bug, bug::normal

#3468 Bump prod release testgrid priority to 1
  .github/workflows/deploy-prod.yaml
Labels: type::chore

#3467 use go function to wait for rook health
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/template/base/install.sh
Labels: type::feature

#3470 Emosbaugh/20220916/fixes
  CONTRIBUTING.md
  addons/contour/template/testgrid/k8s-docker.yaml
  addons/ekco/0.21.0/install.sh
  addons/ekco/template/base/install.sh
  scripts/common/discover.sh
  scripts/common/k3s.sh
  scripts/common/kubernetes.sh
  scripts/common/rke2.sh
  scripts/distro/kubeadm/distro.sh
  scripts/install.sh
Labels: type::chore

#3471 allow specifying timeouts for wait-for-rook and wait-for-ceph functions
  pkg/cli/rook_wait_for_version.go
Labels: type::feature

#3472 Limit containerd autogenerated pr to supported minor versions 5 and 6
  addons/containerd/template/script.sh
  web/src/installers/versions.js
Labels: type::chore

#3482 test rook-ceph 1.0 to 1.4 (or 1.5) upgrade in airgap
  scripts/common/addon.sh
  testgrid/specs/full.yaml
Labels: type::chore

#3483 Fix airgap sonobuoy upgrade kubernetes
  addons/sonobuoy/0.56.10/install.sh
  addons/sonobuoy/0.56.8/install.sh
  addons/sonobuoy/template/base/install.sh
  addons/sonobuoy/template/generate.sh
Labels: type::bug, bug::normal

#3473 Automated MinIO version update RELEASE.2022-09-17T00-09-45Z
  addons/minio/2022-09-17T00-09-45Z/Manifest
  addons/minio/2022-09-17T00-09-45Z/deployment.yaml
  addons/minio/2022-09-17T00-09-45Z/install.sh
  addons/minio/2022-09-17T00-09-45Z/service.yaml
  addons/minio/2022-09-17T00-09-45Z/tmpl-creds-secret.yaml
  addons/minio/2022-09-17T00-09-45Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-09-17T00-09-45Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-09-17T00-09-45Z/tmpl-kustomization.yaml
  addons/minio/2022-09-17T00-09-45Z/tmpl-namespace.yaml
  addons/minio/2022-09-17T00-09-45Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio

#3481 use wait-for-rook and wait-for-ceph in rook 1.6.11 and 1.7.11
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/template/base/install.sh
Labels: type::feature

#3485 when run on an unsupported os, link to the supported os list
  scripts/common/preflights.sh
Labels: type::feature

#3466 doc: Initial Architectural Decision Record
  docs/arch/adr-001-use-openebs.md
  docs/arch/readme.md
Labels: type::docs

#3385 Automate enforcement of type labels on pull [sc-53409]
  .github/workflows/require-pr-labels.yaml
Labels: type::chore

#3489 Automated Kubernetes version update 1.25.2 1.24.6 1.23.12 1.22.15
  packages/kubernetes/1.22.15/Manifest
  packages/kubernetes/1.22.15/conformance/Manifest
  packages/kubernetes/1.23.12/Manifest
  packages/kubernetes/1.23.12/conformance/Manifest
  packages/kubernetes/1.24.6/Manifest
  packages/kubernetes/1.24.6/conformance/Manifest
  packages/kubernetes/1.25.2/Manifest
  packages/kubernetes/1.25.2/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore

#3490 add PR license scanning
  .fossa.yml
  .github/workflows/pr-license-scan.yaml
  README.md
Labels: type::chore

#3491 Rename kots* references to kurl* in the README
  README.md
Labels: type::chore

#3492 increase the actions batch size to 3 to keep the number of generated actions below 256
  bin/list-all-packages-actions-matrix.sh
Labels: type::chore

#3493 test kubernetes 1.25.x
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3494 actually test 1.25.x, not 1.24...
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3495 Fix test-addon workflow
  .github/workflows/test-addon.yaml
Labels: type::chore

#3496 Add addon-testgrid-tester action output message
  .github/actions/addon-testgrid-tester/action.yml
  bin/test-addon.sh
Labels: type::chore

#3497 Fix addon-testgrid-tester action output message
  .github/workflows/test-addon.yaml
Labels: type::chore

#3510 ci: fix add-on package build
  .github/workflows/test-addon.yaml
Labels: type::chore

#3513 addon-testgrid-tester action priority
  .github/actions/addon-testgrid-tester/action.yml
  bin/test-addon.sh
Labels: type::chore

#3517 ci: copy dir contents only
  bin/build-addon-package.sh
Labels: type::chore

#3518 Fix addon build for pr workflow
  .github/workflows/test-addon.yaml
  addons/ekco/0.21.0/install.sh
  bin/build-addon-package.sh
Labels: type::chore

#3519 Fix addon-testgrid-tester action when called from remote repo
  .github/actions/addon-testgrid-tester/action.yml
  bin/test-addon.sh
Labels: type::chore

#3520 Fix import external addons action
  .github/actions/import-external-addons/.babelrc
  .github/actions/import-external-addons/dist/index.js
  .github/actions/import-external-addons/dist/package.json
  .github/actions/import-external-addons/index.js
  .github/actions/import-external-addons/package-lock.json
  .github/actions/import-external-addons/package.json
  .github/actions/import-external-addons/test/util.js
  .github/actions/import-external-addons/util.js
  scripts/common/addon.sh
  scripts/common/common.sh
Labels: type::chore

#3521 New label to identify automated pr as type feature in release notes
  .github/workflows/update-antrea.yaml
  .github/workflows/update-containerd.yaml
  .github/workflows/update-contour.yaml
  .github/workflows/update-ekco.yaml
  .github/workflows/update-goldpinger.yaml
  .github/workflows/update-kubernetes.yaml
  .github/workflows/update-longhorn.yaml
  .github/workflows/update-minio.yaml
  .github/workflows/update-openebs.yaml
  .github/workflows/update-prometheus.yaml
  .github/workflows/update-registry.yaml
  .github/workflows/update-rook.yaml
  .github/workflows/update-sonobuoy.yaml
  .github/workflows/update-velero.yaml
  .github/workflows/update-weave.yaml
Labels: type::chore

#3523 purge staging cloudflare cache after releasing to staging
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-package-staging.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3525 chore: bump kubernetes dependencies to v0.25.2
  go.mod
  go.sum
  kurlkinds/go.mod
  kurlkinds/go.sum
Labels: type::chore

#3526 Automated EKCO version update 0.21.1
  addons/ekco/0.21.1/Manifest
  addons/ekco/0.21.1/README.md
  addons/ekco/0.21.1/deployment.yaml
  addons/ekco/0.21.1/ekco-purge-node.sh
  addons/ekco/0.21.1/install.sh
  addons/ekco/0.21.1/kustomization.yaml
  addons/ekco/0.21.1/namespace.yaml
  addons/ekco/0.21.1/rbac-rook.yaml
  addons/ekco/0.21.1/rbac.yaml
  addons/ekco/0.21.1/reboot/ekco-reboot-containerd.service
  addons/ekco/0.21.1/reboot/ekco-reboot.service
  addons/ekco/0.21.1/reboot/shutdown.sh
  addons/ekco/0.21.1/reboot/startup.sh
  addons/ekco/0.21.1/regen-cert-pod.yaml
  addons/ekco/0.21.1/rolebinding-rook.yaml
  addons/ekco/0.21.1/rolebinding.yaml
  addons/ekco/0.21.1/rotate-certs-rbac.yaml
  addons/ekco/0.21.1/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#3501 Automated Velero version update 1.9.2
  addons/velero/1.9.2/Manifest
  addons/velero/1.9.2/install.sh
  addons/velero/1.9.2/restic-daemonset-privileged.yaml
  addons/velero/1.9.2/s3-migration-configmap.yaml
  addons/velero/1.9.2/tmpl-change-storageclass.yaml
  addons/velero/1.9.2/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.9.2/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.9.2/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.9.2/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.9.2/tmpl-kustomization.yaml
  addons/velero/1.9.2/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.9.2/tmpl-s3-migration-bsl.yaml
  addons/velero/1.9.2/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.9.2/tmpl-s3-migration-secret.yaml
  addons/velero/1.9.2/tmpl-velero-deployment-proxy.yaml
  addons/velero/1.9.2/velero-args-json-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3527 Allow image and asset Manifest assets as local files
  bin/save-manifest-assets.sh
Labels: type::chore

#3529 External addon cleanup
  .github/actions/import-external-addons/util.js
  bin/save-manifest-assets.sh
Labels: type::chore

#3531 Automated Goldpinger version update 3.6.1-5.4.2
  addons/goldpinger/3.6.1-5.4.2/Manifest
  addons/goldpinger/3.6.1-5.4.2/goldpinger.yaml
  addons/goldpinger/3.6.1-5.4.2/install.sh
  addons/goldpinger/3.6.1-5.4.2/kustomization.yaml
  addons/goldpinger/3.6.1-5.4.2/servicemonitor.yaml
  web/src/installers/versions.js
Labels: automated-pr, goldpinger, type::chore, kurl::type::feature

#3530 fallback to raw s3 url if *.kurl.sh fails
  CONTRIBUTING.md
  scripts/Manifest
  scripts/common/common.sh
Labels: type::feature

#3533 use fallback url when downloading common.tar.gz
  scripts/common/common.sh
Labels: type::feature

#3515 doc: adr for rook as multi node default pvc provisioner
  docs/arch/adr-002-rook-distributed.md
Labels: type::chore
