Repository replicatedhq/kURL, pull requests merged in 2022-02, with the labels that each got.

#2656 support rhel 8.5
  scripts/common/preflights.sh
Labels: type::feature

#2653 do not attempt to restart a disabled kubelet when installing containerd
  addons/containerd/1.3.7/install.sh
  addons/containerd/1.3.9/install.sh
  addons/containerd/1.4.10/install.sh
  addons/containerd/1.4.11/install.sh
  addons/containerd/1.4.12/install.sh
  addons/containerd/1.4.3/install.sh
  addons/containerd/1.4.4/install.sh
  addons/containerd/1.4.6/install.sh
  addons/containerd/1.4.8/install.sh
  addons/containerd/1.4.9/install.sh
  addons/containerd/template/Dockerfile.centos8
  addons/containerd/template/base/install.sh
  bin/save-manifest-assets.sh
Labels: type::bug, bug::normal

#2659 Disable dependabot auto merge
  .github/workflows/dependabot-automerge.yaml
Labels: type::chore

#2661 Remove the assignment to the Day 1 team for issue created.
  .github/workflows/dependabot-buildfailure.yaml
Labels: type::chore

#2663 only use strong ciphers
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/kubeadm-cluster-config-v1beta2.yml
Labels: type::bug, team::orange

#2665 fix(preflights): null creationTimestamp for airgap
  kurl_util/cmd/bashmerge/main.go
Labels: type::bug, bug::normal, team::orange

#2675 feat: update versions of k3s and rke2
  bundles/k3s-rhel8/Dockerfile
  bundles/rke2-rhel8/Dockerfile
  packages/k-3-s/v1.23.3-k3s1/Manifest
  packages/rke-2/v1.22.6-rke2r1/Manifest
  testgrid/specs/full.yaml
  web/src/installers/versions.js
Labels: type::chore, team::orange

#2655 Automated Contour version update 1.20.0
  addons/contour/1.20.0/Manifest
  addons/contour/1.20.0/contour.yaml
  addons/contour/1.20.0/install.sh
  addons/contour/1.20.0/patches/job-image.yaml
  addons/contour/1.20.0/tmpl-configmap.yaml
  addons/contour/1.20.0/tmpl-kustomization.yaml
  addons/contour/1.20.0/tmpl-namespace.yaml
  addons/contour/1.20.0/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour

#2676 add 'how to test contour' to contour readme
  addons/contour/template/README.md
Labels: type::docs

#2677 replace 'from centos:8' with 'from rockylinux:8' to fix build issues
  bundles/docker-rhel8/Dockerfile
  bundles/k8s-rhel8/Dockerfile
Labels: type::bug, bug::normal

#2604 Automated Kubernetes version update 1.23.3 1.22.6 1.21.9 1.20.15
  packages/kubernetes/1.20.15/Manifest
  packages/kubernetes/1.20.15/conformance/Manifest
  packages/kubernetes/1.21.9/Manifest
  packages/kubernetes/1.21.9/conformance/Manifest
  packages/kubernetes/1.22.6/Manifest
  packages/kubernetes/1.22.6/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes

#2679 fix(preflights): failing tcp lb check for internal lb
  scripts/common/prompts.sh
Labels: type::bug, bug::normal, team::orange

#2684 Make sure kurl-config exists in k3s and rke2 installs
  scripts/common/k3s.sh
  scripts/common/rke2.sh
  scripts/install.sh
Labels: type::bug, bug::normal, team::orange

#2682 remove minio from future kotsadm versions
  addons/kotsadm/alpha/Manifest
  addons/kotsadm/nightly/Manifest
  addons/kotsadm/template/base/Manifest
  addons/kotsadm/template/generate.sh
Labels: type::feature

#2685 Add registry certs to containerd
  scripts/common/k3s.sh
  scripts/common/rke2.sh
Labels: type::bug, bug::normal, team::orange

#2696 when running with an ekco-provided internal LB, skip the LB connection preflight
  pkg/preflight/assets/host-preflights.yaml
Labels: type::bug, bug::normal

#2702 add rke2 test to testgrid
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/index.ts
Labels: type::chore, team::orange

#2709 allow dependency resolution when using rhel8 and containerd addon
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal, team::orange

#2711 swap openssl libs package for compatible version on RHEL7
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal, team::orange

#2722 fix(web): set kots uiBindPort for rke2 and k3s installers
  web/src/installers/index.ts
  web/src/test/controllers/installers.ts
Labels: type::bug, bug::normal, team::orange

#2723 feat(longhorn): add storage overprovisioning field to installer
  addons/longhorn/1.2.2/install.sh
  addons/longhorn/1.2.2/kustomization.yaml
  addons/longhorn/1.2.2/tmpl-defaults-cm.yaml
  addons/longhorn/template/base/install.sh
  addons/longhorn/template/base/kustomization.yaml
  addons/longhorn/template/base/tmpl-defaults-cm.yaml
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
Labels: type::feature, team::orange
