Repository replicatedhq/kURL, pull requests merged in 2022-10, with the labels that each got.

#3536 Automated MinIO version update RELEASE.2022-10-02T19-29-29Z
  addons/minio/2022-10-02T19-29-29Z/Manifest
  addons/minio/2022-10-02T19-29-29Z/deployment.yaml
  addons/minio/2022-10-02T19-29-29Z/install.sh
  addons/minio/2022-10-02T19-29-29Z/service.yaml
  addons/minio/2022-10-02T19-29-29Z/tmpl-creds-secret.yaml
  addons/minio/2022-10-02T19-29-29Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-10-02T19-29-29Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-10-02T19-29-29Z/tmpl-kustomization.yaml
  addons/minio/2022-10-02T19-29-29Z/tmpl-namespace.yaml
  addons/minio/2022-10-02T19-29-29Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3538 Allow passing testgrid os spec path to action
  .github/actions/addon-testgrid-tester/action.yml
Labels: type::chore

#3522 Document kURL's external add-on capability
  .github/actions/import-external-addons/README.md
  ARCHITECTURE.md
  README.md
Labels: type::chore

#3528 the existence of 'global recovery event' does not make ceph unhealthy
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/testfiles/globalRecoveryEventCephStatus.json
  pkg/rook/testfiles/static.go
Labels: type::feature, type::improvement

#3539 do not apply PodSecurityPolicy related things to k8s 1.25
  scripts/install.sh
Labels: type::feature

#3540 Patch cephfs storageclass name
  addons/rook/1.8.10/install.sh
Labels: type::chore

#3545 Critical CVEs in kurlsh/weave-kube and kurlsh/weaveexec 2.8.1-20220825-237c19d
  addons/weave/2.6.5-20221006/Manifest
  addons/weave/2.6.5-20221006/host-preflight.yaml
  addons/weave/2.6.5-20221006/install.sh
  addons/weave/2.6.5-20221006/kustomization.yaml
  addons/weave/2.6.5-20221006/patch-daemonset.yaml
  addons/weave/2.6.5-20221006/patch-encrypt.yaml
  addons/weave/2.6.5-20221006/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.6.5-20221006/tmpl-patch-no-masq-local.yaml
  addons/weave/2.6.5-20221006/tmpl-secret.yaml
  addons/weave/2.6.5-20221006/weave-daemonset-k8s-1.11.yaml
  addons/weave/2.8.1-20221006/Manifest
  addons/weave/2.8.1-20221006/host-preflight.yaml
  addons/weave/2.8.1-20221006/install.sh
  addons/weave/2.8.1-20221006/kustomization.yaml
  addons/weave/2.8.1-20221006/patch-daemonset.yaml
  addons/weave/2.8.1-20221006/patch-encrypt.yaml
  addons/weave/2.8.1-20221006/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.8.1-20221006/tmpl-patch-no-masq-local.yaml
  addons/weave/2.8.1-20221006/tmpl-secret.yaml
  addons/weave/2.8.1-20221006/weave-daemonset-k8s-1.11.yaml
  web/src/installers/versions.js
Labels: type::security, kurl::type::feature

#3544 Patch critical CVE-2022-40674 in kurlsh/s3cmd:20220825-237c19d
  addons/registry/2.8.1/Manifest
  addons/registry/2.8.1/patch-deployment-migrate-s3.yaml
  addons/registry/2.8.1/patch-deployment-velero.yaml
  addons/velero/1.9.2/Manifest
  addons/velero/1.9.2/tmpl-s3-migration-deployment-patch.yaml
Labels: type::security

#3546 Add action input for specifying staging vs production for testgrid tests
  .github/actions/addon-testgrid-tester/action.yml
  .github/workflows/test-addon.yaml
  bin/test-addon.sh
Labels: type::chore

#3549 upgrade testgrid to test 1.25.x preferentially
  addons/cert-manager/template/testgrid/k8s-docker.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/sonobuoy/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3553 fix on-merge testgrid tests
  testgrid/specs/deploy.yaml
Labels: type::feature

#3543 ADR 3: kURL External Add-On Capability
  ARCHITECTURE.md
  docs/arch/README.md
  docs/arch/adr-003-external-addons.md
Labels: type::chore

#3554 NO_PROXY environment variable can have empty address
  Makefile
  addons/velero/1.9.2/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.9.2/tmpl-velero-deployment-proxy.yaml
  addons/velero/template/base/install.tmpl.sh
  addons/velero/template/base/tmpl-restic-daemonset-proxy.yaml
  addons/velero/template/base/tmpl-velero-deployment-proxy.yaml
  scripts/common/proxy-test.sh
  scripts/common/proxy.sh
  scripts/common/yaml-test.sh
Labels: type::bug, bug::normal

#3555 adr-003-external-addons.md status "Accepted"
  docs/arch/adr-003-external-addons.md
Labels: type::chore

#3556 do not rerun the staging workflow for docs changes
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3552 doc: adding adr for installer object validation
  docs/arch/adr-004-installer-objects-linter.md
Labels: type::chore, type::docs

#3559 Automated MinIO version update RELEASE.2022-10-08T20-11-00Z
  addons/minio/2022-10-08T20-11-00Z/Manifest
  addons/minio/2022-10-08T20-11-00Z/deployment.yaml
  addons/minio/2022-10-08T20-11-00Z/install.sh
  addons/minio/2022-10-08T20-11-00Z/service.yaml
  addons/minio/2022-10-08T20-11-00Z/tmpl-creds-secret.yaml
  addons/minio/2022-10-08T20-11-00Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-10-08T20-11-00Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-10-08T20-11-00Z/tmpl-kustomization.yaml
  addons/minio/2022-10-08T20-11-00Z/tmpl-namespace.yaml
  addons/minio/2022-10-08T20-11-00Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3558 Automated Velero version update 1.9.2
  addons/velero/1.9.2/install.sh
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3563 chore: set adr-04 as "accepted"
  docs/arch/adr-004-installer-objects-linter.md
Labels: type::chore

#3566 Fix registry testgrid post install and upgrade scripts to use ctr
  addons/registry/2.8.1/service.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3567 Daily scan images should only fail for vulnerabilities in images we maintain
  .github/workflows/daily-scan-images.yaml
  bin/scan-images/addons.js
Labels: type::chore

#3568 Upgrade to Rook 1.9.x in testgrid specs
  addons/registry/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3571 Fix testgrid full run for k8s 1.25 changes
  testgrid/specs/full.yaml
Labels: type::chore

#3572 Fix scale up ekc-operator deployment
  addons/ekco/0.22.0/install.sh
  addons/ekco/0.23.0/install.sh
  addons/ekco/template/base/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
Labels: type::bug, bug::regression

#3576 Automated Velero version update 1.9.2
  addons/velero/1.9.2/Manifest
  addons/velero/1.9.2/install.sh
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3570 Remove PSP from Rook Add-on
  addons/rook/1.9.12/operator/cluster-rbac.yaml
  addons/rook/1.9.12/operator/kustomization.yaml
  addons/rook/1.9.12/operator/psp.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
  addons/rook/template/values.yaml
Labels: type::feature

#3574 Automated Kubernetes version update 1.25.3 1.24.7 1.23.13 1.22.15
  packages/kubernetes/1.23.13/Manifest
  packages/kubernetes/1.23.13/conformance/Manifest
  packages/kubernetes/1.24.7/Manifest
  packages/kubernetes/1.24.7/conformance/Manifest
  packages/kubernetes/1.25.3/Manifest
  packages/kubernetes/1.25.3/conformance/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#3577 only check testgrid runs for the latest commit in a branch
  .github/actions/testgrid-checker/index.js
  .github/workflows/test-testgrid-results.yaml
Labels: type::chore

#3579 improve testgrid-checker action logging
  .github/actions/testgrid-checker/index.js
Labels: type::chore

#3580 actually use the updated code
  .github/actions/testgrid-checker/dist/index.js
  .github/actions/testgrid-checker/index.js
Labels: type::chore

#3583 Add external add-on isPrerelease support
  .github/actions/import-external-addons/index.js
  .github/actions/import-external-addons/test/util.js
  .github/actions/import-external-addons/util.js
Labels: type::chore

#3595 Skip kotsadm external add-on in daily scan
  bin/scan-images/addons.js
Labels: type::chore

#3582 Automated MinIO version update RELEASE.2022-10-15T19-57-03Z
  addons/minio/2022-10-15T19-57-03Z/Manifest
  addons/minio/2022-10-15T19-57-03Z/deployment.yaml
  addons/minio/2022-10-15T19-57-03Z/install.sh
  addons/minio/2022-10-15T19-57-03Z/service.yaml
  addons/minio/2022-10-15T19-57-03Z/tmpl-creds-secret.yaml
  addons/minio/2022-10-15T19-57-03Z/tmpl-deployment-hostpath.yaml
  addons/minio/2022-10-15T19-57-03Z/tmpl-deployment-pvc.yaml
  addons/minio/2022-10-15T19-57-03Z/tmpl-kustomization.yaml
  addons/minio/2022-10-15T19-57-03Z/tmpl-namespace.yaml
  addons/minio/2022-10-15T19-57-03Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3598 do not set testgrid status if no testgrid runs are found
  .github/actions/testgrid-checker/dist/index.js
  .github/actions/testgrid-checker/index.js
Labels: type::chore

#3599 rely on testgrid comments to find runs
  .github/actions/testgrid-checker/dist/index.js
  .github/actions/testgrid-checker/index.js
Labels: type::chore

#3581 ADR: Host Packages
  docs/arch/adr-005-host-packages.md
Labels: type::chore

#3600 Automated Velero version update 1.9.2
  addons/velero/1.9.2/Manifest
  addons/velero/1.9.2/install.sh
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3605 Testgrid use ekco latest with rook 1.9.x
  testgrid/specs/full.yaml
Labels: type::chore

#3606 OpenEBS add-on not supported for disableS3
  testgrid/specs/full.yaml
Labels: type::chore

#3604 ADR: Flannel CNI
  docs/arch/adr-006-flannel-cni.md
Labels: type::chore

#3609 Fix testgrid daily run needs more cpu with Rook 1.9.x
  testgrid/specs/full.yaml
Labels: type::chore

#3608 Fix erroneously remove --network-plugin flag prior to 1.24
  scripts/common/upgrade.sh
Labels: type::bug, bug::normal

#3607 Ekco improvements
  addons/ekco/template/base/install.sh
  scripts/upgrade.sh
Labels: type::bug, bug::normal

#3610 Set ADR 6: Flannel CNI status to "Accepted"
  docs/arch/adr-006-flannel-cni.md
Labels: type::chore

#3569 Apply Prometheus Monitor and Import Ceph Grafana Dashboard
  ARCHITECTURE.md
  addons/rook/1.9.12/install.sh
  addons/rook/1.9.12/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.9.12/monitoring/kustomization.yaml
  addons/rook/1.9.12/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/template/base/install.sh
  addons/rook/template/base/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/template/base/monitoring/kustomization.yaml
  addons/rook/template/base/monitoring/rook-ceph-servicemonitor.yaml
  scripts/common/addon.sh
  scripts/common/k3s.sh
  scripts/common/rke2.sh
  scripts/install.sh
Labels: type::chore, kurl::type::feature

#3611 When checking for CRI we should not use "commandExists docker"
  addons/ekco/template/base/install.sh
  scripts/common/preflights.sh
  scripts/join.sh
Labels: type::bug, bug::normal

#3613 Automated Contour version update 1.23.0
  addons/contour/1.23.0/Manifest
  addons/contour/1.23.0/contour.yaml
  addons/contour/1.23.0/install.sh
  addons/contour/1.23.0/patches/job-image.yaml
  addons/contour/1.23.0/patches/resource-limits.yaml
  addons/contour/1.23.0/tmpl-configmap.yaml
  addons/contour/1.23.0/tmpl-kustomization.yaml
  addons/contour/1.23.0/tmpl-namespace.yaml
  addons/contour/1.23.0/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#3614 Fix ekco load balancer changing causes secondary k8s node upgrade to fail
  addons/containerd/template/base/install.sh
  addons/ekco/template/base/install.sh
  scripts/common/addon.sh
  scripts/common/common-test.sh
  scripts/common/common.sh
  scripts/common/k3s.sh
  scripts/common/rke2.sh
  scripts/common/upgrade.sh
  scripts/install.sh
Labels: type::bug, bug::regression

#3615 Fix calls to addon_post_init from k3s and rke2 scripts
  scripts/common/k3s.sh
  scripts/common/rke2.sh
Labels: type::chore

#3617 ekco should be able to list namespaces
  addons/ekco/template/base/rbac.yaml
Labels: type::chore

#3616 Automated EKCO version update 0.23.2
  addons/ekco/0.23.2/Manifest
  addons/ekco/0.23.2/README.md
  addons/ekco/0.23.2/deployment.yaml
  addons/ekco/0.23.2/ekco-purge-node.sh
  addons/ekco/0.23.2/install.sh
  addons/ekco/0.23.2/kustomization.yaml
  addons/ekco/0.23.2/namespace.yaml
  addons/ekco/0.23.2/rbac-rook.yaml
  addons/ekco/0.23.2/rbac.yaml
  addons/ekco/0.23.2/reboot/ekco-reboot-containerd.service
  addons/ekco/0.23.2/reboot/ekco-reboot.service
  addons/ekco/0.23.2/reboot/shutdown.sh
  addons/ekco/0.23.2/reboot/startup.sh
  addons/ekco/0.23.2/regen-cert-pod.yaml
  addons/ekco/0.23.2/rolebinding-rook.yaml
  addons/ekco/0.23.2/rolebinding.yaml
  addons/ekco/0.23.2/rotate-certs-rbac.yaml
  addons/ekco/0.23.2/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#3602 Flannel add-on
  .github/workflows/update-flannel.yaml
  ARCHITECTURE.md
  CONTRIBUTING.md
  Makefile
  addons/flannel/0.20.0/Manifest
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.0/kubeadm.yaml
  addons/flannel/0.20.0/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.20.0/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.20.0/yaml/kube-flannel.yml
  addons/flannel/0.20.0/yaml/kustomization.yaml
  addons/flannel/0.20.0/yaml/troubleshoot.yaml
  addons/flannel/categories.json
  addons/flannel/template/base/Manifest
  addons/flannel/template/base/install.sh
  addons/flannel/template/base/kubeadm.yaml
  addons/flannel/template/base/template/ipv6.patch.tmpl.yaml
  addons/flannel/template/base/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/template/base/yaml/kustomization.yaml
  addons/flannel/template/base/yaml/troubleshoot.yaml
  addons/flannel/template/generate.sh
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  addons/weave/template/base/install.sh
  kurl_util/cmd/yamltobash/main.go
  kurlkinds/pkg/apis/cluster/v1beta1/installer_types.go
  kurlkinds/schemas/installer-cluster-v1beta1.json
  kurlkinds/schemas/installer-kurl-v1beta1.json
  scripts/common/kubernetes.sh
  scripts/common/prompts.sh
  scripts/distro/kubeadm/distro.sh
  web/src/installers/versions.js
Labels: type::feature

#3618 Automated Containerd version update 1.6.8
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#3621 Use stringData for troubleshoot secret
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.0/yaml/troubleshoot.yaml
  addons/flannel/template/base/install.sh
  addons/flannel/template/base/yaml/troubleshoot.yaml
Labels: type::feature

#3622 improve ekco code with support for HA minio
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/rbac-minio.yaml
  addons/ekco/template/testgrid/k8s-docker.yaml
Labels: type::feature

#3623 Automated EKCO version update 0.24.0
  addons/ekco/0.24.0/Manifest
  addons/ekco/0.24.0/README.md
  addons/ekco/0.24.0/deployment.yaml
  addons/ekco/0.24.0/ekco-purge-node.sh
  addons/ekco/0.24.0/install.sh
  addons/ekco/0.24.0/kustomization.yaml
  addons/ekco/0.24.0/namespace.yaml
  addons/ekco/0.24.0/rbac-minio.yaml
  addons/ekco/0.24.0/rbac-rook.yaml
  addons/ekco/0.24.0/rbac.yaml
  addons/ekco/0.24.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.24.0/reboot/ekco-reboot.service
  addons/ekco/0.24.0/reboot/shutdown.sh
  addons/ekco/0.24.0/reboot/startup.sh
  addons/ekco/0.24.0/regen-cert-pod.yaml
  addons/ekco/0.24.0/rolebinding-minio.yaml
  addons/ekco/0.24.0/rolebinding-rook.yaml
  addons/ekco/0.24.0/rolebinding.yaml
  addons/ekco/0.24.0/rotate-certs-rbac.yaml
  addons/ekco/0.24.0/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#3626 Update FOSSA API key
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#3625 ADR 7: Deprecate Support for K3s and RKE2 Add-Ons
  docs/arch/adr-007-deprecate-k3s-and-rke2.md
Labels: type::feature

#3628 Patch weave images for vulnerabilities
  addons/weave/2.6.5-20221025/Manifest
  addons/weave/2.6.5-20221025/host-preflight.yaml
  addons/weave/2.6.5-20221025/install.sh
  addons/weave/2.6.5-20221025/kustomization.yaml
  addons/weave/2.6.5-20221025/patch-daemonset.yaml
  addons/weave/2.6.5-20221025/patch-encrypt.yaml
  addons/weave/2.6.5-20221025/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.6.5-20221025/tmpl-patch-no-masq-local.yaml
  addons/weave/2.6.5-20221025/tmpl-secret.yaml
  addons/weave/2.6.5-20221025/weave-daemonset-k8s-1.11.yaml
  addons/weave/2.6.5/build-images/README.md
  addons/weave/2.8.1-20221025/Manifest
  addons/weave/2.8.1-20221025/host-preflight.yaml
  addons/weave/2.8.1-20221025/install.sh
  addons/weave/2.8.1-20221025/kustomization.yaml
  addons/weave/2.8.1-20221025/patch-daemonset.yaml
  addons/weave/2.8.1-20221025/patch-encrypt.yaml
  addons/weave/2.8.1-20221025/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.8.1-20221025/tmpl-patch-no-masq-local.yaml
  addons/weave/2.8.1-20221025/tmpl-secret.yaml
  addons/weave/2.8.1-20221025/weave-daemonset-k8s-1.11.yaml
  addons/weave/2.8.1/build-images/README.md
  web/src/installers/versions.js
Labels: type::security

#3627 Update npm deps including gaze-run-interrupt
  package-lock.json
  package.json
Labels: type::chore

#3631 Trigger PVC Migration when Removing Rook and Installing OpenEBS
  addons/longhorn/1.1.2/install.sh
  addons/longhorn/1.2.2/install.sh
  addons/longhorn/1.2.4/install.sh
  addons/longhorn/1.3.1/install.sh
  addons/longhorn/template/base/install.sh
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
  go.mod
  go.sum
  scripts/common/rook.sh
  scripts/tasks.sh
Labels: type::chore

#3636 fix storageClass provisioner extraction when migrating from Rook to OpenEBS
  scripts/common/rook.sh
Labels: type::bug, bug::regression

#3635 Fix golangci-lint errors
  Makefile
  go.mod
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/config/main.go
  kurl_util/cmd/docker/main.go
  kurl_util/cmd/installermerge/main.go
  kurl_util/cmd/network/main.go
  kurl_util/cmd/toml/main.go
  kurl_util/cmd/vendorflights/main.go
  kurl_util/cmd/vendorflights/main_test.go
  kurl_util/cmd/yamltobash/main.go
  kurl_util/cmd/yamltobash/main_test.go
  kurl_util/cmd/yamlutil/main.go
  pkg/cli/host_preflight.go
  pkg/cli/host_preflight_test.go
  pkg/cluster/nodes_test.go
  pkg/installer/installer.go
  pkg/preflight/preflight.go
  pkg/rook/health.go
  pkg/rook/migrate_test.go
  pkg/rook/output.go
  pkg/rook/toolbox_test.go
Labels: type::chore

#3637 Add comment for rook_osd_phase_ready unsupported on Rook 1.0.4
  scripts/common/rook.sh
Labels: type::chore

#3640 chore: remove unused go.mod entry
  go.mod
Labels: type::chore

#3638 Prompt User When Migrating Data from Rook to OpenEBS
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
Labels: type::chore

#3642 Modify daily testgrid runs
  .github/workflows/cron-scan-images-daily.yaml
  .github/workflows/cron-testgrid-daily.yaml
  .github/workflows/cron-testgrid-weekly.yaml
Labels: type::chore

#3639 Automated Velero version update 1.9.2
  addons/velero/1.9.2/Manifest
  addons/velero/1.9.2/install.sh
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3643 Fix Rook to OpenEBS Data Migration Prompt
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
Labels: type::bug

#3644 Add Flannel test to testgrid daily and release runs
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::feature

#3649 Rollback openebs to rook migration prompt
  addons/openebs/3.3.0/install.sh
Labels: type::bug, bug::regression

#3651 Ensure Rook is installed in the cluster prior to presenting migration prompt to user
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
Labels: type::bug

#3652 Automated Velero version update 1.9.2
  addons/velero/1.9.2/Manifest
  addons/velero/1.9.2/tmpl-s3-migration-deployment-patch.yaml
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3650 Wait for openebs addmission server
  addons/openebs/1.12.0/install.sh
  addons/openebs/2.6.0/install.sh
Labels: type::bug, bug::normal

#3645 Do not toggle off ekco internal load balancer on upgrade
  scripts/common/kubernetes.sh
  scripts/common/prompts.sh
  scripts/common/utilbinaries.sh
Labels: type::bug, bug::normal

#3647 Upgrade go.mod github.com/rook/rook@v1.9.12
  go.mod
  go.sum
Labels: type::chore

#3632 Containerd version update 1.6.9
  addons/containerd/1.6.9/Manifest
  addons/containerd/1.6.9/crictl.yaml
  addons/containerd/1.6.9/host-preflight.yaml
  addons/containerd/1.6.9/install.sh
  addons/containerd/1.6.9/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.9/kubeadm-join-config-v1beta2.yaml
  addons/containerd/template/script.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  web/src/installers/versions.js
Labels: type::chore, kurl::type::feature

#3634 Automate approval and merging of prs passing testgrid checker
  .github/actions/testgrid-checker/dist/index.js
  .github/actions/testgrid-checker/github.js
  .github/actions/testgrid-checker/index.js
  .github/actions/testgrid-checker/package-lock.json
  .github/actions/testgrid-checker/package.json
  .github/actions/testgrid-checker/pullrequests.js
  .github/actions/testgrid-checker/test.js
  .github/workflows/test-testgrid-results.yaml
Labels: type::chore

#3657 Use two different github tokens for testgrid checker action permissions
  .github/actions/testgrid-checker/action.yml
  .github/actions/testgrid-checker/dist/index.js
  .github/actions/testgrid-checker/github.js
  .github/workflows/test-testgrid-results.yaml
Labels: type::chore
