Repository replicatedhq/kURL, pull requests merged in 2023-08, with the labels that each got.

#4724 chore: Update storage migration test to support Rook 1.12
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4727 chore: Update all tests to use Rook 1.12.x
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#4725 Automated Rook version update 1.12.1
  addons/rook/1.12.1/Manifest
  addons/rook/1.12.1/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.12.1/cluster/cephfs/filesystem.yaml
  addons/rook/1.12.1/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.12.1/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.12.1/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.12.1/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.12.1/cluster/cluster.yaml
  addons/rook/1.12.1/cluster/kustomization.yaml
  addons/rook/1.12.1/cluster/object-user.yaml
  addons/rook/1.12.1/cluster/object.yaml
  addons/rook/1.12.1/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.12.1/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.12.1/cluster/patches/object-Json6902.yaml
  addons/rook/1.12.1/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.12.1/cluster/patches/tmpl-object.yaml
  addons/rook/1.12.1/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.12.1/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.12.1/crds.yaml
  addons/rook/1.12.1/host-preflight.yaml
  addons/rook/1.12.1/install.sh
  addons/rook/1.12.1/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.12.1/monitoring/kustomization.yaml
  addons/rook/1.12.1/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.12.1/operator/cluster-rbac.yaml
  addons/rook/1.12.1/operator/clusterrole.yaml
  addons/rook/1.12.1/operator/clusterrolebinding.yaml
  addons/rook/1.12.1/operator/configmap-rook-config-override.yaml
  addons/rook/1.12.1/operator/configmap.yaml
  addons/rook/1.12.1/operator/deployment.yaml
  addons/rook/1.12.1/operator/kustomization.yaml
  addons/rook/1.12.1/operator/namespace.yaml
  addons/rook/1.12.1/operator/patches/deployment-privileged.yaml
  addons/rook/1.12.1/operator/patches/deployment-tolerations.yaml
  addons/rook/1.12.1/operator/role.yaml
  addons/rook/1.12.1/operator/rolebinding.yaml
  addons/rook/1.12.1/operator/serviceaccount.yaml
  addons/rook/1.12.1/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4729 migrate from longhorn to openebs, then upgrade k8s past 1.24
  addons/openebs/3.7.0/install.sh
  addons/openebs/template/base/install.sh
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::feature

#4730 chore: Update containerd add-on tests to exclude Rock 9.2
  addons/containerd/template/testgrid/k8s-ctrd.yaml
Labels: type::chore

#4720 Automated Containerd version update 1.6.22
  addons/containerd/1.6.22/Manifest
  addons/containerd/1.6.22/crictl.yaml
  addons/containerd/1.6.22/host-preflight.yaml
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.22/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.22/kubeadm-join-config-v1beta2.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#4680 Automated MinIO version update RELEASE.2023-08-04T17-40-21Z
  addons/minio/2023-08-04T17-40-21Z/Manifest
  addons/minio/2023-08-04T17-40-21Z/deployment.yaml
  addons/minio/2023-08-04T17-40-21Z/install.sh
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-08-04T17-40-21Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-08-04T17-40-21Z/service.yaml
  addons/minio/2023-08-04T17-40-21Z/tmpl-creds-secret.yaml
  addons/minio/2023-08-04T17-40-21Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-08-04T17-40-21Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-08-04T17-40-21Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-08-04T17-40-21Z/tmpl-kustomization.yaml
  addons/minio/2023-08-04T17-40-21Z/tmpl-namespace.yaml
  addons/minio/2023-08-04T17-40-21Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4702 Automated Prometheus version update 0.66.0-48.3.1
  addons/prometheus/0.66.0-48.3.1/Manifest
  addons/prometheus/0.66.0-48.3.1/crds/crds.yaml
  addons/prometheus/0.66.0-48.3.1/crds/kustomization.yaml
  addons/prometheus/0.66.0-48.3.1/crds/preserveUnknown.yaml
  addons/prometheus/0.66.0-48.3.1/host-preflight.yaml
  addons/prometheus/0.66.0-48.3.1/install.sh
  addons/prometheus/0.66.0-48.3.1/nodeport-services.yaml
  addons/prometheus/0.66.0-48.3.1/operator/adapter.yaml
  addons/prometheus/0.66.0-48.3.1/operator/default.yaml
  addons/prometheus/0.66.0-48.3.1/operator/kustomization.yaml
  addons/prometheus/0.66.0-48.3.1/operator/longhorn.yaml
  addons/prometheus/0.66.0-48.3.1/operator/matchlabel-instance.yaml
  addons/prometheus/0.66.0-48.3.1/operator/matchlabel-release.yaml
  addons/prometheus/0.66.0-48.3.1/operator/ns.yaml
  addons/prometheus/0.66.0-48.3.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.66.0-48.3.1/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4713 Automated OpenEBS version update 3.8.0
  addons/openebs/3.8.0/Manifest
  addons/openebs/3.8.0/install.sh
  addons/openebs/3.8.0/spec/crds/crds.yaml
  addons/openebs/3.8.0/spec/crds/kustomization.yaml
  addons/openebs/3.8.0/spec/openebs.tmpl.yaml
  addons/openebs/3.8.0/spec/storage/kustomization.yaml
  addons/openebs/3.8.0/spec/storage/tmpl-localpv-storage-class.yaml
  addons/openebs/3.8.0/spec/storage/tmpl-patch-localpv-default.yaml
  addons/openebs/3.8.0/spec/tmpl-kustomization.yaml
  addons/openebs/3.8.0/spec/tmpl-namespace.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, openebs, kurl::type::feature, auto-merge

#4712 Automated Flannel version update 0.22.1
  addons/flannel/0.22.1/Manifest
  addons/flannel/0.22.1/host-preflight.yaml
  addons/flannel/0.22.1/install.sh
  addons/flannel/0.22.1/kubeadm.yaml
  addons/flannel/0.22.1/template/iface.patch.tmpl.yaml
  addons/flannel/0.22.1/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.22.1/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.22.1/yaml/kube-flannel.yml
  addons/flannel/0.22.1/yaml/kustomization.yaml
  addons/flannel/0.22.1/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#4734 Another customer upgrade test
  testgrid/specs/customer-migration-specs.yaml
Labels: type::chore

#4736 fix: Add /etc/kubernetes/audit.yaml to remote primary nodes if not present on Kubernetes upgrades
  scripts/upgrade.sh
Labels: type::bug, bug::normal

#4737 add additional coredns image alias
  scripts/common/common.sh
Labels: type::bug, bug::normal

#4738 Allow 25 go mod PRs per week
  .github/dependabot.yml
Labels: type::chore

#4741 Automated EKCO version update 0.28.2
  addons/ekco/0.28.2/Manifest
  addons/ekco/0.28.2/install.sh
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4744 Revert "Automated Containerd version update 1.6.22"
  addons/containerd/1.6.22/Manifest
  addons/containerd/1.6.22/crictl.yaml
  addons/containerd/1.6.22/host-preflight.yaml
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.22/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.22/kubeadm-join-config-v1beta2.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: type::bug, bug::normal

#4745 run os-latest tests with Ubuntu 1804, not 2004, for better coverage
  testgrid/specs/os-latest.yaml
Labels: type::chore

#4743 chore: Retry Ekco Api Calls for migrate-multinode-storage cmd
  go.mod
  go.sum
  pkg/cli/cluster_migrate_multinode_storage.go
Labels: type::chore

#4746 bump kurlkinds to v1.4.3
  go.mod
  go.sum
Labels: type::chore

#4753 do not log http requests made with retryClient
  pkg/cli/cluster_migrate_multinode_storage.go
Labels: type::bug, bug::normal

#4754 do not log http requests made with retryClient anywhere
  pkg/cli/cluster_migrate_multinode_storage.go
Labels: type::bug, bug::normal

#4757 enable checking for kubernetes 1.28.x versions
  packages/kubernetes/template/script.sh
  web/src/installers/versions.js
Labels: type::chore

#4758 Automated Kubernetes version update 1.28.0 1.27.4 1.26.7 1.25.12 1.24.16 1.23.17 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.28.0/Manifest
  packages/kubernetes/1.28.0/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4760 backport openebs migration changes to 3.7.0
  addons/openebs/3.7.0/install.sh
Labels: type::chore

#4759 another migration spec
  testgrid/specs/customer-migration-specs.yaml
Labels: type::chore

#4761 test with kubernetes 1.28
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4763 load images for openebs addon before installing it during preinit migration
  addons/openebs/3.7.0/install.sh
  addons/openebs/3.8.0/install.sh
  addons/openebs/template/base/install.sh
Labels: type::bug, bug::normal

#4771 only upgrade one verion in the onmerge airgap test
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#4773 pin ubuntu 18.04's containerd at no-greater-than 1.6.21
  addons/containerd/1.6.22/Manifest
  addons/containerd/1.6.22/crictl.yaml
  addons/containerd/1.6.22/host-preflight.yaml
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.22/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.22/kubeadm-join-config-v1beta2.yaml
  addons/containerd/template/script.sh
Labels: type::chore

#4776 fix containerd version generation
  addons/containerd/template/script.sh
Labels: type::chore

#4748 Automated Containerd version update 1.6.22
  addons/containerd/1.6.10/Manifest
  addons/containerd/1.6.11/Manifest
  addons/containerd/1.6.12/Manifest
  addons/containerd/1.6.13/Manifest
  addons/containerd/1.6.14/Manifest
  addons/containerd/1.6.15/Manifest
  addons/containerd/1.6.16/Manifest
  addons/containerd/1.6.18/Manifest
  addons/containerd/1.6.19/Manifest
  addons/containerd/1.6.20/Manifest
  addons/containerd/1.6.21/Manifest
  addons/containerd/1.6.4/Manifest
  addons/containerd/1.6.6/Manifest
  addons/containerd/1.6.7/Manifest
  addons/containerd/1.6.8/Manifest
  addons/containerd/1.6.9/Manifest
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#4775 don't use removed 'kubectl version --short' command
  addons/rook/1.10.11/install.sh
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.11.2/install.sh
  addons/rook/1.11.3/install.sh
  addons/rook/1.11.4/install.sh
  addons/rook/1.11.5/install.sh
  addons/rook/1.11.6/install.sh
  addons/rook/1.11.7/install.sh
  addons/rook/1.11.8/install.sh
  addons/rook/1.12.0/install.sh
  addons/rook/1.12.1/install.sh
  addons/rook/1.4.3/install.sh
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  scripts/tasks.sh
  testgrid/specs/customer-migration-specs.yaml
Labels: type::chore

#4777 use 'kubectl version' with or without '--short' as appropriate
  scripts/common/common.sh
  scripts/common/yaml.sh
  scripts/tasks.sh
Labels: type::chore

#4756 Automated Rook version update 1.12.2
  addons/rook/1.12.2/Manifest
  addons/rook/1.12.2/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.12.2/cluster/cephfs/filesystem.yaml
  addons/rook/1.12.2/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.12.2/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.12.2/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.12.2/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.12.2/cluster/cluster.yaml
  addons/rook/1.12.2/cluster/kustomization.yaml
  addons/rook/1.12.2/cluster/object-user.yaml
  addons/rook/1.12.2/cluster/object.yaml
  addons/rook/1.12.2/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.12.2/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.12.2/cluster/patches/object-Json6902.yaml
  addons/rook/1.12.2/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.12.2/cluster/patches/tmpl-object.yaml
  addons/rook/1.12.2/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.12.2/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.12.2/crds.yaml
  addons/rook/1.12.2/host-preflight.yaml
  addons/rook/1.12.2/install.sh
  addons/rook/1.12.2/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.12.2/monitoring/kustomization.yaml
  addons/rook/1.12.2/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.12.2/operator/cluster-rbac.yaml
  addons/rook/1.12.2/operator/clusterrole.yaml
  addons/rook/1.12.2/operator/clusterrolebinding.yaml
  addons/rook/1.12.2/operator/configmap-rook-config-override.yaml
  addons/rook/1.12.2/operator/configmap.yaml
  addons/rook/1.12.2/operator/deployment.yaml
  addons/rook/1.12.2/operator/kustomization.yaml
  addons/rook/1.12.2/operator/namespace.yaml
  addons/rook/1.12.2/operator/patches/deployment-privileged.yaml
  addons/rook/1.12.2/operator/patches/deployment-tolerations.yaml
  addons/rook/1.12.2/operator/role.yaml
  addons/rook/1.12.2/operator/rolebinding.yaml
  addons/rook/1.12.2/operator/serviceaccount.yaml
  addons/rook/1.12.2/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4707 Automated Velero version update 1.11.1
  addons/velero/1.11.1/Manifest
  addons/velero/1.11.1/install.sh
  addons/velero/1.11.1/node-agent-daemonset-privileged.yaml
  addons/velero/1.11.1/s3-migration-configmap.yaml
  addons/velero/1.11.1/tmpl-change-storageclass.yaml
  addons/velero/1.11.1/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.11.1/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.11.1/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.11.1/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.11.1/tmpl-kustomization.yaml
  addons/velero/1.11.1/tmpl-node-agent-daemonset-proxy.yaml
  addons/velero/1.11.1/tmpl-s3-migration-bsl.yaml
  addons/velero/1.11.1/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.11.1/tmpl-s3-migration-secret.yaml
  addons/velero/1.11.1/tmpl-velero-deployment-proxy.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#4778 Automated Kubernetes version update 1.28.1 1.27.5 1.26.8 1.25.13 1.24.16 1.23.17 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.25.13/Manifest
  packages/kubernetes/1.25.13/conformance/Manifest
  packages/kubernetes/1.26.8/Manifest
  packages/kubernetes/1.26.8/conformance/Manifest
  packages/kubernetes/1.27.5/Manifest
  packages/kubernetes/1.27.5/conformance/Manifest
  packages/kubernetes/1.28.1/Manifest
  packages/kubernetes/1.28.1/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4779 Automated Kubernetes version update 1.24.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.24.17/Manifest
  packages/kubernetes/1.24.17/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4787 remove pinned dependency and update rook
  go.mod
  go.sum
  pkg/cli/longhorn.go
  pkg/cluster/nodes.go
  pkg/cluster/space/openebs_free_disk_space_getter.go
  pkg/cluster/space/openebs_free_disk_space_getter_test.go
Labels: type::chore

#4789 enable testgrid running multi node upgrade tests
  scripts/common/addon.sh
  scripts/common/common.sh
  scripts/common/upgrade.sh
  scripts/install.sh
Labels: type::feature

#4792 bug: bump kurlkinds to 1.4.7 and fixes invalid hostpreflight operation
  go.mod
  go.sum
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/vendorflights/testdata/basic/expected_preflights.yaml
Labels: type::bug, bug::normal

#4646 Replace FOSSA with Trivy for license scan
  .fossa.yml
  .github/workflows/fossa.yaml
  .github/workflows/license.yaml
  .gitignore
  README.md
Labels: type::chore
