Repository replicatedhq/kURL, pull requests merged in 2023-05, with the labels that each got.

#4449 feat: allow specify kubeadm ignore-preflight-errors and better coredns debugging
  Makefile
  bin/watchrsync.js
  go.mod
  go.sum
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/yamltobash/main.go
  scripts/common/kubernetes.sh
  scripts/common/preflights.sh
  scripts/common/upgrade.sh
  scripts/common/utilbinaries.sh
  scripts/install.sh
  scripts/manifests/troubleshoot.yaml
  testgrid/specs/full.yaml
Labels: type::feature

#4451 Remove --container-runtime kubelet CLI argument after 1.27 upgrade
  scripts/common/upgrade.sh
Labels: type::chore

#4453 fix: empty kustomize dir causes script to exit
  Makefile
Labels: type::bug, bug::normal

#4455 feat(kubernetes): configure max pods per node
  go.mod
  go.sum
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/yamltobash/main.go
  scripts/common/utilbinaries.sh
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/patch-kubelet-max-pods.tmpl.yaml
  testgrid/specs/full.yaml
Labels: type::feature

#4456 Exclude Rook patches from Kustomize v5 (1.27) behavior
  scripts/common/yaml.sh
Labels: type::chore

#4457 log more steps in the containerd migration process
  addons/containerd/template/base/install.sh
Labels: type::chore

#4438 Automated EKCO version update 0.26.5
  addons/ekco/0.26.5/Manifest
  addons/ekco/0.26.5/install.sh
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4442 Automated Prometheus version update 0.65.1-45.26.0
  addons/prometheus/0.65.1-45.26.0/Manifest
  addons/prometheus/0.65.1-45.26.0/crds/crds.yaml
  addons/prometheus/0.65.1-45.26.0/crds/kustomization.yaml
  addons/prometheus/0.65.1-45.26.0/crds/preserveUnknown.yaml
  addons/prometheus/0.65.1-45.26.0/host-preflight.yaml
  addons/prometheus/0.65.1-45.26.0/install.sh
  addons/prometheus/0.65.1-45.26.0/nodeport-services.yaml
  addons/prometheus/0.65.1-45.26.0/operator/adapter.yaml
  addons/prometheus/0.65.1-45.26.0/operator/default.yaml
  addons/prometheus/0.65.1-45.26.0/operator/kustomization.yaml
  addons/prometheus/0.65.1-45.26.0/operator/longhorn.yaml
  addons/prometheus/0.65.1-45.26.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.65.1-45.26.0/operator/matchlabel-release.yaml
  addons/prometheus/0.65.1-45.26.0/operator/ns.yaml
  addons/prometheus/0.65.1-45.26.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.65.1-45.26.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4443 Automated MinIO version update RELEASE.2023-05-04T21-44-30Z
  addons/minio/2023-05-04T21-44-30Z/Manifest
  addons/minio/2023-05-04T21-44-30Z/deployment.yaml
  addons/minio/2023-05-04T21-44-30Z/install.sh
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-05-04T21-44-30Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-05-04T21-44-30Z/service.yaml
  addons/minio/2023-05-04T21-44-30Z/tmpl-creds-secret.yaml
  addons/minio/2023-05-04T21-44-30Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-05-04T21-44-30Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-05-04T21-44-30Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-05-04T21-44-30Z/tmpl-kustomization.yaml
  addons/minio/2023-05-04T21-44-30Z/tmpl-namespace.yaml
  addons/minio/2023-05-04T21-44-30Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4458 Automated Flannel version update 0.21.5
  addons/flannel/0.21.5/Manifest
  addons/flannel/0.21.5/host-preflight.yaml
  addons/flannel/0.21.5/install.sh
  addons/flannel/0.21.5/kubeadm.yaml
  addons/flannel/0.21.5/template/iface.patch.tmpl.yaml
  addons/flannel/0.21.5/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.21.5/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.21.5/yaml/kube-flannel.yml
  addons/flannel/0.21.5/yaml/kustomization.yaml
  addons/flannel/0.21.5/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#4467 feat(rook): per node device configuration
  addons/ekco/0.26.5/Manifest
  addons/ekco/0.27.0/Manifest
  addons/ekco/0.27.0/README.md
  addons/ekco/0.27.0/configmap.tmpl.yaml
  addons/ekco/0.27.0/deployment.tmpl.yaml
  addons/ekco/0.27.0/ekco-purge-node.sh
  addons/ekco/0.27.0/install.sh
  addons/ekco/0.27.0/kustomization.yaml
  addons/ekco/0.27.0/namespace.yaml
  addons/ekco/0.27.0/rbac-kotsadm.yaml
  addons/ekco/0.27.0/rbac-minio.yaml
  addons/ekco/0.27.0/rbac-rook.yaml
  addons/ekco/0.27.0/rbac.yaml
  addons/ekco/0.27.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.27.0/reboot/ekco-reboot.service
  addons/ekco/0.27.0/reboot/shutdown.sh
  addons/ekco/0.27.0/reboot/startup.sh
  addons/ekco/0.27.0/regen-cert-pod.yaml
  addons/ekco/0.27.0/rolebinding-kotsadm.yaml
  addons/ekco/0.27.0/rolebinding-minio.yaml
  addons/ekco/0.27.0/rolebinding-rook.yaml
  addons/ekco/0.27.0/rolebinding.yaml
  addons/ekco/0.27.0/rotate-certs-rbac.yaml
  addons/ekco/template/base/configmap.tmpl.yaml
  addons/ekco/template/base/deployment.tmpl.yaml
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/kustomization.yaml
  addons/ekco/template/generate.sh
  addons/rook/1.11.4/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.11.4/install.sh
  addons/rook/template/base/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/template/base/install.sh
  addons/rook/template/test/install.sh
  go.mod
  go.sum
  kurl_util/cmd/yamltobash/main.go
  scripts/common/yaml-test.sh
  scripts/common/yaml.sh
  testgrid/specs/full.yaml
  web/src/installers/versions.js
Labels: type::feature

#4469 Automated Contour version update 1.25.0
  addons/contour/1.25.0/Manifest
  addons/contour/1.25.0/contour.yaml
  addons/contour/1.25.0/install.sh
  addons/contour/1.25.0/patches/job-image.yaml
  addons/contour/1.25.0/patches/resource-limits.yaml
  addons/contour/1.25.0/tmpl-configmap.yaml
  addons/contour/1.25.0/tmpl-kustomization.yaml
  addons/contour/1.25.0/tmpl-namespace.yaml
  addons/contour/1.25.0/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#4468 Automated Prometheus version update 0.65.1-45.27.1
  addons/prometheus/0.65.1-45.27.1/Manifest
  addons/prometheus/0.65.1-45.27.1/crds/crds.yaml
  addons/prometheus/0.65.1-45.27.1/crds/kustomization.yaml
  addons/prometheus/0.65.1-45.27.1/crds/preserveUnknown.yaml
  addons/prometheus/0.65.1-45.27.1/host-preflight.yaml
  addons/prometheus/0.65.1-45.27.1/install.sh
  addons/prometheus/0.65.1-45.27.1/nodeport-services.yaml
  addons/prometheus/0.65.1-45.27.1/operator/adapter.yaml
  addons/prometheus/0.65.1-45.27.1/operator/default.yaml
  addons/prometheus/0.65.1-45.27.1/operator/kustomization.yaml
  addons/prometheus/0.65.1-45.27.1/operator/longhorn.yaml
  addons/prometheus/0.65.1-45.27.1/operator/matchlabel-instance.yaml
  addons/prometheus/0.65.1-45.27.1/operator/matchlabel-release.yaml
  addons/prometheus/0.65.1-45.27.1/operator/ns.yaml
  addons/prometheus/0.65.1-45.27.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.65.1-45.27.1/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4470 fix(testgrid): invalid patch yaml
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal

#4472 chore(rook): add 1.11 tests to testgrid
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#4471 fix(kots): prerelease message always shows in testgrid
  scripts/common/preflights.sh
Labels: type::chore

#4476 fix(rook): testgrid multi-upgrades should respect s3Override URL
  scripts/common/rook-upgrade.sh
Labels: type::bug, bug::normal

#4477 add RBAC roles required to run openebs+minio->rook migration to ekco
  addons/ekco/template/base/configmap.tmpl.yaml
  addons/ekco/template/base/deployment.tmpl.yaml
  addons/ekco/template/base/rbac.yaml
  addons/ekco/template/base/rolebinding.yaml
Labels: type::chore

#4478 Automated EKCO version update 0.27.1
  addons/ekco/0.27.0/Manifest
  addons/ekco/0.27.0/rolebinding.yaml
  addons/ekco/0.27.1/Manifest
  addons/ekco/0.27.1/README.md
  addons/ekco/0.27.1/configmap.tmpl.yaml
  addons/ekco/0.27.1/deployment.tmpl.yaml
  addons/ekco/0.27.1/ekco-purge-node.sh
  addons/ekco/0.27.1/install.sh
  addons/ekco/0.27.1/kustomization.yaml
  addons/ekco/0.27.1/namespace.yaml
  addons/ekco/0.27.1/rbac-kotsadm.yaml
  addons/ekco/0.27.1/rbac-minio.yaml
  addons/ekco/0.27.1/rbac-rook.yaml
  addons/ekco/0.27.1/rbac.yaml
  addons/ekco/0.27.1/reboot/ekco-reboot-containerd.service
  addons/ekco/0.27.1/reboot/ekco-reboot.service
  addons/ekco/0.27.1/reboot/shutdown.sh
  addons/ekco/0.27.1/reboot/startup.sh
  addons/ekco/0.27.1/regen-cert-pod.yaml
  addons/ekco/0.27.1/rolebinding-kotsadm.yaml
  addons/ekco/0.27.1/rolebinding-minio.yaml
  addons/ekco/0.27.1/rolebinding-rook.yaml
  addons/ekco/0.27.1/rolebinding.yaml
  addons/ekco/0.27.1/rotate-certs-rbac.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4452 Automated Rook version update 1.11.5
  addons/rook/1.11.5/Manifest
  addons/rook/1.11.5/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.11.5/cluster/cephfs/filesystem.yaml
  addons/rook/1.11.5/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.11.5/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.11.5/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.11.5/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.11.5/cluster/cluster.yaml
  addons/rook/1.11.5/cluster/kustomization.yaml
  addons/rook/1.11.5/cluster/object-user.yaml
  addons/rook/1.11.5/cluster/object.yaml
  addons/rook/1.11.5/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.11.5/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.11.5/cluster/patches/object-Json6902.yaml
  addons/rook/1.11.5/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.11.5/cluster/patches/tmpl-object.yaml
  addons/rook/1.11.5/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.5/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.5/crds.yaml
  addons/rook/1.11.5/host-preflight.yaml
  addons/rook/1.11.5/install.sh
  addons/rook/1.11.5/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.11.5/monitoring/kustomization.yaml
  addons/rook/1.11.5/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.11.5/operator/cluster-rbac.yaml
  addons/rook/1.11.5/operator/clusterrole.yaml
  addons/rook/1.11.5/operator/clusterrolebinding.yaml
  addons/rook/1.11.5/operator/configmap-rook-config-override.yaml
  addons/rook/1.11.5/operator/configmap.yaml
  addons/rook/1.11.5/operator/deployment.yaml
  addons/rook/1.11.5/operator/kustomization.yaml
  addons/rook/1.11.5/operator/namespace.yaml
  addons/rook/1.11.5/operator/patches/deployment-privileged.yaml
  addons/rook/1.11.5/operator/patches/deployment-tolerations.yaml
  addons/rook/1.11.5/operator/role.yaml
  addons/rook/1.11.5/operator/rolebinding.yaml
  addons/rook/1.11.5/operator/serviceaccount.yaml
  addons/rook/1.11.5/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4473 🐛 fix in cluster preflights which cannot be executed because was not possible to find the config
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#4482 Automated Registry version update 2.8.2
  addons/registry/2.8.2/Manifest
  addons/registry/2.8.2/README.md
  addons/registry/2.8.2/deployment-pvc.yaml
  addons/registry/2.8.2/install.sh
  addons/registry/2.8.2/kustomization.yaml
  addons/registry/2.8.2/patch-deployment-migrate-s3.yaml
  addons/registry/2.8.2/patch-deployment-velero.yaml
  addons/registry/2.8.2/service.yaml
  addons/registry/2.8.2/tmpl-cluster-ip-patch.yaml
  addons/registry/2.8.2/tmpl-configmap-migrate-s3.yaml
  addons/registry/2.8.2/tmpl-configmap-velero.yaml
  addons/registry/2.8.2/tmpl-deployment-objectstore.yaml
  addons/registry/2.8.2/tmpl-node-port-patch.yaml
  addons/registry/2.8.2/tmpl-persistentvolumeclaim.yaml
  addons/registry/2.8.2/tmpl-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, registry

#4362 handle dynamic storage storageclass creation
  addons/ekco/0.27.1/install.sh
  addons/ekco/0.27.1/storageclass-scaling.yaml
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/storageclass-scaling.yaml
  addons/minio/2023-05-04T21-44-30Z/install.sh
  addons/minio/template/base/install.sh
  addons/openebs/3.6.0/install.sh
  addons/openebs/template/base/install.sh
  addons/rook/1.11.5/install.sh
  addons/rook/template/base/install.sh
Labels: type::feature

#4486 Adds collectd to ubuntu 22.04 and tests
  pkg/preflight/assets/host-preflights.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::feature

#4490 chore: remove deprecated set-output command.
  .github/workflows/cron-scan-images-daily.yaml
Labels: type::chore

#4497 chore(actions): deprecate set-output
  .github/workflows/cron-rebuild-packages-prod.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  addons/antrea/template/generate.sh
  addons/containerd/template/script.sh
  addons/contour/template/script.sh
  addons/ekco/template/generate.sh
  addons/flannel/template/generate.sh
  addons/goldpinger/template/generate.sh
  addons/longhorn/template/generate.sh
  addons/metrics-server/template/generate.sh
  addons/minio/template/generate.sh
  addons/openebs/template/generate.sh
  addons/prometheus/template/generate.sh
  addons/registry/template/generate.sh
  addons/rook/template/generate.sh
  addons/sonobuoy/template/generate.sh
  addons/velero/template/generate.sh
  addons/weave/template/generate.sh
  bin/addon-has-changes-matrix.sh
  bin/build-addon-package.sh
  bin/test-addon.sh
  packages/kubernetes/template/script.sh
Labels: type::chore

#4495 fix: weave support with symlinks
  addons/weave/template/base/patch-daemonset.yaml
Labels: type::bug, bug::normal

#4496 Automated Velero version update 1.11.0
  addons/velero/1.11.0/Manifest
  addons/velero/1.11.0/install.sh
Labels: automated-pr, velero, type::chore, kurl::type::feature

#4498 Automated Prometheus version update 0.65.1-45.28.0
  addons/prometheus/0.65.1-45.28.0/Manifest
  addons/prometheus/0.65.1-45.28.0/crds/crds.yaml
  addons/prometheus/0.65.1-45.28.0/crds/kustomization.yaml
  addons/prometheus/0.65.1-45.28.0/crds/preserveUnknown.yaml
  addons/prometheus/0.65.1-45.28.0/host-preflight.yaml
  addons/prometheus/0.65.1-45.28.0/install.sh
  addons/prometheus/0.65.1-45.28.0/nodeport-services.yaml
  addons/prometheus/0.65.1-45.28.0/operator/adapter.yaml
  addons/prometheus/0.65.1-45.28.0/operator/default.yaml
  addons/prometheus/0.65.1-45.28.0/operator/kustomization.yaml
  addons/prometheus/0.65.1-45.28.0/operator/longhorn.yaml
  addons/prometheus/0.65.1-45.28.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.65.1-45.28.0/operator/matchlabel-release.yaml
  addons/prometheus/0.65.1-45.28.0/operator/ns.yaml
  addons/prometheus/0.65.1-45.28.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.65.1-45.28.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4499 add tests to cover symbolic links
  testgrid/specs/full.yaml
Labels: type::chore

#4500 regenerate weave 2.8.1-20230417 and 2.6.5-20230417 to allow it works with specific symbolic link scenario
  addons/weave/2.6.5-20230417/patch-daemonset.yaml
  addons/weave/2.8.1-20230417/patch-daemonset.yaml
Labels: type::bug, bug::normal

#4312 adds check to verify if pods are running for Rook upgrades from 1.x 1.4.9
  addons/rookupgrade/10to14/install.sh
Labels: type::bug, bug::normal

#4502 fix(testgrid): use latest rocky 9.1 image
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::bug, bug::normal

#4510 fix(rook): fix roll out rook 1.1.9 and ceph 14.2.5
  addons/rookupgrade/10to14/install.sh
  pkg/rook/health.go
Labels: type::bug, bug::normal

#4503 reverting changes done for weave 2.6.5-20230417
  addons/weave/2.6.5-20230417/patch-daemonset.yaml
Labels: type::bug, bug::regression

#4511 Automated Kubernetes version update 1.27.2 1.26.5 1.25.10 1.24.14 1.23.17 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.24.14/Manifest
  packages/kubernetes/1.24.14/conformance/Manifest
  packages/kubernetes/1.25.10/Manifest
  packages/kubernetes/1.25.10/conformance/Manifest
  packages/kubernetes/1.26.5/Manifest
  packages/kubernetes/1.26.5/conformance/Manifest
  packages/kubernetes/1.27.2/Manifest
  packages/kubernetes/1.27.2/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4514 fix(rook): improve upgrade to 1.5.12 stability
  addons/rook/1.5.12/install.sh
Labels: type::bug, bug::normal

#4515 fix(kubernetes): images no longer hosted on k8s.gcr.io
  addons/sonobuoy/0.56.8/install.sh
  addons/sonobuoy/template/base/install.sh
  packages/kubernetes/1.22.17/conformance/Manifest
  packages/kubernetes/1.23.17/conformance/Manifest
  packages/kubernetes/1.24.14/conformance/Manifest
  packages/kubernetes/1.25.10/conformance/Manifest
  packages/kubernetes/1.26.5/conformance/Manifest
  packages/kubernetes/1.27.2/conformance/Manifest
  packages/kubernetes/template/script.sh
  scripts/common/common.sh
Labels: type::chore

#4516 fix: install failure no gcr.io images
  scripts/common/common.sh
Labels: type::bug, bug::normal

#4519 fix(rook): flexvolume migration fails with error cant scale replicaset
  pkg/rook/flexvolume.go
Labels: type::bug, bug::normal

#4517 Automated MinIO version update RELEASE.2023-05-18T00-05-36Z
  addons/minio/2023-05-18T00-05-36Z/Manifest
  addons/minio/2023-05-18T00-05-36Z/deployment.yaml
  addons/minio/2023-05-18T00-05-36Z/install.sh
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-05-18T00-05-36Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-05-18T00-05-36Z/service.yaml
  addons/minio/2023-05-18T00-05-36Z/tmpl-creds-secret.yaml
  addons/minio/2023-05-18T00-05-36Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-05-18T00-05-36Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-05-18T00-05-36Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-05-18T00-05-36Z/tmpl-kustomization.yaml
  addons/minio/2023-05-18T00-05-36Z/tmpl-namespace.yaml
  addons/minio/2023-05-18T00-05-36Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4520 (chore)Testgrid airgap install with invalid PROXY
  testgrid/specs/full.yaml
Labels: type::chore

#4508 Adds further information about proxy settings on the scripts
  scripts/common/proxy.sh
Labels: type::feature

#4507 Increase docker proxy configuration logs
  scripts/common/docker.sh
Labels: type::feature

#4506 increase the logs from containerd version 1.5.10
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.19/install.sh
  addons/containerd/1.6.20/install.sh
  addons/containerd/1.6.21/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/install.sh
  addons/containerd/template/base/install.sh
Labels: type::feature

#4518 feat: added command to start ekco storage migration
  pkg/cli/cluster_migrate_multinode_storage.go
  pkg/cli/commands.go
Labels: type::feature

#4504 Automated Rook version update 1.11.6
  addons/rook/1.11.6/Manifest
  addons/rook/1.11.6/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.11.6/cluster/cephfs/filesystem.yaml
  addons/rook/1.11.6/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.11.6/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.11.6/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.11.6/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.11.6/cluster/cluster.yaml
  addons/rook/1.11.6/cluster/kustomization.yaml
  addons/rook/1.11.6/cluster/object-user.yaml
  addons/rook/1.11.6/cluster/object.yaml
  addons/rook/1.11.6/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.11.6/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.11.6/cluster/patches/object-Json6902.yaml
  addons/rook/1.11.6/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.11.6/cluster/patches/tmpl-object.yaml
  addons/rook/1.11.6/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.6/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.6/crds.yaml
  addons/rook/1.11.6/host-preflight.yaml
  addons/rook/1.11.6/install.sh
  addons/rook/1.11.6/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.11.6/monitoring/kustomization.yaml
  addons/rook/1.11.6/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.11.6/operator/cluster-rbac.yaml
  addons/rook/1.11.6/operator/clusterrole.yaml
  addons/rook/1.11.6/operator/clusterrolebinding.yaml
  addons/rook/1.11.6/operator/configmap-rook-config-override.yaml
  addons/rook/1.11.6/operator/configmap.yaml
  addons/rook/1.11.6/operator/deployment.yaml
  addons/rook/1.11.6/operator/kustomization.yaml
  addons/rook/1.11.6/operator/namespace.yaml
  addons/rook/1.11.6/operator/patches/deployment-privileged.yaml
  addons/rook/1.11.6/operator/patches/deployment-tolerations.yaml
  addons/rook/1.11.6/operator/role.yaml
  addons/rook/1.11.6/operator/rolebinding.yaml
  addons/rook/1.11.6/operator/serviceaccount.yaml
  addons/rook/1.11.6/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4530 Adds support to ol8.8 by updating preflight check
  scripts/common/preflights.sh
Labels: type::feature

#4532 fix(kubernetes): build broken change url for gpg key
  bundles/k8s-ubuntu1604/Dockerfile
  bundles/k8s-ubuntu1804/Dockerfile
  bundles/k8s-ubuntu2004/Dockerfile
  bundles/k8s-ubuntu2204/Dockerfile
  packages/kubernetes/template/Dockerfile
Labels: type::chore

#4531 Fixes handling of the additional-no-proxy-addresses flag in the installation script's join command output
  scripts/install.sh
Labels: type::bug, bug::normal

#4535 update unsupported tests targeting rocky-91 with rocky-92
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4536 proper handle additional-no-proxy-addresses flag on upgrade
  scripts/common/addon.sh
Labels: type::bug, bug::normal

#4539 fix k8s upgrades to properly handle the flag
  scripts/common/upgrade.sh
Labels: type::bug, bug::normal

#4540 Applying openssl workaround in order to support rhel9
  addons/rook/1.0.4-14.2.21/install.sh
  addons/rook/1.0.4/install.sh
  addons/rook/1.10.11/install.sh
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.11.2/install.sh
  addons/rook/1.11.3/install.sh
  addons/rook/1.11.4/install.sh
  addons/rook/1.11.5/install.sh
  addons/rook/1.11.6/install.sh
  addons/rook/1.4.3/install.sh
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  scripts/common/object_store.sh
Labels: type::bug, bug::normal

#4541 Revert "Applying openssl workaround in order to support rhel9"
  addons/rook/1.0.4-14.2.21/install.sh
  addons/rook/1.0.4/install.sh
  addons/rook/1.10.11/install.sh
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.11.2/install.sh
  addons/rook/1.11.3/install.sh
  addons/rook/1.11.4/install.sh
  addons/rook/1.11.5/install.sh
  addons/rook/1.11.6/install.sh
  addons/rook/1.4.3/install.sh
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  scripts/common/object_store.sh
Labels: type::bug, bug::regression

#4542 Improve Registry logs - Template
  addons/registry/2.8.2/install.sh
  addons/registry/template/base/install.sh
Labels: type::feature

#4544 fix Rook OpenSSL calls in order to provide support for RHEL 9.2
  addons/rook/1.0.4-14.2.21/install.sh
  addons/rook/1.0.4/install.sh
  addons/rook/1.10.11/install.sh
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.11.2/install.sh
  addons/rook/1.11.3/install.sh
  addons/rook/1.11.4/install.sh
  addons/rook/1.11.5/install.sh
  addons/rook/1.11.6/install.sh
  addons/rook/1.4.3/install.sh
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  scripts/common/object_store.sh
Labels: type::bug, bug::normal

#4543 fix registry OpenSSL calls in order to provide support for RHEL 9.2
  addons/registry/2.7.1/install.sh
  addons/registry/2.8.1/install.sh
  addons/registry/2.8.2/install.sh
  addons/registry/template/base/install.sh
Labels: type::bug, bug::normal

#4521 chore(rook): improve storage migration upgrade tests
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4546 Improve log message to know when the host preflights were ignored and has or not failures
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#4548 nit: remove todo that was addressed for preflight
  scripts/common/preflights.sh
Labels: type::chore

#4545 Fix: Scale Distinct Controller Objects when Preparing for Longhorn Migration
  pkg/cli/longhorn.go
Labels: type::bug, bug::normal

#4552 Add proxy config check to the install script
  scripts/install.sh
Labels: type::feature

#4549 Refining tests done against each PR
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#4554 fix: Retry update on Longhorn volume CR during Longhorn rollback-migration-replicas CLI command
  pkg/cli/longhorn.go
Labels: type::bug, bug::normal

#4551 Fixes weave uninstall by removing interfaces first and began to remove lib/weave
  addons/flannel/0.21.5/install.sh
  addons/flannel/template/base/install.sh
Labels: type::bug, bug::normal

#4553 weave to flannel getting stuck to delete the pods
  addons/flannel/0.21.5/install.sh
  addons/flannel/template/base/install.sh
Labels: type::bug, bug::normal

#4538 bug: configuring containerd and docker https proxy
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.19/install.sh
  addons/containerd/1.6.20/install.sh
  addons/containerd/1.6.21/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/install.sh
  addons/containerd/template/base/install.sh
  scripts/common/docker.sh
  scripts/common/proxy.sh
Labels: type::bug, bug::normal

#4570 removing weave from the nodes
  scripts/tasks.sh
Labels: type::bug, bug::normal

#4571 fix: wait for rook ceph migrator pod ready
  pkg/rook/flexvolume.go
Labels: type::bug, bug::normal

#4567 Increase Flannel waiting and improve log
  addons/flannel/0.21.5/install.sh
  addons/flannel/template/base/install.sh
Labels: type::bug, bug::normal

#4572 refine new tests add, add unsupported
  addons/flannel/template/testgrid/k8s-ctrd.yaml
Labels: type::chore
