Repository replicatedhq/kURL, pull requests merged in 2023-04, with the labels that each got.

#4325 chore: add missing "multi-node" to a testgrid name
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4324 chore: add missing post install script
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4326 bug: scale down ekco during sc migration (rqlite)
  scripts/common/longhorn.sh
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#4327 migrations from Longhorn to OpenEBS only require an object store if one already exists
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#4328 chore: Cleanup Oracle Linux (OL9) References since it's not supported
  addons/containerd/1.6.10/host-preflight.yaml
  addons/containerd/1.6.11/host-preflight.yaml
  addons/containerd/1.6.12/host-preflight.yaml
  addons/containerd/1.6.13/host-preflight.yaml
  addons/containerd/1.6.14/host-preflight.yaml
  addons/containerd/1.6.15/host-preflight.yaml
  addons/containerd/1.6.16/host-preflight.yaml
  addons/containerd/1.6.18/host-preflight.yaml
  addons/containerd/1.6.19/host-preflight.yaml
  addons/containerd/1.6.20/host-preflight.yaml
  addons/containerd/1.6.4/host-preflight.yaml
  addons/containerd/1.6.6/host-preflight.yaml
  addons/containerd/1.6.7/host-preflight.yaml
  addons/containerd/1.6.8/host-preflight.yaml
  addons/containerd/1.6.9/host-preflight.yaml
  addons/containerd/template/script.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  scripts/common/preflights.sh
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4291 feat: allow containerd two minor version upgrades
  Makefile
  addons/containerd/template/script.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  scripts/common/common.sh
  scripts/common/containerd.sh
  scripts/install.sh
  scripts/join.sh
  scripts/upgrade.sh
  testgrid/specs/full.yaml
Labels: type::feature

#4331 bug: downloading previous containerd minor version
  scripts/common/common.sh
  scripts/common/containerd.sh
Labels: type::bug, bug::normal

#4289 feat(preflights): check load balancer health on upgrades
  pkg/preflight/assets/host-preflights.yaml
Labels: type::feature

#4333 fix: error polling until spinner fails
  scripts/common/kubernetes.sh
Labels: type::chore

#4332 fix(testgrid): old weave version failing on rhel-8
  testgrid/specs/full.yaml
Labels: type::chore

#4334 Automated EKCO version update 0.26.5
  addons/ekco/0.26.5/Manifest
  addons/ekco/0.26.5/README.md
  addons/ekco/0.26.5/deployment.yaml
  addons/ekco/0.26.5/ekco-purge-node.sh
  addons/ekco/0.26.5/install.sh
  addons/ekco/0.26.5/kustomization.yaml
  addons/ekco/0.26.5/namespace.yaml
  addons/ekco/0.26.5/rbac-kotsadm.yaml
  addons/ekco/0.26.5/rbac-minio.yaml
  addons/ekco/0.26.5/rbac-rook.yaml
  addons/ekco/0.26.5/rbac.yaml
  addons/ekco/0.26.5/reboot/ekco-reboot-containerd.service
  addons/ekco/0.26.5/reboot/ekco-reboot.service
  addons/ekco/0.26.5/reboot/shutdown.sh
  addons/ekco/0.26.5/reboot/startup.sh
  addons/ekco/0.26.5/regen-cert-pod.yaml
  addons/ekco/0.26.5/rolebinding-kotsadm.yaml
  addons/ekco/0.26.5/rolebinding-minio.yaml
  addons/ekco/0.26.5/rolebinding-rook.yaml
  addons/ekco/0.26.5/rolebinding.yaml
  addons/ekco/0.26.5/rotate-certs-rbac.yaml
  addons/ekco/0.26.5/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4330 Automated Prometheus version update 0.63.0-45.9.1
  addons/prometheus/0.63.0-45.9.1/Manifest
  addons/prometheus/0.63.0-45.9.1/crds/crds.yaml
  addons/prometheus/0.63.0-45.9.1/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.9.1/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.9.1/host-preflight.yaml
  addons/prometheus/0.63.0-45.9.1/install.sh
  addons/prometheus/0.63.0-45.9.1/nodeport-services.yaml
  addons/prometheus/0.63.0-45.9.1/operator/adapter.yaml
  addons/prometheus/0.63.0-45.9.1/operator/default.yaml
  addons/prometheus/0.63.0-45.9.1/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.9.1/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.9.1/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.9.1/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.9.1/operator/ns.yaml
  addons/prometheus/0.63.0-45.9.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.9.1/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4338 Automated Contour version update 1.24.3
  addons/contour/1.24.3/Manifest
  addons/contour/1.24.3/contour.yaml
  addons/contour/1.24.3/install.sh
  addons/contour/1.24.3/patches/job-image.yaml
  addons/contour/1.24.3/patches/resource-limits.yaml
  addons/contour/1.24.3/tmpl-configmap.yaml
  addons/contour/1.24.3/tmpl-kustomization.yaml
  addons/contour/1.24.3/tmpl-namespace.yaml
  addons/contour/1.24.3/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#4339 chore: disable containerd 1.2 on centos 74, 79 and ol-79
  testgrid/specs/full.yaml
Labels: type::chore

#4305 fix velero test which is missing minio
  addons/velero/template/testgrid/k8s-docker.yaml
Labels: type::chore

#4336 fix: typos
  scripts/common/preflights.sh
Labels: type::chore

#4196 create storage migration adr
  docs/arch/adr-009-storage-migration.md
Labels: type::chore

#4342 chore(docs): clarify adr storage migration proposal
  docs/arch/adr-009-storage-migration.md
Labels: type::chore

#4341 bug: allow installation of any containerd version in case of docker
  scripts/common/common.sh
  scripts/common/containerd.sh
Labels: type::bug, bug::regression

#4340 chore: cluster and instance identifier improvements
  scripts/common/common.sh
  scripts/common/reporting.sh
Labels: type::chore

#4343 chore(testgrid): add customer specific migration specs
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4347 fix(preflights): do not run some preflights on join or upgrade
  scripts/common/preflights.sh
  scripts/install.sh
Labels: type::bug, bug::normal

#4348 fix(preflights): do not run in-cluster preflights on upgrade
  scripts/upgrade.sh
Labels: type::bug, bug::normal

#4351 recreate flannel pods after upgrading k8s on each node
  scripts/common/upgrade.sh
Labels: type::bug, bug::normal

#4352 chore(testgrid): use airgap for customer specs
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4353 don't log when checking flannel namespace
  scripts/common/upgrade.sh
Labels: type::chore

#4345 Automated Registry version update 2.8.1
  addons/registry/2.8.1/Manifest
  addons/registry/2.8.1/patch-deployment-migrate-s3.yaml
  addons/registry/2.8.1/patch-deployment-velero.yaml
Labels: automated-pr, type::chore, kurl::type::feature, registry

#4365 fix(testgrid): broken kotsadm version prevents installs and upgrades
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4366 fix(container): migration from docker on remove nodes fails with downgrade not supported message
  scripts/common/upgrade.sh
Labels: type::bug, bug::regression

#4337 Automated Rook version update 1.11.3
  addons/rook/1.11.3/Manifest
  addons/rook/1.11.3/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.11.3/cluster/cephfs/filesystem.yaml
  addons/rook/1.11.3/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.11.3/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.11.3/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.11.3/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.11.3/cluster/cluster.yaml
  addons/rook/1.11.3/cluster/kustomization.yaml
  addons/rook/1.11.3/cluster/object-user.yaml
  addons/rook/1.11.3/cluster/object.yaml
  addons/rook/1.11.3/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.11.3/cluster/patches/object-Json6902.yaml
  addons/rook/1.11.3/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.11.3/cluster/patches/tmpl-object.yaml
  addons/rook/1.11.3/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.3/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.3/crds.yaml
  addons/rook/1.11.3/host-preflight.yaml
  addons/rook/1.11.3/install.sh
  addons/rook/1.11.3/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.11.3/monitoring/kustomization.yaml
  addons/rook/1.11.3/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.11.3/operator/cluster-rbac.yaml
  addons/rook/1.11.3/operator/clusterrole.yaml
  addons/rook/1.11.3/operator/clusterrolebinding.yaml
  addons/rook/1.11.3/operator/configmap-rook-config-override.yaml
  addons/rook/1.11.3/operator/configmap.yaml
  addons/rook/1.11.3/operator/deployment.yaml
  addons/rook/1.11.3/operator/kustomization.yaml
  addons/rook/1.11.3/operator/namespace.yaml
  addons/rook/1.11.3/operator/patches/deployment-privileged.yaml
  addons/rook/1.11.3/operator/patches/deployment-tolerations.yaml
  addons/rook/1.11.3/operator/role.yaml
  addons/rook/1.11.3/operator/rolebinding.yaml
  addons/rook/1.11.3/operator/serviceaccount.yaml
  addons/rook/1.11.3/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4368 chore: allow s3Override in dev env
  scripts/common/common.sh
Labels: type::chore

#4369 fix: dev env upgrade from prod
  scripts/common/preflights.sh
Labels: type::chore

#4270 Automated Velero version update 1.10.2
  addons/velero/1.10.2/Manifest
  addons/velero/1.10.2/install.sh
  addons/velero/1.10.2/tmpl-s3-migration-deployment-patch.yaml
Labels: automated-pr, velero, type::chore, kurl::type::feature

#4370 allow automation to create k8s 1.27 versions
  packages/kubernetes/template/script.sh
  testgrid/specs/deploy.yaml
  web/src/installers/versions.js
Labels: type::feature

#4371 Automated Kubernetes version update 1.27.0 1.26.3 1.25.8 1.24.12 1.23.17 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.27.0/Manifest
  packages/kubernetes/1.27.0/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4373 back out k8s 1.27 until we fix the kubeadm conf issue
  testgrid/specs/deploy.yaml
  web/src/installers/versions.js
Labels: type::feature

#4374 fix: Use KURL_INSTALL_DIRECTORY envar instead of hardcoded /var/lib/kurl
  scripts/common/common.sh
  scripts/common/reporting.sh
  scripts/tasks.sh
  testgrid/specs/full.yaml
Labels: type::bug, bug::regression

#4376 feat: implement node connectivity check
  go.mod
  go.sum
  pkg/cli/commands.go
  pkg/cli/nodes_connectivity.go
  pkg/k8sutil/apply.go
  pkg/k8sutil/daemonset.go
  pkg/k8sutil/job.go
  pkg/k8sutil/node.go
  pkg/rook/flexvolume.go
  pkg/static/nodes_connectivity/kustomize/base-listeners/daemonset.yaml
  pkg/static/nodes_connectivity/kustomize/base-listeners/kustomization.yaml
  pkg/static/nodes_connectivity/kustomize/pinger/job.yaml
  pkg/static/nodes_connectivity/kustomize/pinger/kustomization.yaml
  pkg/static/nodes_connectivity/kustomize/tcp-listeners/daemonset.yaml
  pkg/static/nodes_connectivity/kustomize/tcp-listeners/kustomization.yaml
  pkg/static/nodes_connectivity/kustomize/udp-listeners/daemonset.yaml
  pkg/static/nodes_connectivity/kustomize/udp-listeners/kustomization.yaml
  pkg/static/nodes_connectivity/static.go
Labels: type::feature

#4377 feat: upgrade kubernetes multiple versions
  .github/workflows/test-addon-pr.yaml
  addons/rookupgrade/10to14/install.sh
  scripts/common/addon.sh
  scripts/common/common-test.sh
  scripts/common/common.sh
  scripts/common/discover.sh
  scripts/common/kubernetes.sh
  scripts/common/rook-upgrade-test.sh
  scripts/common/rook-upgrade.sh
  scripts/common/upgrade.sh
  scripts/common/utilbinaries.sh
  scripts/install.sh
  scripts/join.sh
  scripts/tasks.sh
Labels: type::feature

#4385 fix: new kubernetes install tries to upgrade
  scripts/common/upgrade.sh
Labels: type::feature

#4387 fix: cron-weave-update action fixes
  .github/workflows/update-weave.yaml
  addons/weave/template/generate.sh
  web/src/installers/versions.js
Labels: type::chore

#4386 feat: test multiple kubernetes upgrades
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::feature

#4390 feat: test multiple kubernetes upgrades
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  testgrid/specs/full.yaml
Labels: type::feature

#4395 update controller-runtime to @main, and also the things dependent on k8s 1.27
  go.mod
  go.sum
  kurl_util/cmd/yamltobash/main.go
  pkg/cli/longhorn.go
Labels: type::chore

#4391 run testgrid when testgrid is changed
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#4389 Automated Weave version update 2.8.1-20230417
  addons/weave/2.8.1-20230417/Manifest
  addons/weave/2.8.1-20230417/host-preflight.yaml
  addons/weave/2.8.1-20230417/install.sh
  addons/weave/2.8.1-20230417/kustomization.yaml
  addons/weave/2.8.1-20230417/patch-daemonset.yaml
  addons/weave/2.8.1-20230417/patch-encrypt.yaml
  addons/weave/2.8.1-20230417/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.8.1-20230417/tmpl-patch-no-masq-local.yaml
  addons/weave/2.8.1-20230417/tmpl-secret.yaml
  addons/weave/2.8.1-20230417/weave-daemonset-k8s-1.11.yaml
  web/src/installers/versions.js
Labels: automated-pr, weave, type::chore, kurl::type::feature

#4378 Automated Prometheus version update 0.63.0-45.10.1
  addons/prometheus/0.63.0-45.10.1/Manifest
  addons/prometheus/0.63.0-45.10.1/crds/crds.yaml
  addons/prometheus/0.63.0-45.10.1/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.10.1/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.10.1/host-preflight.yaml
  addons/prometheus/0.63.0-45.10.1/install.sh
  addons/prometheus/0.63.0-45.10.1/nodeport-services.yaml
  addons/prometheus/0.63.0-45.10.1/operator/adapter.yaml
  addons/prometheus/0.63.0-45.10.1/operator/default.yaml
  addons/prometheus/0.63.0-45.10.1/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.10.1/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.10.1/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.10.1/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.10.1/operator/ns.yaml
  addons/prometheus/0.63.0-45.10.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.10.1/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4354 Automated MinIO version update RELEASE.2023-04-13T03-08-07Z
  addons/minio/2023-04-13T03-08-07Z/Manifest
  addons/minio/2023-04-13T03-08-07Z/deployment.yaml
  addons/minio/2023-04-13T03-08-07Z/install.sh
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-04-13T03-08-07Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-04-13T03-08-07Z/service.yaml
  addons/minio/2023-04-13T03-08-07Z/tmpl-creds-secret.yaml
  addons/minio/2023-04-13T03-08-07Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-04-13T03-08-07Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-04-13T03-08-07Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-04-13T03-08-07Z/tmpl-kustomization.yaml
  addons/minio/2023-04-13T03-08-07Z/tmpl-namespace.yaml
  addons/minio/2023-04-13T03-08-07Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4388 Automated Weave version update 2.6.5-20230417
  addons/weave/2.6.5-20230417/Manifest
  addons/weave/2.6.5-20230417/host-preflight.yaml
  addons/weave/2.6.5-20230417/install.sh
  addons/weave/2.6.5-20230417/kustomization.yaml
  addons/weave/2.6.5-20230417/patch-daemonset.yaml
  addons/weave/2.6.5-20230417/patch-encrypt.yaml
  addons/weave/2.6.5-20230417/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.6.5-20230417/tmpl-patch-no-masq-local.yaml
  addons/weave/2.6.5-20230417/tmpl-secret.yaml
  addons/weave/2.6.5-20230417/weave-daemonset-k8s-1.11.yaml
  web/src/installers/versions.js
Labels: automated-pr, weave, type::chore, kurl::type::feature

#4379 Automated Rook version update 1.11.4
  addons/rook/1.11.4/Manifest
  addons/rook/1.11.4/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.11.4/cluster/cephfs/filesystem.yaml
  addons/rook/1.11.4/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.11.4/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.11.4/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.11.4/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.11.4/cluster/cluster.yaml
  addons/rook/1.11.4/cluster/kustomization.yaml
  addons/rook/1.11.4/cluster/object-user.yaml
  addons/rook/1.11.4/cluster/object.yaml
  addons/rook/1.11.4/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.11.4/cluster/patches/object-Json6902.yaml
  addons/rook/1.11.4/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.11.4/cluster/patches/tmpl-object.yaml
  addons/rook/1.11.4/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.4/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.4/crds.yaml
  addons/rook/1.11.4/host-preflight.yaml
  addons/rook/1.11.4/install.sh
  addons/rook/1.11.4/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.11.4/monitoring/kustomization.yaml
  addons/rook/1.11.4/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.11.4/operator/cluster-rbac.yaml
  addons/rook/1.11.4/operator/clusterrole.yaml
  addons/rook/1.11.4/operator/clusterrolebinding.yaml
  addons/rook/1.11.4/operator/configmap-rook-config-override.yaml
  addons/rook/1.11.4/operator/configmap.yaml
  addons/rook/1.11.4/operator/deployment.yaml
  addons/rook/1.11.4/operator/kustomization.yaml
  addons/rook/1.11.4/operator/namespace.yaml
  addons/rook/1.11.4/operator/patches/deployment-privileged.yaml
  addons/rook/1.11.4/operator/patches/deployment-tolerations.yaml
  addons/rook/1.11.4/operator/role.yaml
  addons/rook/1.11.4/operator/rolebinding.yaml
  addons/rook/1.11.4/operator/serviceaccount.yaml
  addons/rook/1.11.4/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4396 fix: k8s upgrades to non-step versions unsupported
  scripts/common/common-test.sh
  scripts/common/common.sh
  scripts/common/discover.sh
  scripts/common/kubernetes.sh
  scripts/common/rook-upgrade.sh
  scripts/common/upgrade.sh
  scripts/tasks.sh
  scripts/upgrade.sh
Labels: type::feature

#4255 fix ekco reboot service start
  addons/ekco/0.26.5/install.sh
  addons/ekco/template/base/install.sh
Labels: type::bug, bug::normal

#4402 Upgrade go version from 1.19 to 1.20
  .github/workflows/build-package-prod.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cron-rebuild-packages-prod.yaml
  .github/workflows/cron-rebuild-packages-staging.yaml
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
  .github/workflows/update-openebs.yaml
  CONTRIBUTING.md
  go.mod
Labels: type::chore

#4401 fix: use kurl-install-directory for host os repos
  scripts/common/host-packages.sh
  scripts/tasks.sh
Labels: type::bug, bug::normal

#4404 fix: multi-kubernetes airgap upgrade fixes
  scripts/common/addon.sh
  scripts/common/kubernetes.sh
  scripts/common/upgrade.sh
  scripts/upgrade.sh
Labels: type::feature

#4406 update go version to build
  kurl_util/deploy/Dockerfile
Labels: type::chore

#4408 fix: better messaging when kurl-install-directory does not exist
  scripts/common/common.sh
  testgrid/specs/full.yaml
Labels: type::chore

#4405 Automated Prometheus version update 0.63.0-45.15.0
  addons/prometheus/0.63.0-45.15.0/Manifest
  addons/prometheus/0.63.0-45.15.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.15.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.15.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.15.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.15.0/install.sh
  addons/prometheus/0.63.0-45.15.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.15.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.15.0/operator/default.yaml
  addons/prometheus/0.63.0-45.15.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.15.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.15.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.15.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.15.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.15.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.15.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4380 feat: check flannel udp port prior to migrating
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.2/install.sh
  addons/flannel/0.21.3/install.sh
  addons/flannel/0.21.4/install.sh
  addons/flannel/template/base/install.sh
  pkg/cli/nodes_connectivity.go
  pkg/static/nodes_connectivity/kustomize/tcp-listeners/kustomization.yaml
  pkg/static/nodes_connectivity/kustomize/udp-listeners/kustomization.yaml
  scripts/common/common.sh
  scripts/common/containerd.sh
Labels: type::chore

#4410 Update prompts.sh
  scripts/common/prompts.sh
Labels: type::bug, bug::normal

#4363 Automated Goldpinger version update 3.7.0-6.0.1
  addons/goldpinger/3.7.0-6.0.1/Manifest
  addons/goldpinger/3.7.0-6.0.1/goldpinger.yaml
  addons/goldpinger/3.7.0-6.0.1/install.sh
  addons/goldpinger/3.7.0-6.0.1/kustomization.yaml
  addons/goldpinger/3.7.0-6.0.1/servicemonitor.yaml
  addons/goldpinger/template/testgrid/tests.yaml
  web/src/installers/versions.js
Labels: automated-pr, goldpinger, type::chore, kurl::type::feature

#4412 chore: skip flannel tests with docker on unsupported envs
  addons/flannel/template/testgrid/k8s-ctrd.yaml
Labels: type::chore

#4413 Automated MinIO version update RELEASE.2023-04-20T17-56-55Z
  addons/minio/2023-04-20T17-56-55Z/Manifest
  addons/minio/2023-04-20T17-56-55Z/deployment.yaml
  addons/minio/2023-04-20T17-56-55Z/install.sh
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-04-20T17-56-55Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-04-20T17-56-55Z/service.yaml
  addons/minio/2023-04-20T17-56-55Z/tmpl-creds-secret.yaml
  addons/minio/2023-04-20T17-56-55Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-04-20T17-56-55Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-04-20T17-56-55Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-04-20T17-56-55Z/tmpl-kustomization.yaml
  addons/minio/2023-04-20T17-56-55Z/tmpl-namespace.yaml
  addons/minio/2023-04-20T17-56-55Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4411 Automated Prometheus version update 0.63.0-45.19.0
  addons/prometheus/0.63.0-45.19.0/Manifest
  addons/prometheus/0.63.0-45.19.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.19.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.19.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.19.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.19.0/install.sh
  addons/prometheus/0.63.0-45.19.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.19.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.19.0/operator/default.yaml
  addons/prometheus/0.63.0-45.19.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.19.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.19.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.19.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.19.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.19.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.19.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4420 fix(testgrid): download k8s bundle for storage migration upgrades
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4423 migrate minio to rook even if it is HA
  scripts/common/object_store.sh
Labels: type::bug, bug::regression

#4424 Automated Prometheus version update 0.63.0-45.20.0
  addons/prometheus/0.63.0-45.20.0/Manifest
  addons/prometheus/0.63.0-45.20.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.20.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.20.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.20.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.20.0/install.sh
  addons/prometheus/0.63.0-45.20.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.20.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.20.0/operator/default.yaml
  addons/prometheus/0.63.0-45.20.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.20.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.20.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.20.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.20.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.20.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.20.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4381 chore: standardize logging and example
  cmd/kurl/main.go
  pkg/cli/cli.go
  pkg/cli/longhorn.go
  pkg/cli/longhorn_test.go
  pkg/cli/mock/mock_cli.go
  pkg/cli/netutil.go
Labels: type::chore

#4375 Automated Kubernetes version update 1.27.1 1.26.4 1.25.9 1.24.13 1.23.17 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.24.13/Manifest
  packages/kubernetes/1.24.13/conformance/Manifest
  packages/kubernetes/1.25.9/Manifest
  packages/kubernetes/1.25.9/conformance/Manifest
  packages/kubernetes/1.26.4/Manifest
  packages/kubernetes/1.26.4/conformance/Manifest
  packages/kubernetes/1.27.1/Manifest
  packages/kubernetes/1.27.1/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4400 Automated Containerd version update 1.6.20
  addons/containerd/1.6.10/Manifest
  addons/containerd/1.6.11/Manifest
  addons/containerd/1.6.12/Manifest
  addons/containerd/1.6.13/Manifest
  addons/containerd/1.6.14/Manifest
  addons/containerd/1.6.15/Manifest
  addons/containerd/1.6.16/Manifest
  addons/containerd/1.6.18/Manifest
  addons/containerd/1.6.19/Manifest
  addons/containerd/1.6.20/Manifest
  addons/containerd/1.6.4/Manifest
  addons/containerd/1.6.6/Manifest
  addons/containerd/1.6.7/Manifest
  addons/containerd/1.6.8/Manifest
  addons/containerd/1.6.9/Manifest
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#4426 Enable K8s 1.27.0 and add tests
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/versions.js
Labels: type::chore

#4429 chore: Support --container-runtime kubelet arg removal and kustomize v5 for k8s 1.27
  CONTRIBUTING.md
  addons/flannel/0.20.0/host-preflight.yaml
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.0/template/iface.patch.tmpl.yaml
  addons/flannel/0.20.0/yaml/troubleshoot.yaml
  addons/flannel/0.20.1/host-preflight.yaml
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.1/template/iface.patch.tmpl.yaml
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.0/yaml/kube-flannel.yml
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.1/yaml/kube-flannel.yml
  addons/flannel/0.21.2/install.sh
  addons/flannel/0.21.3/install.sh
  addons/flannel/0.21.4/install.sh
  addons/flannel/template/base/install.sh
  scripts/common/kubernetes.sh
  scripts/common/yaml.sh
  scripts/distro/kubeadm/distro.sh
  scripts/install.sh
  scripts/join.sh
Labels: type::chore

#4432 fix: cli help should go to stderr
  cmd/kurl/main.go
Labels: type::bug, bug::normal

#4434 chore: fix issue with k8s 1.27 (kustomize v5) not supporting multi-doc patches for the Prometheus addon
  scripts/common/yaml.sh
Labels: type::chore

#4433 fix(rook): multi upgrades not possible to version other than ROOK_STEP_VERSIONS
  scripts/common/common-test.sh
  scripts/common/rook-upgrade-test.sh
  scripts/common/rook-upgrade.sh
  scripts/tasks.sh
Labels: type::bug, bug::normal

#4428 Automated Prometheus version update 0.63.0-45.21.0
  addons/prometheus/0.63.0-45.21.0/Manifest
  addons/prometheus/0.63.0-45.21.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.21.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.21.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.21.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.21.0/install.sh
  addons/prometheus/0.63.0-45.21.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.21.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.21.0/operator/default.yaml
  addons/prometheus/0.63.0-45.21.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.21.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.21.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.21.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.21.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.21.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.21.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4435 Automated OpenEBS version update 3.6.0
  addons/openebs/3.6.0/Manifest
  addons/openebs/3.6.0/install.sh
  addons/openebs/3.6.0/spec/crds/crds.yaml
  addons/openebs/3.6.0/spec/crds/kustomization.yaml
  addons/openebs/3.6.0/spec/openebs.tmpl.yaml
  addons/openebs/3.6.0/spec/storage/kustomization.yaml
  addons/openebs/3.6.0/spec/storage/tmpl-localpv-storage-class.yaml
  addons/openebs/3.6.0/spec/storage/tmpl-patch-localpv-default.yaml
  addons/openebs/3.6.0/spec/tmpl-kustomization.yaml
  addons/openebs/3.6.0/spec/tmpl-namespace.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, openebs, kurl::type::feature, auto-merge

#4436 remove NDM from OpenEBS, as it is unused
  addons/openebs/3.6.0/Manifest
  addons/openebs/3.6.0/install.sh
  addons/openebs/3.6.0/spec/openebs.tmpl.yaml
  addons/openebs/template/base/install.sh
  addons/openebs/template/generate.sh
Labels: type::feature

#4437 fix: rook multi upgrades missing 1.4.9 package
  scripts/common/rook-upgrade.sh
Labels: type::bug, bug::normal

#4440 fix(rook): multi upgrades load desired version images
  scripts/common/rook-upgrade.sh
Labels: type::bug, bug::normal

#4441 fix(rook): airgap multi upgrades from versions >= 1.4.x do not prompt to load images on remote nodes
  scripts/common/common-test.sh
  scripts/common/common.sh
Labels: type::bug, bug::normal
