Repository replicatedhq/kURL, pull requests merged in 2023-01, with the labels that each got.

#3901 chore(dependabot): Add node dependabot with monthly interval
  .github/dependabot.yml
Labels: type::chore

#3892 chore: add .golangci config to add common used checks to help us improve the quality
  .golangci.yml
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/config/main.go
  kurl_util/cmd/installermerge/main.go
  kurl_util/cmd/veleroplugin/main.go
  pkg/cli/cluster_free_disk_space.go
  pkg/cli/cluster_images.go
  pkg/cli/format_address.go
  pkg/cli/host_preflight.go
  pkg/cli/host_protectedid.go
  pkg/cli/rook_has_sufficient_blockdevices.go
  pkg/cli/rook_health.go
  pkg/cli/rook_hostpath_to_block.go
  pkg/cli/rook_wait_for_health.go
  pkg/cli/rook_wait_for_version.go
  pkg/cli/sync_object_store.go
  pkg/cli/version.go
  pkg/cluster/nodes.go
  pkg/cluster/nodes_test.go
  pkg/cluster/space/openebs_disk_space_validator_test.go
  pkg/cluster/space/openebs_free_disk_space_getter.go
  pkg/cluster/space/openebs_free_disk_space_getter_test.go
  pkg/preflight/preflight.go
  pkg/rook/health.go
  pkg/rook/health_test.go
  pkg/rook/migrate_test.go
  pkg/rook/toolbox_test.go
Labels: type::chore

#3797 Automated Velero version update 1.9.5
  addons/velero/1.9.5/Manifest
  addons/velero/1.9.5/install.sh
  addons/velero/1.9.5/restic-daemonset-privileged.yaml
  addons/velero/1.9.5/s3-migration-configmap.yaml
  addons/velero/1.9.5/tmpl-change-storageclass.yaml
  addons/velero/1.9.5/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.9.5/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.9.5/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.9.5/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.9.5/tmpl-kustomization.yaml
  addons/velero/1.9.5/tmpl-restic-daemonset-proxy.yaml
  addons/velero/1.9.5/tmpl-s3-migration-bsl.yaml
  addons/velero/1.9.5/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.9.5/tmpl-s3-migration-secret.yaml
  addons/velero/1.9.5/tmpl-velero-deployment-proxy.yaml
  addons/velero/1.9.5/velero-args-json-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3912 Delete update-longhorn.yaml
  .github/workflows/update-longhorn.yaml
Labels: type::chore

#3914 Post a testgrid comment for each commit
  .github/workflows/test-addon.yaml
Labels: type::chore

#3891 feat: add logs for kurl scripts
  scripts/common/prompts.sh
  scripts/install.sh
  scripts/join.sh
  scripts/tasks.sh
  scripts/upgrade.sh
Labels: type::feature

#3913 Automated MinIO version update RELEASE.2023-01-02T09-40-09Z
  addons/minio/2023-01-02T09-40-09Z/Manifest
  addons/minio/2023-01-02T09-40-09Z/deployment.yaml
  addons/minio/2023-01-02T09-40-09Z/install.sh
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-01-02T09-40-09Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-01-02T09-40-09Z/service.yaml
  addons/minio/2023-01-02T09-40-09Z/tmpl-creds-secret.yaml
  addons/minio/2023-01-02T09-40-09Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-01-02T09-40-09Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-01-02T09-40-09Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-01-02T09-40-09Z/tmpl-kustomization.yaml
  addons/minio/2023-01-02T09-40-09Z/tmpl-namespace.yaml
  addons/minio/2023-01-02T09-40-09Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3915 feat: implement functions to migrate and delete longhorn
  scripts/common/longhorn.sh
  scripts/install.sh
Labels: type::feature

#3916 chore: increase prometheus scale down timeout
  scripts/common/longhorn.sh
  scripts/common/rook.sh
Labels: type::chore

#3862 support migrating from weave to flannel
  addons/flannel/0.20.2/install.sh
  addons/flannel/template/base/install.sh
  addons/flannel/template/testgrid/k8s-ctrd.yaml
Labels: type::feature

#3917 chore: remove automated antrea update in favor of flannel
  .github/workflows/update-antrea.yaml
Labels: type::chore

#3918 Wait longer for Rook and Ceph versions to roll out
  addons/rook/1.0.4-14.2.21/install.sh
  addons/rook/1.10.6/install.sh
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  pkg/rook/testfiles/static.go
  pkg/rook/testfiles/waitForRookVersionAllReady.json
  pkg/rook/testfiles/waitForRookVersionNotReady.json
  pkg/rook/testfiles/waitForRookVersionOldVersions.json
  pkg/rook/upgrade.go
  pkg/rook/upgrade_test.go
Labels: type::feature

#3902 chore(rook): update the image ceph/ceph:v14.2.5 to get the latest one built
  addons/rookupgrade/10to14/Manifest
  addons/rookupgrade/10to14/install.sh
  pkg/rook/testfiles/upgradedNode.json
  pkg/rook/testfiles/upgradedNodeLess50Images.json
Labels: type::chore

#3900 fix: create .kube/config for all installs
  scripts/common/common.sh
Labels: type::bug, bug::normal

#3931 fix: failures into rook multi-upgrades from 1.0.4-14.2.21 to 1.4.9
  addons/rookupgrade/10to14/install.sh
  pkg/rook/health.go
Labels: type::bug, bug::normal

#3921 bug: don't attempt to migrate from longhorn on unsupported version
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
Labels: type::bug, bug::normal

#3933 use org-level dockerhub secrets
  .github/workflows/deploy-prod.yaml
  .github/workflows/deploy-staging.yaml
Labels: type::chore

#3818 Automated Rook version update 1.10.8
  addons/rook/1.10.8/Manifest
  addons/rook/1.10.8/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.10.8/cluster/cephfs/filesystem.yaml
  addons/rook/1.10.8/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.10.8/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.10.8/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.10.8/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.10.8/cluster/cluster.yaml
  addons/rook/1.10.8/cluster/kustomization.yaml
  addons/rook/1.10.8/cluster/object-user.yaml
  addons/rook/1.10.8/cluster/object.yaml
  addons/rook/1.10.8/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.10.8/cluster/patches/object-Json6902.yaml
  addons/rook/1.10.8/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.10.8/cluster/patches/tmpl-object.yaml
  addons/rook/1.10.8/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.10.8/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.10.8/crds.yaml
  addons/rook/1.10.8/host-preflight.yaml
  addons/rook/1.10.8/install.sh
  addons/rook/1.10.8/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.10.8/monitoring/kustomization.yaml
  addons/rook/1.10.8/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.10.8/operator/cluster-rbac.yaml
  addons/rook/1.10.8/operator/clusterrole.yaml
  addons/rook/1.10.8/operator/clusterrolebinding.yaml
  addons/rook/1.10.8/operator/configmap-rook-config-override.yaml
  addons/rook/1.10.8/operator/configmap.yaml
  addons/rook/1.10.8/operator/deployment.yaml
  addons/rook/1.10.8/operator/kustomization.yaml
  addons/rook/1.10.8/operator/namespace.yaml
  addons/rook/1.10.8/operator/patches/deployment-privileged.yaml
  addons/rook/1.10.8/operator/patches/deployment-tolerations.yaml
  addons/rook/1.10.8/operator/role.yaml
  addons/rook/1.10.8/operator/rolebinding.yaml
  addons/rook/1.10.8/operator/serviceaccount.yaml
  addons/rook/1.10.8/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#3867 Copy Staging Release for a given Tag when Deploying to Prod
  .github/workflows/deploy-prod.yaml
  bin/list-all-packages-actions-matrix.sh
  bin/list-all-packages.sh
  bin/upload-dist-versioned.sh
  bin/verify-testgrid-run.sh
Labels: type::chore

#3932 Automated Containerd version update 1.6.15
  addons/containerd/1.6.15/Manifest
  addons/containerd/1.6.15/crictl.yaml
  addons/containerd/1.6.15/host-preflight.yaml
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.15/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.15/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#3934 ci/cd(prod): add checkout step to get-staging-release job
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3935 fix: do not allow to remove packages when we use apt-get to fix broken packages
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal

#3937 fix regression to upgrade from 1.0.4
  addons/rookupgrade/10to14/install.sh
Labels: type::bug, bug::regression

#3938 fix(ci/cd): grab staging directory name and not timestamp
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3939 fix(ci/cd): match any length git SHA short ID when looking for staging release folder
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3940 fix(ci/cd): find script which verifies testgrid run
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3941 fix(ci/cd): Fix job name for build-upload-packages strategy matrix
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3942 fix(ci/cd): Don't fail if grep can't find a match
  .github/workflows/deploy-prod.yaml
  bin/verify-testgrid-run.sh
Labels: type::bug, bug::normal

#3943 fix(ci/cd): Use correct GH workflow job matrix syntax
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3944 fix(ci/cd): KURL_UTIL_IMAGE envar required for copy-staging-to-release-prod Job
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3945 chore: remove the bail line when the packages are broken
  scripts/common/host-packages.sh
Labels: type::chore

#3946 fix(ci/cd): set envar for copy-staging-release-to-prod Job
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3947 fix(ci/cd): add dependent job
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3948 feat(ci/cd): Use main for copy-staging-release-to-prod job
  .github/workflows/deploy-prod.yaml
Labels: type::feature

#3950 chore(ci): Temporarily disable checking Testgrid
  bin/verify-testgrid-run.sh
Labels: type::chore

#3952 Revert "fix: create .kube/config for all installs"
  scripts/common/common.sh
Labels: type::bug, bug::normal

#3920 Multi-node weave to flannel
  addons/flannel/0.20.2/install.sh
  addons/flannel/template/base/install.sh
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  scripts/tasks.sh
Labels: type::feature

#3955 Revert "chore(ci): Temporarily disable checking Testgrid"
  bin/verify-testgrid-run.sh
Labels: type::chore

#3956 fix(ci/cd): create release notes after all build jobs complete
  .github/workflows/deploy-prod.yaml
Labels: type::bug, bug::normal

#3957 fix: create .kube/config for all installs
  scripts/common/common.sh
Labels: type::bug, bug::normal

#3954 Automated MinIO version update RELEASE.2023-01-12T02-06-16Z
  addons/minio/2023-01-12T02-06-16Z/Manifest
  addons/minio/2023-01-12T02-06-16Z/deployment.yaml
  addons/minio/2023-01-12T02-06-16Z/install.sh
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-01-12T02-06-16Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-01-12T02-06-16Z/service.yaml
  addons/minio/2023-01-12T02-06-16Z/tmpl-creds-secret.yaml
  addons/minio/2023-01-12T02-06-16Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-01-12T02-06-16Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-01-12T02-06-16Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-01-12T02-06-16Z/tmpl-kustomization.yaml
  addons/minio/2023-01-12T02-06-16Z/tmpl-namespace.yaml
  addons/minio/2023-01-12T02-06-16Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3959 fix: debug print all arguments
  scripts/install.sh
  scripts/join.sh
  scripts/tasks.sh
  scripts/upgrade.sh
Labels: type::chore

#3919 feat: support migrating from longhorn to rook ceph
  addons/rook/1.10.8/install.sh
  addons/rook/template/base/install.sh
  addons/rook/template/testgrid/k8s-docker.yaml
Labels: type::feature

#3936 Allow upgrading Rook past version 1.7.11
  CONTRIBUTING.md
  addons/rook/1.0.4-14.2.21/cluster/tmpl-ceph-storage-class.yaml
  addons/rook/1.0.4/cluster/tmpl-ceph-storage-class.yaml
  addons/rook/1.10.6/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.10.8/install.sh
  addons/rook/1.4.3/cluster/tmpl-ceph-storage-class.yaml
  addons/rook/1.4.9/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/template/base/install.sh
  addons/rookupgrade/10to14/install.sh
  go.mod
  go.sum
  kurl_util/.gitignore
  kurl_util/Makefile
  pkg/cli/commands.go
  pkg/cli/rook_flexvolume_to_csi.go
  pkg/k8sutil/apply.go
  pkg/k8sutil/deployment.go
  pkg/k8sutil/job.go
  pkg/k8sutil/labels.go
  pkg/k8sutil/pod.go
  pkg/k8sutil/pod_test.go
  pkg/k8sutil/storage.go
  pkg/rook/flexvolume.go
  pkg/rook/flexvolume_test.go
  pkg/rook/static/flexmigrator/kustomize/base/flex-migrator.yaml
  pkg/rook/static/flexmigrator/kustomize/base/kustomization.yaml
  pkg/rook/static/flexmigrator/kustomize/overlays/kurl/flex-migrator.patch.yaml
  pkg/rook/static/flexmigrator/kustomize/overlays/kurl/kustomization.yaml
  pkg/rook/static/flexmigrator/static.go
  pkg/rook/static/static.go
  pkg/rook/testfiles/listPVCsByStorageClass.json
  pkg/rook/testfiles/scalePodOwnerDeploy.json
  pkg/rook/testfiles/scalePodOwnerSts.json
  pkg/rook/testfiles/static.go
  scripts/common/rook-upgrade.sh
  scripts/common/rook.sh
  scripts/common/utilbinaries.sh
Labels: type::feature

#3960 add kurl_machine_uuid reporting, remove redundant/unused machine_id reporting
  scripts/common/common.sh
  scripts/common/reporting.sh
Labels: type::bug, bug::normal

#3963 check that flannel images are present on remote nodes in airgap
  addons/flannel/0.20.2/install.sh
  addons/flannel/template/base/install.sh
  scripts/tasks.sh
Labels: type::feature

#3962 Fix rook templating error
  addons/rook/1.0.4-14.2.21/cluster/tmpl-ceph-storage-class.yaml
  addons/rook/1.0.4/cluster/tmpl-ceph-storage-class.yaml
  addons/rook/1.4.3/cluster/tmpl-ceph-storage-class.yaml
Labels: type::bug, bug::normal

#3965 Automated MinIO version update RELEASE.2023-01-18T04-36-38Z
  addons/minio/2023-01-18T04-36-38Z/Manifest
  addons/minio/2023-01-18T04-36-38Z/deployment.yaml
  addons/minio/2023-01-18T04-36-38Z/install.sh
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-01-18T04-36-38Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-01-18T04-36-38Z/service.yaml
  addons/minio/2023-01-18T04-36-38Z/tmpl-creds-secret.yaml
  addons/minio/2023-01-18T04-36-38Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-01-18T04-36-38Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-01-18T04-36-38Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-01-18T04-36-38Z/tmpl-kustomization.yaml
  addons/minio/2023-01-18T04-36-38Z/tmpl-namespace.yaml
  addons/minio/2023-01-18T04-36-38Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3968 Rook: race condition when scaling down prometheuses statefulset
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  pkg/rook/flexvolume.go
  pkg/rook/flexvolume_test.go
Labels: type::bug, bug::normal

#3969 fix(kurl_util): allow bash flags values to contain an equals sign
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/bashmerge/main_test.go
Labels: type::bug, bug::normal

#3967 Add metrics-server 0.6.2
  .github/workflows/update-metrics-server.yaml
  addons/metrics-server/0.6.2/Manifest
  addons/metrics-server/0.6.2/components.yaml
  addons/metrics-server/0.6.2/install.sh
  addons/metrics-server/0.6.2/kubelet-insecure-tls.yaml
  addons/metrics-server/0.6.2/kustomization.yaml
  addons/metrics-server/template/base/Manifest
  addons/metrics-server/template/base/install.sh
  addons/metrics-server/template/base/kubelet-insecure-tls.yaml
  addons/metrics-server/template/base/kustomization.yaml
  addons/metrics-server/template/generate.sh
  addons/metrics-server/template/testgrid/k8s-docker.yaml
  web/src/installers/versions.js
Labels: type::feature

#3974 Automated MinIO version update RELEASE.2023-01-20T02-05-44Z
  addons/minio/2023-01-20T02-05-44Z/Manifest
  addons/minio/2023-01-20T02-05-44Z/deployment.yaml
  addons/minio/2023-01-20T02-05-44Z/install.sh
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-01-20T02-05-44Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-01-20T02-05-44Z/service.yaml
  addons/minio/2023-01-20T02-05-44Z/tmpl-creds-secret.yaml
  addons/minio/2023-01-20T02-05-44Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-01-20T02-05-44Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-01-20T02-05-44Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-01-20T02-05-44Z/tmpl-kustomization.yaml
  addons/minio/2023-01-20T02-05-44Z/tmpl-namespace.yaml
  addons/minio/2023-01-20T02-05-44Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3973 feat: improve the output message to clarify to users kubectl config
  scripts/common/common.sh
Labels: type::chore

#3972 (chore): testgrid: add some tests to check kubectl with kube/config
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#3982 chore: ignore warning about mon usage be higher than 70% to not block…
  pkg/rook/health.go
Labels: type::chore

#3964 Automated Kubernetes version update 1.26.1 1.25.6 1.24.10 1.23.16 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.23.16/Manifest
  packages/kubernetes/1.23.16/conformance/Manifest
  packages/kubernetes/1.24.10/Manifest
  packages/kubernetes/1.24.10/conformance/Manifest
  packages/kubernetes/1.25.6/Manifest
  packages/kubernetes/1.25.6/conformance/Manifest
  packages/kubernetes/1.26.1/Manifest
  packages/kubernetes/1.26.1/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#3984 feat(flannel): log warning flannel udp port 8472 must be open
  addons/flannel/0.20.2/install.sh
  addons/flannel/template/base/install.sh
Labels: type::feature

#3985 Add host preflights for tcp connection on ports 2379 and 6443
  pkg/cli/host_preflight.go
Labels: type::chore, type::improvement

#3989 chore: bump github.com/replicatedhq/troubleshoot v0.55.0
  go.mod
  go.sum
Labels: type::feature

#3971 add serverFlags field to velero add-on
  addons/velero/1.9.5/install.sh
  addons/velero/1.9.5/velero-args-json-patch.yaml
  addons/velero/template/base/install.tmpl.sh
  addons/velero/template/base/velero-args-json-patch.yaml
  go.mod
  go.sum
  kurl_util/cmd/bashmerge/main.go
  kurl_util/cmd/yamltobash/main.go
  scripts/common/utilbinaries.sh
Labels: type::feature, kurl::type::feature

#3986 feat(flannel): preflight UDP port 8472 status
  addons/flannel/0.20.2/host-preflight.yaml
  addons/flannel/template/base/host-preflight.yaml
Labels: type::feature

#3994 also tag k8s.gcr.io images as registry.k8s.io when loading images
  scripts/common/common.sh
  scripts/tasks.sh
Labels: type::bug, bug::regression

#3981 feat: adds "prepare longhorn for migration" command.
  go.mod
  go.sum
  pkg/cli/commands.go
  pkg/cli/longhorn.go
  pkg/cli/longhorn_test.go
Labels: type::feature

#3996 update README cosign command to use double dash flags
  README.md
Labels: type::chore, type::docs

#3998 check for airgap missing images does not account for flannel and possibly other add-ons
  scripts/common/kubernetes.sh
Labels: type::bug, bug::normal

#3997 feat(ci/cd): Batch s3 copies across parallel jobs
  .github/workflows/deploy-prod.yaml
  bin/list-all-packages-actions-matrix.sh
  bin/list-packages-s3.sh
Labels: type::feature

#3987 Automated MinIO version update RELEASE.2023-01-25T00-19-54Z
  addons/minio/2023-01-25T00-19-54Z/Manifest
  addons/minio/2023-01-25T00-19-54Z/deployment.yaml
  addons/minio/2023-01-25T00-19-54Z/install.sh
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-01-25T00-19-54Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-01-25T00-19-54Z/service.yaml
  addons/minio/2023-01-25T00-19-54Z/tmpl-creds-secret.yaml
  addons/minio/2023-01-25T00-19-54Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-01-25T00-19-54Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-01-25T00-19-54Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-01-25T00-19-54Z/tmpl-kustomization.yaml
  addons/minio/2023-01-25T00-19-54Z/tmpl-namespace.yaml
  addons/minio/2023-01-25T00-19-54Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#3995 fix: path to find the manifest filesystem-singlenode.yaml to apply patch from rook version 1.6.11
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
Labels: type::bug, bug::regression

#4001 chore(ci): make flannel the default in testgrid specs
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  addons/contour/template/testgrid/k8s-docker.yaml
  addons/ekco/template/testgrid/k8s-docker.yaml
  addons/minio/template/testgrid/k8s-docker.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
  addons/sonobuoy/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/latest.yaml
Labels: type::feature

#4002 Automated Sonobuoy version update 0.56.15
  addons/sonobuoy/0.56.15/Manifest
  addons/sonobuoy/0.56.15/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#4009 Fix(ci): fix outputs syntax in build-stage-packages-matrix job
  .github/workflows/deploy-prod.yaml
Labels: type::feature

#4011 Automated Containerd version update 1.6.16
  addons/containerd/1.6.16/Manifest
  addons/containerd/1.6.16/crictl.yaml
  addons/containerd/1.6.16/host-preflight.yaml
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.16/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.16/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#4010 Automated Velero version update 1.9.5
  addons/velero/1.9.5/Manifest
  addons/velero/1.9.5/install.sh
Labels: automated-pr, velero, type::chore, kurl::type::feature

#3991 feat(rook): multi package airgap bundles
  Makefile
  pkg/cli/cluster_images.go
  pkg/cluster/nodes.go
  scripts/common/addon-test.sh
  scripts/common/addon.sh
  scripts/common/common-test.sh
  scripts/common/common.sh
  scripts/common/docker-test.sh
  scripts/common/docker.sh
  scripts/common/kubernetes-test.sh
  scripts/common/kubernetes.sh
  scripts/common/prompts.sh
  scripts/common/rook-upgrade-test.sh
  scripts/common/rook-upgrade.sh
  scripts/common/yaml-test.sh
  scripts/common/yaml.sh
Labels: type::feature

#3999 fix check to verify if multiple rook versions are found
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.4.9/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  addons/rookupgrade/10to14/install.sh
Labels: type::bug, bug::normal

#4012 feat: Tag and release specific commit
  Makefile
  README.md
  bin/tag-and-release.sh
Labels: type::feature
