Repository replicatedhq/kURL, pull requests merged in 2023-03, with the labels that each got.

#4164 fix(flannel): incorrect prompt for airgap when migrating from weave
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.2/install.sh
  addons/flannel/template/base/install.sh
Labels: type::bug, bug::normal

#4161 Automated Goldpinger version update 3.7.0-5.6.0
  addons/goldpinger/3.7.0-5.6.0/Manifest
  addons/goldpinger/3.7.0-5.6.0/goldpinger.yaml
  addons/goldpinger/3.7.0-5.6.0/install.sh
  addons/goldpinger/3.7.0-5.6.0/kustomization.yaml
  addons/goldpinger/3.7.0-5.6.0/servicemonitor.yaml
  web/src/installers/versions.js
Labels: automated-pr, goldpinger, type::chore, kurl::type::feature

#4167 fix(flannel): weave to flannel additional primary task has no kubeconfig
  scripts/tasks.sh
Labels: type::bug, bug::normal

#4163 chore: add better info to no block devices found in Rook preflights
  addons/rook/1.10.11/host-preflight.yaml
  addons/rook/1.10.6/host-preflight.yaml
  addons/rook/1.10.8/host-preflight.yaml
  addons/rook/1.4.3/host-preflight.yaml
  addons/rook/1.4.9/host-preflight.yaml
  addons/rook/1.5.10/host-preflight.yaml
  addons/rook/1.5.11/host-preflight.yaml
  addons/rook/1.5.12/host-preflight.yaml
  addons/rook/1.5.9/host-preflight.yaml
  addons/rook/1.6.11/host-preflight.yaml
  addons/rook/1.7.11/host-preflight.yaml
  addons/rook/1.8.10/host-preflight.yaml
  addons/rook/1.9.12/host-preflight.yaml
  addons/rook/template/base/host-preflight.yaml
Labels: type::chore

#4159 improve 'tasks.sh reset' resilience and clean up more things
  scripts/tasks.sh
Labels: type::chore

#4158 fix(ekco): haproxy processes still running after reset script
  Makefile
  addons/ekco/0.26.4/install.sh
  addons/ekco/template/base/install.sh
Labels: type::bug, bug::normal

#4173 fix: host preflight checks results output colored
  go.mod
  pkg/cli/colors.go
  pkg/cli/host_preflight.go
  pkg/cli/host_preflight_test.go
Labels: type::bug, bug::normal

#4174 chore:update golang deps
  go.mod
  go.sum
Labels: dependencies, go, type::chore

#4177 fix colour to output failures for host packages checks
  pkg/cli/colors.go
Labels: type::chore

#4178 chore: increase timeout to check sync-object-store and improve the logs for failures scenarios
  scripts/common/object_store.sh
Labels: type::chore

#4179 fix: ensure that Rook versions from 1.5.9 to 1.10.8 will also check if all Rook pods rollout as it is done for Rook 1.10.11
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.5.10/install.sh
  addons/rook/1.5.11/install.sh
  addons/rook/1.5.12/install.sh
  addons/rook/1.5.9/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
Labels: type::bug, bug::normal

#4180 fix: only allow users to move from Rook to OpenEBS >= 3.3.0
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#4184 Automated MinIO version update RELEASE.2023-03-09T23-16-13Z
  addons/minio/2023-03-09T23-16-13Z/Manifest
  addons/minio/2023-03-09T23-16-13Z/deployment.yaml
  addons/minio/2023-03-09T23-16-13Z/install.sh
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-03-09T23-16-13Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-03-09T23-16-13Z/service.yaml
  addons/minio/2023-03-09T23-16-13Z/tmpl-creds-secret.yaml
  addons/minio/2023-03-09T23-16-13Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-03-09T23-16-13Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-03-09T23-16-13Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-03-09T23-16-13Z/tmpl-kustomization.yaml
  addons/minio/2023-03-09T23-16-13Z/tmpl-namespace.yaml
  addons/minio/2023-03-09T23-16-13Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4182 Automated Flannel version update 0.21.3
  addons/flannel/0.21.3/Manifest
  addons/flannel/0.21.3/host-preflight.yaml
  addons/flannel/0.21.3/install.sh
  addons/flannel/0.21.3/kubeadm.yaml
  addons/flannel/0.21.3/template/iface.patch.tmpl.yaml
  addons/flannel/0.21.3/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.21.3/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.21.3/yaml/kube-flannel.yml
  addons/flannel/0.21.3/yaml/kustomization.yaml
  addons/flannel/0.21.3/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#4176 Automated Prometheus version update 0.63.0-45.7.1
  addons/prometheus/0.63.0-45.7.1/Manifest
  addons/prometheus/0.63.0-45.7.1/crds/crds.yaml
  addons/prometheus/0.63.0-45.7.1/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.7.1/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.7.1/host-preflight.yaml
  addons/prometheus/0.63.0-45.7.1/install.sh
  addons/prometheus/0.63.0-45.7.1/nodeport-services.yaml
  addons/prometheus/0.63.0-45.7.1/operator/adapter.yaml
  addons/prometheus/0.63.0-45.7.1/operator/default.yaml
  addons/prometheus/0.63.0-45.7.1/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.7.1/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.7.1/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.7.1/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.7.1/operator/ns.yaml
  addons/prometheus/0.63.0-45.7.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.7.1/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4185 only wait for minio deployment when we have not moved to ha minio
  addons/minio/template/base/install.sh
  scripts/common/common.sh
Labels: type::bug, bug::regression

#4186 update minio 2023-03-09T23-16-13Z handle ha-minio statefulset
  addons/minio/2023-03-09T23-16-13Z/install.sh
Labels: type::bug, bug::normal

#4181 Fixes issue `failed to find plugin /opt/cni/bin/weave-net`
  scripts/common/kubernetes.sh
Labels: type::bug, bug::normal

#4188 fix: missing error variable substitution log statement
  pkg/rook/migrate.go
Labels: type::bug, bug::normal

#4187 fix: use get_local_node_name instead of hostname
  scripts/common/kubernetes.sh
Labels: type::chore

#4198 Automated MinIO version update RELEASE.2023-03-13T19-46-17Z
  addons/minio/2023-03-13T19-46-17Z/Manifest
  addons/minio/2023-03-13T19-46-17Z/deployment.yaml
  addons/minio/2023-03-13T19-46-17Z/install.sh
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-03-13T19-46-17Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-03-13T19-46-17Z/service.yaml
  addons/minio/2023-03-13T19-46-17Z/tmpl-creds-secret.yaml
  addons/minio/2023-03-13T19-46-17Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-03-13T19-46-17Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-03-13T19-46-17Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-03-13T19-46-17Z/tmpl-kustomization.yaml
  addons/minio/2023-03-13T19-46-17Z/tmpl-namespace.yaml
  addons/minio/2023-03-13T19-46-17Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4201 chore: adds healthy check prior upgrade to openebs
  addons/openebs/3.3.0/install.sh
  addons/openebs/3.4.0/install.sh
  addons/openebs/template/base/install.sh
  scripts/common/object_store.sh
  scripts/common/rook.sh
Labels: type::feature

#4205 fix: just ensure that we have the step so we can have clear logs
  scripts/install.sh
Labels: type::bug, bug::normal

#4204 Fixes issue when migrate from Longhorn and it is not uninstalled by adding a check and better log information to allow users be aware of and the reasons for Longhorn not be able to be uninstalled programmatically.
  scripts/common/longhorn.sh
Labels: type::bug, bug::normal

#4195 fix: Adds check and info to allow users be aware that Rook can not be uninstalled programmatically when the migration from Rook to OpenEBS is done without Minio be installed or when was not possible successfully migrate the Object Store or PVCs
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#4207 Fix invalid upgrade path with Cust1 Upgrade - no HA - Migrate from Rook to OpenEBS is only supported with versions >= 3.3.0
  testgrid/specs/full.yaml
Labels: type::chore

#4169 Automated Velero version update 1.10.2
  addons/velero/1.10.2/Manifest
  addons/velero/1.10.2/install.sh
  addons/velero/1.10.2/node-agent-daemonset-privileged.yaml
  addons/velero/1.10.2/s3-migration-configmap.yaml
  addons/velero/1.10.2/tmpl-change-storageclass.yaml
  addons/velero/1.10.2/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.10.2/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.10.2/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.10.2/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.10.2/tmpl-kustomization.yaml
  addons/velero/1.10.2/tmpl-node-agent-daemonset-proxy.yaml
  addons/velero/1.10.2/tmpl-s3-migration-bsl.yaml
  addons/velero/1.10.2/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.10.2/tmpl-s3-migration-secret.yaml
  addons/velero/1.10.2/tmpl-velero-deployment-proxy.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#4202 Automated Kubernetes version update 1.26.3 1.25.8 1.24.12 1.23.17 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.24.12/Manifest
  packages/kubernetes/1.24.12/conformance/Manifest
  packages/kubernetes/1.25.8/Manifest
  packages/kubernetes/1.25.8/conformance/Manifest
  packages/kubernetes/1.26.3/Manifest
  packages/kubernetes/1.26.3/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4211 when/if we found 2 ceph versions and one of them is 0.0.0-0 we should ignore and does not consider Rook Ceph unhealthy to migrate from it
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#4208 feat: add check to not allow use the installer with previously versions
  scripts/common/kurl.sh
  scripts/common/preflights.sh
Labels: type::feature

#4225 fix: pin k8s amazon linux build to amazonlinux:2
  bundles/k8s-rhel7-force/Dockerfile
Labels: type::chore

#4209 Fixes stuck issues scenarios when is trying to delete Rook and provide better information about the steps performed.
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#4222 fix: does to stop upgrade because was impossible to remove rook
  scripts/common/reporting.sh
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#4224 Adds log to inform what resources are holding the rook-ceph namespace deletion when it fails
  scripts/common/rook.sh
Labels: type::chore

#4223 fix: ensure that Rook Data will be cleanup when rook is removed
  scripts/common/rook.sh
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal

#4226 chore: Use v1.1 instead of v1 to update the report metric when rook delation fails
  scripts/common/rook.sh
Labels: type::chore

#4229 fix regression introduced to check object store
  scripts/common/object_store.sh
Labels: type::bug, bug::regression

#4230 fix: Retry kubeadm init if it fails
  scripts/common/common.sh
  scripts/install.sh
Labels: type::bug, bug::normal

#4228 Automated MinIO version update RELEASE.2023-03-20T20-16-18Z
  addons/minio/2023-03-20T20-16-18Z/Manifest
  addons/minio/2023-03-20T20-16-18Z/deployment.yaml
  addons/minio/2023-03-20T20-16-18Z/install.sh
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-03-20T20-16-18Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-03-20T20-16-18Z/service.yaml
  addons/minio/2023-03-20T20-16-18Z/tmpl-creds-secret.yaml
  addons/minio/2023-03-20T20-16-18Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-03-20T20-16-18Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-03-20T20-16-18Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-03-20T20-16-18Z/tmpl-kustomization.yaml
  addons/minio/2023-03-20T20-16-18Z/tmpl-namespace.yaml
  addons/minio/2023-03-20T20-16-18Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4232 chore: rename duplicated test.
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4233 fix: fix rocky linux 9 vm uri
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#4234 fix: build is missing addon files
  bin/save-manifest-assets.sh
Labels: type::chore

#4237 Adds preflight checks to prevent migrating from Rook to OpenEBS with Registry without MinIO
  scripts/common/preflights.sh
Labels: type::feature

#4241 Fix rhel 9 issues
  bin/save-manifest-assets.sh
  scripts/common/host-packages.sh
  scripts/common/kubernetes.sh
  scripts/common/upgrade.sh
  scripts/install.sh
  scripts/join.sh
  scripts/upgrade.sh
Labels: type::feature

#4244 longhorn uses configmap to set migration from rook
  addons/longhorn/1.1.2/install.sh
  addons/longhorn/1.2.2/install.sh
  addons/longhorn/1.2.4/install.sh
Labels: type::bug, bug::normal

#4240 wait for flannel pods after deleting them, not before
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.2/install.sh
  addons/flannel/0.21.3/install.sh
  addons/flannel/template/base/install.sh
Labels: type::chore

#4249 fix name of the config map to check the migration data
  scripts/common/rook.sh
Labels: type::chore

#4246 feat: better host package verification
  kurl_util/cmd/bashmerge/main.go
  scripts/common/host-packages.sh
  scripts/common/utilbinaries.sh
Labels: type::feature

#4251 fix: testgrid workflows where rook namespace should not be removed because minio is not selected
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4256 fix: addon-manifest-downloader action containertools path
  .github/actions/addon-manifest-downloader/action.yml
Labels: type::bug, bug::regression

#4252 fix: invert flag dismiss-host-packages-preflight
  kurl_util/cmd/bashmerge/main.go
  scripts/common/host-packages.sh
  scripts/common/utilbinaries.sh
Labels: type::feature

#4257 fix: asset path is relative to manifest
  bin/save-manifest-assets.sh
Labels: type::bug, bug::regression

#4262 RHEL 9 testgrid fixes
  testgrid/specs/deploy.yaml
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::feature

#4263 fix: kubectl without cluster access prevents installation
  scripts/common/preflights.sh
Labels: type::bug, bug::regression

#4265 chore: fix testgrid docker specs are not running on rhel 8
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4253 fix unable to remove rook (Rook version 1.4.9 and upper)
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#4220 Always re-apply addons
  kurl_util/cmd/bashmerge/main.go
  scripts/common/addon.sh
  scripts/common/common.sh
  scripts/common/utilbinaries.sh
Labels: type::feature

#4250 fix: Fixes log message upgrading from Rook 1.0.4 to 1.4.9 that caused the Rook Ceph bug
  addons/rookupgrade/10to14/install.sh
  pkg/rook/testfiles/static.go
  pkg/rook/testfiles/waitForRookVersionAllReadyWithEmptyVersion.json
  pkg/rook/upgrade.go
  pkg/rook/upgrade_test.go
Labels: type::bug, bug::normal

#4197 bug: now longer allow migrate the object store twice
  addons/minio/2020-01-25T02-50-51Z/install.sh
  addons/minio/2022-06-11T19-55-32Z/install.sh
  addons/minio/2022-07-06T20-29-49Z/install.sh
  addons/minio/2022-07-17T15-43-14Z/install.sh
  addons/minio/2022-08-02T23-59-16Z/install.sh
  addons/minio/2022-08-22T23-53-06Z/install.sh
  addons/minio/2022-09-01T23-53-36Z/install.sh
  addons/minio/2022-09-07T22-25-02Z/install.sh
  addons/minio/2022-09-17T00-09-45Z/install.sh
  addons/minio/2022-09-25T15-44-53Z/install.sh
  addons/minio/2022-10-02T19-29-29Z/install.sh
  addons/minio/2022-10-05T14-58-27Z/install.sh
  addons/minio/2022-10-08T20-11-00Z/install.sh
  addons/minio/2022-10-15T19-57-03Z/install.sh
  addons/minio/2022-10-20T00-55-09Z/install.sh
  addons/minio/2022-12-12T19-27-27Z/install.sh
  addons/minio/2023-01-02T09-40-09Z/install.sh
  addons/minio/2023-01-06T18-11-18Z/install.sh
  addons/minio/2023-01-12T02-06-16Z/install.sh
  addons/minio/2023-01-18T04-36-38Z/install.sh
  addons/minio/2023-01-20T02-05-44Z/install.sh
  addons/minio/2023-01-25T00-19-54Z/install.sh
  addons/minio/2023-01-31T02-24-19Z/install.sh
  addons/minio/2023-02-09T05-16-53Z/install.sh
  addons/minio/2023-02-10T18-48-39Z/install.sh
  addons/minio/2023-02-17T17-52-43Z/install.sh
  addons/minio/2023-02-22T18-23-45Z/install.sh
  addons/minio/2023-02-27T18-10-45Z/install.sh
  addons/minio/2023-03-09T23-16-13Z/install.sh
  addons/minio/2023-03-13T19-46-17Z/install.sh
  addons/minio/2023-03-20T20-16-18Z/install.sh
  addons/minio/template/base/install.sh
Labels: type::bug, bug::normal

#4266 nit:improve log
  scripts/common/rook.sh
Labels: type::chore

#4267 chore: improve logs when we are removing rook
  scripts/common/rook.sh
Labels: type::chore

#4268 chore: limit storage migration testgrid spec
  .github/workflows/cron-testgrid-daily.yaml
Labels: type::chore

#4254 Automated Weave version update
  addons/weave/2.8.1-20230324/Manifest
  addons/weave/2.8.1-20230324/host-preflight.yaml
  addons/weave/2.8.1-20230324/install.sh
  addons/weave/2.8.1-20230324/kustomization.yaml
  addons/weave/2.8.1-20230324/patch-daemonset.yaml
  addons/weave/2.8.1-20230324/patch-encrypt.yaml
  addons/weave/2.8.1-20230324/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.8.1-20230324/tmpl-patch-no-masq-local.yaml
  addons/weave/2.8.1-20230324/tmpl-secret.yaml
  addons/weave/2.8.1-20230324/weave-daemonset-k8s-1.11.yaml
  web/src/installers/versions.js
Labels: automated-pr, weave, type::chore, kurl::type::feature

#4235 Automated Flannel version update 0.21.4
  addons/flannel/0.21.4/Manifest
  addons/flannel/0.21.4/host-preflight.yaml
  addons/flannel/0.21.4/install.sh
  addons/flannel/0.21.4/kubeadm.yaml
  addons/flannel/0.21.4/template/iface.patch.tmpl.yaml
  addons/flannel/0.21.4/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.21.4/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.21.4/yaml/kube-flannel.yml
  addons/flannel/0.21.4/yaml/kustomization.yaml
  addons/flannel/0.21.4/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#4274 ensure that if the configmap is empty the script does not fail
  scripts/common/rook.sh
Labels: type::chore

#4273 fix migration store check
  addons/minio/2020-01-25T02-50-51Z/install.sh
  addons/minio/2022-06-11T19-55-32Z/install.sh
  addons/minio/2022-07-06T20-29-49Z/install.sh
  addons/minio/2022-07-17T15-43-14Z/install.sh
  addons/minio/2022-08-02T23-59-16Z/install.sh
  addons/minio/2022-08-22T23-53-06Z/install.sh
  addons/minio/2022-09-01T23-53-36Z/install.sh
  addons/minio/2022-09-07T22-25-02Z/install.sh
  addons/minio/2022-09-17T00-09-45Z/install.sh
  addons/minio/2022-09-25T15-44-53Z/install.sh
  addons/minio/2022-10-02T19-29-29Z/install.sh
  addons/minio/2022-10-05T14-58-27Z/install.sh
  addons/minio/2022-10-08T20-11-00Z/install.sh
  addons/minio/2022-10-15T19-57-03Z/install.sh
  addons/minio/2022-10-20T00-55-09Z/install.sh
  addons/minio/2022-12-12T19-27-27Z/install.sh
  addons/minio/2023-01-02T09-40-09Z/install.sh
  addons/minio/2023-01-06T18-11-18Z/install.sh
  addons/minio/2023-01-12T02-06-16Z/install.sh
  addons/minio/2023-01-18T04-36-38Z/install.sh
  addons/minio/2023-01-20T02-05-44Z/install.sh
  addons/minio/2023-01-25T00-19-54Z/install.sh
  addons/minio/2023-01-31T02-24-19Z/install.sh
  addons/minio/2023-02-09T05-16-53Z/install.sh
  addons/minio/2023-02-10T18-48-39Z/install.sh
  addons/minio/2023-02-17T17-52-43Z/install.sh
  addons/minio/2023-02-22T18-23-45Z/install.sh
  addons/minio/2023-02-27T18-10-45Z/install.sh
  addons/minio/2023-03-09T23-16-13Z/install.sh
  addons/minio/2023-03-13T19-46-17Z/install.sh
  addons/minio/2023-03-20T20-16-18Z/install.sh
  addons/minio/template/base/install.sh
Labels: type::chore

#4231 Automated Metrics Server version update 0.6.3
  addons/metrics-server/0.6.3/Manifest
  addons/metrics-server/0.6.3/components.yaml
  addons/metrics-server/0.6.3/install.sh
  addons/metrics-server/0.6.3/kubelet-insecure-tls.yaml
  addons/metrics-server/0.6.3/kustomization.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, metrics-server

#4278 update kurlkinds into kurl
  go.mod
  go.sum
Labels: type::chore

#4280 fix: persist kurl local host repos for rhel 9
  addons/rook/template/testgrid/k8s-docker.yaml
  scripts/common/host-packages.sh
  testgrid/specs/deploy.yaml
Labels: type::feature

#4281 Revert "chore: disable rhel 9 and variants"
  scripts/common/preflights.sh
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#4236 Automated MinIO version update RELEASE.2023-03-24T21-41-23Z
  addons/minio/2023-03-24T21-41-23Z/Manifest
  addons/minio/2023-03-24T21-41-23Z/deployment.yaml
  addons/minio/2023-03-24T21-41-23Z/install.sh
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-03-24T21-41-23Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-03-24T21-41-23Z/service.yaml
  addons/minio/2023-03-24T21-41-23Z/tmpl-creds-secret.yaml
  addons/minio/2023-03-24T21-41-23Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-03-24T21-41-23Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-03-24T21-41-23Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-03-24T21-41-23Z/tmpl-kustomization.yaml
  addons/minio/2023-03-24T21-41-23Z/tmpl-namespace.yaml
  addons/minio/2023-03-24T21-41-23Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4283 Automated Prometheus version update 0.63.0-45.8.0
  addons/prometheus/0.63.0-45.8.0/Manifest
  addons/prometheus/0.63.0-45.8.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.8.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.8.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.8.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.8.0/install.sh
  addons/prometheus/0.63.0-45.8.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.8.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.8.0/operator/default.yaml
  addons/prometheus/0.63.0-45.8.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.8.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.8.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.8.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.8.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.8.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.8.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4282 fix(testgrid): rhel 9 install host packages
  addons/rook/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
Labels: type::chore

#4227 simplify node reboot service logic by deleting all non-system pods
  addons/ekco/0.26.4/reboot/shutdown.sh
  addons/ekco/template/base/reboot/shutdown.sh
Labels: type::bug, bug::normal

#4284 fix: source testhelpers.hs before pre-install script
  addons/rook/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
Labels: type::chore

#4288 update pvmigrate and remove unneeded replaces
  go.mod
  go.sum
Labels: type::chore

#4287 fix: rhel 9 deplist missing noarch packages
  bin/containertools/builddeps.sh
  bundles/k8s-rhel9/containertools/builddeps.sh
Labels: type::feature

#4290 fix: rhel 9 missing kubernetes git dep
  bundles/k8s-rhel9/Dockerfile
  scripts/common/kubernetes.sh
  scripts/install.sh
  scripts/join.sh
  scripts/upgrade.sh
Labels: type::feature

#4293 Adds preflight host check to check K8s API healthz endpoint
  pkg/preflight/assets/host-preflights.yaml
Labels: type::feature

#4296 fix(testgrid): oracle linux 9 vm image
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4298 feat: support for iptables kube proxy mode
  scripts/common/kubernetes.sh
  scripts/common/prompts.sh
  scripts/install.sh
  scripts/kustomize/kubeadm/init-orig/kubeproxy-config-v1alpha1.tmpl.yml
Labels: type::feature

#4300 fix(testgrid): install required deps for rhel-9 airgap
  addons/antrea/template/testgrid/tests.yaml
  addons/cert-manager/template/testgrid/k8s-docker.yaml
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  addons/goldpinger/template/testgrid/tests.yaml
  addons/longhorn/template/testgrid/k8s-ctrd.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
  addons/sonobuoy/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  addons/weave/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#4303 Automated Prometheus version update 0.63.0-45.8.1
  addons/prometheus/0.63.0-45.8.1/Manifest
  addons/prometheus/0.63.0-45.8.1/crds/crds.yaml
  addons/prometheus/0.63.0-45.8.1/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.8.1/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.8.1/host-preflight.yaml
  addons/prometheus/0.63.0-45.8.1/install.sh
  addons/prometheus/0.63.0-45.8.1/nodeport-services.yaml
  addons/prometheus/0.63.0-45.8.1/operator/adapter.yaml
  addons/prometheus/0.63.0-45.8.1/operator/default.yaml
  addons/prometheus/0.63.0-45.8.1/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.8.1/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.8.1/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.8.1/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.8.1/operator/ns.yaml
  addons/prometheus/0.63.0-45.8.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.8.1/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4301 fix: suppress stderr
  scripts/common/preflights.sh
Labels: type::chore

#4299 fix(containerd): do not wait for k8s to report healthy if not yet installed
  addons/containerd/1.6.19/install.sh
  addons/containerd/template/base/install.sh
Labels: type::bug, bug::regression

#4294 adds preflights to check disk space for containerd, rook and openebs
  pkg/preflight/assets/host-preflights.yaml
Labels: type::feature

#4297 adds ability to use Preflight API to perform checks on cluster and began to verify if nodes are healthy
  pkg/cli/cli.go
  pkg/cli/commands.go
  pkg/cli/host_preflight.go
  pkg/cli/host_preflight_test.go
  pkg/cli/mock/mock_cli.go
  pkg/preflight/assets/preflights.yaml
  pkg/preflight/builtin.go
  pkg/preflight/mock/mock_runner.go
  pkg/preflight/preflight.go
  pkg/preflight/runner.go
  scripts/common/preflights.sh
  scripts/install.sh
  scripts/upgrade.sh
Labels: type::feature

#4292 adds preflight host check to verify k8s api and etc certificates
  pkg/preflight/assets/host-preflights.yaml
Labels: type::feature

#4269 fix storage testgrid : Migrate from Rook 1.0.4 to OpenEBS without minio cannot have registry
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4308 Adds check to verify if MinIO Pod(s) is running prior migrate object store
  scripts/common/object_store.sh
Labels: type::feature

#4311 fix: storage test Migrate from Rook 1.0.4 to OpenEBS + Minio (Docker config) into unbuntu 22.04
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4307 Adds a check to verify if OpenEBS and Rook Pod(s) are healthy prior migrate from Rook to OpenEBS.
  addons/openebs/3.3.0/install.sh
  addons/openebs/3.4.0/install.sh
  addons/openebs/3.5.0/install.sh
  addons/openebs/template/base/install.sh
  scripts/common/rook.sh
Labels: type::feature

#4316 fix daily testgrid: is missing minio
  testgrid/specs/full.yaml
Labels: type::chore

#4317 chore: bring missing test command back.
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4314 increase the time to wait nodes be ready and output info
  scripts/common/kubernetes.sh
Labels: type::chore

#4318 migrate from longhorn with registry without object store should be blocked
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#4319 adds checks to ensure that longhorn and openebs are healthy prior migration
  addons/openebs/3.3.0/install.sh
  addons/openebs/3.4.0/install.sh
  addons/openebs/3.5.0/install.sh
  addons/openebs/template/base/install.sh
Labels: type::feature

#4320 fix storage testgrid : apply same rules migrate from longhorn
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4321 adds health checks from longhorn to rook
  addons/rook/1.10.11/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.11.2/install.sh
  addons/rook/template/base/install.sh
Labels: type::feature
