Repository replicatedhq/kURL, pull requests merged in 2023-06, with the labels that each got.

#4580 fix: should be "in cluster" preflights
  scripts/common/preflights.sh
Labels: type::chore

#4581 fix(ci): use os-latest testgrid spec for pr tests
  .github/actions/addon-testgrid-tester/action.yml
Labels: type::chore

#4512 Automated Prometheus version update 0.65.1-46.5.0
  addons/prometheus/0.65.1-46.5.0/Manifest
  addons/prometheus/0.65.1-46.5.0/crds/crds.yaml
  addons/prometheus/0.65.1-46.5.0/crds/kustomization.yaml
  addons/prometheus/0.65.1-46.5.0/crds/preserveUnknown.yaml
  addons/prometheus/0.65.1-46.5.0/host-preflight.yaml
  addons/prometheus/0.65.1-46.5.0/install.sh
  addons/prometheus/0.65.1-46.5.0/nodeport-services.yaml
  addons/prometheus/0.65.1-46.5.0/operator/adapter.yaml
  addons/prometheus/0.65.1-46.5.0/operator/default.yaml
  addons/prometheus/0.65.1-46.5.0/operator/kustomization.yaml
  addons/prometheus/0.65.1-46.5.0/operator/longhorn.yaml
  addons/prometheus/0.65.1-46.5.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.65.1-46.5.0/operator/matchlabel-release.yaml
  addons/prometheus/0.65.1-46.5.0/operator/ns.yaml
  addons/prometheus/0.65.1-46.5.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.65.1-46.5.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4576 Fixes issue to migrate from weave to flannel by ensuring that the operations to remove weave from the filesystem will only be executed when the files are found in the task executed in the nodes and for weave version equals or upper than `0.21.5`
  addons/flannel/0.21.5/install.sh
  addons/flannel/template/base/install.sh
  scripts/tasks.sh
Labels: type::bug, bug::normal

#4582 revert changes from PR 4568
  addons/flannel/0.21.5/install.sh
  addons/flannel/template/base/install.sh
Labels: type::chore

#4584 revert gracePeriod added in PR 4553
  addons/flannel/0.21.5/install.sh
Labels: type::bug, bug::regression

#4585 bug: add https proxy support for add-ons latest versions
  addons/flannel/0.21.5/install.sh
  addons/flannel/template/base/install.sh
  addons/longhorn/1.3.1/install.sh
  addons/longhorn/template/base/install.sh
  addons/velero/1.11.0/install.sh
  addons/velero/1.11.0/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.11.0/tmpl-node-agent-daemonset-proxy.yaml
  addons/velero/1.11.0/tmpl-velero-deployment-proxy.yaml
  addons/velero/template/base/install.tmpl.sh
  addons/velero/template/base/tmpl-kotsadm-restore-config.yaml
  addons/velero/template/base/tmpl-node-agent-daemonset-proxy.yaml
  addons/velero/template/base/tmpl-velero-deployment-proxy.yaml
  scripts/common/addon.sh
  scripts/common/common.sh
  scripts/common/upgrade.sh
  scripts/common/yaml-test.sh
  scripts/install.sh
  scripts/tasks.sh
Labels: type::bug, bug::normal

#4586 missing revert on the template - follow up of 4584
  addons/flannel/template/base/install.sh
Labels: type::chore

#4555 Adds check to ensure weave removal
  addons/flannel/0.21.5/install.sh
  addons/flannel/template/base/install.sh
Labels: type::bug, bug::normal

#4574 Automated EKCO version update 0.27.1
  addons/ekco/0.27.1/Manifest
  addons/ekco/0.27.1/install.sh
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4575 Automated Rook version update 1.11.7
  addons/rook/1.11.7/Manifest
  addons/rook/1.11.7/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.11.7/cluster/cephfs/filesystem.yaml
  addons/rook/1.11.7/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.11.7/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.11.7/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.11.7/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.11.7/cluster/cluster.yaml
  addons/rook/1.11.7/cluster/kustomization.yaml
  addons/rook/1.11.7/cluster/object-user.yaml
  addons/rook/1.11.7/cluster/object.yaml
  addons/rook/1.11.7/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.11.7/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.11.7/cluster/patches/object-Json6902.yaml
  addons/rook/1.11.7/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.11.7/cluster/patches/tmpl-object.yaml
  addons/rook/1.11.7/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.7/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.7/crds.yaml
  addons/rook/1.11.7/host-preflight.yaml
  addons/rook/1.11.7/install.sh
  addons/rook/1.11.7/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.11.7/monitoring/kustomization.yaml
  addons/rook/1.11.7/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.11.7/operator/cluster-rbac.yaml
  addons/rook/1.11.7/operator/clusterrole.yaml
  addons/rook/1.11.7/operator/clusterrolebinding.yaml
  addons/rook/1.11.7/operator/configmap-rook-config-override.yaml
  addons/rook/1.11.7/operator/configmap.yaml
  addons/rook/1.11.7/operator/deployment.yaml
  addons/rook/1.11.7/operator/kustomization.yaml
  addons/rook/1.11.7/operator/namespace.yaml
  addons/rook/1.11.7/operator/patches/deployment-privileged.yaml
  addons/rook/1.11.7/operator/patches/deployment-tolerations.yaml
  addons/rook/1.11.7/operator/role.yaml
  addons/rook/1.11.7/operator/rolebinding.yaml
  addons/rook/1.11.7/operator/serviceaccount.yaml
  addons/rook/1.11.7/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4588 Automated Prometheus version update 0.65.1-46.6.0
  addons/prometheus/0.65.1-46.6.0/Manifest
  addons/prometheus/0.65.1-46.6.0/crds/crds.yaml
  addons/prometheus/0.65.1-46.6.0/crds/kustomization.yaml
  addons/prometheus/0.65.1-46.6.0/crds/preserveUnknown.yaml
  addons/prometheus/0.65.1-46.6.0/host-preflight.yaml
  addons/prometheus/0.65.1-46.6.0/install.sh
  addons/prometheus/0.65.1-46.6.0/nodeport-services.yaml
  addons/prometheus/0.65.1-46.6.0/operator/adapter.yaml
  addons/prometheus/0.65.1-46.6.0/operator/default.yaml
  addons/prometheus/0.65.1-46.6.0/operator/kustomization.yaml
  addons/prometheus/0.65.1-46.6.0/operator/longhorn.yaml
  addons/prometheus/0.65.1-46.6.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.65.1-46.6.0/operator/matchlabel-release.yaml
  addons/prometheus/0.65.1-46.6.0/operator/ns.yaml
  addons/prometheus/0.65.1-46.6.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.65.1-46.6.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4587 Fix Weave to Flanel with Rook on the spec
  addons/flannel/0.21.5/install.sh
  addons/flannel/template/base/install.sh
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  scripts/common/common.sh
Labels: type::bug, bug::normal

#4600 bug: systemd_restart_succeeded should fail if pid is zero
  scripts/common/common.sh
Labels: type::bug, bug::normal

#4596 feat: add EKCO K8s service and tweak EKCO rbac permissions
  addons/ekco/0.27.1/install.sh
  addons/ekco/0.27.1/kustomization.yaml
  addons/ekco/0.27.1/rbac-rook.yaml
  addons/ekco/0.27.1/rbac.yaml
  addons/ekco/0.27.1/service.yaml
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/kustomization.yaml
  addons/ekco/template/base/rbac-rook.yaml
  addons/ekco/template/base/rbac.yaml
  addons/ekco/template/base/service.yaml
Labels: type::feature

#4598 feat(ekco): Generate storage migration API auth token
  addons/ekco/0.27.1/configmap.tmpl.yaml
  addons/ekco/0.27.1/install.sh
  addons/ekco/template/base/configmap.tmpl.yaml
  addons/ekco/template/base/install.sh
Labels: type::feature

#4560 Automated Flannel version update 0.22.0
  addons/flannel/0.22.0/Manifest
  addons/flannel/0.22.0/host-preflight.yaml
  addons/flannel/0.22.0/install.sh
  addons/flannel/0.22.0/kubeadm.yaml
  addons/flannel/0.22.0/template/iface.patch.tmpl.yaml
  addons/flannel/0.22.0/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.22.0/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.22.0/yaml/kube-flannel.yml
  addons/flannel/0.22.0/yaml/kustomization.yaml
  addons/flannel/0.22.0/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#4603 remove test that fails with syslink
  testgrid/specs/full.yaml
Labels: type::chore

#4601 Automated Contour version update 1.25.0
  addons/contour/1.25.0/Manifest
  addons/contour/1.25.0/contour.yaml
Labels: automated-pr, contour, type::chore, kurl::type::feature

#4597 Automated Prometheus version update 0.65.2-46.8.0
  addons/prometheus/0.65.2-46.8.0/Manifest
  addons/prometheus/0.65.2-46.8.0/crds/crds.yaml
  addons/prometheus/0.65.2-46.8.0/crds/kustomization.yaml
  addons/prometheus/0.65.2-46.8.0/crds/preserveUnknown.yaml
  addons/prometheus/0.65.2-46.8.0/host-preflight.yaml
  addons/prometheus/0.65.2-46.8.0/install.sh
  addons/prometheus/0.65.2-46.8.0/nodeport-services.yaml
  addons/prometheus/0.65.2-46.8.0/operator/adapter.yaml
  addons/prometheus/0.65.2-46.8.0/operator/default.yaml
  addons/prometheus/0.65.2-46.8.0/operator/kustomization.yaml
  addons/prometheus/0.65.2-46.8.0/operator/longhorn.yaml
  addons/prometheus/0.65.2-46.8.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.65.2-46.8.0/operator/matchlabel-release.yaml
  addons/prometheus/0.65.2-46.8.0/operator/ns.yaml
  addons/prometheus/0.65.2-46.8.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.65.2-46.8.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4605 Backport fix to migrate from weave to flannel addressed from 0.21.5
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.2/install.sh
  addons/flannel/0.21.3/install.sh
  addons/flannel/0.21.4/install.sh
Labels: type::bug, bug::normal

#4604 add new test to the daily - weave to flannel
  testgrid/specs/full.yaml
Labels: type::chore

#4562 Automated MinIO version update RELEASE.2023-06-09T07-32-12Z
  addons/minio/2023-06-09T07-32-12Z/Manifest
  addons/minio/2023-06-09T07-32-12Z/deployment.yaml
  addons/minio/2023-06-09T07-32-12Z/install.sh
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-06-09T07-32-12Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-06-09T07-32-12Z/service.yaml
  addons/minio/2023-06-09T07-32-12Z/tmpl-creds-secret.yaml
  addons/minio/2023-06-09T07-32-12Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-06-09T07-32-12Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-06-09T07-32-12Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-06-09T07-32-12Z/tmpl-kustomization.yaml
  addons/minio/2023-06-09T07-32-12Z/tmpl-namespace.yaml
  addons/minio/2023-06-09T07-32-12Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4602 bug: make weave_to_flannel idempotent
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.2/install.sh
  addons/flannel/0.21.3/install.sh
  addons/flannel/0.21.4/install.sh
  addons/flannel/0.21.5/install.sh
  addons/flannel/0.22.0/install.sh
  addons/flannel/template/base/install.sh
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#4609 Change ekco svc to node port type
  addons/ekco/0.27.1/configmap.tmpl.yaml
  addons/ekco/0.27.1/install.sh
  addons/ekco/0.27.1/service.tmpl.yaml
  addons/ekco/template/base/configmap.tmpl.yaml
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/service.tmpl.yaml
Labels: type::feature

#4613 bug: port idempotent flannel code to 0.20.1
  addons/flannel/0.20.1/install.sh
Labels: type::bug, bug::normal

#4614 Fix MinIO PVC resize race condition
  addons/minio/2023-06-09T07-32-12Z/install.sh
  addons/minio/template/base/install.sh
  addons/minio/template/testgrid/k8s-docker.yaml
Labels: type::bug, bug::regression

#4610 bug: preserve user defined iptables rules
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.2/install.sh
  addons/flannel/0.21.3/install.sh
  addons/flannel/0.21.4/install.sh
  addons/flannel/0.21.5/install.sh
  addons/flannel/0.22.0/install.sh
  addons/flannel/template/base/install.sh
Labels: type::bug, bug::normal

#4618 Automated Sonobuoy version update 0.56.17
  addons/sonobuoy/0.56.17/Manifest
  addons/sonobuoy/0.56.17/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#4619 Automated Rook version update 1.11.8
  addons/rook/1.11.8/Manifest
  addons/rook/1.11.8/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.11.8/cluster/cephfs/filesystem.yaml
  addons/rook/1.11.8/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.11.8/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.11.8/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.11.8/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.11.8/cluster/cluster.yaml
  addons/rook/1.11.8/cluster/kustomization.yaml
  addons/rook/1.11.8/cluster/object-user.yaml
  addons/rook/1.11.8/cluster/object.yaml
  addons/rook/1.11.8/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.11.8/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.11.8/cluster/patches/object-Json6902.yaml
  addons/rook/1.11.8/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.11.8/cluster/patches/tmpl-object.yaml
  addons/rook/1.11.8/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.8/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.11.8/crds.yaml
  addons/rook/1.11.8/host-preflight.yaml
  addons/rook/1.11.8/install.sh
  addons/rook/1.11.8/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.11.8/monitoring/kustomization.yaml
  addons/rook/1.11.8/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.11.8/operator/cluster-rbac.yaml
  addons/rook/1.11.8/operator/clusterrole.yaml
  addons/rook/1.11.8/operator/clusterrolebinding.yaml
  addons/rook/1.11.8/operator/configmap-rook-config-override.yaml
  addons/rook/1.11.8/operator/configmap.yaml
  addons/rook/1.11.8/operator/deployment.yaml
  addons/rook/1.11.8/operator/kustomization.yaml
  addons/rook/1.11.8/operator/namespace.yaml
  addons/rook/1.11.8/operator/patches/deployment-privileged.yaml
  addons/rook/1.11.8/operator/patches/deployment-tolerations.yaml
  addons/rook/1.11.8/operator/role.yaml
  addons/rook/1.11.8/operator/rolebinding.yaml
  addons/rook/1.11.8/operator/serviceaccount.yaml
  addons/rook/1.11.8/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4622 Automated MinIO version update RELEASE.2023-06-19T19-52-50Z
  addons/minio/2023-06-19T19-52-50Z/Manifest
  addons/minio/2023-06-19T19-52-50Z/deployment.yaml
  addons/minio/2023-06-19T19-52-50Z/install.sh
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-06-19T19-52-50Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-06-19T19-52-50Z/service.yaml
  addons/minio/2023-06-19T19-52-50Z/tmpl-creds-secret.yaml
  addons/minio/2023-06-19T19-52-50Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-06-19T19-52-50Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-06-19T19-52-50Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-06-19T19-52-50Z/tmpl-kustomization.yaml
  addons/minio/2023-06-19T19-52-50Z/tmpl-namespace.yaml
  addons/minio/2023-06-19T19-52-50Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4615 Automated Kubernetes version update 1.27.3 1.26.6 1.25.11 1.24.15 1.23.17 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.24.15/Manifest
  packages/kubernetes/1.24.15/conformance/Manifest
  packages/kubernetes/1.25.11/Manifest
  packages/kubernetes/1.25.11/conformance/Manifest
  packages/kubernetes/1.26.6/Manifest
  packages/kubernetes/1.26.6/conformance/Manifest
  packages/kubernetes/1.27.3/Manifest
  packages/kubernetes/1.27.3/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4599 (Support Case) fix rook check to allow manual fix when is upgrading from only
  addons/openebs/3.3.0/install.sh
  addons/openebs/3.4.0/install.sh
  addons/openebs/3.5.0/install.sh
  addons/openebs/3.6.0/install.sh
  addons/openebs/3.7.0/install.sh
  addons/openebs/template/base/install.sh
  scripts/common/object_store.sh
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#4630 Change preflight check to allow run against RHEL 8.8
  scripts/common/preflights.sh
Labels: type::feature

#4513 (It is just to fix/improve the process to generate auto PRs for weave)fix to allow generate diff templates for 2.6.x
  addons/weave/template/generate.sh
Labels: type::chore

#4637 Upgrade kurl-kinds from v1.3.7 to v1.4.0
  go.mod
  go.sum
Labels: dependencies, go, type::chore

#4632 use patches _correctly_
  addons/flannel/0.22.0/yaml/kustomization.yaml
  addons/flannel/template/base/yaml/kustomization.yaml
  addons/flannel/template/testgrid/k8s-ctrd.yaml
Labels: type::bug, bug::normal

#4639 bug: statically compile velero plugin
  kurl_util/Makefile
Labels: type::bug, bug::normal

#4640 include objectbucket CRDs in rook-ceph removal process
  scripts/common/rook.sh
Labels: type::chore

#4648 Revert "use patches _correctly_"
  addons/flannel/0.22.0/yaml/kustomization.yaml
  addons/flannel/template/base/yaml/kustomization.yaml
Labels: type::bug, bug::regression

#4638 Automated Velero version update 1.11.0
  addons/velero/1.11.0/Manifest
  addons/velero/1.11.0/install.sh
  addons/velero/template/testgrid/k8s-docker.yaml
Labels: automated-pr, velero, type::chore, kurl::type::feature

#4653 test velero with k8s 1.27.x
  addons/velero/template/testgrid/k8s-docker.yaml
Labels: type::chore

#4641 Automated MinIO version update RELEASE.2023-06-23T20-26-00Z
  addons/minio/2023-06-23T20-26-00Z/Manifest
  addons/minio/2023-06-23T20-26-00Z/deployment.yaml
  addons/minio/2023-06-23T20-26-00Z/install.sh
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-06-23T20-26-00Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-06-23T20-26-00Z/service.yaml
  addons/minio/2023-06-23T20-26-00Z/tmpl-creds-secret.yaml
  addons/minio/2023-06-23T20-26-00Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-06-23T20-26-00Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-06-23T20-26-00Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-06-23T20-26-00Z/tmpl-kustomization.yaml
  addons/minio/2023-06-23T20-26-00Z/tmpl-namespace.yaml
  addons/minio/2023-06-23T20-26-00Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4657 bug: remove centos stream from rhel 8 repo list
  bundles/k8s-rhel8/Dockerfile
Labels: type::bug, bug::regression

#4658 feat(ekco): add permission for creating CephObjectStoreUsers resource
  addons/ekco/0.27.1/rbac-rook.yaml
  addons/ekco/template/base/rbac-rook.yaml
Labels: type::feature

#4550 feat(cli): Add new kURL CLI command for orchestrating and starting the OpenEBS to Rook migration
  pkg/cli/cluster_migrate_multinode_storage.go
Labels: type::feature

#4660 bug: remove references to centos stream repos
  addons/containerd/template/Dockerfile.centos8
  bin/save-manifest-assets.sh
  bundles/docker-rhel8/Dockerfile
Labels: type::bug, bug::regression

#4524 feat: Call multi-node storage migration from kURL installer scripts
  kurl_util/cmd/bashmerge/main.go
  scripts/common/common.sh
  scripts/common/rook.sh
  scripts/common/utilbinaries.sh
  scripts/install.sh
  scripts/join.sh
  scripts/tasks.sh
Labels: type::feature

#4664 do not check for rook+openebs when joining nodes
  scripts/common/rook.sh
Labels: type::feature

#4659 Add preflight to validate auto storage scaling
  scripts/common/preflights.sh
  scripts/common/rook.sh
Labels: type::feature
