Repository replicatedhq/kURL, pull requests merged in 2023-07, with the labels that each got.

#4663 Automated MinIO version update RELEASE.2023-06-29T05-12-28Z
  addons/minio/2023-06-29T05-12-28Z/Manifest
  addons/minio/2023-06-29T05-12-28Z/deployment.yaml
  addons/minio/2023-06-29T05-12-28Z/install.sh
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-06-29T05-12-28Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-06-29T05-12-28Z/service.yaml
  addons/minio/2023-06-29T05-12-28Z/tmpl-creds-secret.yaml
  addons/minio/2023-06-29T05-12-28Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-06-29T05-12-28Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-06-29T05-12-28Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-06-29T05-12-28Z/tmpl-kustomization.yaml
  addons/minio/2023-06-29T05-12-28Z/tmpl-namespace.yaml
  addons/minio/2023-06-29T05-12-28Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4672 provide ceph image to ekco
  addons/ekco/0.27.2/configmap.tmpl.yaml
  addons/ekco/template/base/configmap.tmpl.yaml
  addons/rook/1.11.8/install.sh
  addons/rook/template/base/install.sh
Labels: type::feature

#4673 Automated EKCO version update 0.27.2
  addons/ekco/0.27.2/Manifest
  addons/ekco/0.27.2/install.sh
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4674 fix ceph image rollout
  addons/rook/1.11.8/install.sh
  addons/rook/template/base/install.sh
Labels: type::bug, bug::normal

#4675 Automated EKCO version update 0.27.3
  addons/ekco/0.27.2/Manifest
  addons/ekco/0.27.3/Manifest
  addons/ekco/0.27.3/README.md
  addons/ekco/0.27.3/configmap.tmpl.yaml
  addons/ekco/0.27.3/deployment.tmpl.yaml
  addons/ekco/0.27.3/ekco-purge-node.sh
  addons/ekco/0.27.3/install.sh
  addons/ekco/0.27.3/kustomization.yaml
  addons/ekco/0.27.3/namespace.yaml
  addons/ekco/0.27.3/rbac-kotsadm.yaml
  addons/ekco/0.27.3/rbac-minio.yaml
  addons/ekco/0.27.3/rbac-rook.yaml
  addons/ekco/0.27.3/rbac.yaml
  addons/ekco/0.27.3/reboot/ekco-reboot-containerd.service
  addons/ekco/0.27.3/reboot/ekco-reboot.service
  addons/ekco/0.27.3/reboot/shutdown.sh
  addons/ekco/0.27.3/reboot/startup.sh
  addons/ekco/0.27.3/regen-cert-pod.yaml
  addons/ekco/0.27.3/rolebinding-kotsadm.yaml
  addons/ekco/0.27.3/rolebinding-minio.yaml
  addons/ekco/0.27.3/rolebinding-rook.yaml
  addons/ekco/0.27.3/rolebinding.yaml
  addons/ekco/0.27.3/rotate-certs-rbac.yaml
  addons/ekco/0.27.3/service.tmpl.yaml
  addons/ekco/0.27.3/storageclass-scaling.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4676 improve no-docker-on-rhel-9 message
  addons/flannel/0.22.0/install.sh
  addons/flannel/template/base/install.sh
  scripts/common/preflights.sh
Labels: type::feature

#4678 chore(Rook): Redirect stderr and update log message when checking for CephCluster CR
  addons/rook/1.11.7/install.sh
  addons/rook/1.11.8/install.sh
  addons/rook/template/base/install.sh
Labels: type::chore

#4679 chore: add storage-migration-ready-timeout bash flag
  kurl_util/cmd/bashmerge/main.go
  scripts/common/common.sh
  scripts/common/rook.sh
  scripts/common/utilbinaries.sh
Labels: type::chore

#4684 do not require registry IP when joining non-docker nodes
  addons/registry/2.7.1/install.sh
  addons/registry/2.8.1/install.sh
  addons/registry/2.8.2/install.sh
  addons/registry/template/base/install.sh
Labels: type::bug, bug::normal

#4685 Update preflights.sh - RHEL 9.2 Support
  scripts/common/preflights.sh
Labels: type::bug, bug::normal

#4686 Change how bash pattern so rhel and rocky are paired
  scripts/common/preflights.sh
Labels: type::chore

#4687 Automated Kubernetes version update 1.27.3 1.26.6 1.25.11 1.24.15 1.23.17 1.22.17
  packages/kubernetes/1.27.3/Manifest
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4689 feat: Add kurl in-cluster support bundle spec
  scripts/common/kurl.sh
  scripts/install.sh
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::feature

#4693 fix support bundle configmap creation
  scripts/common/kurl.sh
Labels: type::bug, bug::normal

#4692 do not check for rook block devices if minimumNodeCount >= 3
  addons/rook/1.11.4/host-preflight.yaml
  addons/rook/1.11.5/host-preflight.yaml
  addons/rook/1.11.6/host-preflight.yaml
  addons/rook/1.11.7/host-preflight.yaml
  addons/rook/1.11.8/host-preflight.yaml
  addons/rook/template/base/host-preflight.yaml
Labels: type::bug, bug::normal

#4696 report the kurl version as an addon when installing
  scripts/common/reporting.sh
Labels: type::feature

#4694 Automated Kubernetes version update 1.27.4 1.26.7 1.25.12 1.24.16 1.23.17 1.22.17
  hack/testdata/manifest/clean
  packages/kubernetes/1.24.16/Manifest
  packages/kubernetes/1.24.16/conformance/Manifest
  packages/kubernetes/1.25.12/Manifest
  packages/kubernetes/1.25.12/conformance/Manifest
  packages/kubernetes/1.26.7/Manifest
  packages/kubernetes/1.26.7/conformance/Manifest
  packages/kubernetes/1.27.4/Manifest
  packages/kubernetes/1.27.4/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#4695 Automated Containerd version update 1.6.21
  addons/containerd/1.6.10/Manifest
  addons/containerd/1.6.11/Manifest
  addons/containerd/1.6.12/Manifest
  addons/containerd/1.6.13/Manifest
  addons/containerd/1.6.14/Manifest
  addons/containerd/1.6.15/Manifest
  addons/containerd/1.6.16/Manifest
  addons/containerd/1.6.18/Manifest
  addons/containerd/1.6.19/Manifest
  addons/containerd/1.6.20/Manifest
  addons/containerd/1.6.21/Manifest
  addons/containerd/1.6.4/Manifest
  addons/containerd/1.6.6/Manifest
  addons/containerd/1.6.7/Manifest
  addons/containerd/1.6.8/Manifest
  addons/containerd/1.6.9/Manifest
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#4634 Automated Prometheus version update 0.66.0-48.1.2
  addons/prometheus/0.66.0-48.1.2/Manifest
  addons/prometheus/0.66.0-48.1.2/crds/crds.yaml
  addons/prometheus/0.66.0-48.1.2/crds/kustomization.yaml
  addons/prometheus/0.66.0-48.1.2/crds/preserveUnknown.yaml
  addons/prometheus/0.66.0-48.1.2/host-preflight.yaml
  addons/prometheus/0.66.0-48.1.2/install.sh
  addons/prometheus/0.66.0-48.1.2/nodeport-services.yaml
  addons/prometheus/0.66.0-48.1.2/operator/adapter.yaml
  addons/prometheus/0.66.0-48.1.2/operator/default.yaml
  addons/prometheus/0.66.0-48.1.2/operator/kustomization.yaml
  addons/prometheus/0.66.0-48.1.2/operator/longhorn.yaml
  addons/prometheus/0.66.0-48.1.2/operator/matchlabel-instance.yaml
  addons/prometheus/0.66.0-48.1.2/operator/matchlabel-release.yaml
  addons/prometheus/0.66.0-48.1.2/operator/ns.yaml
  addons/prometheus/0.66.0-48.1.2/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.66.0-48.1.2/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4701 Automated EKCO version update 0.28.0
  addons/ekco/0.27.3/Manifest
  addons/ekco/0.28.0/Manifest
  addons/ekco/0.28.0/README.md
  addons/ekco/0.28.0/configmap.tmpl.yaml
  addons/ekco/0.28.0/deployment.tmpl.yaml
  addons/ekco/0.28.0/ekco-purge-node.sh
  addons/ekco/0.28.0/install.sh
  addons/ekco/0.28.0/kustomization.yaml
  addons/ekco/0.28.0/namespace.yaml
  addons/ekco/0.28.0/rbac-kotsadm.yaml
  addons/ekco/0.28.0/rbac-minio.yaml
  addons/ekco/0.28.0/rbac-rook.yaml
  addons/ekco/0.28.0/rbac.yaml
  addons/ekco/0.28.0/reboot/ekco-reboot-containerd.service
  addons/ekco/0.28.0/reboot/ekco-reboot.service
  addons/ekco/0.28.0/reboot/shutdown.sh
  addons/ekco/0.28.0/reboot/startup.sh
  addons/ekco/0.28.0/regen-cert-pod.yaml
  addons/ekco/0.28.0/rolebinding-kotsadm.yaml
  addons/ekco/0.28.0/rolebinding-minio.yaml
  addons/ekco/0.28.0/rolebinding-rook.yaml
  addons/ekco/0.28.0/rolebinding.yaml
  addons/ekco/0.28.0/rotate-certs-rbac.yaml
  addons/ekco/0.28.0/service.tmpl.yaml
  addons/ekco/0.28.0/storageclass-scaling.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4703 chore: Unable to migrate from OpenEBS to Rook msg should not be an error
  scripts/common/rook.sh
Labels: type::chore

#4705 Automated EKCO version update 0.28.1
  addons/ekco/0.28.0/Manifest
  addons/ekco/0.28.1/Manifest
  addons/ekco/0.28.1/README.md
  addons/ekco/0.28.1/configmap.tmpl.yaml
  addons/ekco/0.28.1/deployment.tmpl.yaml
  addons/ekco/0.28.1/ekco-purge-node.sh
  addons/ekco/0.28.1/install.sh
  addons/ekco/0.28.1/kustomization.yaml
  addons/ekco/0.28.1/namespace.yaml
  addons/ekco/0.28.1/rbac-kotsadm.yaml
  addons/ekco/0.28.1/rbac-minio.yaml
  addons/ekco/0.28.1/rbac-rook.yaml
  addons/ekco/0.28.1/rbac.yaml
  addons/ekco/0.28.1/reboot/ekco-reboot-containerd.service
  addons/ekco/0.28.1/reboot/ekco-reboot.service
  addons/ekco/0.28.1/reboot/shutdown.sh
  addons/ekco/0.28.1/reboot/startup.sh
  addons/ekco/0.28.1/regen-cert-pod.yaml
  addons/ekco/0.28.1/rolebinding-kotsadm.yaml
  addons/ekco/0.28.1/rolebinding-minio.yaml
  addons/ekco/0.28.1/rolebinding-rook.yaml
  addons/ekco/0.28.1/rolebinding.yaml
  addons/ekco/0.28.1/rotate-certs-rbac.yaml
  addons/ekco/0.28.1/service.tmpl.yaml
  addons/ekco/0.28.1/storageclass-scaling.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4706 Automated Metrics Server version update 0.6.4
  addons/metrics-server/0.6.4/Manifest
  addons/metrics-server/0.6.4/components.yaml
  addons/metrics-server/0.6.4/install.sh
  addons/metrics-server/0.6.4/kubelet-insecure-tls.yaml
  addons/metrics-server/0.6.4/kustomization.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, metrics-server

#4710 Automated EKCO version update 0.28.2
  addons/ekco/0.28.1/Manifest
  addons/ekco/0.28.2/Manifest
  addons/ekco/0.28.2/README.md
  addons/ekco/0.28.2/configmap.tmpl.yaml
  addons/ekco/0.28.2/deployment.tmpl.yaml
  addons/ekco/0.28.2/ekco-purge-node.sh
  addons/ekco/0.28.2/install.sh
  addons/ekco/0.28.2/kustomization.yaml
  addons/ekco/0.28.2/namespace.yaml
  addons/ekco/0.28.2/rbac-kotsadm.yaml
  addons/ekco/0.28.2/rbac-minio.yaml
  addons/ekco/0.28.2/rbac-rook.yaml
  addons/ekco/0.28.2/rbac.yaml
  addons/ekco/0.28.2/reboot/ekco-reboot-containerd.service
  addons/ekco/0.28.2/reboot/ekco-reboot.service
  addons/ekco/0.28.2/reboot/shutdown.sh
  addons/ekco/0.28.2/reboot/startup.sh
  addons/ekco/0.28.2/regen-cert-pod.yaml
  addons/ekco/0.28.2/rolebinding-kotsadm.yaml
  addons/ekco/0.28.2/rolebinding-minio.yaml
  addons/ekco/0.28.2/rolebinding-rook.yaml
  addons/ekco/0.28.2/rolebinding.yaml
  addons/ekco/0.28.2/rotate-certs-rbac.yaml
  addons/ekco/0.28.2/service.tmpl.yaml
  addons/ekco/0.28.2/storageclass-scaling.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4711 Automated Contour version update 1.25.2
  addons/contour/1.25.2/Manifest
  addons/contour/1.25.2/contour.yaml
  addons/contour/1.25.2/install.sh
  addons/contour/1.25.2/patches/job-image.yaml
  addons/contour/1.25.2/patches/resource-limits.yaml
  addons/contour/1.25.2/tmpl-configmap.yaml
  addons/contour/1.25.2/tmpl-kustomization.yaml
  addons/contour/1.25.2/tmpl-namespace.yaml
  addons/contour/1.25.2/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#4666 feat(testgrid): Auto storage migration tests
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#4697 chore(test): Add Weekly Testgrid Tests for Common kURL Add-on Migrations
  .github/workflows/cron-testgrid-weekly.yaml
  testgrid/specs/customer-common-os.yaml
  testgrid/specs/customer-migration-specs.yaml
Labels: type::chore

#4714 fix(Rook): Fix Rook 1.12.x upgrade and prep for 1.12.x release
  addons/rook/template/base/install.sh
  hack/testdata/manifest/clean
  scripts/Manifest
  scripts/common/yaml.sh
Labels: bug::normal, type::chore

#4718 Automated Rook version update 1.12.0
  addons/rook/1.12.0/Manifest
  addons/rook/1.12.0/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.12.0/cluster/cephfs/filesystem.yaml
  addons/rook/1.12.0/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.12.0/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.12.0/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.12.0/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.12.0/cluster/cluster.yaml
  addons/rook/1.12.0/cluster/kustomization.yaml
  addons/rook/1.12.0/cluster/object-user.yaml
  addons/rook/1.12.0/cluster/object.yaml
  addons/rook/1.12.0/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.12.0/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.12.0/cluster/patches/object-Json6902.yaml
  addons/rook/1.12.0/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.12.0/cluster/patches/tmpl-object.yaml
  addons/rook/1.12.0/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.12.0/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.12.0/crds.yaml
  addons/rook/1.12.0/host-preflight.yaml
  addons/rook/1.12.0/install.sh
  addons/rook/1.12.0/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.12.0/monitoring/kustomization.yaml
  addons/rook/1.12.0/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.12.0/operator/cluster-rbac.yaml
  addons/rook/1.12.0/operator/clusterrole.yaml
  addons/rook/1.12.0/operator/clusterrolebinding.yaml
  addons/rook/1.12.0/operator/configmap-rook-config-override.yaml
  addons/rook/1.12.0/operator/configmap.yaml
  addons/rook/1.12.0/operator/deployment.yaml
  addons/rook/1.12.0/operator/kustomization.yaml
  addons/rook/1.12.0/operator/namespace.yaml
  addons/rook/1.12.0/operator/patches/deployment-privileged.yaml
  addons/rook/1.12.0/operator/patches/deployment-tolerations.yaml
  addons/rook/1.12.0/operator/role.yaml
  addons/rook/1.12.0/operator/rolebinding.yaml
  addons/rook/1.12.0/operator/serviceaccount.yaml
  addons/rook/1.12.0/operator/toolbox.yaml
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature
