Repository replicatedhq/kURL, pull requests merged in 2023-02, with the labels that each got.

#4013 Automated EKCO version update 0.26.3
  addons/ekco/0.26.3/Manifest
  addons/ekco/0.26.3/README.md
  addons/ekco/0.26.3/deployment.yaml
  addons/ekco/0.26.3/ekco-purge-node.sh
  addons/ekco/0.26.3/install.sh
  addons/ekco/0.26.3/kustomization.yaml
  addons/ekco/0.26.3/namespace.yaml
  addons/ekco/0.26.3/rbac-kotsadm.yaml
  addons/ekco/0.26.3/rbac-minio.yaml
  addons/ekco/0.26.3/rbac-rook.yaml
  addons/ekco/0.26.3/rbac.yaml
  addons/ekco/0.26.3/reboot/ekco-reboot-containerd.service
  addons/ekco/0.26.3/reboot/ekco-reboot.service
  addons/ekco/0.26.3/reboot/shutdown.sh
  addons/ekco/0.26.3/reboot/startup.sh
  addons/ekco/0.26.3/regen-cert-pod.yaml
  addons/ekco/0.26.3/rolebinding-kotsadm.yaml
  addons/ekco/0.26.3/rolebinding-minio.yaml
  addons/ekco/0.26.3/rolebinding-rook.yaml
  addons/ekco/0.26.3/rolebinding.yaml
  addons/ekco/0.26.3/rotate-certs-rbac.yaml
  addons/ekco/0.26.3/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4015 fix(rook): only list images in manifest files if they exist
  scripts/common/rook-upgrade.sh
Labels: type::feature

#4017 Automated Contour version update 1.24.0
  addons/contour/1.24.0/Manifest
  addons/contour/1.24.0/contour.yaml
  addons/contour/1.24.0/install.sh
  addons/contour/1.24.0/patches/job-image.yaml
  addons/contour/1.24.0/patches/resource-limits.yaml
  addons/contour/1.24.0/tmpl-configmap.yaml
  addons/contour/1.24.0/tmpl-kustomization.yaml
  addons/contour/1.24.0/tmpl-namespace.yaml
  addons/contour/1.24.0/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#4016 Automated MinIO version update RELEASE.2023-01-31T02-24-19Z
  addons/minio/2023-01-31T02-24-19Z/Manifest
  addons/minio/2023-01-31T02-24-19Z/deployment.yaml
  addons/minio/2023-01-31T02-24-19Z/install.sh
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-01-31T02-24-19Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-01-31T02-24-19Z/service.yaml
  addons/minio/2023-01-31T02-24-19Z/tmpl-creds-secret.yaml
  addons/minio/2023-01-31T02-24-19Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-01-31T02-24-19Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-01-31T02-24-19Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-01-31T02-24-19Z/tmpl-kustomization.yaml
  addons/minio/2023-01-31T02-24-19Z/tmpl-namespace.yaml
  addons/minio/2023-01-31T02-24-19Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4018 feat: scaling down pods before starting the Longhorn to OpenEBS/Rook migration
  addons/rook/template/testgrid/k8s-docker.yaml
  go.mod
  go.sum
  pkg/cli/longhorn.go
  pkg/cli/longhorn_test.go
  scripts/common/longhorn.sh
Labels: type::chore

#4023 feat: flannel is incompatible with docker runtime
  addons/flannel/0.20.2/install.sh
  addons/flannel/template/base/install.sh
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  testgrid/specs/full.yaml
Labels: type::feature

#4014 fix(testgrid): use weave with docker on rhel based distros
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#4026 fix(prometheus): do not hardcode values.yaml, fix adapter prometheus-url
  addons/prometheus/0.62.0-44.3.1/Manifest
  addons/prometheus/0.62.0-44.3.1/crds/crds.yaml
  addons/prometheus/0.62.0-44.3.1/crds/kustomization.yaml
  addons/prometheus/0.62.0-44.3.1/crds/preserveUnknown.yaml
  addons/prometheus/0.62.0-44.3.1/host-preflight.yaml
  addons/prometheus/0.62.0-44.3.1/install.sh
  addons/prometheus/0.62.0-44.3.1/nodeport-services.yaml
  addons/prometheus/0.62.0-44.3.1/operator/adapter.yaml
  addons/prometheus/0.62.0-44.3.1/operator/default.yaml
  addons/prometheus/0.62.0-44.3.1/operator/kustomization.yaml
  addons/prometheus/0.62.0-44.3.1/operator/longhorn.yaml
  addons/prometheus/0.62.0-44.3.1/operator/matchlabel-instance.yaml
  addons/prometheus/0.62.0-44.3.1/operator/matchlabel-release.yaml
  addons/prometheus/0.62.0-44.3.1/operator/ns.yaml
  addons/prometheus/0.62.0-44.3.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.62.0-44.3.1/tmpl-grafana-secret.yaml
  addons/prometheus/template/generate.sh
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/prometheus/template/values.yaml
  web/src/installers/versions.js
Labels: type::bug, bug::regression

#4028 fix(prometheus): backport prometheus-url adapter patch
  addons/prometheus/0.46.0-14.9.0/operator/adapter.yaml
  addons/prometheus/0.46.0/operator/adapter.yaml
  addons/prometheus/0.47.0-15.2.0/operator/adapter.yaml
  addons/prometheus/0.47.0-15.2.1/operator/adapter.yaml
  addons/prometheus/0.47.0-15.3.1/operator/adapter.yaml
  addons/prometheus/0.47.1-16.0.1/operator/adapter.yaml
  addons/prometheus/0.48.0-16.1.2/operator/adapter.yaml
  addons/prometheus/0.48.1-16.10.0/operator/adapter.yaml
  addons/prometheus/0.48.1-16.12.1/operator/adapter.yaml
  addons/prometheus/0.49.0-17.0.0/operator/adapter.yaml
  addons/prometheus/0.49.0-17.1.1/operator/adapter.yaml
  addons/prometheus/0.49.0-17.1.3/operator/adapter.yaml
  addons/prometheus/0.53.1-30.1.0/operator/adapter.yaml
  addons/prometheus/0.56.2-35.2.0/operator/adapter.yaml
  addons/prometheus/0.57.0-36.0.3/operator/adapter.yaml
  addons/prometheus/0.57.0-36.2.0/operator/adapter.yaml
  addons/prometheus/0.58.0-39.11.0/operator/adapter.yaml
  addons/prometheus/0.58.0-39.12.1/operator/adapter.yaml
  addons/prometheus/0.58.0-39.4.0/operator/adapter.yaml
  addons/prometheus/0.58.0-39.9.0/operator/adapter.yaml
  addons/prometheus/0.59.1-40.1.0/operator/adapter.yaml
  addons/prometheus/0.60.1-41.7.3/operator/adapter.yaml
Labels: type::bug, bug::regression

#4003 chore: Add further log information about ceph state for rook upgrades
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  addons/rookupgrade/10to14/install.sh
Labels: type::chore

#4025 Clean up Rook packages after upgrades
  scripts/common/addon.sh
  scripts/common/rook-upgrade.sh
Labels: type::feature

#4032 feat: add utility commands for finding private interface
  pkg/cli/commands.go
  pkg/cli/netutil.go
  pkg/netutils/iface.go
Labels: type::bug, bug::normal

#4033 add a 'upgrade from containerd 1.2' test
  addons/containerd/template/testgrid/k8s-ctrd.yaml
Labels: type::chore

#4034 fix: net utility commands output to stdout
  pkg/cli/netutil.go
Labels: type::bug, bug::normal

#4029 fix(flannel): use alternate interface when private ip is specified
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.20.2/template/iface.patch.tmpl.yaml
  addons/flannel/template/base/install.sh
  addons/flannel/template/base/template/iface.patch.tmpl.yaml
Labels: type::bug, bug::normal

#4022 fixes timetout scenario faced to upgrade rook versions from 1.5.11 to 1.6.12
  addons/rook/1.6.11/install.sh
Labels: type::bug, bug::normal

#4035 chore: increase timeout to check mds from 300 to 1200 in rook upgrades from version 1.7.11
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
Labels: type::chore

#4027 feat: add prompt when preflights warnings are raised
  scripts/common/preflights.sh
Labels: type::feature

#4036 chore: validate rook upgrade after change MDS pods and anti-affinity rules prevent them from co-scheduling on single-node installations from Rook version 1.7.11
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
Labels: type::chore

#4024 Automated Flannel version update 0.21.0
  addons/flannel/0.21.0/Manifest
  addons/flannel/0.21.0/host-preflight.yaml
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.0/kubeadm.yaml
  addons/flannel/0.21.0/template/iface.patch.tmpl.yaml
  addons/flannel/0.21.0/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.21.0/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.21.0/yaml/kube-flannel.yml
  addons/flannel/0.21.0/yaml/kustomization.yaml
  addons/flannel/0.21.0/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#4047 Add restic restore helper image from gcr.io
  addons/velero/1.9.5/Manifest
  addons/velero/template/base/Manifest.tmpl
Labels: type::bug, bug::regression

#4046 chore: clean up cli api
  pkg/cli/cluster_images.go
  pkg/cli/commands.go
  pkg/cli/format_address.go
  pkg/cli/host_preflight.go
  pkg/cli/object_store.go
Labels: type::chore

#4048 chore: fix invocations for renamed cli commands
  addons/rook/1.10.8/install.sh
  addons/rook/template/base/install.sh
  addons/velero/1.9.5/install.sh
  addons/velero/template/base/install.tmpl.sh
  scripts/common/kubernetes.sh
  scripts/common/object_store.sh
  scripts/install.sh
Labels: type::chore

#4038 chore: verifying rook updated prior report success
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
Labels: type::chore

#4049 fix(rook): fix zapping url 404
  addons/rook/1.10.8/install.sh
  addons/rook/template/base/install.sh
Labels: type::bug, bug::normal

#4052 chore: replacing ceph version check in shell by golang command
  addons/rook/1.10.6/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/1.6.11/install.sh
  addons/rook/1.7.11/install.sh
  addons/rook/1.8.10/install.sh
  addons/rook/1.9.12/install.sh
  addons/rook/template/base/install.sh
  addons/rookupgrade/10to14/install.sh
Labels: type::chore

#4053 chore: fix testgrid by updating it to the latest versions to cover rook upgrade workflow
  testgrid/specs/full.yaml
Labels: type::chore

#4056 chore: check flannel health state and network config in upgrades
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/template/base/install.sh
Labels: type::chore

#4059 fix(cis): cis 4.1.1 ensure service file permissions are set to 600 or more restrictive
  scripts/common/kubernetes.sh
Labels: type::bug, bug::normal

#4060 chore: improve debug output around upgrades
  scripts/common/kubernetes.sh
  scripts/common/upgrade.sh
  scripts/upgrade.sh
Labels: type::chore

#4062 Automated Contour version update 1.24.1
  addons/contour/1.24.1/Manifest
  addons/contour/1.24.1/contour.yaml
  addons/contour/1.24.1/install.sh
  addons/contour/1.24.1/patches/job-image.yaml
  addons/contour/1.24.1/patches/resource-limits.yaml
  addons/contour/1.24.1/tmpl-configmap.yaml
  addons/contour/1.24.1/tmpl-kustomization.yaml
  addons/contour/1.24.1/tmpl-namespace.yaml
  addons/contour/1.24.1/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#4061 Automated Flannel version update 0.21.1
  addons/flannel/0.21.1/Manifest
  addons/flannel/0.21.1/host-preflight.yaml
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.1/kubeadm.yaml
  addons/flannel/0.21.1/template/iface.patch.tmpl.yaml
  addons/flannel/0.21.1/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.21.1/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.21.1/yaml/kube-flannel.yml
  addons/flannel/0.21.1/yaml/kustomization.yaml
  addons/flannel/0.21.1/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#4065 fix testgrid daily
  testgrid/specs/full.yaml
Labels: type::chore

#4064 chore: Allow containerd "ctr" command output to stdout
  addons/ekco/0.26.3/install.sh
  addons/ekco/template/base/install.sh
Labels: type::chore

#4045 bug: migrating minio object storage (longhorn to rook migration).
  pkg/cli/longhorn.go
  scripts/common/longhorn.sh
  scripts/common/object_store.sh
Labels: type::bug, bug::normal

#4057 fix: start to delete flannel pods to workaround issue scenario
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/template/base/install.sh
Labels: type::bug, bug::normal

#4068 Automated MinIO version update RELEASE.2023-02-09T05-16-53Z
  addons/minio/2023-02-09T05-16-53Z/Manifest
  addons/minio/2023-02-09T05-16-53Z/deployment.yaml
  addons/minio/2023-02-09T05-16-53Z/install.sh
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-02-09T05-16-53Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-02-09T05-16-53Z/service.yaml
  addons/minio/2023-02-09T05-16-53Z/tmpl-creds-secret.yaml
  addons/minio/2023-02-09T05-16-53Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-02-09T05-16-53Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-02-09T05-16-53Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-02-09T05-16-53Z/tmpl-kustomization.yaml
  addons/minio/2023-02-09T05-16-53Z/tmpl-namespace.yaml
  addons/minio/2023-02-09T05-16-53Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4072 Rook - Increase time to check if PVC is bound for addon testgrid only
  addons/rook/template/testgrid/k8s-docker.yaml
Labels: type::chore

#4075 Revert "Rook - Increase time to check if PVC is bound for addon testgrid only"
  addons/rook/template/testgrid/k8s-docker.yaml
Labels: type::chore

#4076 chore: sleep before post upgrade test.
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
Labels: type::chore

#4078 use actual flannel version in addons
  addons/flannel/0.21.0/Manifest
  addons/flannel/0.21.0/yaml/kube-flannel.yml
  addons/flannel/0.21.1/Manifest
  addons/flannel/0.21.1/yaml/kube-flannel.yml
Labels: type::bug, bug::normal

#4079 Automated MinIO version update RELEASE.2023-02-10T18-48-39Z
  addons/minio/2023-02-10T18-48-39Z/Manifest
  addons/minio/2023-02-10T18-48-39Z/deployment.yaml
  addons/minio/2023-02-10T18-48-39Z/install.sh
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-02-10T18-48-39Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-02-10T18-48-39Z/service.yaml
  addons/minio/2023-02-10T18-48-39Z/tmpl-creds-secret.yaml
  addons/minio/2023-02-10T18-48-39Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-02-10T18-48-39Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-02-10T18-48-39Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-02-10T18-48-39Z/tmpl-kustomization.yaml
  addons/minio/2023-02-10T18-48-39Z/tmpl-namespace.yaml
  addons/minio/2023-02-10T18-48-39Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4084 chore: fix lint-fix makefile target
  Makefile
Labels: type::chore

#4088 chore: add minio and registry to longhorn to rook/openebs testgrids
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
Labels: type::chore, type::tests

#4089 chore: enable push and pull tests for longhorn migration.
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
Labels: type::chore

#4090 simplify reporting code by deduplicating the main report curl
  scripts/common/reporting.sh
Labels: type::chore

#4092 fix disk latency preflight message
  pkg/preflight/assets/host-preflights.yaml
Labels: type::chore

#4069 check available disk space before performing rook upgrade
  scripts/common/rook-upgrade-test.sh
  scripts/common/rook-upgrade.sh
Labels: type::feature

#4091 Update cronjob daily to start at 1:00 instead of 05:00
  .github/workflows/cron-testgrid-daily.yaml
Labels: type::chore

#4074 adds new command to get hostname as it is done by k8s api to use it crosswise
  pkg/cli/commands.go
  pkg/cli/hostname.go
  pkg/host/hostname.go
Labels: type::feature

#4086 chore:update image used to package krew
  bundles/krew/Dockerfile
Labels: type::chore

#4085 chore: update image used to package helm
  bundles/helm/Dockerfile
Labels: type::chore

#4077 fix: kubelet pause image gets garbage collected, does not match containerd sandbox image
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/template/base/install.sh
  scripts/common/kubernetes-test.sh
  scripts/common/kubernetes.sh
  scripts/install.sh
  scripts/join.sh
  scripts/kustomize/kubeadm/init-orig/kubelet-args-pause-image.patch.tmpl.yaml
  scripts/kustomize/kubeadm/join-orig/kubelet-args-pause-image.patch.tmpl.yaml
  scripts/upgrade.sh
Labels: type::bug, bug::normal

#4097 chore:update dependencies and kurlkind
  go.mod
  go.sum
Labels: type::chore

#4098 chore: Update daily cronjob to create test with commit ref
  .github/workflows/cron-testgrid-daily.yaml
Labels: type::chore

#4099 cronjob: Small typo fix replace " with '
  .github/workflows/cron-testgrid-daily.yaml
Labels: type::chore

#4093 Report kurl_cluster_uuid to make it possible to tie runs on different instances in a cluster together
  scripts/common/reporting.sh
  scripts/install.sh
Labels: type::feature

#4100 remove the use of uuidgen, as it is not always present
  scripts/common/common.sh
  scripts/common/reporting.sh
Labels: type::bug, bug::regression

#4106 kurl_cluster_uuid should have been kurl-cluster-uuid
  scripts/common/reporting.sh
Labels: type::bug, bug::regression

#4073 feat: preparing longhorn for migration.
  addons/openebs/3.3.0/install.sh
  addons/openebs/template/base/install.sh
  addons/rook/1.10.8/install.sh
  addons/rook/template/base/install.sh
Labels: type::feature

#4107 kurl_cluster_uuid should have been kurl-cluster-uuid
  scripts/common/reporting.sh
Labels: type::chore

#4108 testgrid: Update reference to have the commit
  .github/workflows/cron-testgrid-daily.yaml
Labels: type::chore

#4109 testgrid : daily cronjob cleanup
  .github/workflows/cron-testgrid-daily.yaml
Labels: type::chore

#4054 Automated Prometheus version update 0.63.0-45.1.0
  addons/prometheus/0.63.0-45.1.0/Manifest
  addons/prometheus/0.63.0-45.1.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.1.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.1.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.1.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.1.0/install.sh
  addons/prometheus/0.63.0-45.1.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.1.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.1.0/operator/default.yaml
  addons/prometheus/0.63.0-45.1.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.1.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.1.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.1.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.1.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.1.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.1.0/tmpl-grafana-secret.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4115 chore(prometheus): testgrid test unsupported on centos-74
  addons/prometheus/template/testgrid/k8s-docker.yaml
Labels: type::chore

#4117 fix(rook): multi-upgrades fail if package already exists on server
  scripts/common/addon.sh
Labels: type::bug, bug::normal

#4123 chore: bump pvmigrate to v0.8.0.
  go.mod
  go.sum
Labels: type::chore

#4121 Automated OpenEBS version update 3.4.0
  addons/openebs/3.4.0/Manifest
  addons/openebs/3.4.0/install.sh
  addons/openebs/3.4.0/spec/crds/crds.yaml
  addons/openebs/3.4.0/spec/crds/kustomization.yaml
  addons/openebs/3.4.0/spec/openebs.tmpl.yaml
  addons/openebs/3.4.0/spec/storage/kustomization.yaml
  addons/openebs/3.4.0/spec/storage/tmpl-localpv-storage-class.yaml
  addons/openebs/3.4.0/spec/storage/tmpl-patch-localpv-default.yaml
  addons/openebs/3.4.0/spec/tmpl-kustomization.yaml
  addons/openebs/3.4.0/spec/tmpl-namespace.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, openebs, kurl::type::feature, auto-merge

#4122 Automated Containerd version update 1.6.18
  addons/containerd/1.6.18/Manifest
  addons/containerd/1.6.18/crictl.yaml
  addons/containerd/1.6.18/host-preflight.yaml
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.18/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.6.18/kubeadm-join-config-v1beta2.yaml
  web/src/installers/versions.js
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#4120 Automated Prometheus version update 0.63.0-45.1.1
  addons/prometheus/0.63.0-45.1.1/Manifest
  addons/prometheus/0.63.0-45.1.1/crds/crds.yaml
  addons/prometheus/0.63.0-45.1.1/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.1.1/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.1.1/host-preflight.yaml
  addons/prometheus/0.63.0-45.1.1/install.sh
  addons/prometheus/0.63.0-45.1.1/nodeport-services.yaml
  addons/prometheus/0.63.0-45.1.1/operator/adapter.yaml
  addons/prometheus/0.63.0-45.1.1/operator/default.yaml
  addons/prometheus/0.63.0-45.1.1/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.1.1/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.1.1/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.1.1/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.1.1/operator/ns.yaml
  addons/prometheus/0.63.0-45.1.1/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.1.1/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4118 fix(docs): fix contributing url to download add-on bundles
  CONTRIBUTING.md
Labels: type::chore

#4126 disable kurl support bundle collection/upload
  scripts/common/reporting.sh
Labels: type::bug, bug::normal

#4127 add ha flag to testgrid
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#4129 Revert "add ha flag to testgrid"
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#4132 Automated MinIO version update RELEASE.2023-02-17T17-52-43Z
  addons/minio/2023-02-17T17-52-43Z/Manifest
  addons/minio/2023-02-17T17-52-43Z/deployment.yaml
  addons/minio/2023-02-17T17-52-43Z/install.sh
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-02-17T17-52-43Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-02-17T17-52-43Z/service.yaml
  addons/minio/2023-02-17T17-52-43Z/tmpl-creds-secret.yaml
  addons/minio/2023-02-17T17-52-43Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-02-17T17-52-43Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-02-17T17-52-43Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-02-17T17-52-43Z/tmpl-kustomization.yaml
  addons/minio/2023-02-17T17-52-43Z/tmpl-namespace.yaml
  addons/minio/2023-02-17T17-52-43Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4135 Update Golang dep for kURL
  go.mod
  go.sum
Labels: dependencies, go, type::chore

#4128 fix(ekco): fix error flags --detach and --rm cannot be specified together
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  addons/ekco/0.11.0/install.sh
  addons/ekco/0.12.0/install.sh
  addons/ekco/0.13.0/install.sh
  addons/ekco/0.14.0/install.sh
  addons/ekco/0.15.0/install.sh
  addons/ekco/0.16.0/install.sh
  addons/ekco/0.17.0/install.sh
  addons/ekco/0.18.0/install.sh
  addons/ekco/0.19.0/install.sh
  addons/ekco/0.19.1/install.sh
  addons/ekco/0.19.2/install.sh
  addons/ekco/0.19.3/install.sh
  addons/ekco/0.19.6/install.sh
  addons/ekco/0.19.9/install.sh
  addons/ekco/0.20.0/install.sh
  addons/ekco/0.21.0/install.sh
  addons/ekco/0.21.1/install.sh
  addons/ekco/0.22.0/install.sh
  addons/ekco/0.23.0/install.sh
  addons/ekco/0.23.1/install.sh
  addons/ekco/0.23.2/install.sh
  addons/ekco/0.24.0/install.sh
  addons/ekco/0.24.1/install.sh
  addons/ekco/0.25.0/install.sh
  addons/ekco/0.26.0/install.sh
  addons/ekco/0.26.1/install.sh
  addons/ekco/0.26.2/install.sh
  addons/ekco/0.26.3/install.sh
  addons/ekco/template/base/install.sh
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::bug, bug::regression

#4136 Automated Prometheus version update 0.63.0-45.2.0
  addons/prometheus/0.63.0-45.2.0/Manifest
  addons/prometheus/0.63.0-45.2.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.2.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.2.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.2.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.2.0/install.sh
  addons/prometheus/0.63.0-45.2.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.2.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.2.0/operator/default.yaml
  addons/prometheus/0.63.0-45.2.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.2.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.2.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.2.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.2.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.2.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.2.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4063 chore(Rook): Check for Rook pods in namespace to be in Running or Completed phase
  scripts/common/common.sh
  scripts/common/rook.sh
Labels: type::chore

#4133 Add addon v0.21.2 for flannel and address a fix to its script to generate the new versions
  addons/flannel/0.21.2/Manifest
  addons/flannel/0.21.2/host-preflight.yaml
  addons/flannel/0.21.2/install.sh
  addons/flannel/0.21.2/kubeadm.yaml
  addons/flannel/0.21.2/template/iface.patch.tmpl.yaml
  addons/flannel/0.21.2/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.21.2/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.21.2/yaml/kube-flannel.yml
  addons/flannel/0.21.2/yaml/kustomization.yaml
  addons/flannel/0.21.2/yaml/troubleshoot.yaml
  addons/flannel/template/generate.sh
  web/src/installers/versions.js
Labels: type::chore

#4138 fix: [testgrid] Rook Upgrade to 1.8.x cannot be tested against centos-7.4
  testgrid/specs/full.yaml
Labels: type::chore

#4144 Automated Weave version update
  addons/weave/2.6.5-20230222/Manifest
  addons/weave/2.6.5-20230222/host-preflight.yaml
  addons/weave/2.6.5-20230222/install.sh
  addons/weave/2.6.5-20230222/kustomization.yaml
  addons/weave/2.6.5-20230222/patch-daemonset.yaml
  addons/weave/2.6.5-20230222/patch-encrypt.yaml
  addons/weave/2.6.5-20230222/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.6.5-20230222/tmpl-patch-no-masq-local.yaml
  addons/weave/2.6.5-20230222/tmpl-secret.yaml
  addons/weave/2.6.5-20230222/weave-daemonset-k8s-1.11.yaml
  web/src/installers/versions.js
Labels: automated-pr, weave, type::chore, kurl::type::feature

#4148 Automated Weave version update
  addons/weave/2.8.1-20230222/Manifest
  addons/weave/2.8.1-20230222/host-preflight.yaml
  addons/weave/2.8.1-20230222/install.sh
  addons/weave/2.8.1-20230222/kustomization.yaml
  addons/weave/2.8.1-20230222/patch-daemonset.yaml
  addons/weave/2.8.1-20230222/patch-encrypt.yaml
  addons/weave/2.8.1-20230222/tmpl-patch-ip-alloc-range.yaml
  addons/weave/2.8.1-20230222/tmpl-patch-no-masq-local.yaml
  addons/weave/2.8.1-20230222/tmpl-secret.yaml
  addons/weave/2.8.1-20230222/weave-daemonset-k8s-1.11.yaml
  web/src/installers/versions.js
Labels: automated-pr, weave, type::chore, kurl::type::feature

#4116 fix: allow kubeadm to choose node name
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/install.sh
  addons/containerd/template/base/install.sh
  addons/ekco/0.26.3/install.sh
  addons/ekco/0.26.3/reboot/shutdown.sh
  addons/ekco/0.26.3/reboot/startup.sh
  addons/ekco/template/base/install.sh
  addons/ekco/template/base/reboot/shutdown.sh
  addons/ekco/template/base/reboot/startup.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.2/install.sh
  addons/flannel/template/base/install.sh
  scripts/common/common.sh
  scripts/common/docker.sh
  scripts/common/kubernetes.sh
  scripts/common/rook-upgrade.sh
  scripts/install.sh
  scripts/join.sh
  scripts/kustomize/kubeadm/init-orig/kubeadm-init-config-v1beta2.yml
  scripts/kustomize/kubeadm/init-orig/kubeadm-init-hostname.patch.tmpl.yaml
  scripts/kustomize/kubeadm/join-orig/kubeadm-join-hostname.patch.tmpl.yaml
  scripts/tasks.sh
  scripts/upgrade.sh
  testgrid/specs/full.yaml
Labels: type::bug, bug::normal

#4150 Automated MinIO version update RELEASE.2023-02-22T18-23-45Z
  addons/minio/2023-02-22T18-23-45Z/Manifest
  addons/minio/2023-02-22T18-23-45Z/deployment.yaml
  addons/minio/2023-02-22T18-23-45Z/install.sh
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-02-22T18-23-45Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-02-22T18-23-45Z/service.yaml
  addons/minio/2023-02-22T18-23-45Z/tmpl-creds-secret.yaml
  addons/minio/2023-02-22T18-23-45Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-02-22T18-23-45Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-02-22T18-23-45Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-02-22T18-23-45Z/tmpl-kustomization.yaml
  addons/minio/2023-02-22T18-23-45Z/tmpl-namespace.yaml
  addons/minio/2023-02-22T18-23-45Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4149 Automated EKCO version update 0.26.4
  addons/ekco/0.26.4/Manifest
  addons/ekco/0.26.4/README.md
  addons/ekco/0.26.4/deployment.yaml
  addons/ekco/0.26.4/ekco-purge-node.sh
  addons/ekco/0.26.4/install.sh
  addons/ekco/0.26.4/kustomization.yaml
  addons/ekco/0.26.4/namespace.yaml
  addons/ekco/0.26.4/rbac-kotsadm.yaml
  addons/ekco/0.26.4/rbac-minio.yaml
  addons/ekco/0.26.4/rbac-rook.yaml
  addons/ekco/0.26.4/rbac.yaml
  addons/ekco/0.26.4/reboot/ekco-reboot-containerd.service
  addons/ekco/0.26.4/reboot/ekco-reboot.service
  addons/ekco/0.26.4/reboot/shutdown.sh
  addons/ekco/0.26.4/reboot/startup.sh
  addons/ekco/0.26.4/regen-cert-pod.yaml
  addons/ekco/0.26.4/rolebinding-kotsadm.yaml
  addons/ekco/0.26.4/rolebinding-minio.yaml
  addons/ekco/0.26.4/rolebinding-rook.yaml
  addons/ekco/0.26.4/rolebinding.yaml
  addons/ekco/0.26.4/rotate-certs-rbac.yaml
  addons/ekco/0.26.4/tmpl-configmap.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, ekco, kurl::type::feature

#4145 Automated Velero version update 1.10.1
  addons/velero/1.10.1/Manifest
  addons/velero/1.10.1/tmpl-s3-migration-deployment-patch.yaml
Labels: automated-pr, velero, type::chore, kurl::type::feature

#4142 chore: add test to verify rook migration OpenEBS in the daily checks
  testgrid/specs/full.yaml
Labels: type::chore

#4140 chore: add new tests for addons to ensure that is possible to migrate from rook 1.10x
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::chore

#4139 chore: add check to ensure that rook-ceph namespace is removed after migration from it
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
Labels: type::chore

#4151 Automated Prometheus version update 0.63.0-45.3.0
  addons/prometheus/0.63.0-45.3.0/Manifest
  addons/prometheus/0.63.0-45.3.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.3.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.3.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.3.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.3.0/install.sh
  addons/prometheus/0.63.0-45.3.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.3.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.3.0/operator/default.yaml
  addons/prometheus/0.63.0-45.3.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.3.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.3.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.3.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.3.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.3.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.3.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4152 Automated Prometheus version update 0.63.0-45.4.0
  addons/prometheus/0.63.0-45.4.0/Manifest
  addons/prometheus/0.63.0-45.4.0/crds/crds.yaml
  addons/prometheus/0.63.0-45.4.0/crds/kustomization.yaml
  addons/prometheus/0.63.0-45.4.0/crds/preserveUnknown.yaml
  addons/prometheus/0.63.0-45.4.0/host-preflight.yaml
  addons/prometheus/0.63.0-45.4.0/install.sh
  addons/prometheus/0.63.0-45.4.0/nodeport-services.yaml
  addons/prometheus/0.63.0-45.4.0/operator/adapter.yaml
  addons/prometheus/0.63.0-45.4.0/operator/default.yaml
  addons/prometheus/0.63.0-45.4.0/operator/kustomization.yaml
  addons/prometheus/0.63.0-45.4.0/operator/longhorn.yaml
  addons/prometheus/0.63.0-45.4.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.63.0-45.4.0/operator/matchlabel-release.yaml
  addons/prometheus/0.63.0-45.4.0/operator/ns.yaml
  addons/prometheus/0.63.0-45.4.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.63.0-45.4.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#4157 Automated MinIO version update RELEASE.2023-02-27T18-10-45Z
  addons/minio/2023-02-27T18-10-45Z/Manifest
  addons/minio/2023-02-27T18-10-45Z/deployment.yaml
  addons/minio/2023-02-27T18-10-45Z/install.sh
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-02-27T18-10-45Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-02-27T18-10-45Z/service.yaml
  addons/minio/2023-02-27T18-10-45Z/tmpl-creds-secret.yaml
  addons/minio/2023-02-27T18-10-45Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-02-27T18-10-45Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-02-27T18-10-45Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-02-27T18-10-45Z/tmpl-kustomization.yaml
  addons/minio/2023-02-27T18-10-45Z/tmpl-namespace.yaml
  addons/minio/2023-02-27T18-10-45Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature
