Repository replicatedhq/kURL, pull requests merged in 2023-10, with the labels that each got.

#4852 Automated Registry version update 2.8.3
  addons/registry/2.8.3/Manifest
  addons/registry/2.8.3/README.md
  addons/registry/2.8.3/deployment-pvc.yaml
  addons/registry/2.8.3/install.sh
  addons/registry/2.8.3/kustomization.yaml
  addons/registry/2.8.3/patch-deployment-migrate-s3.yaml
  addons/registry/2.8.3/patch-deployment-velero.yaml
  addons/registry/2.8.3/service.yaml
  addons/registry/2.8.3/tmpl-cluster-ip-patch.yaml
  addons/registry/2.8.3/tmpl-configmap-migrate-s3.yaml
  addons/registry/2.8.3/tmpl-configmap-velero.yaml
  addons/registry/2.8.3/tmpl-deployment-objectstore.yaml
  addons/registry/2.8.3/tmpl-node-port-patch.yaml
  addons/registry/2.8.3/tmpl-persistentvolumeclaim.yaml
  addons/registry/2.8.3/tmpl-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, registry

#4857 provide commands to load assets on remote nodes for testgrid
  scripts/common/common.sh
Labels: type::chore

#4866 print the phase+name of unhealthy pods in the kurl namespace
  scripts/common/preflights.sh
Labels: type::chore

#4859 Automated Rook version update 1.12.5
  addons/rook/1.12.5/Manifest
  addons/rook/1.12.5/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.12.5/cluster/cephfs/filesystem.yaml
  addons/rook/1.12.5/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.12.5/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.12.5/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.12.5/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.12.5/cluster/cluster.yaml
  addons/rook/1.12.5/cluster/kustomization.yaml
  addons/rook/1.12.5/cluster/object-user.yaml
  addons/rook/1.12.5/cluster/object.yaml
  addons/rook/1.12.5/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.12.5/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.12.5/cluster/patches/object-Json6902.yaml
  addons/rook/1.12.5/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.12.5/cluster/patches/tmpl-object.yaml
  addons/rook/1.12.5/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.12.5/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.12.5/crds.yaml
  addons/rook/1.12.5/host-preflight.yaml
  addons/rook/1.12.5/install.sh
  addons/rook/1.12.5/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.12.5/monitoring/kustomization.yaml
  addons/rook/1.12.5/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.12.5/operator/cluster-rbac.yaml
  addons/rook/1.12.5/operator/clusterrole.yaml
  addons/rook/1.12.5/operator/clusterrolebinding.yaml
  addons/rook/1.12.5/operator/configmap-rook-config-override.yaml
  addons/rook/1.12.5/operator/configmap.yaml
  addons/rook/1.12.5/operator/deployment.yaml
  addons/rook/1.12.5/operator/kustomization.yaml
  addons/rook/1.12.5/operator/namespace.yaml
  addons/rook/1.12.5/operator/patches/deployment-privileged.yaml
  addons/rook/1.12.5/operator/patches/deployment-tolerations.yaml
  addons/rook/1.12.5/operator/role.yaml
  addons/rook/1.12.5/operator/rolebinding.yaml
  addons/rook/1.12.5/operator/securityContextConstraints.yaml
  addons/rook/1.12.5/operator/serviceaccount.yaml
  addons/rook/1.12.5/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#4867 limit the number of PRs fetched when generating changelogs
  .github/workflows/deploy-prod.yaml
Labels: type::chore

#4868 Don't scale down Longhorn pods before pvmigrate runs
  pkg/cli/longhorn.go
Labels: type::bug, bug::normal

#4873 install fio before running preflights
  scripts/install.sh
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#4874 allow pvmigrate to scale down prometheus pods for openebs volume placement
  pkg/cli/longhorn.go
  scripts/common/longhorn.sh
  scripts/common/rook.sh
Labels: type::bug, bug::normal

#4875 restore old post-pvmigrate-failure longhorn scaling behavior
  pkg/cli/longhorn.go
  scripts/common/longhorn.sh
Labels: type::chore

#4878 update troubleshoot and use fileNotCollected
  go.mod
  go.sum
  pkg/preflight/assets/host-preflights.yaml
Labels: type::bug, bug::regression

#4840 Automated Velero version update 1.12.0
  addons/velero/1.12.0/Manifest
  addons/velero/1.12.0/install.sh
  addons/velero/1.12.0/node-agent-daemonset-privileged.yaml
  addons/velero/1.12.0/s3-migration-configmap.yaml
  addons/velero/1.12.0/tmpl-change-storageclass.yaml
  addons/velero/1.12.0/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.12.0/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.12.0/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.12.0/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.12.0/tmpl-kustomization.yaml
  addons/velero/1.12.0/tmpl-node-agent-daemonset-proxy.yaml
  addons/velero/1.12.0/tmpl-s3-migration-bsl.yaml
  addons/velero/1.12.0/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.12.0/tmpl-s3-migration-secret.yaml
  addons/velero/1.12.0/tmpl-velero-deployment-proxy.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#4885 Automated Contour version update 1.26.0
  addons/contour/1.26.0/Manifest
  addons/contour/1.26.0/contour.yaml
Labels: automated-pr, contour, type::chore, kurl::type::feature

#4860 Automated MinIO version update RELEASE.2023-10-07T15-07-38Z
  addons/minio/2023-10-07T15-07-38Z/Manifest
  addons/minio/2023-10-07T15-07-38Z/deployment.yaml
  addons/minio/2023-10-07T15-07-38Z/install.sh
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-10-07T15-07-38Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-10-07T15-07-38Z/service.yaml
  addons/minio/2023-10-07T15-07-38Z/tmpl-creds-secret.yaml
  addons/minio/2023-10-07T15-07-38Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-10-07T15-07-38Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-10-07T15-07-38Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-10-07T15-07-38Z/tmpl-kustomization.yaml
  addons/minio/2023-10-07T15-07-38Z/tmpl-namespace.yaml
  addons/minio/2023-10-07T15-07-38Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4887 fix post-completion/failure longhorn prometheus scale code
  pkg/cli/longhorn.go
  scripts/common/longhorn.sh
  testgrid/specs/storage-migration.yaml
Labels: type::bug, bug::regression

#4888 run fewer tests more often
  .github/workflows/cron-testgrid-daily.yaml
  .github/workflows/cron-testgrid-weekly.yaml
  testgrid/specs/os-customer-common.yaml
Labels: type::chore

#4896 Automated Contour version update 1.26.1
  addons/contour/1.26.1/Manifest
  addons/contour/1.26.1/contour.yaml
  addons/contour/1.26.1/install.sh
  addons/contour/1.26.1/patches/job-image.yaml
  addons/contour/1.26.1/patches/resource-limits.yaml
  addons/contour/1.26.1/tmpl-configmap.yaml
  addons/contour/1.26.1/tmpl-kustomization.yaml
  addons/contour/1.26.1/tmpl-namespace.yaml
  addons/contour/1.26.1/tmpl-service-patch.yaml
  web/src/installers/versions.js
Labels: automated-pr, contour, type::chore, kurl::type::feature

#4897 Automated Sonobuoy version update 0.57.0
  addons/sonobuoy/0.57.0/Manifest
  addons/sonobuoy/0.57.0/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#4889 Automated MinIO version update RELEASE.2023-10-16T04-13-43Z
  addons/minio/2023-10-16T04-13-43Z/Manifest
  addons/minio/2023-10-16T04-13-43Z/deployment.yaml
  addons/minio/2023-10-16T04-13-43Z/install.sh
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/hostpath/service.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/minio-pvc.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2023-10-16T04-13-43Z/migrate-fs/pvc/service.yaml
  addons/minio/2023-10-16T04-13-43Z/service.yaml
  addons/minio/2023-10-16T04-13-43Z/tmpl-creds-secret.yaml
  addons/minio/2023-10-16T04-13-43Z/tmpl-deployment-hostpath.yaml
  addons/minio/2023-10-16T04-13-43Z/tmpl-deployment-pvc.yaml
  addons/minio/2023-10-16T04-13-43Z/tmpl-ha-statefulset.yaml
  addons/minio/2023-10-16T04-13-43Z/tmpl-kustomization.yaml
  addons/minio/2023-10-16T04-13-43Z/tmpl-namespace.yaml
  addons/minio/2023-10-16T04-13-43Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#4908 make the reset script more resilient
  scripts/tasks.sh
Labels: type::bug, bug::normal

#4912 make failing to install fio not a fatal error
  scripts/common/common.sh
Labels: type::bug, bug::regression

#4911 if the rook dir existed when resetting, warn about rook disks
  scripts/tasks.sh
Labels: type::chore

#4909 Automated Velero version update 1.12.1
  addons/velero/1.12.1/Manifest
  addons/velero/1.12.1/install.sh
  addons/velero/1.12.1/node-agent-daemonset-privileged.yaml
  addons/velero/1.12.1/s3-migration-configmap.yaml
  addons/velero/1.12.1/tmpl-change-storageclass.yaml
  addons/velero/1.12.1/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.12.1/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.12.1/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.12.1/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.12.1/tmpl-kustomization.yaml
  addons/velero/1.12.1/tmpl-node-agent-daemonset-proxy.yaml
  addons/velero/1.12.1/tmpl-s3-migration-bsl.yaml
  addons/velero/1.12.1/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.12.1/tmpl-s3-migration-secret.yaml
  addons/velero/1.12.1/tmpl-velero-deployment-proxy.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#4914 chore: inform users that 15% of the root disk is reserved
  pkg/cluster/space/openebs_disk_space_validator.go
Labels: type::chore
