Repository replicatedhq/kURL, pull requests merged in 2024-10, with the labels that each got.

#5415 Automated Kubernetes version update 1.31.1 1.30.5 1.29.9 1.28.14 1.27.16
  packages/kubernetes/1.27.16/Manifest
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#5430 Remove npm from dependabot as there is no longer js code in this repo
  .github/dependabot.yml
Labels: type::chore

#5431 Revert "Remove npm from dependabot as there is no longer js code in this repo"
  .github/dependabot.yml
Labels: type::chore

#5436 Revert "chore(deps): bump github.com/vishvananda/netlink from 1.2.1-b…
  go.mod
  go.sum
Labels: type::bug, bug::normal

#5439 Automated Kubernetes version update 1.31.2 1.30.6 1.29.10 1.28.15 1.27.16
  hack/testdata/manifest/clean
  packages/kubernetes/1.28.15/Manifest
  packages/kubernetes/1.28.15/conformance/Manifest
  packages/kubernetes/1.29.10/Manifest
  packages/kubernetes/1.29.10/conformance/Manifest
  packages/kubernetes/1.30.6/Manifest
  packages/kubernetes/1.30.6/conformance/Manifest
  packages/kubernetes/1.31.2/Manifest
  packages/kubernetes/1.31.2/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#5440 chore(deps): bump github.com/replicatedhq/troubleshoot
  go.mod
  go.sum
Labels: dependencies, type::chore

#5442 fix(velero): fails to install nfs-common on ubuntu 22.04 due to deps
  scripts/common/host-packages.sh
Labels: type::bug, bug::normal

#5443 chore(deps): bump sigs.k8s.io/kustomize/api and sigs.k8s.io/kustomize/kyaml
  go.mod
  go.sum
Labels: dependencies, go, type::chore
