Repository replicatedhq/kURL, pull requests merged in 2024-08, with the labels that each got.

#5286 Automated Containerd version update 1.6.33
  addons/containerd/1.5.10/Manifest
  addons/containerd/1.5.10/host-preflight.yaml
  addons/containerd/1.5.11/Manifest
  addons/containerd/1.5.11/host-preflight.yaml
  addons/containerd/1.6.10/Manifest
  addons/containerd/1.6.10/host-preflight.yaml
  addons/containerd/1.6.11/Manifest
  addons/containerd/1.6.11/host-preflight.yaml
  addons/containerd/1.6.12/Manifest
  addons/containerd/1.6.12/host-preflight.yaml
  addons/containerd/1.6.13/Manifest
  addons/containerd/1.6.13/host-preflight.yaml
  addons/containerd/1.6.14/Manifest
  addons/containerd/1.6.14/host-preflight.yaml
  addons/containerd/1.6.15/Manifest
  addons/containerd/1.6.15/host-preflight.yaml
  addons/containerd/1.6.16/Manifest
  addons/containerd/1.6.16/host-preflight.yaml
  addons/containerd/1.6.18/Manifest
  addons/containerd/1.6.18/host-preflight.yaml
  addons/containerd/1.6.19/Manifest
  addons/containerd/1.6.19/host-preflight.yaml
  addons/containerd/1.6.20/Manifest
  addons/containerd/1.6.20/host-preflight.yaml
  addons/containerd/1.6.21/Manifest
  addons/containerd/1.6.21/host-preflight.yaml
  addons/containerd/1.6.22/Manifest
  addons/containerd/1.6.22/host-preflight.yaml
  addons/containerd/1.6.24/Manifest
  addons/containerd/1.6.24/host-preflight.yaml
  addons/containerd/1.6.25/Manifest
  addons/containerd/1.6.25/host-preflight.yaml
  addons/containerd/1.6.26/Manifest
  addons/containerd/1.6.26/host-preflight.yaml
  addons/containerd/1.6.27/Manifest
  addons/containerd/1.6.27/host-preflight.yaml
  addons/containerd/1.6.28/Manifest
  addons/containerd/1.6.28/host-preflight.yaml
  addons/containerd/1.6.31/Manifest
  addons/containerd/1.6.31/host-preflight.yaml
  addons/containerd/1.6.32/host-preflight.yaml
  addons/containerd/1.6.33/Manifest
  addons/containerd/1.6.33/host-preflight.yaml
  addons/containerd/1.6.4/Manifest
  addons/containerd/1.6.4/host-preflight.yaml
  addons/containerd/1.6.6/Manifest
  addons/containerd/1.6.6/host-preflight.yaml
  addons/containerd/1.6.7/Manifest
  addons/containerd/1.6.7/host-preflight.yaml
  addons/containerd/1.6.8/Manifest
  addons/containerd/1.6.8/host-preflight.yaml
  addons/containerd/1.6.9/Manifest
  addons/containerd/1.6.9/host-preflight.yaml
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#5291 update helm binary to v3.15.3
  bundles/helm/Dockerfile
Labels: type::chore

#5292 fix the download of helmfile
  bundles/helm/Dockerfile
Labels: type::chore

#5293 remove the 'outdated' krew plugin
  bundles/krew/Dockerfile
  scripts/common/plugins.sh
Labels: type::chore

#5294 build the latest github.com/ceph/persistent-volume-migrator binary
  kurl_util/Makefile
Labels: type::chore

#5297 run 'can we upgrade' tests from a static kurl version
  testgrid/specs/customer-migration-specs.yaml
  testgrid/specs/full.yaml
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#5300 fix cis conformance test 4.1.9
  scripts/common/kubernetes.sh
  scripts/install.sh
  scripts/join.sh
  testgrid/specs/deploy.yaml
Labels: type::chore

#5290 include container-selinux manually
  addons/containerd/1.6.33/Manifest
  addons/containerd/1.6.33/install.sh
  addons/containerd/1.7.18/Manifest
  addons/containerd/1.7.18/crictl.yaml
  addons/containerd/1.7.18/host-preflight.yaml
  addons/containerd/1.7.18/install.sh
  addons/containerd/1.7.18/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.7.18/kubeadm-join-config-v1beta2.yaml
  addons/containerd/1.7.19/Manifest
  addons/containerd/1.7.19/crictl.yaml
  addons/containerd/1.7.19/host-preflight.yaml
  addons/containerd/1.7.19/install.sh
  addons/containerd/1.7.19/kubeadm-init-config-v1beta2.yaml
  addons/containerd/1.7.19/kubeadm-join-config-v1beta2.yaml
  addons/containerd/template/base/install.sh
  addons/containerd/template/script.sh
Labels: type::chore

#5301 reenable building k8s packages with centos/rhel/amazon/ol 7
  Makefile
Labels: type::chore

#5302 Automated Containerd version update 1.6.33
  addons/containerd/1.5.10/Manifest
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/Manifest
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/Manifest
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/Manifest
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/Manifest
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/Manifest
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/Manifest
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/Manifest
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/Manifest
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/Manifest
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.19/Manifest
  addons/containerd/1.6.19/install.sh
  addons/containerd/1.6.20/Manifest
  addons/containerd/1.6.20/install.sh
  addons/containerd/1.6.21/Manifest
  addons/containerd/1.6.21/install.sh
  addons/containerd/1.6.22/Manifest
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.24/Manifest
  addons/containerd/1.6.24/install.sh
  addons/containerd/1.6.25/Manifest
  addons/containerd/1.6.25/install.sh
  addons/containerd/1.6.26/Manifest
  addons/containerd/1.6.26/install.sh
  addons/containerd/1.6.27/Manifest
  addons/containerd/1.6.27/install.sh
  addons/containerd/1.6.28/Manifest
  addons/containerd/1.6.28/install.sh
  addons/containerd/1.6.31/Manifest
  addons/containerd/1.6.31/install.sh
  addons/containerd/1.6.32/Manifest
  addons/containerd/1.6.32/install.sh
  addons/containerd/1.6.4/Manifest
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/Manifest
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/Manifest
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/Manifest
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/Manifest
  addons/containerd/1.6.9/install.sh
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#5304 test rook installation on merge
  testgrid/specs/deploy.yaml
Labels: type::chore

#5305 skip build of Rook 1.4.3 and 1.4.9
  bin/list-all-packages.sh
Labels: type::chore

#5306 fix indentation for rook onmerge test
  testgrid/specs/deploy.yaml
Labels: type::chore

#5310 fix log line
  bin/upload-dist-staging.sh
Labels: type::chore

#5311 run the container-selinux installation on centos 7 as part of the 'install' step
  addons/containerd/1.6.33/install.sh
  addons/containerd/template/base/install.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
Labels: type::chore

#5312 Automated Containerd version update 1.6.33
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.19/install.sh
  addons/containerd/1.6.20/install.sh
  addons/containerd/1.6.21/install.sh
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.24/install.sh
  addons/containerd/1.6.25/install.sh
  addons/containerd/1.6.26/install.sh
  addons/containerd/1.6.27/install.sh
  addons/containerd/1.6.28/install.sh
  addons/containerd/1.6.31/install.sh
  addons/containerd/1.6.32/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/install.sh
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#5314 use the already-pulled 'registry:2.8.3' image in on-merge tests, not 'registry:2.8.1'
  testgrid/specs/deploy.yaml
Labels: type::chore

#5296 ship v5 kustomize in supported k8s versions not v2 + v3
  addons/flannel/0.20.0/yaml/kustomization.yaml
  addons/flannel/0.20.1/yaml/kustomization.yaml
  addons/flannel/0.20.2/yaml/kustomization.yaml
  addons/flannel/0.21.0/yaml/kustomization.yaml
  addons/flannel/0.21.1/yaml/kustomization.yaml
  addons/flannel/0.21.2/yaml/kustomization.yaml
  addons/flannel/0.21.3/yaml/kustomization.yaml
  addons/flannel/0.21.4/yaml/kustomization.yaml
  addons/flannel/0.21.5/yaml/kustomization.yaml
  addons/flannel/0.22.0/yaml/kustomization.yaml
  addons/flannel/0.22.1/yaml/kustomization.yaml
  addons/flannel/0.22.2/yaml/kustomization.yaml
  addons/flannel/0.22.3/yaml/kustomization.yaml
  addons/flannel/0.23.0/yaml/kustomization.yaml
  addons/flannel/0.24.0/yaml/kustomization.yaml
  addons/flannel/0.24.1/yaml/kustomization.yaml
  addons/flannel/0.24.2/yaml/kustomization.yaml
  addons/flannel/0.24.4/yaml/kustomization.yaml
  addons/flannel/0.25.1/yaml/kustomization.yaml
  addons/flannel/0.25.2/yaml/kustomization.yaml
  addons/flannel/0.25.3/yaml/kustomization.yaml
  addons/flannel/0.25.4/yaml/kustomization.yaml
  addons/flannel/0.25.5/yaml/kustomization.yaml
  addons/flannel/template/base/yaml/kustomization.yaml
  packages/kubernetes/1.27.16/Manifest
  packages/kubernetes/1.28.12/Manifest
  packages/kubernetes/1.29.7/Manifest
  packages/kubernetes/1.30.3/Manifest
  packages/kubernetes/template/script.sh
  scripts/common/yaml.sh
Labels: type::chore

#5316 resolve flannel on old k8s issues
  addons/flannel/0.25.5/install.sh
  addons/flannel/template/base/install.sh
  addons/flannel/template/testgrid/k8s-ctrd.yaml
Labels: type::chore

#5317 backport flannel changes to all previous versions
  addons/flannel/0.20.0/install.sh
  addons/flannel/0.20.1/install.sh
  addons/flannel/0.20.2/install.sh
  addons/flannel/0.21.0/install.sh
  addons/flannel/0.21.1/install.sh
  addons/flannel/0.21.2/install.sh
  addons/flannel/0.21.3/install.sh
  addons/flannel/0.21.4/install.sh
  addons/flannel/0.21.5/install.sh
  addons/flannel/0.22.0/install.sh
  addons/flannel/0.22.1/install.sh
  addons/flannel/0.22.2/install.sh
  addons/flannel/0.22.3/install.sh
  addons/flannel/0.23.0/install.sh
  addons/flannel/0.24.0/install.sh
  addons/flannel/0.24.1/install.sh
  addons/flannel/0.24.2/install.sh
  addons/flannel/0.24.4/install.sh
  addons/flannel/0.25.1/install.sh
  addons/flannel/0.25.2/install.sh
  addons/flannel/0.25.3/install.sh
  addons/flannel/0.25.4/install.sh
Labels: type::chore

#5207 Automated MinIO version update RELEASE.2024-08-03T04-33-23Z
  addons/minio/2024-08-03T04-33-23Z/Manifest
  addons/minio/2024-08-03T04-33-23Z/deployment.yaml
  addons/minio/2024-08-03T04-33-23Z/install.sh
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/hostpath/service.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/minio-pvc.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2024-08-03T04-33-23Z/migrate-fs/pvc/service.yaml
  addons/minio/2024-08-03T04-33-23Z/service.yaml
  addons/minio/2024-08-03T04-33-23Z/tmpl-creds-secret.yaml
  addons/minio/2024-08-03T04-33-23Z/tmpl-deployment-hostpath.yaml
  addons/minio/2024-08-03T04-33-23Z/tmpl-deployment-pvc.yaml
  addons/minio/2024-08-03T04-33-23Z/tmpl-ha-statefulset.yaml
  addons/minio/2024-08-03T04-33-23Z/tmpl-kustomization.yaml
  addons/minio/2024-08-03T04-33-23Z/tmpl-namespace.yaml
  addons/minio/2024-08-03T04-33-23Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#5321 backport the flannel-ethtool.service file to older versions
  addons/flannel/0.20.0/flannel-ethtool.service
  addons/flannel/0.20.1/flannel-ethtool.service
  addons/flannel/0.20.2/flannel-ethtool.service
  addons/flannel/0.21.0/flannel-ethtool.service
  addons/flannel/0.21.1/flannel-ethtool.service
  addons/flannel/0.21.2/flannel-ethtool.service
  addons/flannel/0.21.3/flannel-ethtool.service
  addons/flannel/0.21.4/flannel-ethtool.service
  addons/flannel/0.21.5/flannel-ethtool.service
  addons/flannel/0.22.0/flannel-ethtool.service
  addons/flannel/0.22.1/flannel-ethtool.service
  addons/flannel/0.22.2/flannel-ethtool.service
  addons/flannel/0.22.3/flannel-ethtool.service
  addons/flannel/0.23.0/flannel-ethtool.service
  addons/flannel/0.24.0/flannel-ethtool.service
  addons/flannel/0.24.1/flannel-ethtool.service
Labels: type::bug, bug::regression

#5322 Automated Kubernetes version update 1.30.4 1.29.8 1.28.13 1.27.16
  hack/testdata/manifest/clean
  packages/kubernetes/1.28.13/Manifest
  packages/kubernetes/1.28.13/conformance/Manifest
  packages/kubernetes/1.29.8/Manifest
  packages/kubernetes/1.29.8/conformance/Manifest
  packages/kubernetes/1.30.4/Manifest
  packages/kubernetes/1.30.4/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#5334 support and test centos 9 stream
  scripts/common/preflights.sh
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::feature

#5335 centos 9 test fixes
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#5338 Automated Kubernetes version update 1.31.0
  hack/testdata/manifest/clean
  packages/kubernetes/1.31.0/Manifest
  packages/kubernetes/1.31.0/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#5339 chore: migrate testgrid to kubernetes v1.31
  addons/cert-manager/template/testgrid/k8s-docker.yaml
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  addons/contour/template/testgrid/k8s-docker.yaml
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/k8s-upgrade.yaml
Labels: type::chore

#5340 chore: disable test on amazon 2023
  testgrid/specs/deploy.yaml
Labels: type::chore

#5341 add amazon-2023 to kubernetes package build make command
  Makefile
Labels: type::chore

#5345 support host package checking on Ubuntu 2404
  bin/save-manifest-assets.sh
  bundles/k8s-ubuntu2404/Dockerfile
  scripts/common/host-packages.sh
Labels: type::chore

#5346 do intelligent detection of which ubuntu 24.04 deps are provided by k8s packages
  bundles/k8s-ubuntu2404/Dockerfile
  scripts/common/host-packages.sh
Labels: type::chore

#5343 Add ubuntu 24.04 to testgrid
  addons/containerd/1.6.33/install.sh
  addons/containerd/template/base/install.sh
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#5348 chore: disable amazon 2023 tests for k8s < 1.24
  addons/antrea/template/testgrid/tests.yaml
  addons/cert-manager/template/testgrid/k8s-docker.yaml
  addons/collectd/template/testgrid/k8s-docker.yaml
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  addons/contour/template/testgrid/k8s-docker.yaml
  addons/ekco/template/testgrid/k8s-docker.yaml
  addons/flannel/template/testgrid/k8s-ctrd.yaml
  addons/fluentd/template/testgrid/k8s-docker.yaml
  addons/goldpinger/template/testgrid/tests.yaml
  addons/longhorn/template/testgrid/k8s-ctrd.yaml
  addons/metrics-server/template/testgrid/k8s-docker.yaml
  addons/minio/template/testgrid/k8s-docker.yaml
  addons/openebs/template/testgrid/k8s-docker-localpv.yaml
  addons/prometheus/template/testgrid/k8s-docker.yaml
  addons/registry/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  addons/weave/template/testgrid/k8s-docker.yaml
  scripts/common/preflights.sh
  testgrid/specs/customer-migration-specs.yaml
  testgrid/specs/full.yaml
  testgrid/specs/k8s-upgrade.yaml
  testgrid/specs/latest.yaml
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#5349 fix apt package detection
  scripts/common/host-packages.sh
Labels: type::chore

#5350 fix apt host package check
  scripts/common/host-packages.sh
Labels: type::chore

#5351 improve 'is k8s already installed' check in flannel addon
  addons/flannel/0.25.5/install.sh
  addons/flannel/template/base/install.sh
Labels: type::chore

#5352 install containerd as part of kurl on Amazon 2023 and Ubuntu 24.04
  addons/containerd/1.6.33/install.sh
  addons/containerd/template/base/install.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#5347 Automated Containerd version update 1.6.33
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.19/install.sh
  addons/containerd/1.6.20/install.sh
  addons/containerd/1.6.21/install.sh
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.24/install.sh
  addons/containerd/1.6.25/install.sh
  addons/containerd/1.6.26/install.sh
  addons/containerd/1.6.27/install.sh
  addons/containerd/1.6.28/install.sh
  addons/containerd/1.6.31/install.sh
  addons/containerd/1.6.32/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/install.sh
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#5353 prevent host package checks from being skipped due to other os coming first
  scripts/common/host-packages.sh
Labels: type::chore

#5354 disable cri-containerd.apparmor.d on ubuntu 24.04
  addons/containerd/1.6.33/install.sh
  addons/containerd/template/base/install.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#5355 Automated Containerd version update 1.6.33
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.19/install.sh
  addons/containerd/1.6.20/install.sh
  addons/containerd/1.6.21/install.sh
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.24/install.sh
  addons/containerd/1.6.25/install.sh
  addons/containerd/1.6.26/install.sh
  addons/containerd/1.6.27/install.sh
  addons/containerd/1.6.28/install.sh
  addons/containerd/1.6.31/install.sh
  addons/containerd/1.6.32/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/install.sh
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#5324 Automated MinIO version update RELEASE.2024-08-17T01-24-54Z
  addons/minio/2024-08-17T01-24-54Z/Manifest
  addons/minio/2024-08-17T01-24-54Z/deployment.yaml
  addons/minio/2024-08-17T01-24-54Z/install.sh
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/hostpath/service.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/minio-pvc.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2024-08-17T01-24-54Z/migrate-fs/pvc/service.yaml
  addons/minio/2024-08-17T01-24-54Z/service.yaml
  addons/minio/2024-08-17T01-24-54Z/tmpl-creds-secret.yaml
  addons/minio/2024-08-17T01-24-54Z/tmpl-deployment-hostpath.yaml
  addons/minio/2024-08-17T01-24-54Z/tmpl-deployment-pvc.yaml
  addons/minio/2024-08-17T01-24-54Z/tmpl-ha-statefulset.yaml
  addons/minio/2024-08-17T01-24-54Z/tmpl-kustomization.yaml
  addons/minio/2024-08-17T01-24-54Z/tmpl-namespace.yaml
  addons/minio/2024-08-17T01-24-54Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#5356 upgrade prometheus in storage migration destination spec to a version that still exists
  testgrid/specs/storage-migration.yaml
Labels: type::chore

#5357 do not fail upgrades due to newer installed containerd on host-containerd OSes
  addons/containerd/1.6.33/install.sh
  addons/containerd/template/base/install.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
  scripts/common/containerd.sh
Labels: type::chore

#5358 Automated Containerd version update 1.6.33
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.19/install.sh
  addons/containerd/1.6.20/install.sh
  addons/containerd/1.6.21/install.sh
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.24/install.sh
  addons/containerd/1.6.25/install.sh
  addons/containerd/1.6.26/install.sh
  addons/containerd/1.6.27/install.sh
  addons/containerd/1.6.28/install.sh
  addons/containerd/1.6.31/install.sh
  addons/containerd/1.6.32/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/install.sh
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#5363 bug: bail out if no policycoreutils-python-utils
  scripts/common/utilbinaries.sh
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::bug, bug::normal

#5364 chore: disable unsupported amazon 2023 tests
  testgrid/specs/full.yaml
Labels: type::chore

#5365 chore(testgrid): install collectd on amazon 2023
  addons/collectd/template/testgrid/k8s-docker.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#5366 chore: install containerd rpm on amazon 2023
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#5367 Revert "chore(deps): bump github.com/vishvananda/netlink from 1.2.1-beta.2 to 1.3.0"
  go.mod
  go.sum
Labels: type::chore

#5370 chore: add missing testhelpers.sh source
  testgrid/specs/full.yaml
Labels: type::chore

#5371 bug: patch pause image on amazon 2023
  addons/containerd/1.5.10/install.sh
  addons/containerd/1.5.11/install.sh
  addons/containerd/1.6.10/install.sh
  addons/containerd/1.6.11/install.sh
  addons/containerd/1.6.12/install.sh
  addons/containerd/1.6.13/install.sh
  addons/containerd/1.6.14/install.sh
  addons/containerd/1.6.15/install.sh
  addons/containerd/1.6.16/install.sh
  addons/containerd/1.6.18/install.sh
  addons/containerd/1.6.19/install.sh
  addons/containerd/1.6.20/install.sh
  addons/containerd/1.6.21/install.sh
  addons/containerd/1.6.22/install.sh
  addons/containerd/1.6.24/install.sh
  addons/containerd/1.6.25/install.sh
  addons/containerd/1.6.26/install.sh
  addons/containerd/1.6.27/install.sh
  addons/containerd/1.6.28/install.sh
  addons/containerd/1.6.31/install.sh
  addons/containerd/1.6.32/install.sh
  addons/containerd/1.6.33/install.sh
  addons/containerd/1.6.4/install.sh
  addons/containerd/1.6.6/install.sh
  addons/containerd/1.6.7/install.sh
  addons/containerd/1.6.8/install.sh
  addons/containerd/1.6.9/install.sh
  addons/containerd/template/base/install.sh
Labels: type::bug, bug::normal

#5298 Automated Prometheus version update 0.76.0-62.3.0
  addons/prometheus/0.76.0-62.3.0/Manifest
  addons/prometheus/0.76.0-62.3.0/crds/crds.yaml
  addons/prometheus/0.76.0-62.3.0/crds/kustomization.yaml
  addons/prometheus/0.76.0-62.3.0/crds/preserveUnknown.yaml
  addons/prometheus/0.76.0-62.3.0/host-preflight.yaml
  addons/prometheus/0.76.0-62.3.0/install.sh
  addons/prometheus/0.76.0-62.3.0/nodeport-services.yaml
  addons/prometheus/0.76.0-62.3.0/operator/adapter.yaml
  addons/prometheus/0.76.0-62.3.0/operator/default.yaml
  addons/prometheus/0.76.0-62.3.0/operator/kustomization.yaml
  addons/prometheus/0.76.0-62.3.0/operator/longhorn.yaml
  addons/prometheus/0.76.0-62.3.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.76.0-62.3.0/operator/matchlabel-release.yaml
  addons/prometheus/0.76.0-62.3.0/operator/ns.yaml
  addons/prometheus/0.76.0-62.3.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.76.0-62.3.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#5372 save apt dependencies in ubuntu-24.04/Deps
  bin/save-manifest-assets.sh
Labels: type::feature

#5374 chore: add missing collectd package
  addons/collectd/template/testgrid/k8s-docker.yaml
  addons/collectd/v5/Manifest
  testgrid/specs/full.yaml
Labels: type::chore

#5373 Automated Flannel version update 0.25.6
  addons/flannel/0.25.6/Manifest
  addons/flannel/0.25.6/flannel-ethtool.service
  addons/flannel/0.25.6/host-preflight.yaml
  addons/flannel/0.25.6/install.sh
  addons/flannel/0.25.6/kubeadm.yaml
  addons/flannel/0.25.6/template/iface.patch.tmpl.yaml
  addons/flannel/0.25.6/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.25.6/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.25.6/yaml/kube-flannel.yml
  addons/flannel/0.25.6/yaml/kustomization.yaml
  addons/flannel/0.25.6/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#5375 Ubuntu 24.04 testgrid deps
  addons/collectd/template/testgrid/k8s-docker.yaml
  addons/longhorn/template/testgrid/k8s-ctrd.yaml
  addons/rook/template/testgrid/k8s-docker.yaml
  addons/velero/template/testgrid/k8s-docker.yaml
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#5369 Automated MinIO version update RELEASE.2024-08-26T15-33-07Z
  addons/minio/2024-08-26T15-33-07Z/Manifest
  addons/minio/2024-08-26T15-33-07Z/deployment.yaml
  addons/minio/2024-08-26T15-33-07Z/install.sh
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/hostpath/service.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/minio-pvc.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2024-08-26T15-33-07Z/migrate-fs/pvc/service.yaml
  addons/minio/2024-08-26T15-33-07Z/service.yaml
  addons/minio/2024-08-26T15-33-07Z/tmpl-creds-secret.yaml
  addons/minio/2024-08-26T15-33-07Z/tmpl-deployment-hostpath.yaml
  addons/minio/2024-08-26T15-33-07Z/tmpl-deployment-pvc.yaml
  addons/minio/2024-08-26T15-33-07Z/tmpl-ha-statefulset.yaml
  addons/minio/2024-08-26T15-33-07Z/tmpl-kustomization.yaml
  addons/minio/2024-08-26T15-33-07Z/tmpl-namespace.yaml
  addons/minio/2024-08-26T15-33-07Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#5376 bug: prefer libcurl-minimal over libcurl
  bin/containertools/builddeps.sh
Labels: type::bug, bug::normal

#5377 modprobe rbd if needed
  addons/rook/1.12.8/install.sh
  addons/rook/template/base/install.sh
Labels: type::chore
