Repository replicatedhq/kURL, pull requests merged in 2024-07, with the labels that each got.

#5253 run shell tests with oracle linux 7 images instead of centos 7
  hack/test-shell/Dockerfile.rhel-7
Labels: type::chore

#5232 Automated Velero version update 1.14.0
  addons/velero/1.14.0/Manifest
  addons/velero/1.14.0/install.sh
  addons/velero/1.14.0/node-agent-daemonset-privileged.yaml
  addons/velero/1.14.0/s3-migration-configmap.yaml
  addons/velero/1.14.0/tmpl-change-storageclass.yaml
  addons/velero/1.14.0/tmpl-internal-snaps-deployment-patch.yaml
  addons/velero/1.14.0/tmpl-internal-snaps-ds-patch.yaml
  addons/velero/1.14.0/tmpl-internal-snaps-pvc.yaml
  addons/velero/1.14.0/tmpl-kotsadm-restore-config.yaml
  addons/velero/1.14.0/tmpl-kustomization.yaml
  addons/velero/1.14.0/tmpl-node-agent-daemonset-proxy.yaml
  addons/velero/1.14.0/tmpl-s3-migration-bsl.yaml
  addons/velero/1.14.0/tmpl-s3-migration-deployment-patch.yaml
  addons/velero/1.14.0/tmpl-s3-migration-secret.yaml
  addons/velero/1.14.0/tmpl-troubleshoot.yaml
  addons/velero/1.14.0/tmpl-velero-deployment-proxy.yaml
  web/src/installers/versions.js
Labels: automated-pr, velero, type::chore, kurl::type::feature

#5256 Automated Kubernetes version update 1.30.2 1.29.6 1.28.11 1.27.15
  packages/kubernetes/1.30.2/Manifest
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#5261 Automated Flannel version update 0.25.5
  addons/flannel/0.25.5/Manifest
  addons/flannel/0.25.5/flannel-ethtool.service
  addons/flannel/0.25.5/host-preflight.yaml
  addons/flannel/0.25.5/install.sh
  addons/flannel/0.25.5/kubeadm.yaml
  addons/flannel/0.25.5/template/iface.patch.tmpl.yaml
  addons/flannel/0.25.5/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.25.5/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.25.5/yaml/kube-flannel.yml
  addons/flannel/0.25.5/yaml/kustomization.yaml
  addons/flannel/0.25.5/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#5260 Automated Kubernetes version update 1.30.3 1.29.7 1.28.12 1.27.16
  hack/testdata/manifest/clean
  packages/kubernetes/1.27.16/Manifest
  packages/kubernetes/1.27.16/conformance/Manifest
  packages/kubernetes/1.28.12/Manifest
  packages/kubernetes/1.28.12/conformance/Manifest
  packages/kubernetes/1.29.7/Manifest
  packages/kubernetes/1.29.7/conformance/Manifest
  packages/kubernetes/1.30.3/Manifest
  packages/kubernetes/1.30.3/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#5271 remove RHEL7, CentOS7, and Oracle Linux 7 packages and support
  Makefile
  addons/containerd/template/Dockerfile.centos7
  addons/containerd/template/Dockerfile.centos7-force
  addons/containerd/template/script.sh
  bin/save-manifest-assets.sh
  bundles/docker-rhel7-force/Dockerfile
  bundles/docker-rhel7/Dockerfile
  bundles/k8s-rhel7-force/Dockerfile
  bundles/k8s-rhel7-force/kubernetes.repo
  bundles/k8s-rhel7/Dockerfile
  bundles/k8s-rhel7/kubernetes.repo
  scripts/common/preflights.sh
Labels: type::chore

#5274 there were many more old containerd versions
  addons/containerd/1.3.7/Manifest
  addons/containerd/1.3.9/Manifest
  addons/containerd/1.4.10/Manifest
  addons/containerd/1.4.11/Manifest
  addons/containerd/1.4.12/Manifest
  addons/containerd/1.4.13/Manifest
  addons/containerd/1.4.4/Manifest
  addons/containerd/1.4.6/Manifest
  addons/containerd/1.4.8/Manifest
  addons/containerd/1.4.9/Manifest
Labels: type::chore

#5276 don't build addons with v1 docker images
  bin/list-all-packages.sh
  bin/save-manifest-assets.sh
Labels: type::chore

#5257 Automated Velero version update 1.14.0
  addons/velero/1.14.0/Manifest
  addons/velero/1.14.0/install.sh
Labels: automated-pr, velero, type::chore, kurl::type::feature

#5217 Automated Prometheus version update 0.75.2-61.6.0
  addons/prometheus/0.75.2-61.6.0/Manifest
  addons/prometheus/0.75.2-61.6.0/crds/crds.yaml
  addons/prometheus/0.75.2-61.6.0/crds/kustomization.yaml
  addons/prometheus/0.75.2-61.6.0/crds/preserveUnknown.yaml
  addons/prometheus/0.75.2-61.6.0/host-preflight.yaml
  addons/prometheus/0.75.2-61.6.0/install.sh
  addons/prometheus/0.75.2-61.6.0/nodeport-services.yaml
  addons/prometheus/0.75.2-61.6.0/operator/adapter.yaml
  addons/prometheus/0.75.2-61.6.0/operator/default.yaml
  addons/prometheus/0.75.2-61.6.0/operator/kustomization.yaml
  addons/prometheus/0.75.2-61.6.0/operator/longhorn.yaml
  addons/prometheus/0.75.2-61.6.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.75.2-61.6.0/operator/matchlabel-release.yaml
  addons/prometheus/0.75.2-61.6.0/operator/ns.yaml
  addons/prometheus/0.75.2-61.6.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.75.2-61.6.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#5279 remove docker
  Makefile
  bin/list-all-packages.sh
  bundles/docker-rhel8/Dockerfile
  bundles/docker-ubuntu1604/Dockerfile
  bundles/docker-ubuntu1804/Dockerfile
  bundles/docker-ubuntu2004/Dockerfile
  bundles/docker-ubuntu2004/build.sh
  bundles/docker-ubuntu2204/Dockerfile
  bundles/docker-ubuntu2204/build.sh
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
  web/src/installers/versions.js
Labels: type::chore

#5280 do not expect docker versions to exist
  bin/generate-addons.js
Labels: type::chore

#5282 1.6.33 is not available on centos/ol/rhel 8
  addons/containerd/template/script.sh
Labels: type::chore

#5277 Automated Containerd version update 1.6.33
  addons/containerd/1.6.33/Manifest
  addons/containerd/1.6.33/host-preflight.yaml
  addons/containerd/template/testgrid/k8s-ctrd.yaml
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#5283 fix containerd 1.6.33/32 on Oracle Linux again
  addons/containerd/1.6.33/Manifest
  addons/containerd/template/script.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
Labels: type::chore

#5284 reenable centos/rhel/ol 7 + amazon linux 2 package builds
  addons/containerd/1.6.32/Manifest
  addons/containerd/template/Dockerfile.centos7
  addons/containerd/template/Dockerfile.centos7-force
  addons/containerd/template/script.sh
  bin/save-manifest-assets.sh
  bundles/k8s-rhel7-force/Dockerfile
  bundles/k8s-rhel7-force/kubernetes.repo
  bundles/k8s-rhel7/Dockerfile
  bundles/k8s-rhel7/kubernetes.repo
Labels: type::chore

#5285 fix containerd version generation with centos 7
  addons/containerd/template/script.sh
Labels: type::chore
