Repository replicatedhq/kURL, pull requests merged in 2024-09, with the labels that each got.

#5382 fix(kURL): add pre-check to remove docker in AL2
  scripts/common/docker.sh
Labels: type::bug, bug::normal

#5386 add kubernetes + docker version preflights for Ubuntu 24.04 and Amazon Linux 2023
  pkg/preflight/assets/host-preflights.yaml
Labels: type::chore

#5387 add 'containerd' package to pre-install package deps for Ubuntu 24.04 and Amazon Linux 2023
  addons/containerd/template/script.sh
  bin/save-manifest-assets.sh
Labels: type::chore

#5389 fix containerd pre-install package deps
  addons/containerd/template/script.sh
Labels: type::chore

#5390 add containerd to ubuntu 24.04 OS setup
  testgrid/specs/os-firstlast.yaml
  testgrid/specs/os-full.yaml
  testgrid/specs/os-latest.yaml
Labels: type::chore

#5391 ensure the registry image does not need to be pulled for the image push test
  testgrid/specs/deploy.yaml
Labels: type::chore

#5379 Automated Sonobuoy version update 0.57.2
  addons/sonobuoy/0.57.2/Manifest
  addons/sonobuoy/0.57.2/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#5378 Automated Prometheus version update 0.76.1-62.6.0
  addons/prometheus/0.76.1-62.6.0/Manifest
  addons/prometheus/0.76.1-62.6.0/crds/crds.yaml
  addons/prometheus/0.76.1-62.6.0/crds/kustomization.yaml
  addons/prometheus/0.76.1-62.6.0/crds/preserveUnknown.yaml
  addons/prometheus/0.76.1-62.6.0/host-preflight.yaml
  addons/prometheus/0.76.1-62.6.0/install.sh
  addons/prometheus/0.76.1-62.6.0/nodeport-services.yaml
  addons/prometheus/0.76.1-62.6.0/operator/adapter.yaml
  addons/prometheus/0.76.1-62.6.0/operator/default.yaml
  addons/prometheus/0.76.1-62.6.0/operator/kustomization.yaml
  addons/prometheus/0.76.1-62.6.0/operator/longhorn.yaml
  addons/prometheus/0.76.1-62.6.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.76.1-62.6.0/operator/matchlabel-release.yaml
  addons/prometheus/0.76.1-62.6.0/operator/ns.yaml
  addons/prometheus/0.76.1-62.6.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.76.1-62.6.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#5396 Automated Kubernetes version update 1.31.1 1.30.5 1.29.9 1.28.14
  hack/testdata/manifest/clean
  packages/kubernetes/1.28.14/Manifest
  packages/kubernetes/1.28.14/conformance/Manifest
  packages/kubernetes/1.29.9/Manifest
  packages/kubernetes/1.29.9/conformance/Manifest
  packages/kubernetes/1.30.5/Manifest
  packages/kubernetes/1.30.5/conformance/Manifest
  packages/kubernetes/1.31.1/Manifest
  packages/kubernetes/1.31.1/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#5412 fix: /etc/kubernetes/super-admin.conf file perms for cis benchmark
  scripts/common/kubernetes.sh
  scripts/install.sh
  scripts/join.sh
Labels: type::bug, bug::normal

#5413 chore(ci): use kube-bench v0.8.0 with cis-1.8
  testgrid/specs/deploy.yaml
  testgrid/specs/full.yaml
Labels: type::chore

#5414 download kubeadm from dl.k8s.io not storage.googleapis.com
  packages/kubernetes/1.28.14/Manifest
  packages/kubernetes/1.29.9/Manifest
  packages/kubernetes/1.30.5/Manifest
  packages/kubernetes/1.31.1/Manifest
  packages/kubernetes/template/script.sh
Labels: type::chore
