Repository replicatedhq/kURL, pull requests merged in 2025-02, with the labels that each got.

#5557 Automated Containerd version update 1.7.25
  addons/containerd/1.7.25/Manifest
  addons/containerd/1.7.25/host-preflight.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
Labels: automated-pr, containerd, type::chore, kurl::type::feature

#5549 Automated Flannel version update 0.26.4
  addons/flannel/0.26.4/Manifest
  addons/flannel/0.26.4/flannel-ethtool.service
  addons/flannel/0.26.4/host-preflight.yaml
  addons/flannel/0.26.4/install.sh
  addons/flannel/0.26.4/kubeadm.yaml
  addons/flannel/0.26.4/template/iface.patch.tmpl.yaml
  addons/flannel/0.26.4/template/ipv6.patch.tmpl.yaml
  addons/flannel/0.26.4/template/kube-flannel-cfg.patch.tmpl.yaml
  addons/flannel/0.26.4/yaml/kube-flannel.yml
  addons/flannel/0.26.4/yaml/kustomization.yaml
  addons/flannel/0.26.4/yaml/troubleshoot.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, kurl::type::feature, flannel

#5518 Automated Prometheus version update 0.80.0-69.2.0
  addons/prometheus/0.80.0-69.2.0/Manifest
  addons/prometheus/0.80.0-69.2.0/crds/crds.yaml
  addons/prometheus/0.80.0-69.2.0/crds/kustomization.yaml
  addons/prometheus/0.80.0-69.2.0/crds/preserveUnknown.yaml
  addons/prometheus/0.80.0-69.2.0/host-preflight.yaml
  addons/prometheus/0.80.0-69.2.0/install.sh
  addons/prometheus/0.80.0-69.2.0/nodeport-services.yaml
  addons/prometheus/0.80.0-69.2.0/operator/adapter.yaml
  addons/prometheus/0.80.0-69.2.0/operator/default.yaml
  addons/prometheus/0.80.0-69.2.0/operator/kustomization.yaml
  addons/prometheus/0.80.0-69.2.0/operator/longhorn.yaml
  addons/prometheus/0.80.0-69.2.0/operator/matchlabel-instance.yaml
  addons/prometheus/0.80.0-69.2.0/operator/matchlabel-release.yaml
  addons/prometheus/0.80.0-69.2.0/operator/ns.yaml
  addons/prometheus/0.80.0-69.2.0/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.80.0-69.2.0/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#5560 use rhel docker-containerd packages for rhel/containerd/rocky 8, not centos
  addons/containerd/1.6.33/Manifest
  addons/containerd/1.7.25/Manifest
  addons/containerd/template/Dockerfile.centos8
Labels: type::bug, bug::normal

#5561 cert-manager 1.17.1
  addons/cert-manager/1.17.1/Manifest
  addons/cert-manager/1.17.1/cert-manager.yaml
  addons/cert-manager/1.17.1/install.sh
  addons/cert-manager/1.17.1/kustomization.yaml
  addons/cert-manager/template/testgrid/k8s-docker.yaml
  web/src/installers/versions.js
Labels: type::feature

#5563 Automated Kubernetes version update 1.32.2 1.31.6 1.30.10 1.29.14
  hack/testdata/manifest/clean
  packages/kubernetes/1.29.14/Manifest
  packages/kubernetes/1.29.14/conformance/Manifest
  packages/kubernetes/1.30.10/Manifest
  packages/kubernetes/1.30.10/conformance/Manifest
  packages/kubernetes/1.31.6/Manifest
  packages/kubernetes/1.31.6/conformance/Manifest
  packages/kubernetes/1.32.2/Manifest
  packages/kubernetes/1.32.2/conformance/Manifest
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, kubernetes, type::chore, kurl::type::feature

#5564 use kubernetes 1.32 in daily tests
  testgrid/specs/full.yaml
Labels: type::chore

#5565 fix an issue where the containerd health check failed on k8s 1.32
  addons/containerd/1.6.33/install.sh
  addons/containerd/1.7.25/install.sh
  addons/containerd/template/base/install.sh
  addons/containerd/template/testgrid/k8s-ctrd.yaml
Labels: type::bug, bug::normal

#5567 update install scripts for containerd 1.6.28+, fix preflights
  addons/containerd/1.6.28/install.sh
  addons/containerd/1.6.31/install.sh
  addons/containerd/1.6.32/install.sh
  addons/containerd/1.6.33/host-preflight.yaml
  addons/containerd/1.7.25/host-preflight.yaml
Labels: type::chore

#5582 add rook 1.14.12
  addons/rook/1.13.10/Manifest
  addons/rook/1.14.12/Manifest
  addons/rook/1.14.12/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.14.12/cluster/cephfs/filesystem.yaml
  addons/rook/1.14.12/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.14.12/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.14.12/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.14.12/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.14.12/cluster/cluster.yaml
  addons/rook/1.14.12/cluster/kustomization.yaml
  addons/rook/1.14.12/cluster/object-user.yaml
  addons/rook/1.14.12/cluster/object.yaml
  addons/rook/1.14.12/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.14.12/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.14.12/cluster/patches/object-Json6902.yaml
  addons/rook/1.14.12/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.14.12/cluster/patches/tmpl-object.yaml
  addons/rook/1.14.12/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.14.12/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.14.12/crds.yaml
  addons/rook/1.14.12/host-preflight.yaml
  addons/rook/1.14.12/install.sh
  addons/rook/1.14.12/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.14.12/monitoring/kustomization.yaml
  addons/rook/1.14.12/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.14.12/operator/cluster-rbac.yaml
  addons/rook/1.14.12/operator/clusterrole.yaml
  addons/rook/1.14.12/operator/clusterrolebinding.yaml
  addons/rook/1.14.12/operator/configmap-rook-config-override.yaml
  addons/rook/1.14.12/operator/configmap.yaml
  addons/rook/1.14.12/operator/deployment.yaml
  addons/rook/1.14.12/operator/kustomization.yaml
  addons/rook/1.14.12/operator/namespace.yaml
  addons/rook/1.14.12/operator/patches/deployment-privileged.yaml
  addons/rook/1.14.12/operator/patches/deployment-tolerations.yaml
  addons/rook/1.14.12/operator/role.yaml
  addons/rook/1.14.12/operator/rolebinding.yaml
  addons/rook/1.14.12/operator/securityContextConstraints.yaml
  addons/rook/1.14.12/operator/serviceaccount.yaml
  addons/rook/1.14.12/operator/toolbox.yaml
  web/src/installers/versions.js
Labels: type::feature

#5503 Automated MinIO version update RELEASE.2025-02-07T23-21-09Z
  addons/minio/2025-02-07T23-21-09Z/Manifest
  addons/minio/2025-02-07T23-21-09Z/deployment.yaml
  addons/minio/2025-02-07T23-21-09Z/install.sh
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/hostpath/service.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/minio-pvc.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2025-02-07T23-21-09Z/migrate-fs/pvc/service.yaml
  addons/minio/2025-02-07T23-21-09Z/service.yaml
  addons/minio/2025-02-07T23-21-09Z/tmpl-creds-secret.yaml
  addons/minio/2025-02-07T23-21-09Z/tmpl-deployment-hostpath.yaml
  addons/minio/2025-02-07T23-21-09Z/tmpl-deployment-pvc.yaml
  addons/minio/2025-02-07T23-21-09Z/tmpl-ha-statefulset.yaml
  addons/minio/2025-02-07T23-21-09Z/tmpl-kustomization.yaml
  addons/minio/2025-02-07T23-21-09Z/tmpl-namespace.yaml
  addons/minio/2025-02-07T23-21-09Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature

#5584 use less ancient k8s in minio tests
  addons/minio/2025-02-07T23-21-09Z/Manifest
  addons/minio/template/testgrid/k8s-docker.yaml
Labels: type::chore

#5585 prevent these versions of rook from being installed on RHEL 7 and similar OSes
  addons/rook/1.13.10/host-preflight.yaml
  addons/rook/1.14.12/host-preflight.yaml
  addons/rook/1.15.8/host-preflight.yaml
  addons/rook/1.16.3/host-preflight.yaml
  addons/rook/1.16.3/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/template/base/host-preflight.yaml
  addons/rook/template/generate.sh
  addons/rook/template/testgrid/k8s-docker.yaml
Labels: type::chore

#5586 fix(prometheus): increase grafana limits
  addons/prometheus/template/values.yaml
Labels: type::bug, bug::normal

#5571 Automated Prometheus version update 0.80.0-69.3.3
  addons/prometheus/0.80.0-69.3.3/Manifest
  addons/prometheus/0.80.0-69.3.3/crds/crds.yaml
  addons/prometheus/0.80.0-69.3.3/crds/kustomization.yaml
  addons/prometheus/0.80.0-69.3.3/crds/preserveUnknown.yaml
  addons/prometheus/0.80.0-69.3.3/host-preflight.yaml
  addons/prometheus/0.80.0-69.3.3/install.sh
  addons/prometheus/0.80.0-69.3.3/nodeport-services.yaml
  addons/prometheus/0.80.0-69.3.3/operator/adapter.yaml
  addons/prometheus/0.80.0-69.3.3/operator/default.yaml
  addons/prometheus/0.80.0-69.3.3/operator/kustomization.yaml
  addons/prometheus/0.80.0-69.3.3/operator/longhorn.yaml
  addons/prometheus/0.80.0-69.3.3/operator/matchlabel-instance.yaml
  addons/prometheus/0.80.0-69.3.3/operator/matchlabel-release.yaml
  addons/prometheus/0.80.0-69.3.3/operator/ns.yaml
  addons/prometheus/0.80.0-69.3.3/operator/rook-ceph-rolebindings.yaml
  addons/prometheus/0.80.0-69.3.3/tmpl-grafana-secret.yaml
  web/src/installers/versions.js
Labels: automated-pr, prometheus, type::chore, kurl::type::feature

#5587 fix rook prometheus servicemonitor
  addons/rook/1.13.10/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.14.12/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.15.8/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.16.3/monitoring/kustomization.yaml
  addons/rook/1.16.3/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/template/base/monitoring/rook-ceph-servicemonitor.yaml
Labels: type::chore

#5591 Automated Sonobuoy version update 0.57.3
  addons/sonobuoy/0.57.3/Manifest
  addons/sonobuoy/0.57.3/install.sh
  web/src/installers/versions.js
Labels: automated-pr, sonobuoy, type::chore, kurl::type::feature

#5590 Automated Rook version update 1.16.4
  addons/rook/1.16.4/Manifest
  addons/rook/1.16.4/cluster/cephfs/cephfs-storageclass.yaml
  addons/rook/1.16.4/cluster/cephfs/filesystem.yaml
  addons/rook/1.16.4/cluster/cephfs/patches/cephfs-storageclass.yaml
  addons/rook/1.16.4/cluster/cephfs/patches/filesystem-singlenode.yaml
  addons/rook/1.16.4/cluster/cephfs/patches/tmpl-filesystem-Json6902.yaml
  addons/rook/1.16.4/cluster/cephfs/patches/tmpl-filesystem.yaml
  addons/rook/1.16.4/cluster/cluster.yaml
  addons/rook/1.16.4/cluster/kustomization.yaml
  addons/rook/1.16.4/cluster/object-user.yaml
  addons/rook/1.16.4/cluster/object.yaml
  addons/rook/1.16.4/cluster/patches/ceph-cluster-tolerate.yaml
  addons/rook/1.16.4/cluster/patches/cluster-nodes.tmpl.yaml
  addons/rook/1.16.4/cluster/patches/object-Json6902.yaml
  addons/rook/1.16.4/cluster/patches/tmpl-cluster.yaml
  addons/rook/1.16.4/cluster/patches/tmpl-object.yaml
  addons/rook/1.16.4/cluster/patches/tmpl-rbd-storageclass.yaml
  addons/rook/1.16.4/cluster/tmpl-rbd-storageclass.yaml
  addons/rook/1.16.4/crds.yaml
  addons/rook/1.16.4/host-preflight.yaml
  addons/rook/1.16.4/install.sh
  addons/rook/1.16.4/monitoring/ceph-cluster-dashboard.yaml
  addons/rook/1.16.4/monitoring/kustomization.yaml
  addons/rook/1.16.4/monitoring/rook-ceph-servicemonitor.yaml
  addons/rook/1.16.4/operator/cluster-rbac.yaml
  addons/rook/1.16.4/operator/clusterrole.yaml
  addons/rook/1.16.4/operator/clusterrolebinding.yaml
  addons/rook/1.16.4/operator/configmap-rook-config-override.yaml
  addons/rook/1.16.4/operator/configmap.yaml
  addons/rook/1.16.4/operator/deployment.yaml
  addons/rook/1.16.4/operator/kustomization.yaml
  addons/rook/1.16.4/operator/namespace.yaml
  addons/rook/1.16.4/operator/patches/deployment-privileged.yaml
  addons/rook/1.16.4/operator/patches/deployment-tolerations.yaml
  addons/rook/1.16.4/operator/role.yaml
  addons/rook/1.16.4/operator/rolebinding.yaml
  addons/rook/1.16.4/operator/securityContextConstraints.yaml
  addons/rook/1.16.4/operator/serviceaccount.yaml
  addons/rook/1.16.4/operator/toolbox.yaml
  hack/testdata/manifest/clean
  scripts/Manifest
  web/src/installers/versions.js
Labels: automated-pr, rook, type::chore, kurl::type::feature

#5597 remove a on-merge test that always hangs due to firewall issues
  testgrid/specs/deploy.yaml
Labels: type::chore

#5588 Automated MinIO version update RELEASE.2025-02-18T16-25-55Z
  addons/minio/2025-02-18T16-25-55Z/Manifest
  addons/minio/2025-02-18T16-25-55Z/deployment.yaml
  addons/minio/2025-02-18T16-25-55Z/install.sh
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/hostpath/deployment.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/hostpath/kustomization.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/hostpath/original-service.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/hostpath/service.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/minio-backup-pvc.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/minio-pvc.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/pvc/deployment.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/pvc/kustomization.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/pvc/original-service.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/pvc/pvc.yaml
  addons/minio/2025-02-18T16-25-55Z/migrate-fs/pvc/service.yaml
  addons/minio/2025-02-18T16-25-55Z/service.yaml
  addons/minio/2025-02-18T16-25-55Z/tmpl-creds-secret.yaml
  addons/minio/2025-02-18T16-25-55Z/tmpl-deployment-hostpath.yaml
  addons/minio/2025-02-18T16-25-55Z/tmpl-deployment-pvc.yaml
  addons/minio/2025-02-18T16-25-55Z/tmpl-ha-statefulset.yaml
  addons/minio/2025-02-18T16-25-55Z/tmpl-kustomization.yaml
  addons/minio/2025-02-18T16-25-55Z/tmpl-namespace.yaml
  addons/minio/2025-02-18T16-25-55Z/tmpl-pvc.yaml
  web/src/installers/versions.js
Labels: automated-pr, type::chore, minio, kurl::type::feature
